### ISSUE TITLE
[BRUKERHISTORIE] Eksempler på (videre)bruk av datasett og APIer 

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#100]
Som: privat virksomhet eller frivillig organisasjon
Ønsker jeg å: relatere mitt produkt som bruker/konsument av ett eller flere åpne datasett eller APIer i FDK
Slik at: mitt produkt kan tjene som eksempel på at åpne data skaper verdier og nye tjenester (og jeg får promotert tjenesten min...)

Relatert til epos: 
#187
#36
#1 
#569 

Lenke til design: https://data.norge.no/app 
Lenke til løsningsarkitektur: vurdere bruk av CPSV som modell og å la dette inngå som en del av en fremtidig tjenestekatalog.

Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire (dedicated section for showcasing usecases)

Felter i registreringsskjemaet med referanse til egenskaper i [CPSV v 2.2.1](https://joinup.ec.europa.eu/solution/core-public-service-vocabulary-application-profile/release/221):

* Navn på tjeneste/produkt  -> `dct:title` 1..1
* Beskrivelse ->`dct:description`, 1..1
* Brukte datasett (relasjoner til datasett i katalogen som er brukt av tjenesten) -> `dct:requires` http://purl.org/dc/terms/requires (mitt forslag - mangler i CPSV)
* Lisens (programvarelisens) `dct:license` (denne mangler i CPSV)
* Relevante lenker (lenke til Appstore/Google play/nett-tjeneste osb) ->`cv:hasChannel` , 0..n
* Kategori (tema) (samme som for datasett) `dcat:theme`
* Emneord (fritekst) `dcat:keyword`
* Georafi (dekningsområde) `dct:spatial`
* Kontaktinfo (epost):  `cv:hasContactpoint`
* Pris ->`cv:hasCost` Nice to have - Ikke et eksisterende felt

* Organisasjon/eier/bedrift ->`foaf:Agent`
* Sektor -> `cv:sector`
* Språk ->`dct:language`

**Comment by oystein-asnes** [comment]
ISA2 har en del prosjekter på Github som treffer både denne og #1  . Sjekk ut https://github.com/catalogue-of-services-isa

**Comment by lillelars** [comment]
@livarb @oystein-asnes Har vi tenkt at dette er noe som kommer med "Tjenestekatalogen" ? Eller er dette ansett som veldig viktig ?

**Comment by stigbd** [comment]
Feature som dette issuet impliserer, kan vere med på å realisere funksjonaliteten EU (maturity-indeks) etterspør i dette spørsmålet:
> Are there activities in place to support and incentivise public bodies in measuring the re-use of their own or other public bodies' open data (e.g., monitoring)?

**Comment by oystein-asnes** [comment]
Denne er nå delvis  realisert gjennom [datalandsbyen- gode eksempler og inspirasjon](https://datalandsbyen.norge.no/category/2/gode-eksempler-og-inspirasjon), men på siden av tjenestekatalogen og uten de strukturene som ligger i CPSV. Det kan fungere fint, men savner veldig relasjoner/koblinger til datasett i apiene i katalogen som er brukt. Dette gjør eksemplene bedre og er svært nyttig informasjon for datatilbyder (det blir en indikator på verdier som delingen skaper). 

Dette er allerede mulig ved å lenke til datasettene/apiene i fritekst/html i selve posten, men som vi ser av de innkomne eksemplene blir ikke dette gjort.

Løsningsforslag (stigende etter ambisjonsnivå): 
1) Tydeliggjøre hvordan dette gjøres i fritekst i ingressteksten til tråden  
2) Opprette et definert felt for denne kategorien der en kan oppgi "0 til mange" lenker til datasettsett/apier i katalogen
3) Lage en magisk søkewidget der en kan søke i datasett/API-katalogen for å hente inn lenker til det definerte feltet (jf punkt 2)

**Comment by livarb** [comment]
Legg til pkt. 4. Kunne oppgje organisasjon ein har brukt data/API frå, i tillegg til å lenke direkte til sjølve datasett/API-oppføringar.

Årsaka til dette kan vere at det ikkje finst ei korrekt oppføring slik det er i dag, eller at det er så mange oppføringar at det vert upraktisk å legge inn alle referansane (f.eks. tidsseriar som har mange oppføringar i data.norge).

**Comment by oystein-asnes** [comment]
Lukkar saka. Har oppretta nytt issue for å ivareta punkt 4 frå @livarb  (#697)
