### ISSUE TITLE
[BRUKERHISTORIE] Mulighet for flere endringsforslag ila. begrepets liv

### ISSUE THREAD

**Issue by kristinekv** [Informasjonsforvaltning/behov#1004]
Som: lesebruker
Ønsker jeg å: kunne komme med nytt endringsforslag, når tidligere endringsforslag har blitt godkjent eller avslått
Slik at: jeg kan forbedre begreper over tid

Relatert til epos:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by KurtStian** [comment]
Løst av: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1022
