### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over bruk av virksomhetens datasett og APIer

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#101]
Som: tilbyder av (åpne) offentlige datasett og APier i FDK
Ønsker jeg å: være informert/ha oversikt over hvilke produkter og tjenester som (videre)bruker virksomhetens (åpne) data
Slik at: jeg kan se om data jeg tilbyr skaper verdier utenfor egen virksomhet

Relatert til epos: #1 #36 
Relatert til brukerhistorie: #100 

Lenke til design: (utlisting av tjenester som har registrerte relasjoner til virksomhetens datasett og APIer) - se kommentar under
Lenke til løsningsarkitektur:

**Comment by oystein-asnes** [comment]
Skjermdump av dagens løsning på data.norge:
![image](https://user-images.githubusercontent.com/11029809/53630720-00f9eb00-3c11-11e9-82a5-012fc3f7cc25.png)

**Comment by KjerstiSteien** [comment]
Gjenåpnes hvis behovet reaktualiseres.
