### ISSUE TITLE
[BRUKERHISTORIE] Kontaktinfo til brukere av mine API

### ISSUE THREAD

**Issue by joachim-me** [Informasjonsforvaltning/behov#102]
Som: API-tilbyder   
Ønsker jeg å: kontakte brukere av mine API
Slik at: jeg kan ta kontakt med dem

Relatert til epos: #49 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by KjerstiSteien** [comment]
Lager ny sak dersom behovet reaktualiseres. Lukker denne.
