### ISSUE TITLE
[BRUKERHISTORIE] Navigering i portal

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#103]
Som: bruker av FDK
Ønsker jeg å: komme tilbake til mitt opprinnelige søk
Slik at: jeg slipper å gjøre samme søk på nytt

Relatert til epos:

Trådskisser
Se "Tilbake til søk"-lenken under brødsmulestien her: https://69d4ft.axshare.com/#g=1&p=detaljside_datasett

Lenke til design: https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/345287059

Lenke til løsningsarkitektur:

**Akseptansekriterier:** 
,# language: no
Egenskap: 
Akseptansekriterier:
⦁	Bruker skal kunne returnere fra detaljsiden Datasett og tilbake til framsøkte datasett ved hjelp av lenken "Tilbake til søket".
⦁	Bruker skal kunne returnere fra detaljsiden API-beskrivelser og tilbake til framsøkte AÅI-beskrivelser ved hjelp av lenken "Tilbake til søket".
⦁	Bruker skal kunne returnere fra detaljsiden Begrep og tilbake til framsøkte begrep ved hjelp av lenken "Tilbake til søket".
⦁	Bruker skal kunne returnere fra detaljsiden Informasjonsmodeller og tilbake til framsøkte informasjonmodeller ved hjelp av lenken "Tilbake til søket".
⦁	Lenken "Tilbake til søket" skal ikke vises når bruker navigerer til en detaljside fra andre steder enn søkelister. 
Dekkes ikke:

Referanser:

Nedenfor følger akseptansekriterier for Datasett. Tilsvarende skal utvikles for API-beskrivelser, Begrep oig Informasjonsmodeller.

Scenario: Retur fra detaljside Datasett
Gitt at det finnes en liste over framsøkte datasett 
Og at bruker har navigert til detaljsiden fra søkesiden til et gitt datasett
Så skal bruker kunne trykke på lenken "Tilbake til søket"  
Og forrige søk blant datasett skal vises. 

Scenario: Inngang til detaljside Datasett fra andre steder
Gitt at bruker har navigert til detaljsiden via et annet datasett
Så skal lenken "Tilbake til søket"  ikke vises

**Comment by RogerSOlsen** [comment]
Dette blir ikke prioritert. Dekkes av tilbakeknappen i nettleseren.
