### ISSUE TITLE
[BRUKERHISTORIE] Navigere mellom detaljsider

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#104]
Som: bruker av FDK
Ønsker jeg å: kunne navigere meg mellom treffene mine
Slik at:  jeg slipper å gå frem og tilbake til resultatsiden.

Relatert til epos:

Lenke til design:  https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/345287059

Lenke til løsningsarkitektur:

Akseptansekriterier: 
-# language: no
Egenskap: 
Akseptansekriterier:
⦁	Bruker skal kunne bla blant framsøkte data mellom forrige og neste Datasett detaljside.
⦁	Bruker skal kunne bla blant framsøkte data mellom forrige og neste API-beskrivelse detaljside 
⦁	Bruker skal kunne bla blant framsøkte data mellom forrige og neste Begrep detaljside
⦁	Bruker skal kunne bla blant framsøkte data mellom forrige og neste Informassjonmodell detaljside 

Dekkes ikke:
⦁	Funksjonen "Til toppen" som vises i designskissen er ikke en del av denne brukerhistorien
Referanser:

_Nedenfor følger akseptansekriterier for Datasett. Tilsvarende skal utvikles for API-beskrivelser, Begrep og Informasjonsmodeller._

Scenario: Blaing detaljside Datasett - Midt i rekka
Gitt at det finnes 3 framsøkte datasett 
Og at bruker står på detaljsiden for datasett nr 2 i lista
Så skal bruker kunne navigere direkte til neste detaljside blant framsøkte datasett 
Og bruker skal kunne navigere til forrige detaljside blant framsøkte datasett 

Scenario: Blaing detaljside Datasett - Først i rekka
Gitt at det finnes 3 framsøkte datasett 
Og at bruker står på detaljsiden for datasett nr 1 i lista
Så skal bruker kunne navigere direkte til neste detaljside blant framsøkte datasett 
Og valget "Forrige datasett" skal ikke vises 

Scenario: Blaing detaljside Datasett - Sist i rekka
Gitt at det finnes 3 framsøkte datasett 
Og at bruker står på detaljsiden for datasett nr 3 i lista
Så skal bruker kunne navigere direkte til forrige detaljside blant framsøkte datasett 
Og valget "Neste datasett" skal ikke vises

**Comment by RogerSOlsen** [comment]
Blir ikke prioritert. Er heller ikke etterspurt.
