### ISSUE TITLE
[BRUKERHISTORIE] Lover og hjemler knyttet til API-et

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#105]
Som: bruker av FDK
Ønsker jeg å: se hvilke lover og hjemler som er knyttet til bruk av api-et
Slik at: jeg kan vurdere om jeg kan benytte api-et i min tjeneste

Godkjenningskriterier:
- det skal komme fram om api-et bruker sensitive data
- hjemmelsbolken fra datasett skal gjenbrukes

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@joebrreg oppfylt med lenke til datasett - lukker du denne?

**Comment by joebrreg** [comment]
Denne brukerhistorien er levert. Det er mulig å knytte datasettbeskrivelser, hvor lover og hjemler er beskrevet, til en API-beskrivelse.
