### ISSUE TITLE
[BRUKERHISTORIE] Beskrive standardiserte autentiserings- og autorisaksjonsmekansimer

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#107]
Som: API-konsument
Ønsker jeg å: beskrive standardiserte autentiserings- og autorisaksjonsmekansimer som kan gjenbrukes på tjenester beskrevet for API-ene
Slik at: tilgangsstyring mot flere tjenester kan forenkles

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@stigb trenger vel ikke frontend for dette - bør dette da være en brukerhistorie? Evnt bør vi skrive N/A på disse punktene?

**Comment by sskagemo** [comment]
Denne er duplikat av #8 og følges opp videre der. Lukker denne.
