### ISSUE TITLE
[EPOS] Oppslag på standardiserte API-beskrivelser

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#11]
Behovet treffer de tilfeller hvor samme type data er distribuert på flere organisasjoner, men disse implementerer et "likt" (dvs. standardisert) API.

Det må være mulig å 
1) beskrive API-er som baserer seg på en standard spesifikasjon.  
2) En konsument trenger i kjøretid å vite hvilken server/endepunkt som betjener en organisasjon slik at han kan gjøre et oppslag.

Behovet er uttrykt gjennom
1) Helse, behov for addressering 
2) API-katalogen skal løse DSOP-prosjektenes behov knyttet til eOppslag.
3) Nordic Smart Government, behov for ruting av oppslag til ERP-systemer

Trådskisser (se feltet "Tjenestetype")
Søkeportal: https://69d4ft.axshare.com/#g=1&p=detaljside_api 
Admingrensesnitt: https://69d4ft.axshare.com/#g=1&p=import_ok 

Lenke til overordna arkitektur: [SA_Informasjonsforvaltning](https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/6fc0f5aa-e7df-4765-b5bb-c0fd695c35dc.html)

**Comment by data-david** [comment]
Her er lenke til Confluence med kravene fra Skatt knyttet til DSOP Kontroll: https://confluence.brreg.no/display/KOFUVI/Behov+og+overordnede+brukerhistorier+fra+skatteetaten
 
Her er lenke til brukerhistoriene KoFuVi har lagd i forbindelse med piloten: https://confluence.brreg.no/pages/viewpage.action?pageId=104500561

**Comment by data-david** [comment]
Link til REST-Docs for era-smp:
https://era-smp.ppe.brreg.no/docs/index.html

**Comment by stigbd** [comment]
Ifølge skisser og design skal det inn til vidare heite "Tjenestetype (standard). Navnet på tjenestetypene skal vere som skissene viser, dvs norske.

**Comment by markkopaas** [comment]
De lenkene @data-david sendte ser ut viktige, men er ikke tilgjengelig. Kan du sende de i noe ant formater:
----
Her er lenke til Confluence med kravene fra Skatt knyttet til DSOP Kontroll: https://confluence.brreg.no/display/KOFUVI/Behov+og+overordnede+brukerhistorier+fra+skatteetaten

Her er lenke til brukerhistoriene KoFuVi har lagd i forbindelse med piloten: https://confluence.brreg.no/pages/viewpage.action?pageId=104500561

**Comment by lillelars** [comment]
Hele dette eposet med påfølgende brukerhistorier kan flyttes videre for akseptanse. @stigbd

**Comment by lillelars** [comment]
@stigbd  Kan vi flytte og lukke dette eposet snart...?

**Comment by stigbd** [comment]
Er løst.
