### ISSUE TITLE
[BRUKERHISTORIE] Kommentere på begrepsregistrering

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#110]
Som: Skrivebruker og intern leser 
Ønsker jeg å: kunne kommentere på innholdet til begreper som jobbes med i registreringsløsning
Slik at: jeg kan gi innspill til innholdet

Relatert til epos: #329 
Relatert til brukerhistorier: #79 

Lenke til trådskisser: 
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by marittor** [comment]
Har flyttet tilbake denne da det ikke er skisset på ennå.

**Comment by marittor** [comment]
@AleksandraHrpka Her mangler vi trådskisser, men denne kommer ikke før del 3 av begrepsforvaltning.

**Comment by marittor** [comment]
Oppsummering: 
- Det må kunne gå an å svare på en gitt kommentar (ikke flat struktur).
- Det er ikke behov for å kunne gi en enkeltkommentar til ett enkelt felt, holder med en kommentarfunksjon (et felt) nederst på siden. 
- Kommentarer skal kunne redigeres/slettes av den som har laget kommentaren.

**Comment by KjerstiSteien** [comment]
Løst gjennom https://github.com/Informasjonsforvaltning/behov/issues/807
