### ISSUE TITLE
[BRUKERHISTORIE] Registrere gyldighetsperiode til et begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#111]
Som: skrivebruker
Ønsker jeg å: registrere gyldighetsperiode til et begrep og at det skal komme tydelig fram dersom et begrep ikke ennå er gyldig (blir gyldig), eller det ikke lenger er gyldig (utgått), både med markør og dato. 
Slik at: de som skal bruke begrepene vet hva som er å anse som gyldig/gjeldende. 

Det skal dukke opp en informasjonstekst når man skriver input i gyldig t.o.m, se skisser. 

Gyldighetsperiode som er fylt ut skal dukke opp på detaljside. Varsel om at noe er i ferd med å utgå, skal vises på søkeside, se skisser (må inn lenke) 

Relatert til epos: #153 
Relatert til brukerhistorier: #76 

**Trådskisse**
Scroll ned til "Gyldighet" her: https://vfy2gg.axshare.com/#g=1&p=bokm_l_valgt
Lenke til design
https://invis.io/3SRCN149CQN#/356261432_BEGREP-REG-Gyldighet-Default--D-
Lenke til design - informasjonstekst om lenking til evt erstattende begrep: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356259401 
Lenke til design i portal søkeside:
https://invis.io/3SRCN149CQN#/382272197_BEGREP-PORTAL-S-K-Default--D-
Lenke til design i portal detaljside (to skisser):
https://invis.io/3SRCN149CQN#/387607015_BEGREP-PORTAL-DETALJ-Default-Blir-Gyldig--D-
Lenke til løsningsarkitektur: denne løses ved at [api-et](https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml) må støtte feltene gyldigFom og gyldigTom, samt validering av disse.

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Registrering av datoer
Dekkes ikke:   (Dekkes i andre brukerhistorier) 

Referanser:
Scenario: Registrering av datoer
Gitt at bruker med skriverettigheter er logget inn
Når bruker oppretter en ny "Anbefalt term" 
Så skal bruker kunne registrere verdien "01.01.2019" i feltet  "Gyldig fra og med"
og bruker skal kunne registrere verdien "31.12.2019" i feltet  "Gyldig til og med"

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by tereseskavhaug** [comment]
Klarte å close denne ved en feil, beklager. Håper den ligger riktig nå!

**Comment by lillelars** [comment]
@stigbd - Denne støtter gyldigFom, men trenger å utvids til å støtte gyldigTom ?Ser ikke ut som dette blir støttet

https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml

**Comment by stigbd** [comment]
Er utvida i ny branch feature/addGyldighetsperiode:
https://github.com/Informasjonsforvaltning/concept-catalogue/tree/feature/addGyldighetsperiode

Må implementeres.

**Comment by marittor** [comment]
Bør denne lukkes? Er den ikke levert?
