### ISSUE TITLE
[BRUKERHISTORIE] Tilordne en status til et begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#112]
Som: Skrivebruker
Ønsker jeg å: tilordne et begrep en status (f. eks: Utkast, Publisert (dvs i portal), 
Slik at: jeg kan uttrykke hvilken tilstand begrepet er i 

Relatert til epos: #2 
Relatert til brukerhistorier: #76 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by marittor** [comment]
Må avklares om vi skal ha avpublisert-status, er på saken her.

**Comment by marittor** [comment]
Flyttet tilbake til analysere behov siden det ikke er skisset for Klar til publisering i trådskisser.

**Comment by marittor** [comment]
Skal ikke ha avpublisering, avklart med Difi. Vi mener at når det begrep først er publisert bør det ikke bare fjernes, men heller bli utgått.

**Comment by tereseskavhaug** [comment]
@marittor hvorfor skal vi ha "Klar til publisering" her? Da må i så fall én rolle ha skrivetilgang uten publiseringstilgang, og en annen ha skrivetilgang med mulighet for publisering. Jeg oppfattet det som at behovet for å ha skriverolle uten publiseringstilgang ikke var så stort. Det forutsetter at denne rollen opprettes, noe jeg trodde vi ikke skulle i første omgang?

**Comment by marittor** [comment]
Er ivaretatt av #76 og #81 og lukkes derfor.
