### ISSUE TITLE
[BRUKERHISTORIE] Oversikt for å vurdere etterlevelse - tilsynsmyndigheter

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#113]
Som: Tilsynsmyndighet 
Ønsker jeg å: få oversikt over etatens behandlingsaktiviteter 
Slik at: jeg enklere kan vurdere etterlevelse av (GDPR-) forordningens regler.

Relatert til epos: #10 

Lenke til trådskisser: https://69d4ft.axshare.com/#g=1&p=oversiktside_protokoll_s_kbehandlingsaktiviteter 
Lenke til design:  
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@marittor #114 #115 #113 --> beskriver disse tre brukerhistoriene samme funksjon i løsningen? Eller tolker du det slik at hver av disse har tre ulike roller i løsningen vår?

**Comment by tereseskavhaug** [comment]
@marittor er dette en annen side/funksjonalitet enn oversikttsiden: https://69d4ft.axshare.com/#g=1&p=oversiktside_beh_akt_ ?

**Comment by marittor** [comment]
Dekkes av  #168  og #169 og lukkes derfor.
