### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over etatens behandlingsaktiviteter - sikkerhet

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#114]
Som: Sikkerhetsansvarlig 
Ønsker jeg å: ha oversikt over etatens behandlingsaktiviteter og systemer
Slik at: jeg kan holde oversikt over hvor det er gjennomført ros-analyse, DPIA og når. 

Relatert til epos: #10 

**Trådskisser**
Oversiktsside for behandlingsaktiviteter: https://69d4ft.axshare.com/#g=1&p=oversiktside_beh_akt_

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@marittor Er #115 og #114 duplikater?/kunne vært dratt inn i samme brukerhistorie?

**Comment by marittor** [comment]
Dekkes av #168 og #169, lukkes derfor.
