### ISSUE TITLE
[BRUKERHISTORIE] Behov for oversikt ifm innsynsbegjæringer

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#118]
Som: Kontaktpunkt for innsynsbegjæringer
Ønsker jeg å: få oversikt over hvilke behandlingsaktiviteter og personopplysninger som behandles. 
Slik at: jeg enkelt og effektivt kan behandle innsynsbegjæringer

Relatert til epos: #10 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@marittor betyr dette at vi skal ha flere statuser på behandlingsaktiviteter? Nå har vi skissert bare for "Utkast" og "publisert"

**Comment by tereseskavhaug** [comment]
@marittor er dette en annen side/funksjonalitet enn oversikttsiden? https://69d4ft.axshare.com/#g=1&p=oversiktside_beh_akt_

**Comment by marittor** [comment]
Dekkes av #168 og #169, lukkes derfor.
