### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over personopplysninger som behandles på eget tjenesteområde

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#120]
Som: Tjenesteeier
Ønsker jeg å: få oversikt over alle behandlingsaktiviteter som skjer i min tjeneste og hvordan den skjer. 
Slik at: jeg får kjennskap til hva som skjer på eget tjenesteområde

Relatert til epos: #10 

Fordrer at man kan registrere og sortere på tjenesteområder/fagområder per behandlingsaktivitet? 

Trådskisser:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@marittor samme spørsmål som i #113 #114 #115... Er disse fire brukerhistoriene egentlig samme funksjon eller er det faktiske ulike roller i løsningen vår?

**Comment by tereseskavhaug** [comment]
@marittor er dette en annen side/funksjonalitet enn oversikttsiden? https://69d4ft.axshare.com/#g=1&p=oversiktside_beh_akt_

**Comment by marittor** [comment]
@tereseskavhaug Litt usikker på om det er et ønske om å kunne sortere på fag/tjenesteområder (intern kodeliste i hver virksomhet)? Skal sjekke opp dette med behovseier.

**Comment by marittor** [comment]
Lukkes etter avklaring med behovseier.
