### ISSUE TITLE
[BRUKERHISTORIE] LOS - Registrering av datasett der de blir tagget med tema

### ISSUE THREAD

**Issue by joachim-me** [Informasjonsforvaltning/behov#121]
Relatert til epos: #36 
Relatert til brukerhistorie #128 

Som eier av et datasett
ønsker jeg å tagge mine datasett med emneord så presist som mulig
slik at jeg forenkler gjenfinning av datasett.

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
•	Et datasett skal kunne ha null-til-mange tema
•	Et datasett skal kunne ha tema på flere nivå, (hovedkategori, underkategori, emneord)
•	Bruker skal kunne plukke temaord til et datasett fra et LOS-hierarki eller med frisøk mot LOS termer

Dekkes ikke:

Referanser:
https://docs.google.com/document/d/1ZOkBDpVLUtUHiROJo88p8NYDdInnIydxxme5rOxKE3U/edit?ts=5c90f41e#

Scenario: Et datasett skal kunne ha mange tema
Gitt at Datasettet "IQ1" eksisterer i registreringsløsingen
Når bruker åpner opp datasettet for editering
Så skal bruker kunne legge til temaene "mobbing" og  "helse"

Scenario: Et datasett skal kunne ha tema på flere nivå, (hovedkategori, underkategori , emneord)
Gitt at Datasettet "IQ1" eksisterer i registreringsløsingen
Når bruker åpner opp datasettet for editering
Så skal bruker kunne legge til tema "Arbeid" fra hovedkategori
Og bruker skal kunne legge til tema "Arbeidsliv" fra underkategori
Og bruker skal kunnr legge til emneordet  "Mobbing" ++

Scenario: Bruker skal kunne plukke temaord til et datasett fra et LOS-hierarki eller med frisøk mot LOS termer
Gitt at Datasettet "IQ1" eksisterer i registreringsløsingen
Når bruker åpner opp datasettet for editering
Så skal bruker kunne velge tema  "Inntekt" fra et hierarki
Og bruker skal kunne søke fram og velge tema "mobbing" ved hjelp av frisøk

**Trådskisser**
Utgangspunkt for trådskisser, konkludert i arbeidsmøter:
- Vi viser default 1. og 2.-nivå på kategorier
- Emner skjules, men kan søkes etter
- Dersom man velger tema, vil tilhørende emner vises
- Dersom man søker etter et emne, vil kun tilhørende tema vises i temalisten
- Valgte tema og emner vises som boks med kryss, på samme måte som på filtrering i portal

Default (scroll til "Tema")
https://69d4ft.axshare.com/#g=1&p=registrer_ny_datasettbeskrivelse

Tema valgt
https://69d4ft.axshare.com/#g=1&p=tema_valgt&hi=1

Tema og emne valgt
https://69d4ft.axshare.com/#g=1&p=tema_og_emne_valgt&hi=1

Søk med treff på emne, uten tema valgt
https://69d4ft.axshare.com/#g=1&p=s_kt_etter_emne&hi=1

Lenke til design: 
Lenke til løsningsarkitektur:

Nyttig info:
Illustrasjon om hvordan LOS er bygd opp:
https://doc.difi.no/los/

Ser at norge.no benytter LOS - ta en titt her:
https://www.norge.no/nb/search/site/mobbing

**Comment by lillelars** [comment]
Ser at norge.no benytter LOS - ta en titt her:
https://www.norge.no/nb/search/site/mobbing

**Comment by sskagemo** [comment]
Med tanke på senere tilgjengeliggjøring via DCAT er det et poeng at vi fortsatt beholder knytning til Data theme fra EUs Publication Offices:

Fra DCAT-standarden:
"Referanse til et hovudtema for datasettet. Et datasett kan assosieres med flere tema. Bruk av vokabularet Data theme som er publisert av EUs Publication Offices er påkrevd. Bruk av Difis Los-vokabular er anbefalt. Også andre nasjonale og internasjonale vokabular kan brukes om de oppfyller denne standardens krav til kontrollerte vokabular."
