### ISSUE TITLE
[BRUKERHISTORIE] Ta med eksempelfelt i spørringen til begrepspubliserer 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#123]
Som: produkteier for BR begrepskatalog
Ønsker jeg å:  kunne hente ut data som ligger i eksempel-feltet til BEGREP via begrepspublisereren
Slik at: jeg kan tilgjengeliggjøre eksempler under begreps-fanen (detaljsiden) i Felles datakatalog

Se Confluence for spesifikasjon: https://confluence.brreg.no/pages/viewpage.action?pageId=93422058 

Relatert til epos: -

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by stigbd** [comment]
Antar vi snakkar om følgande felt:

| Felt i Jira | Felt i standarden | URI til defiinisjon | Eksempel SKOS | Datatype | Eksempel på begrep |
| ---------- | ------------------ | ------------------- | ---------------- | ---------- | ----------------------- |
| fields.customfield_14900 | Begrep.eksempel.språkMålform | skos:example | <> skos:example “”@no . |

**Comment by marittor** [comment]
> 
> 
> Antar vi snakkar om følgande felt:
> Felt i Jira 	Felt i standarden 	URI til defiinisjon 	Eksempel SKOS 	Datatype 	Eksempel på begrep
> fields.customfield_14900 	Begrep.eksempel.tekst 	skos:example 	skos:example “dittogdatt”@no 		
> 
> @marittor : Har du lenke til eit begrep i Jira som brukar dette feltet?

Det stemmer, se godkjente begreper med eksempler her: https://jira.brreg.no/issues/?jql=project%20%3D%20BEGREP%20AND%20issuetype%20%3D%20Begrep%20AND%20status%20%3D%20Godkjent%20ORDER%20BY%20cf%5B14900%5D%20ASC (sortert ascending med de begreper med eksempler først)

**Comment by stigbd** [comment]
Utført og løsning akseptert.
