### ISSUE TITLE
[BRUKERHISTORIE] Etablere støtte for å høste begreper formattert i tråd med standarden TBX-AP-NO 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#126]
Gitt at virksomheten har en begrepskatalog i virksomheten
og at denne katalogen eksponerer sine begreper som TBX-AP-NO
Som: virksomhetens Admin i Begrepskatalogens GUI
Ønsker jeg å: kunne sette opp høsting av min virksomhets begrepskatalog
Slik at: jeg kan få publisert begrepene i Felles Datakatalog Portal

TBX-AP-NO [(Difi, høringsversjon](https://www.difi.no/sites/difino/files/vedl2_-_horingsnotat_med_forslag_til_forvaltningsstandarder_for_maskinell_tilgjengeliggjoring_av_begrepsbeskrivelser_2018-08-17.pdf  ))

Relatert til epos: #345 

Forretningsverdi: viktig
Lenke til design: N/A
Lenke til løsningsarkitektur: dette løses ved å implementere tre ting:
1. concept-cat applikasjonen må støtte høsting av tbx-ap-no
2. det må lages en backend (fdk-harvester-adm) som holder på endepunkter
3. det må lages et gui der administrator kan registrere (endre, slette, etc) endepunkter i fdk-harvester-adm.
Arkitektur likt som her: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/f48b3ecc-ae46-45c0-8e5a-bc73889e185c.html

**Akseptansekriterier:**
,# language: no

Egenskap: 
Kriterier:
⦁	Høste begrep vha TBX-AP-NO

Dekkes ikke:

Referanser:
https://www.difi.no/sites/difino/files/vedl2_-_horingsnotat_med_forslag_til_forvaltningsstandarder_for_maskinell_tilgjengeliggjoring_av_begrepsbeskrivelser_2018-08-17.pdf

Scenario: Høste begrep ved bruk av standarden TBX-AP-NO
Gitt at "Språkrådet" tilbyr Begrep (Alle felt) ved hjelp av standarden TBX-AP-NO
Så skal det automatisk høstes nye begrep fra "Språkrådets Termwiki" 
Og de nye begrepene skal vises på søkesiden i søkeportalen

**Comment by lillelars** [comment]
@marittor betyr dette at vi skal støtte TBX formatet i tillegg til SKOS? 
trenger vel ikke skisser på dette ? kan vi i såfall skrive N/A på disse punkten

**Comment by marittor** [comment]
Det stemmer. Vi trenger ikke skisser på dette. setter N/A.

**Comment by marittor** [comment]
Vil gjerne ha Språkrådets termwiki som pilot her.

**Comment by marittor** [comment]
Språkrådet har notert status hos seg: "Vi er klare (TBX-format): http://www.termwiki.sprakradet.no/wiki/Hovedside "

**Comment by marittor** [comment]
@sindresandvik2 Det blir litt snevert scenario kun å skrive "anbefalte termer", for egentlig gjelder dette å kunne høste alle feltene i standard for begrepsbeskrivelser som Språkrådet (eller andre) mappet til TBX-AP-NO, tilsvarende slik vi gjorde det når vi lagde støtte for å høste begrepsbeskrivelser på SKOS-AP-NO-formatet.

**Comment by sindresandvik2** [comment]
Enig i kommentar.  Akesptansekriteriet er gjort meir generell til å gjelde alle "begreps-felt"

**Comment by Te-Bert** [comment]
Vi var tidligere i dialog med Standard Norge for å se på mulighetene til å høste begreper basert på TBX-standarden fra termbasen SNORRE. Det ble gjort en tilrettelegging og en test som viste at dette kunne fungere.
Senere har det kommet frem at innholdet i SNORRE også vil bli tilgjengelig via den nye Termportalen - basert på SKOS. Vi har ikke vært i kontakt med andre termbaser som benytter TBX. Hvis disse også blir tilgjengelig i Termportalen, trenger vi kanskje bare å støtte høsting av innhold basert på SKOS.

**Comment by KjerstiSteien** [comment]
@Te-Bert Har du hørt noe mer om dette? Kan vi lukke saken og satse på at innholdet i SNORRE blir tilgjengelig i Termportalen?

**Comment by KjerstiSteien** [comment]
Jeg lukker denne, da vi ikke lenger kjenner til noen virksomheter som bruker TBX-AP-NO.
