### ISSUE TITLE
[BRUKERHISTORIE] Legge til labels på begrep, offentlig sektor, Felleskomponent, standard mv.

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#13]
Som: skrivebruker
Ønsker jeg å: kunne tagge begreper (offentlig godkjente/sektor/standard osv.)
Slik at: det blir enklere å benytte/gjenbruke referansearkitekturer.

EPOS: #2 
Relatert til brukerhistorie: #76 
Relatert til brukerhistorie #384

**Comment by marittor** [comment]
#2

**Comment by marittor** [comment]
Det er også kommet behov om som ligner: F. eks tillits”score” for hver term (eks. 86%) beregnet med algoritme ut fra “sist oppdatert” “eier” “hvor mye lenket/brukt” etc. slik at man kan vurdere hvor mye man kan stole på dataene.

**Comment by marittor** [comment]
Kan trolig løses på samme måte som nasjonal felleskomponent-tag, eller autoritativ kilde-tag?

**Comment by KjerstiSteien** [comment]
Regner denne som løst, da man har mulighet til å legge til labels i registreringsløsning.
