### ISSUE TITLE
[BRUKERHISTORIE] Høste "eksempel"-felt 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#130]
Som: Felles datakatalog 
Ønsker jeg å: kunne hente ut data som ligger i eksempel-feltet via begrepspublisereren, fra https://data.brreg.no/begrep/
Slik at: jeg kan tilgjengeliggjøre eksempler under begreps-fanen (detaljsiden) i Felles datakatalog

Krav: 
eksempel-feltet skal representeres i SKOS, slik at dette kan gjenbrukes ved høsting fra andre som bruker SKOS, slik som angitt i kolonne 4: "Begrep.eksempel.tekst" på side 4. i SKOS-AP-NO-standarden(pdf s. 19): https://www.difi.no/sites/difino/files/vedl2_-_horingsnotat_med_forslag_til_forvaltningsstandarder_for_maskinell_tilgjengeliggjoring_av_begrepsbeskrivelser_2018-08-17.pdf 

Relatert til epos: -
Relaterte brukerhistorier: #123 (intern jobb på begrepspubliserer)

Lenke til design: https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/326837011 
Lenke til løsningsarkitektur:

**Akseptansekriterier**
,# language: no
Egenskap: 

Kriterier: 
⦁	Alle begrep som har tilknyttet eksempel skal vise dette på begrep detaljside
⦁	Alle begrep som har ikke har tilknyttet eksempel skal ikke vise dette på begrep detaljside

Scenario: Vise eksempel for begrep
Gitt at publisert begrep har verdier i feltet eksempel
Så skal feltet eksempel vises på detaljsiden for gitt begrep
Og menyvalget "Eksempel" skal vises i venstremenyen

Scenario: Vise  begrep som ikke har eksempel
Gitt at publisert begrep ikke har verdier i feltet eksempel
Så skal feltet eksempel ikke vises på detaljsiden for gitt begrep
Og menyvalget "Eksempel" skal ikke vises i venstremenyen

**Comment by lillelars** [comment]
@marittor Vet du om noen begreper som bruker dette feltet i dag?

**Comment by marittor** [comment]
@lillelars: https://jira.brreg.no/issues/?jql=project%20%3D%2012400%20AND%20status%20%3D%20Godkjent%20ORDER%20BY%20cf%5B14900%5D%20ASC (lenke til intern Begrepskatalog), se eksempler i kolonnen engst til høyre.

**Comment by marittor** [comment]
T.o: Noen av eksemplene vi leverer fra oss per idag er formattert slik: 
ditt
datt
ting

Dette vil endres til å være opplisting med komma, slik som designskissene viser. Kan hende det ser litt rart ut i løsningen første neste dagene dersom dette kommer på plass tidligst mandag (de som skal gjøre jobben internt på BR er tilbake først til uka)

**Comment by lillelars** [comment]
Eksempel finnes ved:
Step 1: naviger til side:: https://data.brreg.no/begrep/
Step 2: ctrl+f søk etter: http://data.brreg.no/begrep/52060 
Step 3: Se under core#example

**Comment by sindresandvik2** [comment]
Denne historien er nå klar for Akesptansetest.  Kan nå sjekkast i UT1.  Blir etter planen produksjonssatt i morgon!

**Comment by marittor** [comment]
Dette ser fint ut. Setter til utført.
