### ISSUE TITLE
[BRUKERHISTORIE] Ny status på datasett

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#133]
Som dataeier
Ønsker jeg i registreringsløsningen å kunne styre publiseringen av et datasett
Slik at den kan publiseres enten kun til virksomhetsintern datasettkatalog eller til både virksomhetsintern datasettkatalog og felles datasettkatalog

Relatert til epos: #5 

Lenke til design (flyt på flere klikkbare skisser):
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/392127787
Lenke til løsningsarkitektur:

Akseptansekritereier: Datasettet er publisert kun på virksomhetsintern datasettkatalog eller på begge

**Comment by lillelars** [comment]
@BRespen bør alle disse være knyttet til et EPOS?

**Comment by BRespen** [comment]
Samme brukerhistorie som #235 ?

**Comment by BRespen** [comment]
Mange virksomheter har ikke ressurser eller ambisjoner om å etablere egne løsninger for informasjonsforvaltning knyttet til "orden i eget hus". I og med at forvaltningsbehovet er overlappende mellom virksomhetene kan de tenke seg en funksjonell "fellesløsning" som kan brukes til denne oppgaven. Grunnkonseptet er å dokumentere den informasjonen de forvalter på en standardisert måte. Vårt (FDK) utgangspunkt har vært å starte med informasjon som kan/skal distribueres, men virksomhetene vil også kunne se behovet opp mot dokumentering i forhold til system, arkiv, GDPR, prosesser, tjenester, sikkerhet, kvalitet, lovverk osv. I dette ligger det potensial for en gradvis utvidelse av nye felter som dekker disse ulike behovene. Disse behovene kan være direkte knyttet mot datasettene eller også mot begrep og modeller. Det er viktig at en slik virksomhetsintern datasettkatalog kun er tilgjengelig for virksomheten slik at den kan dekke interne behov uten fare for å eksponere dette utad. Noen av datasettene er kun for intern bruk mens andre skal eksponeres over i felles datasettkatalog. Det må derfor være funksjonalitet for "publiser til FDK" slik at virksomhetene har full kontroll på hva som skal eksponeres utad.
