### ISSUE TITLE
[BRUKERHISTORIE] Forvaltningskommentar

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#134]
Som dataeier
Ønsker jeg å beskrive interne kommentarer til datasettet
Slik at dette er kjent for interne brukere, men ikke for eksterne

Relatert til epos: #5 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by marittor** [comment]
Er dette duplikat til #63 ?

**Comment by BRespen** [comment]
Vurderes å være dekt av #213 og lukkes derfor
