### ISSUE TITLE
[BRUKERHISTORIE] Eksponere Felles begrepskatalog som TBX-AP-NO

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#135]
Som: konsument av FDK sitt begreps-API
Ønsker jeg å: konsumere den publiserte begrepssamlingen som TBX-AP-NO
Slik at: jeg kan enkelt bruke begrepssamlingen på en standardisert måte

Relatert til epos: #345 
Relaterte brukerhistorier #126 
Forretningsverdi: viktig

Lenke til design: N/A
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Lukker denne, da vi ikke lenger kjenner til noen virksomheter som bruker tbx-ap-no
