### ISSUE TITLE
[BRUKERHISTORIE] Mapping av URLer fra data.norge.no til FDK-løsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#138]
Som: bruker av dagens data.norge.no
Ønsker jeg at: dagens urler fører meg til det samme innholdet i ny løsning
Slik at: djuplenker til datasett og annet innhold fremdeles fungerer

Relatert til epos: #91 
Relaterte brukerhistorier: https://github.com/Informasjonsforvaltning/fdk/issues/1457  

Moglege løysingar:
a) Treff på gammal URL gir ein redirect til nye URL.
b) Tilsvarande sider på nye plattformen har samme URL

**"Must have"-lenker**
Offisielle landingssider for NLOD-lisensen:

Landingssider:
https://data.norge.no/nlod/no
https://data.norge.no/nlod/en
https://data.norge.no/nlod/ (redirect til rett språk)

Juridiske tekstar:
https://data.norge.no/nlod/no/2.0
https://data.norge.no/nlod/no/1.0
https://data.norge.no/nlod/en/2.0
https://data.norge.no/nlod/en/1.0

Lenke til design: 
Lenke til løsningsarkitektur: definere ein mapping mellom gamle og nye URLer

**Comment by livarb** [comment]
Er det landingsside for oversikt over alt innhald frå ei verksemd i dagens FDK?
https://data.norge.no/organization/registerenheten-i-br%C3%B8nn%C3%B8ysund

**Comment by lillelars** [comment]
@livarb @oystein-asnes  I stedet for å  "mappe URL'er" fra:
https://data.norge.no/nlod/no
https://data.norge.no/nlod/en
https://data.norge.no/nlod/(redirect til rett språk)
https://data.norge.no/nlod/no/2.0 (juridisk tekst)

Kan vi ikke opprette nye artikkelsider på dette?
I første omgang benytter vi mock-filen (bare for å berike startsiden og disse sidene og legger inn disse som egne artikkel-sider),
men så fort portal-teamet har prodklar CMS så kan redaktørene våre opprette disse sidene..
Hva tenker dere?

**Comment by livarb** [comment]
@lillelars : Med å "opprette nye artikkelsider", betyr det at URL-ane du nemner ikkje fungerer? Det er mange som lenker til dei URL-ane, så i den nye løysinga bør ein framleis kome fram til rett innhald. NLOD-lenkene er nok dei viktigaste URL-ane å behalde i nye løysinga.

**Comment by stigbd** [comment]
Er det landa noko på denne? Eg foreslår at nlod ikkje blir lagt til som artikkel, men som statiske sider på same måte som specification/dcat-ap-no etc. Då vil gamle url funke som før. Men eitt eller anna må lage innhaldet. Ligg disse tinga i drupal i dag?

**Comment by stigbd** [comment]
Ettersom vi er einige om å legge dette til eit repo i GitHub, har eg oppretta repo:
https://github.com/Informasjonsforvaltning/nlod

**Comment by livarb** [comment]
@stigbd : Supert! Spørsmålet er då om vi skal legge dei to landingssidene i FDK og kun ha lisenstekstane i repo'et, eller om vi skal ha alt i repo'et. Tippar det sistnemde er enklast. @oystein-asnes

**Comment by livarb** [comment]
Midlertidige redirects er sett opp for datasett og organisasjonar.
