### ISSUE TITLE
[EPOS] Redaksjonelt innhold på data.norge.no/FDK

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#139]
Som: Pådriver for innhold i katalogene (data.norge.no/FDK)
Ønsker jeg å: publisere og redigere dynamisk og statisk innhold på portalen
Slik at: jeg kan bruke portalen som informasjonskanal for pådriverarbeid, veiledning, mm

Syndikering av innhold med (fra) digdir.no (Drupal 8) må vurderes (for eksempel basert på tags). 

Relatert til epos: , #91 #187 #420
Relatert til brukerhistorie #469 #470 
Lenke til design:

**Comment by oystein-asnes** [comment]
@lillelars Vi jobber nå konkret med å få Digdirs Drupal 8 site til å eksponere et REST-API. Oppgaven for FDK-utviklingsteam vil da være avgrenset til å hente innhold inn i FDKs frontend-rammeverk.

**Comment by shenluna** [comment]
Relatert til sammenslåing som ble fullført i 2020, lukker eposet.
