### ISSUE TITLE
[BRUKERHISTORIE] Twitter-embed på data.norge.no

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#140]
Som: Redaktør av data.norge.no
Ønsker jeg å: bygge inn Difis åpnedata-konto på Twitter (eller søk og filtrering som vi har definert)
Slik at: vi kan kommunisere med brukerne og publisere nyheter på portalen

Relatert til epos: #187 #420 

Dagens filter på data.norge.no:
#opnedata OR #åpnedata OR from:opnedata exclude:retweets

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til løsningsarkitektur:

Twitter-feed kjem ikkje frå Drupal headless-CMS. Ein må hente inn desse dataa sjølv frå Twitter sitt API. Avklaring med Sture i videomøte 11/3.

**Comment by livarb** [comment]
La inn info om Twitter-filteret for Twitter-embed på data.norge.no i dag.
Denne oppskrifta bør kanskje endrast. F.eks. til å både ta inn tweets frå FDK-kontoen og @opnedata-kontoen?

**Comment by livarb** [comment]
Oppdaterte beskrivinga, la til:
Twitter-feed kjem ikkje frå Drupal headless-CMS. Ein må hente inn desse dataa sjølv frå Twitter sitt API. Avklaring med Sture i videomøte 11/3.

**Comment by livarb** [comment]
Foreslår vi går for å vise innhald for emneknaggane #opnedata og #åpnedata og tweets frå kontoane @opnedata og @datakatalogen. Ser vi hadde exclude:retweets på filteret i data.norge.no. Foreslår ein testar og ser kva ein tykkjer er best når det gjeld akkurat den biten.

**Comment by oystein-asnes** [comment]
Denne har ligget i konstruksjon lenge. Hva skal til for å dytte denne over kanten @shenluna ?

**Comment by shenluna** [comment]
Fjerner komponenten fra forsiden, men legger til lenke til twitter i footeren.
