### ISSUE TITLE
[BRUKERHISTORIE] God kommunikasjon og veiledning ved migrering av brukere

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#141]
Som: Tilbyder av datasett i dagens data.norge.no
Ønsker jeg å: motta enhetlig informasjon og veiledning om flytting til ny registreringsløsning
Slik at: overgangen blir så sømløs som mulig for virksomheten

Relatert til epos: #186 
Relatert til brukerhistorie #92 
Lenke til design: 
Lenke til løsningsarkitektur:

Tiltak:
- Sende e-post til alle kontakter registrert i data-oppføringar på data.norge.no
- Aktuelt-post på data.norge.no
- Tweet frå @opnedata
- Send info til kommunikasjonsavd. (KOM) så dei kan skrive artiklar (digdir.no?)

**Comment by lillelars** [comment]
Hva gjør vi med denne? @livarb @oystein-asnes  Har vi begynt kommunikasjon med brukere enda?

**Comment by livarb** [comment]
Foreslår vi sender ut e-post til alle kontaktpersonar og legg ut aktuelt-post på data.norge.no (og tweet'er om posten).

**Comment by livarb** [comment]
La inn liste over tiltak i beskrivinga. La også til punktet foreslått nettopp om å sende info til KOM.
