### ISSUE TITLE
[BRUKERHISTORIE] Avsjekk om alt innhold blir migrert til FDK 

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#142]
Som: Systemeier for dagens data.norge.no
Ønsker jeg å: ta en avsjekk om det kan være innhold i datasett-katalogen (på dagens data.norge.no)  som ikke blir høstet av FDK
Slik at: jeg kan sikre at informasjon ikke går tapt ved migrering til ny registreringsløsning

Relatert til epos: #186 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by livarb** [comment]
Lenker på datasett har gått tapt under migreringa. Skal finne fram detaljar om dette.

**Comment by livarb** [comment]
@oystein-asnes : Foreslår denne kan lukkast. Problem med tittel på lenker som ikkje vart migrert tar vi i #432
