### ISSUE TITLE
[BRUKERHISTORIE] Menneskelesbare formater i GUIet

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#145]
Som: bruker av FDK/data.norge
Ønsker jeg å: en intuitiv måte å se hvilke formater datasettene er tilgjengelig på 
Slik at: jeg slipper å forholde meg til lange identifikatorer som dette: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

Relatert til epos: #91 
Relatert til brukerhistorie #411 og #422 

Noe alá dette: https://data.norge.no/data/aure-kommune/budsjett-og-%C3%B8konomiplan-2014-2017 
Lenke til design, søkeside: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/search-default.html
Lenke itl skisse, detaljside: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html
Lenke til løsningsarkitektur: lage mapping fra gyldige IANA-verdier til mer menneskelesbare designelement

Akseptansekriterie:

- Bruker skal se hvilke formater datasettene er tilgjengelige på allerede i sammendragsboksene. Dette skal vises som enkle ikoner
- Dersom datasettet har flere distribusjoner som gir samme format skal det vises antall av denne type distribusjon i sammendragsboksen
- På detaljesiden skal bruker se tydelige ikoner per distribusjon for hvilke formater som er tilgjengelige fra denne distribusjonen
- Distribusjonsbeskrivelsene skal kunne ekspanderes hvor formatet også skal være skrevet i klartekst (dette mtp UU)

Scenario: Bruker skal se hvilke formater datasettene er tilgjengelige på allerede i sammendragsboksene. 
Gitt at det finnes datasett på minst et format
og bruker står på resultatsiden for datasettbeskrivelser
Så skal datasettbeskrivelser vise formatet i sammendragsboksen

Scenario: Dersom datasettet har flere distribusjoner som gir samme format skal det vises antall av denne type distribusjon i sammendragsboksen
Gitt at det finnes datasett som har distribusjon som gir flere av samme format
og bruker står på resultatsiden for datasettbeskrivelser
Så skal datasettbeskrivelsen vise antallet hver distribusjon gir av hvert format i sammendragsboksen

Scenario: På detaljesiden skal bruker se tydelige ikoner per distribusjon for hvilke formater som er tilgjengelige fra denne distribusjonen
Gitt at det finnes datasett på minst et format
og bruker står på detaljesiden for en slik datasettbeskrivelse
Så skal det vises ikoner per distribusjon for de tilgjengelige formatet

Scenario:Distribusjonsbeskrivelsene skal kunne ekspanderes hvor formatet også skal være skrevet i klartekst 
Gitt at det finnes datasett på minst et format
og bruker står på detaljesiden for en slik datasettbeskrivelse
når bruker trykker på en distribusjon
Så skal distribusjonen ekspanderes 
og det skal vises formatet datasettet er tilgjengelig på i klartekst

**Comment by livarb** [comment]
Forstod det slik at det også kjem eksempel på korleis eit ukjent format (representert som "Annet" eller liknande) vert vist. 

Tenker det bør vere mogleg å sjå meir informasjon inne på detaljvisninga enn berre "Annet", til dømes sjå mime-type.

**Comment by livarb** [comment]
Fungerer ikkje på teknisk kjøretøyinformasjon frå vegvesenet:
![image](https://user-images.githubusercontent.com/3617256/80989058-b2f3ff00-8e34-11ea-8959-c8c2e060fcd8.png)
På den første blir ikkje mime-typar omsett til korte. På den andre blir ikkje dei ulike formata slått saman til ei liste, så verdiane blir duplisert mange ganger.

Angåande akseptansekriterie nr. 2 ("Dersom datasettet har flere distribusjoner som gir samme format skal det vises antall av denne type distribusjon i sammendragsboksen"). Eit alternativ kan vere å droppe antallet format heilt. Tenker det er overflødig informasjon. Har ikkje nokon sterke meiningar her. Det viktigaste er at eit format ikkje blir gjentatt fleire gangar dersom det er fleire distribusjonar som har samme format.

**Comment by shenluna** [comment]
Fungerer nå for Teknisk kjøretøyinformasjon, hvor navnene til mediatypene fra IANA blir vist.
![image](https://user-images.githubusercontent.com/73637969/134491427-b9317ea5-099c-4b0e-8fe4-8ee43942a8ed.png)
