### ISSUE TITLE
[BRUKERHISTORIE] Behov for å importere begrep på TBX-AP-NO-format i begrepsregistreringen 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#147]
Som: Skrivebruker
Ønsker jeg å: Jeg ønsker å importere mine begreper som jeg har representert i TBX-AP-NO
Slik at: jeg kan jobbe videre med dem i registreringsløsningen.

Relatert til epos: #345 
Relaterte brukerhistorier: #146 
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
@Te-Bert @oystein-asnes Kan dere diskutere om tbx-ap-no er en spek som fortsatt anses som relevant for begrep?

**Comment by KjerstiSteien** [comment]
vi ser ikke noen som har dette behovet i dag. Lukker derfor saken og oppretter heller et nytt issue, dersom behovet dukker opp senere.
