### ISSUE TITLE
[BRUKERHISTORIE] Angi "forhold til kilde" i tråd med standarder fra Difi (begrep)

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#148]
Som: Skrivebruker som skal opprette/oppdatere begrep
Ønsker jeg å: kunne angi "forhold til kilde"
Slik at: jeg kan si noe om hvorvidt begrepet er et sitat, basert på eller om det er egendefinert, slik Standard for begrepsbeskrivelser legger opp til. 

Forhold til kilde skal være definert som en kodeliste og ha følgende verdier: 
Sitat fra kilde
Basert på kilde
Egendefinert

Når Egendefinert er valgt, skal denne teksten "Egendefinert" dukke opp i kildefeltet. Se designskisser for portal for hvordan dette var tenkt løst sammen med kilde og hyperlenke. 

Forhold til kilde skal plasseres over tittel og lenke på kilde, slik at brukeren kan ta stilling til dette før han ser tittel og lenkefelt

Relatert til epos: #2 
Relaterte brukerhistorier: #76 

**Trådskisser**
Se bolken "Term, definisjon og kilde", scroll til "Kilde til definisjon" --> "Forhold til kilde": https://69d4ft.axshare.com/#g=1&p=registrer_nytt_begrep_skriverolle

Lenke til design: 
Lenke til løsningsarkitektur:

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Registrering av "Forhold til kilde" i ny "Anbefalt term"
⦁	Oppdatering av "Forhold til kilde" i eksisterende "Anbefalt term"
Dekkes ikke:   (Dekkes i andre brukerhistorier) 

Referanser:
Scenario: Registrering av "Forhold til kilde" i ny "Anbefalt term"
Gitt at bruker med skriverettigheter er logget inn
Når bruker oppretter en ny "Anbefalt term" 
Så skal bruker kunne registrere verdien "Sitat fra kilde" i feltet  "Forhold til kilde"

Scenario: Oppdatering av "Forhold til kilde" i eksisterende "Anbefalt term"
Gitt at bruker med skriverettigheter er logget inn
Gitt at "Anbefalt Term" = "Saksarkiv" finnes 
Når bruker åpner "Anbefalt term" = "Saksarkiv" 
Så skal bruker kunne registrere verdien "Basert på kilde" i feltet  "Forhold til kilde"

**Comment by marittor** [comment]
Kan vi ta en prat om denne på møte senere idag, @tereseskavhaug ?

**Comment by marittor** [comment]
Diskutert på innføringsmøte 10. mai: 

Her ser det ut som om vi bør gjøre noen tilpasninger (selv om standard lister opp ft kilde som kodeliste). Man bør kanskje kunne huke av for at begrepet er egendefinert, og da kan virksomhetens navn hentes opp og vises ved siden av feltet i detaljside, f. eks slik: Egendefinert av <hent ansvarlig virksomhet> "Skatteetaten"? Når vi jobber oss gjennom dette og prøver å bruke det i praksis, så er det ikke naturlig at brukeren går til "forhold til kilde" når virksomheten har definert dette selv. @AleksandraHrpka og @eggedosis , kan vi se på dette sammen i skissene?

**Comment by marittor** [comment]
Har flyttet tilbake denne da det ikke er skisset på siste ønske fra innføringsteamet ennå.

**Comment by marittor** [comment]
Avklart på møte 25.6 at vi flytter forhold til kilde opp over tittel og lenkefelt til kilde. Beholder egendefinert som del av kodelisten all den tid det er anbefalt i standarden.

**Comment by marittor** [comment]
@sindresandvik2, denne kan jeg vel flytte over til I Kontruksjon?

**Comment by sindresandvik2** [comment]
Jepp. Flytt!
