### ISSUE TITLE
[BRUKERHISTORIE] SKOS-AP-NO-begrep validator

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#149]
Som: konsument av et SKOS-AP-NO begreps-API
Ønsker jeg å: validere at det jeg får ut av API'et er gyldig SKOS-AP-NO
Slik at: jeg kan stole på at datakvaliteten er god.

Relatert til epos: #345 

Lenke til design: 
Lenke til løsningsarkitektur: antagelegvis kan vi legge dette inn dcat-ap-no-validator-service og tilhøyrande gui.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Vi har laget en mvp for en frittstående dcat-validering (shacl) som kan være et utgangspunkt for en SKOS-AP-NO validator. I prinsippet er det bare å tilpasse valideringsreglene. https://difi.github.io/dcat-ap-no-validator/

**Comment by marittor** [comment]
@stigbd har vi et mer intuitivt navn på denne historien?

**Comment by stigbd** [comment]
@jimjyang  Vi må få laga eit minimumssett av valideringssregler (shacl) for skos-ap-no-begrep.

**Comment by jimjyang** [comment]
Ja, vi trenger en SHACL-fil (Mateo startet den gang, men var langt fra å være ferdig). Har planer om å fullføre SHACL, sammen med å bygge om hele standarden (til å være i samme stil som f.eks. DCAT-AP-NO).

**Comment by stigbd** [comment]
Under "Velg regelsett" kan man nå velge SKOS-AP-NO-Begrep 1.0
