### ISSUE TITLE
[BRUKERHISTORIE] Informasjonselement referere til begrep

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#151]
Gjennomføres i fase 3.
Som: arkitekt
Ønsker jeg å: se referanse fra et element i en informasjonsmodell til begreper i en begrepskatalog
Slik at: jeg kan slå opp definisjonen

Relatert til epos: #310

Lenke til design: sjå epos
Lenke til løsningsarkitektur: n/a

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Verifisere kopling til begrep

Dekkes ikke:   (Dekkes i andre brukerhistorier) 
   
Referanser:
Scenario: Verifisere kopling til begrep
Gitt at detaljsida for informasjonmodell = "Testdata XX" vises
Når bruker velger fanen "Grafisk" 
Og bruker klikker på Vis begrepsdefinisjon
Og bruker klikker på Term= "Begrep YY"
Så skal detaljsiden for "Begrep YY" vises

**Comment by marittor** [comment]
Er dette duplikat av #19 ? Se saken.

**Comment by stigbd** [comment]
Forslag til løysing:
Vi legger på ein externalDocs i Schema Object i openAPI-spesifikasjonen (som modellen er henta ut i frå). Denne kan front end bruke til å hente begreps-info. Eksempel:
```
components:
  schemas:
    Regnskap:
        type: object
        description: Et regnskap for et gitt år
        properties:
          id:
            type: string
            description: system-generert id (GUID)
          virksomhet:
            $ref: "#/components/schemas/Virksomhet"
          regnskapsperiode:
            $ref: "#/components/schemas/Tidsperiode"
          valuta:
            $ref: "#/components/schemas/Valutakode"
          avviklingsregnskap:
            type: boolean
          oppstillingsplan:
            type: string
            externalDocs:
              description: Lenke til begrepet i begrepskatalaogen
              url: https://fellesdatakatalog.brreg.no/concepts/23e99544-46ae-4dda-ac60-b027dd151fd8
            enum:
            - smaa
            - store
            - oevrige
```
