### ISSUE TITLE
[BRUKERHISTORIE] Tilby knapp for å laste ned datasett.

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#158]
Som: bruker av dataportalen
Ønsker jeg å: laste ned datasett "direkte" fra portalen
Slik at: jeg slipper å gå til en ny landingsside for å laste ned filen

Relatert til epos: #91 
Relatert til brukerhistorie: #426, #145 #430 

Selv om dataportalen bare inneholder beskrivelse av datasett, er det mulig å tilby en nedlastningsfunksjon (knapp med "last ned datasettet") ettersom `dcat:downloadURL` er dedikert til direktelinker til filer. 

Funksjonaliteten av dagens data.norge.no-løsning og er etterspurt i EDP Open data Landscaping Questionaire

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-open-distribution-expanded.html

**Comment by eggedosis** [comment]
@oystein-asnes Knapp for nedlasting lagt til, tar du en titt? Lenke til skisse finner du i beskrivelsen over. Knappen finnes på de to øverste disktribusjonene (begge kan ekspanderes i skissevisningen).

**Comment by livarb** [comment]
@eggedosis Beklager seint svar! Tykkjer knappane ser bra ut :)

![image](https://user-images.githubusercontent.com/3617256/76507691-81bb0c00-644d-11ea-902f-6b2a9695d8d9.png)

Foreslår å droppe formatet frå lenka. Så vidt eg kan sjå, har vi uansett ikkje informasjon i datamodellen til å knytte format til ei spesifikk nedlastingslenke. 

Unntaket er dersom det kun er oppgitt eitt format på distribusjonen. Då kan ein ta med format. Det enklaste er nok å droppe format.

**Comment by lillelars** [comment]
@livarb Hva skjer dersom det fkatisk er flere nedlastingslenker? Skal vi bare vise 1 uansett?

**Comment by livarb** [comment]
@lillelars : Sidan den noverande standarden støttar at ein kan ha fleire nedlastingslenker på ein distribusjon, så kan det vere greitt å gje fleire nedlastingsknappar. I tilfelle ein haustar inn DCAT der det er tilfelle.

**Comment by shenluna** [comment]
Lukker denne saken da nedlastningsknapp er implementert og i produkjson
