### ISSUE TITLE
[BRUKERHISTORIE] Tilby SPARQL-søk

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#159]
Som: utvikler i et lenka data-miljø
Ønsker jeg å: gjøre spørringer mot den nasjonale datakatalogens SPARQL-endepunkt
Slik at: jeg kan motta data i RDF

Relatert til epos: #91 
Relatert til brukerhistorie #93 
Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by shenluna** [comment]
Dette er utført med https://data.norge.no/sparql, lukker dermed saken
