### ISSUE TITLE
[BRUKERHISTORIE] Forenklet metode for registrering av begrep i Felles datakatalog

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#16]
Ved registrering av "Begrep" i Felles datakatalog" (FDK) ønsker jeg funksjon for å laste opp de aktuelle begrep (tilhørende det datasett som er under registrering), slik at jeg unngår omfattende manuelt arbeid.

EPOS: #2 
Relatert til: #15

**Comment by KjerstiSteien** [comment]
Anser denne som løst, da vi har importfunksjon for begrep.
