### ISSUE TITLE
[BRUKERHISTORIE] Etterspørre datasett som ikke finnes i katalogen

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#160]
Som: bruker av datakatalogen
Ønsker jeg å: kunne etterspørre datasett som ikke finnes i katalogen fra før
Slik at: virksomheten som forvalter datasettet får melding om forespørselen (og prioriterer å beskrive det som etterlyses)

Forretningsverdi:
Viktig

Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire
Relatert til epos: #188  

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by oystein-asnes** [comment]
Denne brukerhistorien langt på vei realisert gjennom [datalandsbyen](https://datalandsbyen.norge.no/category/6/ettersp%C3%B8r-datasett-og-api-er). Epos #188 er imidlertid mer ambisiøst: At en etterspørsel gjennom dataportalen (landsbyen)  har formell  status som søknad om innsyn. Det er i dag ingen formelle prosesser som starter når en etterspør datasett i datalandsbyen. @ChristianeFrhlich @livarb @stigbd

**Comment by oystein-asnes** [comment]
Er relatert til #600 #585 #587

**Comment by RogerSOlsen** [comment]
Er realisert i Datalandsbyen, i følge @oystein-asnes
