### ISSUE TITLE
[BRUKERHISTORIE] Muligheter for å motta varslinger

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#162]
Som: bruker av den nasjonale dataportalen
Ønsker jeg å: motta varslinger (feks ved hjelp av RSS/ATOM eller annet) 
Slik at: jeg kan få vite når det har kommet et nytt datasett knyttet til et tema, fra en virksomhet, eller basert på et annet filter

Relatert til epos: #91 #346 
Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire. Finnes delvis på data.norge.no i dag

Enkleste design er at det for hver side er en egen RSS-link-knapp - f.eks. i footer, som gir RSS feed for det aktuelle filteret. Minimum-filtrering er tema (for å skille transporportal fra andre), men løsningen bør være generell uavhengig av hva man har valgt å filtrere på.

Eksempel på side som har en RSS-knapp for datasett pr organisasjon:
https://data.norge.no/organisasjoner/harstad-kommune

Relatert til brukerhistorie #179  (samme trigger, annen målgruppe)

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by sskagemo** [comment]
Møte med SVV - filtrering på:
- ingen filtrering -- får varsel om alle endringer i Transportportal.no
- filtrering på tema
- filtrering på utgiver
- filtrering på konkret datasett (ved publisering av oppdatert beskrivelse)

Antas at evt epostvarsel vil kreve større endringer (brukeradministrasjon, lagre endringer i filter).
