### ISSUE TITLE
[BRUKERHISTORIE] Diskusjonsforum for brukerne (tilbydere og konsumenter)

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#164]
Som: bruker av katalogen (enten som tilbyder eller konsument)
Ønsker jeg : tilgang til et diskusjonsforum 
Slik at: jeg kan diskutere ulike problemstillinger knyttet til å bruke (og å tilby) offentlige data med tilbydere og andre konsumenter 

Forretningsverdi:
Viktig

Relatert til epos:
#36
#569 

Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire

Lenke til design: 
Lenke til løsningsarkitektur: Slack-kanal  som er lenket til fra portalen?

**Comment by data-david** [comment]
Generell historie som også omfatter generelle datasett ikke kun åpne data. Anbefales å sees i sammenheng med disqus for API-katalog.

**Comment by shenluna** [comment]
Dette er lagt tilrette for i nettforumet Datalandsbyen
