### ISSUE TITLE
[BRUKERHISTORIE] Tilby retningslinjer og verktøy for datatilbydere for å forbedre datakvaliteten

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#165]
Som: som tilbyder av data
Ønsker jeg å: få tilgang til verktøy og retningslinjer via/gjennom portalen som hjelper meg i arbeidet med å forbedre kvaliteten på datasettbeskrivelsene (og datasettene) som virksomheten tilbyr
Slik at: jeg vet hva som gapet mellom det vi tilbyr og ønsket situasjon

Relatert til epos: #91 #346 
Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire. 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by data-david** [comment]
Refererer til [Forslaget om kvalitetsmålinger på datasett](https://docs.google.com/document/d/1mjIqqjw9PnwT7E0yYceXHtIonEyWVCrNqYyxeTUhBXY/edit)

**Comment by data-david** [comment]
Refererer til EUs metadata kvalitetsverktøy 
<img width="708" alt="Skjermbilde 2019-03-17 kl  20 10 15" src="https://user-images.githubusercontent.com/6650039/55455295-64e24b80-55e3-11e9-86cf-2b4f2fc00a14.png">

**Comment by data-david** [comment]
Refererer til EUs metadata kvalitetsverktøy
![Skjermbilde 2019-04-03 kl  07 37 22](https://user-images.githubusercontent.com/6650039/55455317-7af00c00-55e3-11e9-9cd7-0f7ccdde67b1.png)

**Comment by data-david** [comment]
[15032019 - EDP_Country Session NO.pdf](https://github.com/Informasjonsforvaltning/behov/files/3037013/15032019.-.EDP_Country.Session.NO.pdf)

**Comment by sskagemo** [comment]
Tilsvarende behov for å få tilbakemelding på kvaliteten i beskrivelser er også drøftet for begrepsbeskrivelser i innføringsmøtet for begrep 16. oktober 2019. @marittor

**Comment by eggedosis** [comment]
Her er skisser på visning av metadatakvalitet for en virksomhet (p.t. work in progress):
https://eggedosis.github.io/fdk-design/redirects/portal/report/metadataquality.html

**Comment by joebrreg** [comment]
Førsteversjon er utviklet. Se eksempel her: https://data.norge.no/organizations/991825827/datasets
