### ISSUE TITLE
[BRUKERHISTORIE] Opprette ny behandlingsaktivitet - obligatorisk

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#167]
Som: skrivebruker
Ønsker jeg å: kunne opprette en behandlingsaktivitet og beskrive obligatorisk informasjon i en Behandlingsaktivitetsoversikt
Slik at: jeg kan dokumentere hvordan virksomheten behandler personopplysninger, og 
Slik at: vi ivaretar den enkeltes personvern og etterlever personvernforordningen i EU (GDPR)

Per behandlingsaktivitet må følgende felt støttes (obligatoriske): 

- Formål med behandlingen 
- Kategorier av registrerte
- Kategorier av personopplysninger

- Kategorier av mottakere
- Planlagte tidsfrister for sletting
- Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak

- Navn og kontaktopplysninger til felles behandlingsasnvarlig
- Navn på tredjeland eller internasjonale organisasjoner som personopplysninger overføres til (JA/NEI - Hvis JA, skal det dukke opp et fritekstfelt hvor man skal skrive inn navn)
- Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner

Felter som ikke er obligatoriske iht Datatilsynets mal men som også må prioriteres for å få på plass det grunnleggende: 
-Hva gjelder behandlingen? (kan hete tittel i oversiktsbilde over alle BA) (eneste som skal markeres obligatorisk av disse fire grunnleggende punktene)
- Tilhørende datasett
- Er det gjennomført risikovurdering (DPIA)? ( Ja/Nei, hvis JA, skal det dukke opp lenkefelt, lenke til DPIA)
- Databehandleravtale (lenkefelt, lenke til databehandleravtale) 
Lenke til hjelpetekster: https://docs.google.com/document/d/1B55vGWVdezos4lotFd5SMGuZfx8n0pyVNnNQd0mklv0/edit?usp=sharing

Relatert til epos: #10 
Relatert til brukerhistorier: #380

Gammel Trådskisser skrivebruker: https://vfy2gg.axshare.com/#g=1&p=legg_til_ny_behandlingsaktivitet 

NY trådskisse: https://invis.io/8WTQMR2A35G#/385427326_REGISTRERING-NyBehandlingsaktivitet-01

Lenke til design (flere skisser): https://invis.io/APUPOL4B4G7#/395858477_BEHAKT-REG-Behansvar-Default--D-
Lenke til løsningsarkitektur: se epos

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Registrere en behandlingsaktivitet
  
 
Referanser:
Scenario: Registrere en behandlingsaktivitet
Gitt at hovedsiden for Behandlingsaktiviteter vises
Når bruker klikker på  knappen "Legg til ny behandlingsaktivitet"
Og registerer verdien "Attestløsning" i feltet "Tittel Behandlingsaktivitet" 
Og avslutter siden
Så skal behandlingsaktiviteten  "Attestløsning" vises i lista

**Comment by RogerSOlsen** [comment]
**Resultater fra test i demomiljø 06.10.2020:** 

1. **Opprette en behandlingsaktivitet**: 
Resultat: Man kan opprette en behandlingsaktivitet ved å klikke på knapp “Legg til behandlingsaktivitet”. Behandlingsaktivitet opprettes med status Utkast. 
Behandlingsaktiviteten vises ikke i listen over behandlingsaktiviteter etter at man går ut av behandlingsaktiveten, dersom man ikke har fylt ut noe i noen av feltene i behandlingsaktiveten eller ikke angitt noe verdi i noen av bolkene og går tilbake til oversikt over behandlingsaktiviteter. 

Behandlingsaktiviteten vises uten navn i listen over behandlingsaktiviteter (viser blankt felt i kolonnen Navn/tittel) etter at man går ut av behandlingsaktiveten, dersom man har fylt ut noe i noen av feltene i behandlingsaktiveten eller angitt noe verdi i noen av bolkene, og deretter sletter alt det man har registrert før man går ut. 

Behandlingsaktiviteten vises uten navn i listen over behandlingsaktiviteter (viser blankt felt i kolonnen Navn/tittel) etter at man går ut av behandlingsaktiveten, dersom man har fylt ut noe i noen av feltene i behandlingsaktiveten med unntak av “Behandlingen gjelder”.  

Behandlingsaktiviteten vises med navn i kolonnen Navn/tittel i listen over behandlingsaktiviteter dersom det er fylt ut noe i feltet “Behandlingen gjelder”.  

Det er mulig å endre status for en behandlingsaktivitet fra status Utkast til Godkjent dersom det er fylt ut noe eller angitt noen verdi i alle obligatoriske tema i behandlingsaktiviteten.  

Det er mulig å endre status fra Godkjent til Utkast. 

Det er mulig slette en behandlingsaktivitet ved å klikke på “Slett” inne i den enkelte behandlingsaktivitet.  

2. **Formål med behandlingen** 
Resultat:  det finnes eget felt «Formålene med behandlingen» i bolk Behandlingsaktiviteter. 

3. **Kategorier av registrerte** 
Resultat: «Kategorier av registrerte» var tidligere et eget felt. Feltet ble erstattet i oktober 2020 av kombinert felt «Kategorier av registrerte og kategorier av personopplysninger» i bolk «Personopplysninger», ref [BRUKERHISTORIE] Kople kategorier av registrerte og kategorier av personopplysninger #475 (https://github.com/Informasjonsforvaltning/behov/issues/475) 

4. **Kategorier av personopplysninger** 
Resultat: «Kategorier av personopplysninger» var tidligere et eget felt.  
Feltet ble erstattet i oktober 2020 av kombinert felt «Kategorier av registrerte og kategorier av personopplysninger» i bolk «Personopplysninger», ref [BRUKERHISTORIE] Kople kategorier av registrerte og kategorier av personopplysninger #475 (https://github.com/Informasjonsforvaltning/behov/issues/475) 

5. **Kategorier av mottakere** 
Resultat: det finnes felt «Mottakere eller kategori av mottakere» i bolk «Overføring av personopplysningene».  

6. **Planlagte tidsfrister for sletting** 
Resultat: det finnes felt «Planlagte tidsfrister for sletting» i bolk Personopplysninger 

7. **Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak** 
Resultat: det finnes felt «Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak» i bolk «Sikkerhetstiltak og DPIA» 

8. **Navn og kontaktopplysninger til felles behandlingsansvarlig** 
Resultat. det finnes felt «Felles behandlingsansvar» i bolk Behandlingsansvar og databbehandler med mulighet for å legge til ingen, ett eller flere kontaktpunkt. På hvert kontaktpunkt kan det registreres navn på kontaktpunkt, e-post og telefon. 

9. **Navn på tredjeland eller internasjonale organisasjoner som personopplysninger overføres til (JA/NEI - Hvis JA, skal det dukke opp et fritekstfelt hvor man skal skrive inn navn)** 
Resultat: det fantes felt «Overføres personopplysningene til tredjeland?». Dersom man klikket på Ja, kom det fram felt «Oppgi hvilke(t) tredjeland personopplysningene overføres til». 
Dette ble i oktober 2020 endret til «Er mottakerne tredjeland eller internasjonale organisasjoner» og lagt til bolk «Overføring av opplysningene» med valg ja/nei. Hvis man velger ja, kan man registrere i felt «Tredjeland eller internasjonale organisasjoner», ref https://github.com/Informasjonsforvaltning/fdk/issues/3166 

10. **Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner** 
Resultat: Det fantes felt «Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner».  

Dette ble endret til «Nødvendige garantier ved overføring» i oktober 2020 og ligger i bolk «Overføring av personopplysningene». Feltet vises dersom man der trykker på Ja på spørsmål «Er mottakerne tredjeland eller internasjonale organisasjoner?» 

**Felter som ikke er obligatoriske iht Datatilsynets mal men som også må prioriteres for å få på plass det grunnleggende:**  

11. **-Hva gjelder behandlingen? (kan hete tittel i oversiktsbilde over alle BA) (eneste som skal markeres obligatorisk av disse fire grunnleggende punktene)** 
Resultat: det finnes felt «Behandlingen gjelder». Det fremgår ikke av artikkel 30 at det er obligatorisk, men det er merket  «Obligatorisk» for å sikre at bruker registrerer et navn på behandlingsaktivitet slik at navnet vises i listen over behandlingsaktiviteter og i rapport 

12. **Tilhørende datasett** 
Resultat: det finnes felt «Tilhørende datasett» i bolk «Behandlingsaktiviteter».  
Det er mulig å søke opp og kople til datasett blant virksomhetens egne datasettbeskrivelser i Felles datakatalog. Dette gjelder for datasettbeskrivelser med status Godkjent og Publisert, men ikke for status Utkast. 
I følge kommentar på https://github.com/Informasjonsforvaltning/behov/issues/173   21.11.2019 skal navnet på feltet endres til "Søk etter datasettbeskrivelse". 

13. **Er det gjennomført risikovurdering (DPIA)? ( Ja/Nei, hvis JA, skal det dukke opp lenkefelt, lenke til DPIA)** 
Resultat: det fantes tidligere felt «Er det gjennomført risikovurdering?» med valg Ja/Nei. Felt "Lenke til risikovurdering" ble vist dersom dersom man klikket på Ja.  
I oktober 2020 ble felt «Er det gjennomført risikovurdering?» endret til felt «Er det gjennomført vurdering av personvernkonsekvenser (DPIA)» og lagt i bolk «Sikkerhetstiltak og DPIA». Dersom man svarer ja på «Er det gjennomført vurdering av personvernkonsekvenser (DPIA)», får man opp et registreringsfelt med overskrift «Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)». Se [BRUKERHISTORIE] bolk for Risikovurdering og sikkerhet #482 (https://github.com/Informasjonsforvaltning/behov/issues/482).  

14. **Databehandleravtale (lenkefelt, lenke til databehandleravtale)** 
Resultat: Det finnes felt «Databehandlere og databehandleravtaler» i bolk «Behandlingsansvar og databehandler» med felt «Navn på databehandler» og felt «Lenke til databehandleravtale».  


**Akseptansekriterier**: 
**# language: no:**
Resultat: Ved registrering av ordene «meg», «eg» og «me» kommer det rød strek under «eg» og «me». Løsningen er tilpasset norsk bokmål.

**Egenskap: 
Kriterier: 
⦁ Registrere en behandlingsaktivitet: 
Det er mulig å registrere behandlingsaktivitet med obligatoriske felter. Behandlingsaktiviteten vises i listen over behandlingsaktiviteter og kan åpnes etter at den er lukket.**  
Resultat: det er mulig å registrere behandlingsaktivitet med obligatoriske felter. Behandlingsaktiviteten vises i listen over behandlingsaktiviteter og kan åpnes etter at den er lukket.
