### ISSUE TITLE
[BRUKERHISTORIE] Liste opp alle behandlingsaktiviteter

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#168]
Som: Intern leser og skrivebruker
Gitt at jeg står i Min virksomhets Registreringsløsnings landingsside for kataloger
Og jeg klikker på Behandlingsaktivitetsoversikt
Ønsker jeg å: se en liste over alle behandlingsaktiviteter som jeg kan sortere på,  alfabetisk etter tittel på behandlingsaktivitet, etter daglig behandlingsansvar og på status,
OG å kunne søke blant behandlingsaktivitetene i min liste
Slik at: jeg enkelt kan se hvilke behandlingsaktiviteter som er dokumentert i min virksomhet og framskaffe oversikt til tilsynsmyndigheter ved tilsyn.

Felter som skal støttes i førsteomgang på listesiden: 
For protokollen totalt sett (gjeldende for alle behandlingsaktiviteter)
Behandlingsansvarlig med navn, postadresse, telefon, epost
Personvernobud med navn, postadresse, telefon, epost
Behandlingsansvarliges representant med navn, postadresse, telefon, epost

NB: Intern leser kan gjøre det samme som skrivebruker unntatt: å legge til ny behandlingsaktivitet.

NB 2: "Status" i denne konteksten avviker fra de andre katalogene, da dette er for virksomhetens interne bruk._ Hvorvidt behandlingsaktivitetene skal vises i en slags intern portal for gitte brukere i virksomheten må landes. Livsløpet til behandlingsaktiviteter skal gå gjennom følgende statuser: "Utkast","Godkjent", "Utgått".

Relatert til epos: #10
Relaterte brukerhistorier: #305  

Trådskisser skrivebruker: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/387848756 
Lenke til design: https://invis.io/APUPOL4B4G7#/395260963_BEHAKT-REG-OVERSIKT-Default--D-
Lenke til løsningsarkitektur: se epos

Lenke til hjelpetekster: https://docs.google.com/document/d/1B55vGWVdezos4lotFd5SMGuZfx8n0pyVNnNQd0mklv0/edit?usp=sharing

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Starte opp behandlingsaktiviter fra landingsside
⦁	Vise og sortere liste over behandlingsaktiviteter
⦁	Knapp for ny behandlingsaktivitet

Dekkes ikke:   (Dekkes i andre brukerhistorier) 

- Detaljside Behandlingsaktrivitet
- Søking
- Andre brukergrupper enn skriverettighet

 
Referanser:
Scenario: Starte opp behandlingsaktiviter fra landingsside
Gitt at bruker er pålogget landingssiden for sin virksomhet
Når bruker klikker på  "Behandlingsaktiviteter" 
Så skal  hovedsiden for Behandlingsaktiviteter vises

Scenario: Vise og sortere liste over behandlingsaktiviteter
Gitt at hovedsiden for Behandlingsaktiviteter vises
Når bruker klikker på  kolonneheading pil opp 
Så skal listen over alle behandlingsaktiviteter vises i sortert rekkefølge

Scenario: Knapp for ny behandlingsaktivitet
Gitt at hovedsiden for Behandlingsaktiviteter vises
Når bruker klikker på  knappen "Legg til ny behandlingsaktivitet"
Så skal siden "Ny behandlingsaktivitet" vises

**Comment by marittor** [comment]
Skal det her skisses for interne lesere? Er det egentlig like relevant her som for Begrep? Det er sansynligvis et behov å kunne se en hel liste og velge å **lese** én behandlingsaktivitet. Mener vi har diskutert noe rundt en portalvisning for dette, så da kan det hende at lesetilgangen løses vha denne, men hvis ikke, bør det vel kunne være en mulighet til å gå inn og se én aktivitet, uten å ha skriverettigheter/være i redigeringsmodus? @tereseskavhaug vi kan se på dette imorgen.

**Comment by marittor** [comment]
@AleksandraHrpka : Det som gjenstår å skisse på her er status. Idag står det utkast og publisert, det er arv fra et annet skjema og stemmer ikke.

**Comment by marittor** [comment]
Tittel på oversikten skal hete "Protokoll over behandlingsaktiviteter hos" xxx/Parker Industries/e.l

**Comment by marittor** [comment]
@frode-kleven - jeg tror vi bør gjøre noen endringer i skissene mtp på å liste opp personvernombud og behandlingsansvaret (med navn, epost, og tlf, se brukerhistorien). Dette vil for alle behandlingsaktivitetene i protokollen være likt, altså virksomhetens øverste leder (er alltid behandlingsansvarlig), og det er ofte ett personvernombud i virksomheten (ett navn). Vi har jo tatt høyde for å registrere representant for beh.ansvarlig inne på den enkelte BA (altså er ansvaret delegert fra øverste leder til noen som har det daglige behandlingsansvaret), men vi mangler de to andre.

**Comment by marittor** [comment]
Enige om å fjerne søk og filtrering fra liste opp begrep for å scope ned - tas i samme møte som kommentar over.

**Comment by RogerSOlsen** [comment]
@lillelars Jeg får ikke testet akseptansekriterier med lesebruker, ref at det står lesebruker i brukerhistorien. Kan se ut som at protokollen ikke er klargjort for lesebruker, ref testing av om det finnes lesebruker sammen med @joebrreg i dag

**Comment by RogerSOlsen** [comment]
Test av lesebruker og skrivebruker: akseptansekriterier er i hovedsak oppfylt. Brukerhistorien blir derfor lukket.


**_Akseptansekriterier**:
,# language: no_
**Testresultat**: sider for både lese- og skrivebruker er på bokmål. 

_Egenskap:
Kriterier:
⦁ Starte opp behandlingsaktiviter fra landingsside_
**Testresultat**: både lese- og skrivebruker får startet opp side for behandlingsaktiviteter (kalles nå "Behandlingsoversikt") fra landingsside for kataloger
 
_⦁ Vise og sortere liste over behandlingsaktiviteter_
**Testresultat**: liste over behandlingsaktiviteter finnes i for lese- og skrivebruker. Det er mulig for både lese- og skrivebruker å sortere på "Navn/tittel" og "Status". Det finnes sorteringspil på "Daglig behandlingsansvarlig" som viser at man også skal kunne sortere behandlingsaktiviteter alfabetisk etter "Daglig behandlingsansvarlig" , men den virker virker ikke for lesebruker og skrivebruker. Dette er meldt som egen issue:  https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/42 slik at man må kunne forvente at dette blir rettet og levert.

⦁ _Knapp for ny behandlingsaktivitet_
**Testresultat**: Knapp for ny behandlingsaktivitet, "Legg til ny behandlingsaktivetet", virker for skrivebruker. Den er ikke tilgjengelig for lesebruker og skal heller ikke være det.
