### ISSUE TITLE
[BRUKERHISTORIE] Se detaljer på behandlingsaktivitet

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#169]
Som: intern leser
Ønsker jeg å: se detaljer på behandlingsaktivitet
Slik at: jeg kan gjøre meg kjent med innholdet

Relatert til epos: #391 
Relaterte brukerhistorier: #305

Trådskisse lesebruker: Mangler

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/register-new-readonly.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by marittor** [comment]
@tereseskavhaug vi har ikke skisset på dette mener jeg, men denne henger egentlig sammen med #168, se egen kommentar der.

**Comment by marittor** [comment]
@AleksandraHrpka Vi mangler trådskisser på lesebruker/intern leser.

**Comment by marittor** [comment]
@RogerSOlsen , skal det ikke leveres mulighet for å lesetilgang til behandlingsaktivitet? En konsekvens for oss blir da at BAer ikke blir tilgjengelige for virksomheten, kun for et fåtall. Hva er begrunnelsen for at denne ikke skal leveres? Eller er den dekket av en annen historie? Ønsker en kommentar til lukkingen.

**Comment by joebrreg** [comment]
@marittor Denne er ikke levert, så jeg åpner saken igjen. Logger du inn med lesetilgang, skal du få beskjed om at du ikke har tilgang, så her er det en feil.

**Comment by lillelars** [comment]
@RogerSOlsen Lesebruker er nå implementert og åpnet for :) Setter denne til klar til akseptanse

**Comment by RogerSOlsen** [comment]
Testresultat som lesebruker i demo-miljø:

- lesebruker får ikke endret på informasjon 
- Lesebruker får lest informasjon som er registrert om «Behandlingsansvarlig», «Personvernombud» og «Representant for behandlingsansvarlig». 
- Lesebruker får se oversikt over behandlingsaktiviteter 
- lesebruker får sortert på kolonnene "Navn/tittel" og "Status". Sorteringsfunksjon på "Daglig behandlingsansvarlig virker ikke (dette gjelder også for skrivebruker). Dette er meldt som egen issue https://github.com/informasjonsforvaltning/fdk-issue-tracker/issues/42
- lesebruker får lest detaljer om den enkelte behandlingsaktivitet. 
- Felt som ikke er utfylt i behandlingsaktiviteter, blir vist som blanke felt. 
- Lesebruker får ikke endret status på behandlingsaktivitet  eller slettet behandlingsaktivitet: (knappene «Utkast», «Godkjent» og «Slett vises ikke).
- Lesebruker får generert rapportene «Behandlingsoversikt" og "Protokoll".


Skjermdump fra lesebruker angående Behandlingsansvarlig og Personvernombud:
![image](https://user-images.githubusercontent.com/32771488/95985801-57875d80-0e25-11eb-96a7-fd97bd56a566.png)

 



Skjermdump fra lesebruker angående «Representant for behandlingsansvarlig»:
 
![image](https://user-images.githubusercontent.com/32771488/95985817-5c4c1180-0e25-11eb-92dd-d0edc1fcff09.png)


Skjermdump fra lesebruker som viser oversikt over behandlingsaktiviteter:
![image](https://user-images.githubusercontent.com/32771488/95985933-87cefc00-0e25-11eb-8982-d91290e0dbd4.png)


Skjermdump fra detaljer på behandlingsaktivitet:
![image](https://user-images.githubusercontent.com/32771488/95985955-90273700-0e25-11eb-8b9a-d456e77a4c1f.png)
 



Leser får ikke endret status på behandlingsaktivitet  eller slettet behandlingsaktivitet: (knappene «Utkast», «Godkjent» og «Slett" vises ikke):
 
![image](https://user-images.githubusercontent.com/32771488/95985971-96b5ae80-0e25-11eb-8259-030d7a7a3fa6.png)
