### ISSUE TITLE
[BRUKERHISTORIE] Oppdatere detaljer på en behandlingsaktivitet

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#170]
Som: Skrivebruker
Ønsker jeg å: Oppdatere detaljer på en behandlingsaktivitet
Slik at: jeg kan forvalte innholdet og ta høyde for at forhold knyttet til behandlingen kan endre seg over tid

NB! Her må det avklares hvordan vi tar vare på historikk når noe skal endres. Hvilke etterlevelseskrav ligger til grunn for forvaltning av protokollen, hva må vi ha kontroll på av historiske versjoner? Tenker dette er strengere enn for vurderinger som er gjort på Begrep. 

Relatert til epos: #10 

Trådskisser: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/385427326
Lenke til design:  https://invis.io/APUPOL4B4G7#/395858477_BEHAKT-REG-Behansvar-Default--D-
Lenke til løsningsarkitektur: Se epos

Akseptansekriterier: 

- [ ] Sjekk at editering/endringer i alle obligatoriske felt blir lagret
- [ ] Sjekk at editering/endringer i "Ikke-obligatoriske" felt blir lagret

**Comment by marittor** [comment]
Kan man gjenbruke noen tanker fra trådskissene her, tro? @tereseskavhaug 
Endre et publisert begrep: https://69d4ft.axshare.com/#g=1&p=endre_eksisterende_begrep
Endringene er publisert: https://69d4ft.axshare.com/#g=1&p=endringer_publisert

**Comment by marittor** [comment]
@AleksandraHrpka Vi mangler også trådskisser her, men vi kan gjenbruke noen tanker fra det som er gjort på begrep?

**Comment by RogerSOlsen** [comment]
Test av brukerhistorie: akseptansekriterier er oppfylt og brukerhistorien lukkes

**Kommentar til tekst:**
_NB! Her må det avklares hvordan vi tar vare på historikk når noe skal endres. Hvilke etterlevelseskrav ligger til grunn for forvaltning av protokollen, hva må vi ha kontroll på av historiske versjoner? Tenker dette er strengere enn for vurderinger som er gjort på Begrep._
Dette er lagt inn i [BRUKERHISTORIE] ta vare på historikk i behandlingsoversikt #523  https://github.com/Informasjonsforvaltning/behov/issues/523 

_Akseptansekriterier:
 Sjekk at editering/endringer i alle obligatoriske felt blir lagret_
**Test**:  Alle endringer i obligatoriske felt blir lagret

 _Sjekk at editering/endringer i "Ikke-obligatoriske" felt blir lagret_
**Test**: alle endringer i ikke-obligatoriske felt blir lagret
