### ISSUE TITLE
[BRUKERHISTORIE] Koble behandlingsaktivitet til datasett 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#173]
Som: Skrivebruker som registrerer en behandlingsaktivitet
Ønsker jeg å: kunne koble behandlingsaktiviteten til ett eller flere godkjente eller publiserte datasett i min virksomhetsinterne datasettkatalog 
Slik at: jeg kan uttrykke forholdet mellom behandlingen av personopplysninger og datasettene jeg har

Feltet "Tilhørende datasett" kan gjenbruke søkefunksjonen fra datasettregistrering. 

Relatert til epos: #10 

Trådskisser: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/385427326

Lenke til design: https://invis.io/APUPOL4B4G7#/395858480_BEHAKT-REG-Behaktivitet-Input--D-

Lenke til løsningsarkitektur: bruk registration-api sitt API

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Kople til datasett til behandlingsaktivitet

Dekkes ikke:   (Dekkes i andre brukerhistorier) 
   
Referanser:
Scenario: Kople til datasett til behandlingsaktivitet
Gitt at detaljsiden for en behandlingsaktiviteter vises
Når bruker registerer et datasett i feltet "Tilhørende datasett"
Så skal valgt registrert datasett vises på siden "Behnadlingsaktivitet"  i feltet "Tilhørende datasett"

**Comment by marittor** [comment]
@eggedosis og @frode-kleven 
Se på felt "tilhørende datasett": 
Endre "ledetekst her" til "Søk etter datasettbeskrivelse"

**Comment by RogerSOlsen** [comment]
@lillelars : navnet på feltet "Tilhørende datasett" skal endres til "Søk etter datasettbeskrivelse", ref kommentar fra Marit 21.11.2019

**Comment by RogerSOlsen** [comment]
Resultat:  
som skrivebruker kan jeg i feltet “Tilhørende datasett” søke på datasettbeskrivelser som står med status Godkjent og Publisert i egen virksomhet sin datasettkatalog i Felles datakatalog. Koplingen bekreftes ved klikke på datasettbeskrivelsen man får opp i listen når man søker på datasettbeskrivelsen.
