### ISSUE TITLE
[BRUKERHISTORIE] Duplikatsjekk ved migrering til FDKs registreringsløsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#174]
Som: tilbyder av en virksomhetskatalog som høstes av FDK
Ønsker jeg å: unngå duplikater med datasett som er registrert direkte i FDKs registreringsløsning  
Slik at: ikke FDK inneholder duplikater av datasett

Relatert til epos: #186 
Relatert til brukerhistorie #92 

Lenke til design: 
Lenke til løsningsarkitektur:

Tanker om løsning: manuell engangsjobb for å sjekke for- og skjule eventuelle duplikater.

**Comment by livarb** [comment]
Kva må eventuelt gjerast av utvikling eller anna før denne manuelle jobben gjerast?

**Comment by livarb** [comment]
Kva er gjort her? Er det gjort ein manuell jobb?

Veit det er ein duplikat på "tekniske kjøretøyopplysninger". Eg skal ta den direkte med vegvesenet.

**Comment by livarb** [comment]
@shenluna : Ping om kommentar over. Ønskjer meg korte kommentarar om kva som er gjort, eller berre lenke til side på FDK der ein kan sjå ferdig resultat. Så er det lettare å vurdere mot akseptansekriterier.

**Comment by shenluna** [comment]
@livarb Det som ble gjort var å be alle brukere om å sjekke sine datasett for duplikater da vi slo sammen data.norge.no og FDK.
Når det gjelder veivesenet skyldes duplikat registrering i deres egen dataportal + oppføringen vi har hos oss i vår registreringsløsning.

**Comment by oystein-asnes** [comment]
Lukkar denne ettersom den er knytt til migreringa. Duplikatsjekk er fortsatt eit tema.
