### ISSUE TITLE
[BRUKERHISTORIE] Filtrere på begreper

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#175]
Som: lesebruker og skrivebruker
Gitt at jeg står i Registreringsløsningens landingsside kataloger
Og jeg klikker på Begrepskatalog_
Ønsker jeg å: se en liste over alle begrep som jeg kan filtrere på fagområder og gyldighet (der default er de som er gyldige)
Slik at: jeg enkelt kan se begreper som allerede er registrert i begrepskatalogen og hvor de kommer fra, hvorvidt de er gyldige, og få oversikt etter hvert som det blir mange begreper i min virksomhets katalog.

Om "gyldighetsfilter":
Ønsker en visning som gir meg 3 valgmuligheter i brukergrensesnitt -
default: nåværende begreper
valg: historiske begreper (utgåtte)
valg: kommende begreper (blir gyldige)

Relatert til epos: #329 
Relatert til brukerhistorier:
#75

Trådskisser skrivebruker
Oversiktside/opplisting av begrep med filter for skrivebruker: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_skriverolle

Designskisser skrivebruker (flere skisser som viser flyten):
https://invis.io/3SRCN149CQN#/385434196_BEGREP-REG-Beskrivelser-Oversikt-Dropdown-Fagomrade-Valgt--D-

Lenke til løsningsarkitektur: denne løses ved at [api-et](https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml) må støtte "filter-queries" på list begreper (følgende filtre: fagområde, gyldighet) samt at gui må implementere "standard" filter.

Trådskisser lesebruker
Oversiktside/opplisting av begrep med filter og søk for skrivebruker: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_leserolle

Deisgnskisser lesebruker
https://invis.io/3SRCN149CQN#/356258578_BEGREP-REG-Beskrivelser-Oversikt-Leserolle--D-

**Akseptansekriterier:**
,# language: no
Egenskap: 

Kriterier:
⦁	Filtrere på fagområde- skrivetilgang
⦁	Filtrere på gyldighet - lesetilgang
Dekkes ikke:   (Dekkes i andre brukerhistorier) 

Referanser:
Scenario: Filtrere på fagområde - skrivetilgang
Gitt at bruker er pålogget med skrivetilgang
og bruker har startet opp siden "Begrep fra..."
Når bruker setter filter for fagområde= "økonomi" 
Så skal listen med begrep kun inneholde anbefalt term innenfor fagområdet "økonomi"

Scenario: Filtrere på gyldighet - lesetilgang
Gitt at bruker er pålogget med lesetilgang
og bruker har startet opp siden "Begrep fra..."
Når bruker setter filter for "historiske begreper" 
Så skal listen med begrep kun inneholde anbefalt term innenfor gyldighet "historiske begreper"

**Comment by eggedosis** [comment]
Mener du _sortering_ og ikke filtrering?

**Comment by KjerstiSteien** [comment]
Anser denne saken som løst gjennom samarbeidet om virksomhetsintern begrepskatalog. https://github.com/Informasjonsforvaltning/behov/issues/792
