### ISSUE TITLE
[BRUKERHISTORIE] Migrering av brukere fra data.norge.no til FDK

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#178]
Som: bruker av dagens data.norge.no
Ønsker jeg å: få en sømløs overgang til ny løsning
Slik at: jeg ikke må bruke mye tid på å få de tilgangene jeg trenger i ny løsning

Relatert til epos: #186 

Lenke til design: N/A
Lenke til løsningsarkitektur:

**Comment by livarb** [comment]
Trur denne er ok. Veit ikkje om nokon problem, så tenker denne kan setjast til ferdig. Kva trur de andre? @shenluna @oystein-asnes

**Comment by shenluna** [comment]
Enig, jeg lukker denne.
