### ISSUE TITLE
[BRUKERHISTORIE] Tilby rapporter til datatilbyderne for å gi innsikt i virksomhetens metadatakvalitet

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#179]
Som: tilbyder av en virksomhetskatalog 
Ønsker jeg å: få innsikt i katalogens metadatakvalitet
Slik at: jeg kan arbeide systematisk med å forbedre beskrivelsene av virksomhetens datasett

Rapporten bør inneholde en oversikt over obligatoriske, anbefalte og valgfrie felt for virksomhetens katalog 

Relatert til epos: #91 #346 
Relatert til brukerhistorie: #165 
Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/report/metadataquality.html
Lenke til løsningsarkitektur:

**Comment by joebrreg** [comment]
Førsteversjon utviklet. Se #165 .
