### ISSUE TITLE
[BRUKERHISTORIE] Visualisere begreper

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#18]
Som IT-arkitekt/informasjonsarkitekt ønsker jeg en forståelig måte å visualisere begreper slik at alle kan kjenne seg igjen og forstå hvorfor det er viktig for dem.

Epos: #2 også relatert til epos #6 ?
Relaterte brukerhistorier: #19

**Comment by marittor** [comment]
Usikker på om denne skal kobles til begrepsregistrering?

**Comment by marittor** [comment]
@ToHelland Skal denne lukkes i og med at den vel dekkes av en av historiene på modeller?

**Comment by ToHelland** [comment]
Skal se p? det i morgen. Er dessverre p? jobb n?.

Sendt fra min iPhone

27. mai 2019 kl. 10:14 skrev Marit Torseth <notifications@github.com<mailto:notifications@github.com>>:


@ToHelland<https://github.com/ToHelland> Skal denne lukkes i og med at den vel dekkes av en av historiene p? modeller?

-
