### ISSUE TITLE
[EPOS] Høste andre API-kataloger

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#184]
Som:  forvalter av API-katalog for flere virksomheter
Ønsker jeg å: kunne publisere hele eller deler av innholdet i API-katalogen jeg forvalter i Felles datakatalog
Slik at: den blir synlig i felles datakatalog uten at jeg må gjøre jobben manuelt

Lenke til trådskisser: 
Lenke til overordna arkitektur:

behov bl.a. fra Oslo kommune, FINT
Relatert til epos #137

**Comment by stigbd** [comment]
Dette vil også løse BITS sitt behov for å tilgjengeliggjøre endepunkter for ulike bankers api i DSOP-kontroll konteksten ved at BITS kan lage en katalog som vi kan høste.

**Comment by sskagemo** [comment]
Duplikat av #12, lukkes.
