### ISSUE TITLE
[BRUKERHISTORIE] Utveksle API-kataloger

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#185]
Som: forvalter av API-katalog
Ønsker jeg å: ha noe à la DCAT-AP-NO og SKOS-AP-NO
Slik at: jeg kan utveksle innholdet i API-katalogen jeg forvalter med Felles datakatalog på en standardisert måte

Relatert til epos: #12

Lenke til design:  N/A
Lenke til løsningsarkitektur: Implementere støtte i fdk-api-harvester for ny DCAT-AP-NO (foreløpig) som støtter API-kataloger gjennom klassen "dcat:DataService", ref https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/f48b3ecc-ae46-45c0-8e5a-bc73889e185c.html

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk (forutsetning for #12 og #137 )

Akseptansekriterier:
(overordnet)
Gitt  at endepunkt er satt opp skal en kunne regelmessig høste API-beskrivelse fra gitt virksomhet

**Comment by sskagemo** [comment]
Eksempler som utgangspunkt:
- eksempel DCAT - der katalog knyttes til organisasjonsnummer: https://github.com/data-david/DatasetCatalogs/blob/master/StatensPensjonskasse.ttl
- dagens API-katalog for BR: https://github.com/brreg/openAPI/blob/master/specs/API-catalog.ttl
- innspill til revisjon av DCAT i W3C: https://rawgit.com/w3c/dxwg/annette-dataservices/dcat/index.html#Class:Data_API

**Comment by RogerSOlsen** [comment]
Løst ved implementering av DCAT-AP-NO 2.1
