### ISSUE TITLE
[EPOS] Migrering av brukere og innhold fra data.norge.no til FDK-registreringsløsning

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#186]
Som: Dataeier
Ønsker jeg at: mine datasett og brukerprofil blir flyttet til ny løsning i FDK
Slik at: jeg kan forholde meg til ett verktøy for åpne og lukkede datasett

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Tilknyttet brukerhistorier for dette EPOS:
#174 
#178 
#141 
#142

**Comment by shenluna** [comment]
Lukker denne, dette ble utført i mai 2020.
