### ISSUE TITLE
[EPOS] Utvidet funksjonalitet knyttet til åpne data 

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#187]
Som: bruker av åpne data
Ønsker jeg å: funksjonalitet som retter seg mot åpne data
Slik at: jeg kan benytte FDK som løsning

Relatert til:  #159, #158, #163, #161, #160, #164, #179 #401 
Lenke til trådskisser: 
Lenke til overordna arkitektur:

**Comment by oystein-asnes** [comment]
Denne overlapper med #91 og kan eventuelt lukkes.

**Comment by KjerstiSteien** [comment]
Brukerhistoriene er flyttet eller lukket. Eposet lukkes.
