### ISSUE TITLE
[BRUKERHISTORIE] Dedikert URL for NAP subsettet av Felleskatalogen?

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#189]
Som: bruker av NAP
Ønsker jeg: en dedikert URL for NAP subsettet av Felles datakatalogen?
Slik at: jeg ser at jeg er innenfor dette domenet

Relatert til epos: #7 

Lenke til design: N/A
Lenke til løsningsarkitektur: N/A

Akseptansekriterie:   Brukerhistorien aksepteres når nap-løsningen kjører på egen URL

Beslutning: URL skal være  transportportal.no (se kommentar 24. mai)

**Comment by sskagemo** [comment]
I møte med SVV idag ble det bekreftet at URL skal være transportportal.no, som pr idag ruter videre til http://dataut.vegvesen.no/group/about/nap

**Comment by stigbd** [comment]
Vi må dermed lage en url som peikar på vår nap-løsning. Forslag: https://nap.fellesdatakatalog.brreg.no.
