### ISSUE TITLE
[BRUKERHISTORIE] Koble begreper til modeller

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#19]
Som informasjonsarkitekt ønsker jeg en fast struktur, og å kunne koble begreper til modeller slik at jeg kan sikre riktig informasjon og vise fram til konsumenter hva begrepene i modellen min betyr.

EPOS: #6 
Relaterte brukerhistorier: #18

**Comment by marittor** [comment]
T.H bør også kobles på her.

**Comment by marittor** [comment]
Tenker at modellene bør peke til begreper, altså ser jeg for meg at dette går andre veien  (altså, vi legger ikke opp til å koble til informasjonsmodell _fra_ begrep, men til begrep _fra_ informasjonsmodell). Bør assignes til ansvarlig for informasjonsmodeller, T.H.

**Comment by marittor** [comment]
Foreløpig satt til @data-david, regner med denne tildeles til ansvarlig informasjonsmodellkatalog etterhvert?

**Comment by marittor** [comment]
@data-david kan denne dekke behovet du nevner om begrepsreferanse i informasjonsmodeller?

**Comment by ToHelland** [comment]
For meg ser det ut som om det er overlapp mellom brukerhistoriene.
