### ISSUE TITLE
[BRUKERHISTORIE]  dedikert design av NAP subsettet, med tydeliggjøring av det vi ønsker å tydeliggjøre rundt SVV sin rolle

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#190]
Som: bruker av NAP
Ønsker jeg:  dedikert design av NAP subsettet, med tydeliggjøring av det vi ønsker å tydeliggjøre rundt SVV sin rolle
Slik at: jeg ser at jeg er innenfor NAP-domenet

Relatert til epos: #7 

Lenke til design:
https://invis.io/PVQIEP15ADG#/369545086_TRAFIKK-S-K-Default--D-

Lenke til løsningsarkitektur:

Akseptansekriterier:  Design som kan demonstreres og gi grunnlag for detaljerte beslutninger for videreutvikling

**Comment by sskagemo** [comment]
Filtreringen av innhold baseres på kategoriseringen iht LOS, og LOS er for tiden under revisjon. For å ivareta behovet for SVV er SVV invitert av Difi til å gi innspill til den pågående revisjonen (epost fra Difi til SVV idag).
