### ISSUE TITLE
[BRUKERHISTORIE] Beskrive datasett på flere språk

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#194]
Som: dataeier
Ønsker jeg å: tospråklighet – norsk og engelsk
Slik at: jeg kan registrere datasett på flere språk, og datasettet kan finnes av engelskspråklige

Relatert til epos: #7 

Lenke til design: 
Lenke til løsningsarkitektur:

Spørsmål fra SVV:
tospråklighet – norsk og engelsk?

Svar fra BRREG:
Portalen støtter flerspråklighet i brukergrensesnittet (i dag bokmål, nynorsk og engelske oversettelser). Kodelister osv. er også flerspråklige og endrer språk etter valgt språk i browser.  Registereringsløsningen som dataeiere kan benytte er p.t. språket i brukergrensesnittet kun på norsk.

Innhold, beskrivelser av datasett, følger standarden DCAT-AP-NO som også gir flerspråklighet på tekster. Registeringsløsningen her er imidlertid begrenset slik at du i dag må velge beskrivelse av datasettet på engelsk eller norsk.  

Dersom behovet, og dataeierene aktivt ser for seg å beskrive datasettene på flere språk, kan vi prioritere opp muligheten til å registrere samme datasett med flere språk.

**Comment by joebrreg** [comment]
Duplikat. Se brukerhistorie #59
