### ISSUE TITLE
[BRUKERHISTORIE] Utenlandske aktører skal registrere datasett

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#195]
Som: dataeier fra utlandet, uten norsk organisasjonsummer
Ønsker jeg å: kunne legge inn datasett
Slik at: det blir tilgjengelig for NAP

Relatert til epos: #7

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by sskagemo** [comment]
I møte med SVV idag ble vi enige om at vi kan forutsette at aktørene har norsk organisasjonsnummer.
