### ISSUE TITLE
[EPOS] Begrep: Språkstøtte

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#2]
Som ansvarlig virksomhet (begrepseier) ønsker jeg å kunne dele begreper med andre etter anbefalte standarder, slik at andre virksomheter (menneske og maskin) kan se og gjenbruke begreper innenfor vårt domene.

Lenke til trådskisser: 
Lenke til overordna arkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/7f868918-ba8e-42e1-a5ba-872d56c91a3e.html

Tilknyttet brukerhistorier for dette EPOS:
#86 
#308 

Andre relaterte epos: #26

**Comment by KjerstiSteien** [comment]
@Te-Bert Kan du vurdere status og prioritet på det som gjenstår i dette eposet? 

Se denne listen for et utgangspunkt for vurdering av prioritet: 
Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag)
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
Regner denne som løst. Restanser løses som egne saker.
