### ISSUE TITLE
[BRUKERHISTORIE] Kobling datasett og prosesskart

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#20]
Som informasjonsforvalter ønsker jeg kobling til prosesskart og datasett slik at bildet kompletteres.

**Comment by marittor** [comment]
Behovet er meldt inn i konteksten Felles begrepskatalog. Altså kan det tolkes som om man ønsker kobling begrep+prosesskart, kobling begrep+datasett. Sistnevnte er levert. Usikker på om kobling til prosesskart er noe som planlegges?

**Comment by RogerSOlsen** [comment]
Vi har ikke noe forhold til prosesskart, så vi lukker denne
