### ISSUE TITLE
[BRUKERHISTORIE] OPPRETTE nytt begrep - ekstra felter

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#201]
Som: skrivebruker
Ønsker jeg å: kunne opprette et nytt begrep og beskrive det i Felles begrepskatalog
Slik at: begrepet er opprettet med status "Utkast"
OG jeg kan synliggjøre min virksomhets begrepsforståelse i tråd med gjeldende standarder, i begrepskatalog GUI, for alle brukere i virksomheten

I tillegg til feltene som ønskes i #76  skal følgende ekstra felter skal være med: 

• Eksempel
• Fagområde
• Bruksområde
• Verdiområde (omfang)
• Kontaktpunkt
• Forhold til kilde

Det skal kunne knyttes hjelpetekster til alle feltene, se versjon 1.0 her: https://docs.google.com/document/d/1FrrPgJJ_4Krqrb58sNdSFCJpF__5_NGqpuKfaF2HaL0/edit?usp=sharing

Relatert til epos: #176 
Relatert til brukerhistorier: #76 

Erstatter følgende brukerhistorier: 
#25
#22 

**Trådskisser skrivebruker**
Registrer på bokmål: https://69d4ft.axshare.com/#g=1&p=bokm_l_valgt

Lenke til design: 
Lenke til løsningsarkitektur:

**Akseptansekriterier:** (Samme som for #76)
,# language: no
Egenskap: 

Kriterier:
⦁	Et begrep skal kunne lagres med mulig innhold i alle felt som er beskrevet i brukerhistorien med status "Utkast"
⦁	Hvert felt  skal ha en tilhørende hjelpetekst som kan vises ved behov.
Dekkes ikke:   (Dekkes i andre brukerhistorier) 
⦁	Publisere begrep
⦁	Slette begrep

Referanser:

Scenario: Et begrep skal kunne lagres med mulig innhold i alle felt som er beskrevet i brukerhistorien med status "Utkast"
Gitt at bruker med skriverettigheter har opprettet nytt begrep med informasjon i alle felt
Når bruker avslutter registreringsbildet 
Så skal verdiene i alle registrete felt lagres
Og lagret begrep skal ha status  = "Utkast"

Scenario: Hvert felt  skal ha en tilhørende hjelpetekst som kan vises ved behov
Gitt at  registreringssiden for nytt begrep er åpnet
Når bruker klikker på linken "hjelp" for  et gitt felt
Så skal  hjelpeteskt for gitt felt vises

**Comment by sindresandvik2** [comment]
@marittor Reknar med at språkvariasjonsfelta IKKJE skal vere med i denne historien?    Bør fjernast herifrå og brukast i ein eigen brukerhistorie!

**Comment by marittor** [comment]
@sindresandvik2 Vi klarer nok ikke språkstøtte i førsteomgang, nei. Men disse er ivaretatt i #86 , så jeg fjernet de og lot bokmål-skissa stå igjen.
