### ISSUE TITLE
[BRUKERHISTORIE] Brukervennlig registrering-GUI

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#22]
Som terminolog og fagperson ønsker jeg et enkelt og brukervennlig grensesnitt for å registrere mitt fagfelts begreper, termer og sammenhenger
slik at jeg enklere kan samle og strukturere termene 
og slik at jeg kan jobbe med utvalgte felter av gangen
og slik at den tekniske delen av begrepsarbeidet ikke føles som et hinder. 

EPOS: #2

**Comment by marittor** [comment]
Det bør være enkelt (et klikk) å skifte mellom fullvisning og valgt visning. Kan evt løses på samme måte, med expand, slik det er gjort i FDK-registrering.

**Comment by marittor** [comment]
Ivaretas av #76

**Comment by lillelars** [comment]
@marittor  Hva legger du i "Full visning" og "valgt visning" her?

HVIS denne er allerede "Closed" så bør vi fjerne den fra "Analysere Behov" kolonnen.
