### ISSUE TITLE
[BRUKERHISTORIE] Skravere termer når begrep er registrert, men ikke publisert

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#23]
Som skrivebruker/selvstendig organisasjon
ønsker jeg selv å kunne velge når termen skal være synlig for andre
slik at jeg kan bruke verktøyet i alle faser av arbeidet.

EPOS: #2

**Comment by marittor** [comment]
Behandlet på møte i innføringsteam begrep 16.01.2019. Følgende ble diskutert i gruppa:

Denne historien kan tolkes på to måter: 
1. Ønsker å vise fram at begrepet jobbes med/er i prosess, ved at termen er søkbar, men ikke f. eks klikkbar
2. Ønsker å kunne jobbe "i fred", vise fram når man er klar for dette. 

Vi diskuterte først med utgangspunkt i tolkning nr 1: Vil virksomheten som er pålogget kunne vise internt i virksomheten eller til alle? 
 
Tror det dreier seg om å vise dette på allmennheten – mulig å kunne vise fram at dette er WIP. Spm er om man skal ha en egen tag for å si at noe er klart til publisering eller godkjent, eller kommunisere at noe er under arbeid.
 
Kan legge inn kommentarer til begrepet om at dette er det beste vi har nå.
 
Alle de eksporterte vil ikke ha støtte, så det blir urettferdig for de som allerede har kataloger lokalt.. 
 
Forslag om å ta denne bort nå, heller ta opp igjen senere etter første versjon. Lage så enkel flyt som mulig nå - Utkast-->publisert. 
 
2- Kan tolkes motsatt – sikre at dette ikke publiseres - hvis vi tolker den slik er det ikke noen stor oppgave - begrepet er usynlig for andre fram til den ansvarlige virksomheten velger å publisere det. Det kan enkelt løses idag.

**Comment by marittor** [comment]
Lurer på om denne fortsatt er relevant, gitt at begrep i registreringsGUI kan ha ulike statuser og at intern leser vil kunne se begreper som jobbes med før de er ferdig? Hva tenker du, @stigbd

**Comment by marittor** [comment]
Denne avvises. er ivaretatt av #77 og #112

**Comment by stigbd** [comment]
Enig med din siste kommentar, Marit. Og denne dekkes av anna historie.
