### ISSUE TITLE
[BRUKERHISTORIE] Gi tilgangsrettighet til virksomhetsintern datakatalog

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#234]
Som: leder i virksomhet
Ønsker jeg å: kunne se, tildele og fradele tilganger til registreringsløsning for virksomhetsintern datakatalog uavhengig av hvilken påloggingsmetode som brukes
Slik at: jeg har kontroll på tilgangsrettigheter på vegne av min virksomhet

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by KjerstiSteien** [comment]
Jeg tror ikke vi kommer til å kunne løse dette uavhengig av påloggingsmetode. Her må virksomhetene velge hvilken påloggingsmetode de skal bruke. De fleste vil måtte bruke Altinn per i dag.
