### ISSUE TITLE
[BRUKERHISTORIE] Gi tilgangsrettighet til virksomhetsintern datakatalog

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#235]
Som: leder
Ønsker jeg å: kunne administrere tilganger til virksomhetsintern datakatalog  gjennom eksisterende løsninger for brukergrupper
Slik at: det blir enkelt å vedlikeholde tilgangsrettigheter

Relatert til brukerhistorie: #300

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by BRespen** [comment]
Vurderes å være dekt av brukerhistorie #300 og lukkes derfor
