### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til regnskapstall fra siste regnskapsår 

### ISSUE THREAD

**Issue by BR-Svein** [Informasjonsforvaltning/behov#244]
Som: Bruker av API`et
Ønsker jeg å: få tilgang til regnskapstall fra siste regnskapsår som er innrapportert til Regnskapsregisteret i maskinlesbart format
Slik at: jeg alltid får tilgang på de ferskeste regnskapstall som er levert

Relatert til epos: #180 

Lenke til design: 
Lenke til løsningsarkitektur:
Forretningsverdi: VIKTIG

**Comment by data-david** [comment]
Er denne en duplikat (slightly mer eller mindre spesifikk) med #257

**Comment by BR-Svein** [comment]
Den spesifiserer hvilke tall som skal levers



S

Fra: data-david <notifications@github.com>
Sendt: fredag 26. april 2019 14.57
Til: Informasjonsforvaltning/behov <behov@noreply.github.com>
Kopi: Grønmo, Svein Erik <svein.gronmo@brreg.no>; Author <author@noreply.github.com>
Emne: Re: [Informasjonsforvaltning/behov] [BRUKERHISTORIE] Tilgang til regnskapstall fra siste regnskapsår (#244)


Er denne en duplikat (slightly mer eller mindre spesifikk) med #257<https://github.com/Informasjonsforvaltning/behov/issues/257>

**Comment by data-david** [comment]
Jeg velger å slå dem sammen, og heller flytte "siste regnskapsår" til EPOSet.
