### ISSUE TITLE
[BRUKERHISTORIE] Få de mest relevante treffene øverst når jeg har gjort et søk i portal

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#264]
Som: Intern leser som søker i Felles begrepskatalog portal
Ønsker jeg å: få de mest relevante treffene øverst når, for eksempel at begrepet "barn" eller begrepet "skattepliktig inntekt" dukker opp som henholdsvis nr. 1 i søket (framfor at jeg finner "barn" som nr. 9. i søket, og "skattepliktig inntekt som nr 2 i søket"] 
Slik at: Jeg enklere kan få oversikt over om begrepene finnes i Felles begrepskatalog. 

Relatert til epos:
Relatert til brukerhistorier: #54 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig - Skatteetaten har 3137 begreper i FDK - og det er umulig å finne fram. Må prioriteres høyt.

**Comment by marittor** [comment]
@joebrreg, har lagt inn denne og også her referert til #54. Ser at 54 ligger i design og løsningsarkitektur, så kanskje er dette allerede tenkt på. Vet du hvor lenge det er til den er klar til konstruksjon? Vi kommer ut med en kronikk på Felles begrepskatalog i mai, og da er det fint hvis dere har fått gjort noe knyttet til forbedring av søk.

**Comment by joebrreg** [comment]
@marittor Ja, dette skal forhåpentligvis løses med #54. Saken er snart klar for konstruksjon.

**Comment by marittor** [comment]
@joebrreg betyr det at jeg nå kan lukke denne?

**Comment by marittor** [comment]
@joebrreg Skulle det gjøres noen flere grep for å sørge for enda høyere treff? F eks at løsøre alltid vil komme foran løsøreregisteret (som jo blir 'løsøre*')? Idag kommer nok denne (LR) først fordi den har stor forbokstav? Da avventer jeg med å lukke saken til det er gjort, hvis det er planer om det.

**Comment by joebrreg** [comment]
@marittor Ja, vi skal ta flere grep her, da er høyere vekting av eksakt treff et av de. Når det blir, er litt mer usikkert. Det blir ikke i sprinten som starter i dag.
