### ISSUE TITLE
[BRUKERHISTORIE] Visning av modellbeskrivelse (metadata om modell)

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#267]
Som: Modellkonsument
Ønsker jeg å: kunne få vist fram modellbeskrivelsen (metadata om modellen) basert på spesifikasjonen for informasjonsmodeller (dcatno:informationModel)
Slik at: jeg kan få bedre kunnskap om hva modellene beskriver og lettere kan søke fram til modeller

Eksempler på metadata på modeller: tittel, kontaktpunkt, publiseringsdato, landingsside m.m.
Relatert til epos: #406   

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by RogerSOlsen** [comment]
Lukket i møte Rydding av behovsboard 02.03.2022
