### ISSUE TITLE
[BRUKERHISTORIE] Publisere oversikter over API-er på vegne av andre

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#27]
Tilhører epos: #12 
"Som forvalter av "Annen API-katalog" ønsker jeg å kunne publisere innholdet i felles API-katalog uten manuelle prosesser"

Eksempel: FINT tilbyr API-er på vegne av fylkeskommunene. De ønsker å synliggjøre disse API-ene i felles API-katalog. FINT har ikke rolle i Altinn for alle fylkeskommunene. FINT ønsker ikke å registrere tilleggsinformasjon om API-ene manuelt.

Parallell til hva vi gjør for kataloger for datasettbeskrivelser, f.eks. data.norge.no og GeoNorge.
Viktig at det ikke er åpent for at aktører selvbetjent kan publisere på vegne av andre (via registreringsløsningen) -- FDK må ha kontroll på hvem som har rett til å publisere på vegne av andre.

Ok, @fsjovatsen ?

Løsningsarkitektur: Baserer seg på høsting av API-katalober med API-beskrivelser i form av revidert DCAT-AP-NO, ref #185. Brukerhistorien inkluderer ikke støtte for registrering og publisering på vegne av andre gjennom registreringsløsningen.

**Comment by RogerSOlsen** [comment]
er løst ved implementering av DCAT-AP-NO 2.1
