### ISSUE TITLE
[EPOS] Administrere endepunkter (API) på vegne av flere tilbydere

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#274]
Som: forvalter av api-beskrivelser på vegne av andre aktører
Ønsker jeg å: administrere informasjon knytta til API'er
Slik at: aktørenes API er søkbare i API-katalogen, også maskinelt

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by stigbd** [comment]
I dette eposet dokumenterer vi særlig funksjonalitet knytta til "standardiserte API"/"tjenesteyper", og først og fremst brukerbehov i DSOP-kontroll universet, ut over det som til no er tatt fram i API-katalogen.

**Comment by sskagemo** [comment]
Denne er  duplikat av #12 , som også inkluderer publisering "på vegne av". Lukker derfor denne.
