### ISSUE TITLE
[BRUKERHISTORIE] Visning informasjonsmodeller - kobling til API

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#284]
Som: modellkonsument
Ønsker jeg at: koblingene modellen har til en API-beskrivelse skal vises i detaljsiden til modellbeskrivelsen og at det skal være mulig å navigere seg fra modellbeskrivelsen til API'et og tilbake
Slik at: jeg enklere kan se sammenhengen mellom modellen og API'et det er knyttet til.

Relatert til epos: #406

Lenke til design:
Infomod detalj – https://eggedosis.github.io/fdk-design/redirects/portal/infomodel/detail-structure-default.html
API detalj – https://eggedosis.github.io/fdk-design/redirects/portal/dataservice/detail-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ToHelland** [comment]
Mulig i dagens løsning.

**Comment by RogerSOlsen** [comment]
Lukket i møte Rydding av behovsboard 03.03.2022
