### ISSUE TITLE
[BRUKERHISTORIE] Generell informasjon om NAP (menyvalg)

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#288]
Som: bruker av transportdata
Ønsker jeg å: få informasjon om hva NAP er, hvem som har ansvaret for NAP, hvor jeg skal hendvende meg om spørsmål om NAP, hvilke datasett som hører hjemme på NAP, regelverket etc
Slik at: jeg får svar på spørsmål om NAP

Relatert til epos: #7 

Lenke til design: https://projects.invisionapp.com/share/PVQIEP15ADG#/screens/369545086
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

I møte med SVV presenterte SVV skisse til innhold for informasjonssider om NAP, inkludert landingsside.

Denne brukerhistorien dreier seg bare om lenke i toppen av skissene "Om nasjonalt tilgangspunkt for Transportdata"

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Åpne siden "Om nasjonalt tilgangspunkt for Transportdata"

Dekkes ikke:   (Dekkes i andre brukerhistorier) 
 
Referanser:
Scenario: Om nasjonalt tilgangspunkt for Transportdata"
Gitt at bruker er pålogget siden nap.fellesdatakatalog.no
Når bruker klikker på menylenken "Om nasjonalt tilgangspunkt for Transportdata"
Så skal  "siden Om nasjonalt tilgangspunkt for Transportdata" vises

**Comment by data-david** [comment]
CMS er ikke en del av FDK koden, og det er derfor kun menyvalgene som endres her.

**Comment by lillelars** [comment]
@sskagemo Her mangler vi en url til hvor lenken "Om Nasjonalt tilgangspunkt for transportdata" skal ta brukeren
