### ISSUE TITLE
Datasett registrering: Utvidet søk i felter og visning av flere felter i livesøk under bolken "Søkeord og begrep""

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#291]
Som skrivebruker 
Gitt at jeg skal koble begreper og datasett i datasettregistrering
Ønsker jeg at tillatte og frarådde termer inngår i søket og at det gir et treff på riktig term. 
OG at ansvarlig virksomhet for begrepet vises i treffene
OG at fagområde til begrepet vises i treffene
Slik at jeg kan velge riktig term til tross for at jeg har skrevet inn en tillatt eller frarådd term til begrepet 
OG slik at jeg får hjelp til å velge riktig begrep ut fra fagområde og ansvarlig virksomhet, når jeg får flere treff på termen. 

Eksempel: Dokumentnummer (anbefalt term) skal dukke opp når man søker opp f. eks dagboknummer (som er en tillatt term). 

Lenke til trådskisser: Mangler
Lenke til design: https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/343911175_DATA-REG-Begrep-S-k--D
Lenke til løsningarkitektur: 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig

**Comment by marittor** [comment]
@joebrreg Satte deg på denne, da dette egentlig gjelder datasettregistreringen, og slik sett er det et behov som de som skal registrere datasett har.

**Comment by RogerSOlsen** [comment]
denne blir ikke prioritert fordi vi mener at at det er tilstrekkelig med de feltene som finnes i dag
