### ISSUE TITLE
[BRUKERHISTORIE] Tydelig skille mellom søkeportal og registreringsløsning

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#293]
Som bruker av søkeportal og registreringsløsning 
Ønsker jeg å tydelig se skille på disse to løsningene
Slik at jeg kan lettere se hvilken løsning jeg til envher tid er inne i.

(Hint: Dette kan være så enkle grep som å justere fargen littegrann.)

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Dette løser vi som del av arbeid med registreringsløsning og portal. Lukker denne saken.
