### ISSUE TITLE
[BRUKERHISTORIE] hente nye årsregnskap siden en gitt dato

### ISSUE THREAD

**Issue by bgrova** [Informasjonsforvaltning/behov#294]
Som: data-aggregator
Ønsker jeg å: hente alle nye årsregnskap som er gjort tilgjengelig i Regnskapsregisteret siden en gitt dato
Slik at: jeg kan oppdatere min egen database, uten å måtte lage en spørring for hver enkelt organisasjonsnummer

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette er ikke lengre relevant for dette prosjektet. Lukker dermed saken.
