### ISSUE TITLE
[BRUKERHISTORIE] laste ned alle årsregnskap

### ISSUE THREAD

**Issue by bgrova** [Informasjonsforvaltning/behov#295]
Som: data-aggregator
Ønsker jeg å: laste ned alle årsregnskap 
Slik at: jeg kan få en kopi av alle årsregnskap uten å måtte gjøre en spørring for hvert enkelt organisasjonsnummer

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette er ikke lengre relevant for dette prosjektet. Lukker dermed saken.
