### ISSUE TITLE
[BRUKERHISTORIE] beskrivelse av felter

### ISSUE THREAD

**Issue by bgrova** [Informasjonsforvaltning/behov#297]
Som: bruker av regnskapsdata
Ønsker jeg å: lese en beskrivelse av feltene i Regnskapsregisteret
Slik at: jeg vet hvordan jeg skal tolke dataene

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette er ikke lengre relevant for dette prosjektet. Lukker dermed saken.
