### ISSUE TITLE
[BRUKERHISTORIE] Behov for ledetekst og hjelpetekster

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#3]
Som: skrivebruker/fagperson
Ønsker jeg: at systemet gir god beskjed om hvordan begreper skal defineres og dokumenterer f.eks. entall/flertall, og gjerne påminnelse om utskiftningsprinsippet
Slik at: bruken blir harmonisert.

EPOS: #2 
Relatert til brukerhistorie: #76

**Comment by marittor** [comment]
F. eks bruke Termlosen som guidance?

**Comment by marittor** [comment]
Få feedback under registreringen?

**Comment by marittor** [comment]
Nærmere behandlet på innføringsmøte 27.2. Språkrådet kontakter relevante org. ifm Termlosen. Kan ellers se hvorvidt standard for begrepsbeskrivelser og formuleringer her kan passe inn som hjelpetekst eller ledetekst. Bør kunne ha noe tilsvarende det som er gjort i registreringsløsning datasett, en mulig kombo av utdrag fra veileder, termlosen (hvis avklart at dette er OK) og eksempler der dette er nyttig.

**Comment by lillelars** [comment]
@marittor Hva er status på denne? Velding fint om Lene får hjelpetekster til skissene sine

**Comment by marittor** [comment]
@lillelars - Venter fortsatt litt på avklaringer om vi kan bruke noe fra Termlosen. Skal snakke med de andre igjen, slik at vi kan sikre oss at vi ikke bryter med noe opphavsrett/åndsverk.

**Comment by marittor** [comment]
Lagt inn som krav i hhv #76  og #201 og lukkes derfor som egen historie.
