### ISSUE TITLE
[BRUKERHISTORIE]Brukerroller virksomhetsintern datasettkatalog

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#300]
Som:  virksomhet
Ønsker jeg å: kunne tildele enten lese- eller skriverolle til interne brukere
Slik at: hele organisasjonen har tilgang til katalogen

Relatert til epos: #5 
Relatert til brukerhistorie: #71 og #372 
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by stigbd** [comment]
Denne har overlapp med #60 , #69, #71 og #68. Eg tenker vi må rydde opp i dette og lage ein løsningsbeskrivelse som dekker alle disse behova (viss mulig).

**Comment by BRespen** [comment]
Brukerhistorie #300 er en "gammel" historie som er blitt erstattet av den nye brukerhistorie #372.
