### ISSUE TITLE
[EPOS] Utvidet funksjonalitet for oppslag på standardiserte API-beskrivelser

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#302]
Som: bruker av FDKs funksjonalitet for oppslag på standardiserte API-er
Ønsker jeg å: ha støttefunksjoner for å håndtere flere aktører på en smidig måte og endringer over tid
Slik at: API-ene kan videreutvikles over tid uavhengig av hverandre

Dette eposet samler behov som er dukket opp etter implementeringen av epos #11

Tilknyttede brukerhistorier:
(prioritert rekkefølge)
- [x] #330 
- [x] #340 
- [x] #304 
- [x] #303 
- [x] #339 
- [x] #367 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig (NB! #330 er kritisk for DSOP H2019)

**Comment by KjerstiSteien** [comment]
@livarb kan du se på status og prioritet for brukerhistoriene knyttet til dette eposet?

**Comment by KjerstiSteien** [comment]
Denne saken må beskrives på nytt. Derfor lav prioritet.

**Comment by KjerstiSteien** [comment]
Lukkes da sakene i stor grad er knyttet til endepunktet for API-oppslag vi leverte for Bits. Dette vil fremover tilbys gjennom data.altinn.no. Noen av behovene kan fortsatt være gyldige, men krever en oppdatering av dcat-ap-no før vi kan legge dem inn i vår kø.

**Comment by KjerstiSteien** [comment]
Team Data som ressurs og data.altinn.no er orientert om lukkingen og har fått tilsendt saken, dersom de ønsker å ta behovene videre i sitt arbeid.
