### ISSUE TITLE
[BRUKERHISTORIE] Utvidbarhet for beskrivelse av et endepunkt i en API-beskrivelse ("key/value")

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#303]
Som: tilbyder av et API
Ønsker jeg å: kunne utvide beskrivelsen av et endepunkt ved hjelp av et generisk "key/value"-element for bruk innenfor et bestemt bruksområde/gruppe
Slik at: jeg kan dekke behov for ekstra informasjon som oppstår, uten at det påvirker hele økosystemet for Felles datakatalog

Basert på følgende behovsbeskrivelse fra Skatteetaten:
<klipp>
Det bør mulig å registrere ytterligger opplysninger knyttet til et endepunkt i form av "navn/verdi"-par ("extensions"). Dersom det etter hvert viser seg at enkelte verdier ofte er relevante kan de legges inn som faste(valgfrie) attributter etterhvert.
</klipp>

Relatert til epos: #302 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Løses ikke, da vi mener behovet må dekkes av data.altinn.no, som vil være de som leverer oppslags-API-et heretter.
