### ISSUE TITLE
[BRUKERHISTORIE] Ulike versjoner av endepunkter for standardiserte API-beskrivelser

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#304]
Som: konsument/tilbyder av API
Ønsker jeg å: angi at et endepunkt som støtter et standardisert API, støtter en spesifikk versjon av dette standardiserte API-et, og angi når støtte begynner/slutter
Slik at: forenkler overgangen til nye versjoner av standardiserte API-er

Relatert til epos: #302 

Basert på innspill fra Skatteetaten:
<klipp>
Løsningen må støtte ulike versjoner av endepunkter (F.eks. Konto v1, v2) med overlappende start og slutt-tidspunkter.
</klipp>

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Løses i data.altinn.no
