### ISSUE TITLE
[BRUKERHISTORIE] Generere en rapport med alle behandlingsaktiviteter

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#305]
Som: skrivebruker og lesebruker
*Gitt at jeg står i Protokoll over behandlingsaktiviteter hos [virksomhet x]*
Ønsker jeg å: generere en rapport som viser alle behandlingsaktiviteter i protokollen
Slik at: jeg kan dokumentere overfor f. eks tilsynsmyndigheter at jeg etterlever personvernet og GDPR. 

Relatert til epos: #10 
Relaterte brukerhistorier: #168  

Lenke til trådskisser: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/387848756
Lenke til design (viser kun selve knappen, ikke hva som skjer ved klikk): https://invis.io/APUPOL4B4G7#/392166476_BEHAKT-REG-OVERSIKT-Default--D-
Lenke til rapporten (design): 
Lenke til løsningsarkitektur: se epos

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Generere rapport behandlingsaktiviteter

Dekkes ikke:   (Dekkes i andre brukerhistorier) 
   
Referanser:
Scenario: Generere rapport behandlingsaktiviteter
Gitt at siden for alle behandlingsaktiviteter vises
Når bruker klikker på knappen "Rapport"
Så skal behandlingsaktiviteter med alle felter listes opp

Må også få med kontaktinfo til  behandlingsansvarliges representant(er) og PVO i rapporten.

**Comment by marittor** [comment]
@AleksandraHrpka Dette er en ny historie som vi trenger skisser på. :)

**Comment by stigbd** [comment]
Er det eit krav at rapporten skal bli generert i pdf? Det er ei enkel sak å printe ei vanlig side til pdf ved å utnytte nettleserens skriv ut funksjon.

**Comment by marittor** [comment]
Behovet går ut på å kunne få en rapport hvor alle feltene i behandlingsaktiviteten kommer fram. Det vil si at man f. eks kan velge å generere rapporten på selve "list opp alle BA"-siden, men rapporten som kommer ut må gi informasjon utover denne listen, altså detaljene i innholdet i behandlingsaktivitetene.

**Comment by stigbd** [comment]
Ok, altså ikkje krav om pdf. Kanskje fint om akseptanse-kriteria reflekterer dette, ref
> Så skal nytt pdf-dokument opprettes der alle behandlingsaktiviteter skal listes opp

**Comment by marittor** [comment]
@eggedosis og @frode-kleven: Kan vi sette oss ned og lage et design på rapporten?

**Comment by eggedosis** [comment]
@marittor Det kan vi selvsagt. Har du mulighet til å sende oss gode eksempeldata for flere  behandlingsaktiviteter?

**Comment by marittor** [comment]
@stigbd rettet opp "se også" til "se epos" på løsningsarkitekturen.

**Comment by RogerSOlsen** [comment]
@lillelars: jeg får ikke fullført test av akseptansekriterier fordi protokollen ser ut til å mangle lesebruker. Brukerhistorien omfatter også lesebruker.   Testet om det var tilgang til lesebruker sammen med @joebrreg i dag

**Comment by RogerSOlsen** [comment]
Det finnes to valg for rapport; "Behandlingsoversikt" og "Protokoll". Begge rapporter kan genereres av lesebruker og skrivebruker. Brukerhistorien er derfor lukket.

Rapportvalg «Behandlingsoversikt» tilsvarer «Rapport» slik den var tidligere. "Behandlingsoversikt" genererer rapport om alt som er registrert i alle behandlingsaktiviteter, både de som har status Godkjent og de som har status Utkast, samt navn og kontaktopplysninger til Personvernombud, behandlingsansvarlig, behandlingsansvarliges representant – og representant for behandlingsansvarlig utenfor EU/EØS dersom dette finnes.

Rapportvalg «Protokoll» genererer rapport over obligatoriske felter i godkjente behandlingsaktiviteter, samt navn og kontaktopplysninger til Personvernombud, behandlingsansvarlig, behandlingsansvarliges representant – og representant for behandlingsansvarlig utenfor EU/EØS
