### ISSUE TITLE
[BRUKERHISTORIE] Lese relasjoner mellom begreper på detaljside

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#307]
Som: lesebruker
Ønsker jeg å: se et begreps relasjon til et annet på detaljesiden i FDK Portal
Slik at: jeg kan se hvilke begreper som er relatert til hverandre

Det som skal synes i portal er 
type relasjon| begrep
Når relasjonen er av typen assosiativ, skal det i tillegg vises fram på detaljsiden "beskrivelse: <input>"
Når relasjonen er av typen generisk eller partitiv, skal det i tillegg vises fram på detaljsiden "inndelingskriterium": <input>". Dette kommer fram i skissene

Relatert til epos: 
 #26 
Lenke til trådskisser: 
Lenke til design: https://invis.io/3SRCN149CQN#/387607015_BEGREP-PORTAL-DETALJ-Default-Blir-Gyldig--D-
Lenke til løsningsarkitektur: gitt at dette er i FDK Portal, må dette løysast ved at fdk-concept-harvester returnerer alle relasjoner i begreps-api. Api-spesifikasjonen må endrast for å støtte dette.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Prioritet fra innføringteam etter prio-runde på resterende brukerbehov "Del 3", 21.8.2019: Viktig (nest høyest prioritet)

Akseptansekriterier:
,# language: no
Egenskap:
Kriterier:
⦁ Lesing av begrepsrelasjoner

Referanser:
Scenario: Lesing av begrepsrelasjoner
Gitt at bruker med leserettigheter er logget inn
og at begrepet "Sjømann" er relatert til begrepet "Person"  med typen generisk
Når bruker går inn på siden Begrepskatalog i søkeportalen 
Så skal bruker kunne se begrepsrelasjonen "Sjømann" og "Person" med type "Generisk"

**Comment by marittor** [comment]
@stigbd Kan du gå inn her og se på om det skal lenkes til noe løsningsarkitektur?

**Comment by stigbd** [comment]
Eg har lagt til ein kommentar under løsningsarkitektur.

**Comment by marittor** [comment]
@sindresandvik2 : Er det noen akseptansekriterier som du vil legge på her?

**Comment by sindresandvik2** [comment]
Done!

**Comment by marittor** [comment]
> 
> 
> Done!

Supert! Har satt denne videre Klar til konstruksjon.

**Comment by KjerstiSteien** [comment]
Relaterte saker: 
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/917
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/935

**Comment by KjerstiSteien** [comment]
Relasjoner kan leses på detaljside for begrep. Lukker denne saken.
