### ISSUE TITLE
[EPOS] GUI for å adminstrere høsting av API-kataloger

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#314]
Som: forvalter av API-katalog
Ønsker jeg å: kunne administrere hvilke api-kataloger i et enkelt gui
Slik at: jeg kan enkelt bestemme hvilke kataloger som skal høstes inn av FDK

Tilknyttet overordnet EPOS: #12 
Tilknyttede brukerhistorier:

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by stigbd** [comment]
Typiske funksjoner vil vere:
- Legge til en katalog som skal høstes
- Se på detaljer om en katalog-oppføring
- Endre en katalog-oppføring
- Fjerne en katalog-oppføring

**Comment by stigbd** [comment]
I dag ser det tilsvarande for datasett slik ut:
![image](https://user-images.githubusercontent.com/1702357/62370770-4cebeb80-b533-11e9-84cb-6312a9b624c4.png)

**Comment by oystein-asnes** [comment]
Usikkert om status for ved innhøsting er realisert, men epost lukkes
