### ISSUE TITLE
[BRUKERHISTORIE] Lenkede data fra enhetsregisteret

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#319]
Som: konsument av lenkede data
Ønsker jeg å: få lenkede data i RDF fra enhetsregisteret
Slik at: jeg kan lenke data fra RR (regnskap), ER (enhet), Kartverkets Adm.grenser(kommune) og utenlandske registre for å oppnå best mulig datakvalitet.

Relatert til epos: #317 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by shenluna** [comment]
@stigbd Kan denne lukkes?

**Comment by stigbd** [comment]
Lukker sidan tjenesten ligger hos Brønnøysundregistrene og issue er gjenskapt der:
https://github.com/datautvikling/behov/issues/2
