### ISSUE TITLE
[BRUKERHISTORIE] Spesifisere miljø ved oppslag på standardiserte API

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#330]
Som: bruker av API-katalogens løsning for oppslag på standardiserte API
Ønsker jeg å: angi hvilket miljø jeg ønsker endepunktsadresse for
Slik at: kan skille mellom test-, preproduksjon- og produksjonsmiljø i tjenestene som skal benytte API-ene

Relatert til epos: #302

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig (forutsetning for DSOP-Kontrollinformasjon). Alternativt må vi skille mellom ulike API-beskrivelser i ulike FDK-miljø og ha en sterk binding mellom våre miljø og miljøene i bankene og Skatteetaten/Nav

**Comment by sskagemo** [comment]
Aktuell løsning er å utnytte OAS og muligheten til å angi "description" for de ulike url-ene i "servers"-elementet, og legge dette til som en spørreparameter, f.eks: https://demo.fellesdatakatalog.brreg.no/api/apis/endpoints?serviceType=Kontoopplysninger&orgNos=984851006,837884942&servers=Production

**Comment by sskagemo** [comment]
Enige i møte med BITS og etatene om å kalle query-parameteren "environment"

**Comment by sskagemo** [comment]
Enige i møte med BITS og etatene om å kalle de to ulike miljøene hhv "Production" og "Test"

**Comment by KjerstiSteien** [comment]
Løses gjennom flytting av endepunkt for oppslag på standardiserte API til data.altinn.no
