### ISSUE TITLE
[BRUKERHISTORIE] Vise hvilken portal det publiseres tili

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#331]
Som: datasetteier
Ønsker jeg å: gjennom valg som gjøres i registreringen se om datasettet blir publisert henholdsvis i åpne data portal og sektor-portal (f.eks. NAP)
Slik at: jeg forstår konsekvensene av mine valg

Relatert til epos: #346

Lenke til design: https://invis.io/SFTW6CSAD94#/384955884_REGISTRERING-Datasett-01
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Vise meldinger om at datasett publiseres til NAP

Referanser:
Scenario: Vise meldinger om at datasett publiseres til NAP
Gitt at detaljsiden for registrere nytt datasett vises
Når bruker velger "Tilgangsnivå" = "Offentlig" 
og bruker velger "Tema" = "Trafikk, reiser og samferdsel"
Så skal meldingen "Datasettet vil bli publisert i Felles datakatalog og NAP"  vises på siden

**Comment by sskagemo** [comment]
For NAP, ved valg av det rette utvalg av tema skal det bli synlig at datasettbeskrivelsen blir synlig i NAP-portalen, i tillegg til Felles datakatalog

**Comment by sskagemo** [comment]
Notater fra møte med SVV:
- Skisse presentert i møte er OK for varsel om at innhold vil bli publisert til transportportal.no, når kriteriene er tilfredsstilt
- Skisse som viser hva som skjer når krtieriene ikke lenger er tilfredsstilt (når datasettet angis som "begrenset" er OK.
- tilsvarende melding som når datasettet endres fra offentlig til begrenset må gis ved "fravalg" av relevante LOS-tema
- statusen i publiseringslinjen nederst er OK gitt oppdatert tekst.

SVV kommer med tekst / navn på portalen
