### ISSUE TITLE
[BRUKERHISTORIE] Liste organisasjonsnummer jeg kan registrere på vegne av

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#332]
Som: ansvarlig for registrering av datasett for en større aktørgruppe
Ønsker jeg å: kunne liste orgnummer som jeg ønsker å inkludere i min portefølje
Slik at: disse kan varsles om at jeg kan registre på deres vegne, og registreringen kan skje

Relatert til epos:#341

Lenke til design: https://invis.io/8WTQMR2A35G#/382412354_WF_-_DATA-REG-332_333-01
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by joebrreg** [comment]
Dette blir løst på en annen måte i #335
