### ISSUE TITLE
[BRUKERHISTORIE] velge i registreringsløsningen hvem jeg registrerer på vegne av

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#333]
Som:ansvarlig for registrering av datasett for en større aktørgruppe
Ønsker jeg å: kunne velge konkret i registreringsløsningen hvem jeg registrerer på vegne av
Slik at: registreringen skjer på den aktuelle organisasjonen

Relatert til epos: #341 

Lenke til design:
Valgt design er nedtrekksmeny:
https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/382412352
 https://invis.io/8WTQMR2A35G#/382412354_WF_-_DATA-REG-332_333-01
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by sskagemo** [comment]
Landingssiden: Ingen endringer; vil være noen virksomheter som har fått delegert rettigheter, andre ikke.
Liste over datasett: Trenger å synliggjøre hvem som eier de ulike i tabellen dersom de har fått delegert rettigheter
Registrering av datasett: Trenger felt for å angi datasetteier

**Comment by sskagemo** [comment]
Møte med SVV:
- enig i "drop-down"-tilnærmingen
- må være forhåndsutfylt med egen organisasjon, så man slipper å ta aktivt valg på det som vil være det normale
