### ISSUE TITLE
[BRUKERHISTORIE] administrasjonsgrensesnitt for å whiteliste private organisasjoner

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#334]
Som: ansvarlig for felles datakatalog
Ønsker jeg å: et administrasjonsgrensesnitt der jeg kan whiteliste private organisasjoner
Slik at: dette kan utføres av relevant personell

Relatert til epos:#341

Lenke til design: https://invis.io/8WTQMR2A35G#/382414024_334-01
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by sskagemo** [comment]
@stigbd sjekker om dette kan løses i Altinn dersom Altinn kan begrense tilgangen til tjenestetypen til en viss type organisasjoner.

**Comment by stigbd** [comment]
Altinn overlater til oss å bestemme kva personen som har fått delegert rolle i virksomhet skal få lov til å gjøre. (Dette har slik eg forstod med å gjere at vi er ein lenketjeneste, og ikkje ei teneste som køyrer i Altinn. Altinn-tjenester er det mulig å avgrense tilgang til.) Altinn kan dermed ikkje begrense tilgangen til tjenestetypen.

**Comment by RogerSOlsen** [comment]
Lukkes fordi at  det er lite henvendelser om dette og behovet kan løses manuelt.
