### ISSUE TITLE
[BRUKERHISTORIE] Gi virksomheter rett til å registrere på vegne av andre virksomheter

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#335]
Som: ansvarlig for registrering av datasett for en større aktørgruppe
Ønsker jeg å: kunne få rettighet for registrering på vegne av andre aktører
Slik at: jeg kan beskrive datasett på vegne av andre

Relatert til epos:#341

Forutsetning:
- sporbarhet: Hvor kommer dette innholdet fra? Ligger støtte i DCAT-standarden. F.eks. metadata om katalog er uavhengig av metadata om datasett. Informasjon om hvem som har gjort hva bør også synliggjøres som del av visningen.
- abonnere på innholdet? Følge med på endringer som gjelder en selv #162 

Lenke til design: 

Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by joebrreg** [comment]
Hvordan skal administrator for felles datakatalog få tilgang til de inkluderte organisasjonsnumre? Skal han hente godkjenning fra de berørte organisasjonene?
