### ISSUE TITLE
[BRUKERHISTORIE] filtrere og gruppere API på tjenestetype i portalen

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#339]
Som: bruker av portalen
Ønsker jeg å: kunne gruppere og filtrere API-ene på tjenestetype (standardisert API)
Slik at: jeg ikke mister oversikten når det er mange innslag av det samme API-et i katalogen

Idag er halvparten av innslagene i katalogen ulike aktører som tilbyr det samme API-et (kontoppslag) og det er forventet å øke iløpet av høsten. Etterhvert forventer vi at f.eks. kommuner kommer med standardiserte API på en rekke områder (f.eks. NOARK 5 WS) som gjentas pr kommune. Da kan det være hensiktsmessig å ha en visning som gjør at disse API-ene er gruppert eller kan filtreres på.

Relatert til epos: #302

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig

**Comment by KjerstiSteien** [comment]
Denne informasjonen støttes ikke lenger, da den ikke er del av DCAT-AP-NO

**Comment by KjerstiSteien** [comment]
Lukkes, da vi denne informasjonen ikke er støttet av standarden. Informasjonen vises derfor ikke i portal.
