### ISSUE TITLE
[BRUKERHISTORIE] sikre validering av angivelse av "environment" ved standardiserte API

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#340]
Som: tilbyder av et standardisert API
Ønsker jeg å: være sikker på at de ulike URL-ene til mitt API får korrekt "environment"
Slik at: oppslag på standardisert API fungerer som forventet med bruk av environment-variabelen

I #330 er det bestemt at endpoint-oppslag også skal ha en query-parameter for "environment". For de ulike standardiserte API må det finnes en kodeliste for hva de ulike environments kalles. For kontoppslag er det f.eks. bestemt at det skal være to miljø, "production" og "test". Da er det viktig at det registrering av nye tilbydere av kontoppslag får sine URL-er angitt med riktig type. En mulighet er at URL-ene registreres fra en kilde (f.eks. CSV). En annen mulighet er at tilbyder angir dette selv gjennom bruk av "description"-feltet for servers i OpenAPI-specification-fila. Uansett må det mekanismer på plass som sikrer at de riktige verdiene benyttes.

Valideringen kan implementeres som del av registreringen (registreringen feiler), eller som en del av en jevnlig kvalitetssjekk av innholdet i Felles datakatalog som rapporteres som advarsel både til tilbyder og til forvaltningsteamet.

Relatert til epos: #12 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
- Mindre viktig så lenge FDK-forvaltningsteamet tar ansvar for å registrere url-ene, og bruker egne verktøy for dette
- Viktig/Kritisk når det blir større grad av selvbetjening på dette området.

**Comment by KjerstiSteien** [comment]
Regnes ikke som relevant lenger, da oppslag på API er flyttet til data.altinn.no
