### ISSUE TITLE
[EPOS] Virksomhet skal kunne registrere datasett på vegne av andre virksomheter

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#341]
Som: ansvarlig for registrering av datasett for en større aktørgruppe
Ønsker jeg å: kunne registrere datasett med på vegne av andre virksomheter
Slik at: datasettet blir publisert på vegne av de andre virksomhetene

Tilknyttede brukerhistorier: 
 #333, #335, #386 

Venter med: #332 (uavklart hvordan autorisere)

Dette er et område som må balansere faren for misbruk og administrative prosedyrer. Pr idag har noen virksomheter allerede rett til å publisere beskrivelser på vegne av andre der hvor de forvalter kataloger, som Data.norge.no og GeoNorge. Dette er en kvalifisert vurdering gjort av forvalter av Felles datakatalog.

Dette eposet dreier seg om å få tilsvarende mulighet gjennom registreringsløsningen. Forslag til løsning er at forvalter av Felles datakatalog etter en vurdering gir en virksomhet en utvidet rolle i form av rett til å registrere på vegne av andre virksomheter. Det er deretter opp til virksomheten med den utvidete rollen å bestemme hvem de kan registrere for.

Epost gjelder også andre områder enn datasett, har samme behov fra begrep, API ...

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk
Funksjonaliteten er betalt av vegvesenet.

**Comment by RogerSOlsen** [comment]
Alle brukerhistoriene til eposet er løst unntatt en som ikke hørte hjemme her og som derfor flyttet ut av eposet
