### ISSUE TITLE
[BRUKERHISTORIE] Eksponere Felles begrepskatalog som SKOS-AP-NO

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#342]
Som: konsument av FDK sitt begreps-API
Ønsker jeg å: konsumere den publiserte begrepssamlingen som SKOS-AP-NO
Slik at: jeg kan enkelt bruke begrepssamlingen på en standardisert måte

Relatert til epos: #345 
Relaterte brukerhistorier #135 

Lenke til design: N/A
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Regner denne som løst av https://github.com/Informasjonsforvaltning/fdk-concept-harvester/issues/63
