### ISSUE TITLE
[BRUKERHISTORIE] Støtte registrering av datatjeneste (DCAT-AP-NO 2.0)

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#352]
Som: tilbyder av API-er
Ønsker jeg å: publisere beskrivelser andre typer API-er enn de som kan beskrives med swagger/OAS
Slik at: jeg kan få verdi av publisering av API-beskrivelser i Felles datakatalog for andre, viktige API-er jeg tilbyr, både eksisterende og fremtidige

Relatert til epos: #12 
Relatert til brukerhistorie: #429, #428, #425,  
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

En generell måte å beskrive API - à la DCAT2 "DataService" kan gi mulighet til å beskrive langt flere typer API-er, både eksisterende, sentrale SOAP-tjenester, samt forventede nye tjenester som meldingskøer, GraphQL

Gjeldende utkast til revidert DCAT-AP-NO for beskrivelse av API gjennom bruk av DCAT2 DataService er her: https://github.com/difi/dcat-ap-no/blob/feature/add-ontology/ontology/catalog.ttl

**Akseptansekriterier:**
#Må revurderes...
,# language: no
Egenskap: 
Kriterier:
⦁	Støtte innlasting av DCAT2

Referanser:
Scenario: Støtte innlasting av DCAT2
Gitt at siden "Registrer ny API_beskrivelse" vises 
Når bruker trykker på knappen "Importer via fil"
og velger filen "Enhetsregisteret_DCAT2.txt"
Så skal meldingen "Import fra Enhetsregisteret_DCAT2.txt var vellykket" vises

**Comment by stigbd** [comment]
Er framleis usikker på om #185 faktisk dekker denne.

**Comment by stigbd** [comment]
Denne brukerhistorien går på å kunne registrere et API på DCAT AP 2.0 format.

**Comment by oystein-asnes** [comment]
Slik blir dcat-ap-no versjon 2 dersom vi kjøper EUs applikasjonsprofil uten tilpasninger: https://doc.difi.no/review/dcat-ap-no/#datatjeneste

**Comment by shenluna** [comment]
Lukker denne saken, registreringsløsningen støtter idag registrering av API
