### ISSUE TITLE
[BRUKERHISTORIE] Datasett med EU-tema "Transport" må vises i NAP

### ISSUE THREAD

**Issue by joachim-me** [Informasjonsforvaltning/behov#359]
Som: bruker av NAP
Ønsker jeg å: se alle datasett markert med "Transport" og "Trafikk, reiser og samferdsel" i portal
Slik at: jeg kan sammenligne de uavhengig av temakategorisering.

Relatert til epos: #7 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by lillelars** [comment]
Forslag fra Stig er at vi bare manipulerer filteret til å inkludere datasett tagget med "Transport", slik at vi viser disse datasettene i NAP-kontekst også.

Det vil være en enkel løsning i første omgang.. Hva tror dere? @joebrreg @sskagemo
