### ISSUE TITLE
[BRUKERHISTORIE] Se alle endringer gjort på begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#361]
Som: begrepskonsument
Ønsker jeg å: se alle endringer som er gjort på et begrep
Slik at: jeg kan se begrepets livssyklus

Relatert til epos: #153 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Løst gjennom arbeidet som er gjort med virksomhetsintern begrepskatalog https://github.com/Informasjonsforvaltning/behov/issues/787
