### ISSUE TITLE
[BRUKERHISTORIE] Behov for aktiveringsdato for innslagene i API-katalogen

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#367]
_Som_ bruker av endpoint-api i API-katalogen 
_Ønsker jeg å_ få en liste av alle endpoints som er støtter transportprofil="eoppslag" og endpoint skal inkludere aktiveringsdato (datoen endpointet faktisk blir satt i produksjon av tilbyder)
_Slik at_ jeg kan avlede hvem som søtter eoppslag "runtime"

----
Basert på:
> Behovet for aktiveringsdato for innslagene i API-katalogen har dukket opp allerede nå. Det er behov for å registrere prod endepunkter på forhånd, selv om det ikke er i produksjon ennå. Vi bruker innslagene i katalogen for å avlede hvem som støtter eoppslag "runtime".
----

*Avklaringsbehov*
- Er aktiveringsdato = datoen endpointet faktisk blir satt i produksjon av tilbyder
- Skal aktiveringsdato også vere en query-parameter?

Relatert til epos: #302 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by stigbd** [comment]
Det er mulig at dette er inkludert i #304 ? Men sistnemde inkluderer versjonering, som ikkje er implisitt i dette behovet.

**Comment by KjerstiSteien** [comment]
Lukkes, da vi ikke lenger har et endepunkt for oppslag av APIer. Dette flyttes til data.altinn.no.
