### ISSUE TITLE
[BRUKERHISTORIE] Registrere et API uten en spesifikasjonsfil

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#368]
Som: Forvalter av et API
Ønsker jeg å: Registrere et API, selv om jeg ikke har en spesifikasjonsfil (OAS, Swagger el.l.)
Slik at: kan registrere ulike typer API-er

Relatert til epos: #12 

Lenke til design: 
Lenke til løsningsarkitektur: Forutsetter #352, som et felles, generisk vokabular for å beskrive API-er, og som blir "output" av en slik registrering.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig, ettersom vi allerede jobber med andre API-er enn det som kan beskrives som OAS

**Comment by KjerstiSteien** [comment]
@KurtStian @livarb Slik jeg leser saken har vi støtte for dette i API-katalogen i dag. Er dere enige?

**Comment by livarb** [comment]
> @KurtStian @livarb Slik jeg leser saken har vi støtte for dette i API-katalogen i dag. Er dere enige?

@KjerstiSteien Trur det. Skal for ordens skyld logge meg på og sjekke sjølv.

**Comment by KurtStian** [comment]
> @KurtStian @livarb Slik jeg leser saken har vi støtte for dette i API-katalogen i dag. Er dere enige?

@KjerstiSteien Ja, det mener jeg. Vokabularet er https://data.norge.no/specification/dcat-ap-no#Datatjeneste. Og vi har registreringsløsning for å registrere API-er basert på dette vokabularet.

**Comment by KjerstiSteien** [comment]
Regner denne som løst
