### ISSUE TITLE
[EPOS] Representere api'er på en standardisert måte

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#37]
Som: informasjonsforvalter
Ønsker jeg å: få informasjon om api'er på en standardisert måte
Slik at: jeg kan forstå og importere api-beskrivelsen

Slik som datasett er representert i DCAT-AP-NO og begrep er representert i SKOS, bør vi kunne representere (via API-et vårt) API på en standardisert måte. Utfordringa som bur i dette er å identifisere eksisterande standarder, om slike i det heile teke fins.

**Comment by stigbd** [comment]
Det er oppretta ein "task-force" på dette, med blant andre disse deltakarane:
Eirik Broen, Oslo Kommune @eirikbroen
Øystein Åsens, Difi @oystein-asnes

**Comment by sskagemo** [comment]
Dette eposet følges nå opp i #184, lukkes som duplikat
