### ISSUE TITLE
[USER STORY] Provide audit trail

### ISSUE THREAD

**Issue by ekoskent** [Informasjonsforvaltning/behov#370]
Som: As an auditor or tax auditor
Ønsker jeg å: I need to be able to know which accounting entries are derived from which vouchers
Slik at: So that I can see what kind of business transactions are under the accounting entries and if they are correctly recorded.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ekoskent** [comment]
We need to add the voucher number given by the reference implementation to the business transaction data (possibly this is already in the data base linked). The correct  element in the XBRL GL data is gl-cor:documentNumber with in the entryDetails

**Comment by ekoskent** [comment]
Also the assigned business transactionID may be added to the gl-cor:uniqueID element in XBRL GL

**Comment by shenluna** [comment]
This user story is no longer relevant for this project. Closing issue.
