### ISSUE TITLE
[USER STORY] Bring business transactions from another system

### ISSUE THREAD

**Issue by ekoskent** [Informasjonsforvaltning/behov#371]
Som: As a business owner
Ønsker jeg å: I want to bring business transaction details from another system that are created there
Slik at: I can use flexible system architecture to fit my business needs

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ekoskent** [comment]
The same this as updating business data #155 but this time the transaction is not existing already in the target system. 

What about the voucher for these, is it enough that they might be stored somewhere else and only linked in the system?

**Comment by shenluna** [comment]
This user story is no longer relevant for this project. Closing issue.
