### ISSUE TITLE
[BRUKERHISTORIE] API endpoint skal returnere versjonsnummer til API-spec

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#377]
Som konsument av API-katalogens API
Ønsker jeg å få egenskapen versjon når jeg ber om endpoint-informasjon
Slik at jeg vet hvilken versjon API-spesifikasjonen til APIet har

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Versjon er ikke støttet for API lenger. Saken lukkes.
