### ISSUE TITLE
[BRUKERHISTORIE] API endpoint skal returnere status til API

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#378]
Som konsument av API-katalogens API
Ønsker jeg å få egenskapen status når jeg ber om endpoint-informasjon
Slik at jeg vet hvilken status APIet har

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Egenskapet "Status" er ikke lenger støttet. Saken lukkes.
