### ISSUE TITLE
[BRUKERHISTORIE] Opprette ny behandlingsaktivitet - valgfrie felt

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#380]
Som: skrivebruker
Ønsker jeg å: kunne opprette en behandlingsaktivitet og beskrive valgfri informasjon i en Behandlingsaktivitetsoversikt
Slik at: jeg kan dokumentere hvordan virksomheten behandler personopplysninger, og
Slik at: vi ivaretar den enkeltes personvern og etterlever personvernforordningen i EU (GDPR)

Per behandlingsaktivitet skal følgende valgfrie felt støttes (iht datatilsynets mal er disse merket som "hensiktsmessige" å ta med):
- Daglig behandlingsansvar
- Funksjonsområde
- Hvor kommer opplysningene fra (kilde)
- Behandlingsgrunnlag artikkel 6
- Rettslig forpliktelse, berettighet interesse mv.
- Behandlingsgrunnlag artikkel 9 eller 10
- I hvilke av våre systemer behandles opplysningene
- Kan behandlingen innebære høy personvernrisiko
- Navn på databehandlere

Lenke til hjelpetekster: https://docs.google.com/document/d/1B55vGWVdezos4lotFd5SMGuZfx8n0pyVNnNQd0mklv0/edit?usp=sharing

Relatert til epos: #391 
Relatert til brukerhistorier: #167 

Gammel Trådskisser skrivebruker: https://vfy2gg.axshare.com/#g=1&p=legg_til_ny_behandlingsaktivitet

NY trådskisse: https://invis.io/8WTQMR2A35G#/385427326_REGISTRERING-NyBehandlingsaktivitet-01

Lenke til design:
https://invis.io/APUPOL4B4G7#/395858477_BEHAKT-REG-Behansvar-Default--D-
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterier:
,# language: no
Egenskap:
Kriterier:
⦁ Registrere en behandlingsaktivitet

Referanser:
Scenario: Registrere en behandlingsaktivitet
Gitt at hovedsiden for Behandlingsaktiviteter vises
Når bruker klikker på knappen "Legg til ny behandlingsaktivitet"
Og registerer verdien "Attestløsning" i feltet "Tittel Behandlingsaktivitet"
Og avslutter siden
Så skal behandlingsaktiviteten "Attestløsning" vises i lista

**Comment by RogerSOlsen** [comment]
Resultater fra test i demomiljø 07.10.2020:
Per behandlingsaktivitet skal følgende valgfrie felt støttes (iht datatilsynets mal er disse merket som "hensiktsmessige" å ta med):
1.	**Daglig behandlingsansvar**
Resultat Utført! Tema «Daglig behandlingsansvar» ligger i bolk «Behandlingsansvar og databehandler»

2.	**Funksjonsområde**
Resultat Utført! Det fantes registreringsfelt for «Funksjonsområde behandlingen faller inn under». Dette er endret til «Funksjons- eller virksomhetsområde» og ligger i bolk «Behandlingsaktiviteter»

3.	**Hvor kommer opplysningene fra (kilde)**
Resultat Utført! Det finnes registreringsfelt for «Kilder til personopplysningene» i bolk «Personopplysninger

4.	**Behandlingsgrunnlag artikkel 6**
Resultat Utført. Det finnes felt «Behandlingsgrunnlag artikkel 6» i bolk «Behandlingsaktiviteter». 

5.	**Rettslig forpliktelse, berettighet interesse mv.**
Resultat Utført! Det finnes valg for artikkel 6.1 c, e og f i drop-down-liste i felt «Behandlingens lovlighet» i under «Behandlingsgrunnlag artikkel 6» i bolk «Behandlingsaktiviteter».

6.	**Behandlingsgrunnlag artikkel 9 eller 10**
Resultat Utført! Det finnes tema «Behandlingsgrunnlag artikkel 9 og 10» i bolk «Behandlingsaktiviteter».

7.	**I hvilke av våre systemer behandles opplysningene**
Resultat Utført! Det finnes registreringsfelt for «System i virksomheten som behandler personopplysningene» i bolk «Personopplysninger».

8.	**Kan behandlingen innebære høy personvernrisiko**
Resultat Utført og fjernet! Det fantes felt for «Kan behandlingen innebære høy personvernrisiko?». Dette er fjernet, ref https://github.com/Informasjonsforvaltning/fdk/issues/3169


9.	**Navn på databehandlere**
Resultat Utført! Finnes registreringsfelt «Navn på databehandler» under tema «Databehandlere og databehandleravtaler» i bolk Behandlingsansvar og databehandler». 


**Akseptansekriterier:**
,# language: no:: 
Resultat Utført. Ved registrering av ordene «meg», «eg» og «me» kommer det rød strek under «eg» og «me».

Egenskap:
Kriterier:
⦁ Registrere en behandlingsaktivitet:
Resultat Utført. Det er mulig å registrere behandlingsaktivitet med obligatoriske felter. Behandlingsaktiviteten vises i listen over behandlingsaktiviteter og kan åpnes etter at den er lukket.
