### ISSUE TITLE
[BRUKERHISTORIE] Kontekst for registreringsløsningen

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#382]
Som: tilbyder som ønsker å registrere i registreringsløsningen for en spesifikk portal, f.eks. transportportal.no
Ønsker jeg å: få spesifikk veiledning/tilpasning og forhåndsutfylte felt
Slik at: det blir lettere å registrere riktig

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Åpner denne igjen dersom behovet blir meldt inn på nytt.
