### ISSUE TITLE
[BRUKERHISTORIE] Migrering av kataloger ved kommunesammenslåing

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#383]
Som: dataeier for en kommune som blir slått sammen 
Ønsker jeg at:   min katalog og de andre kommune som jeg blir slått sammen med automatisk blir migrert fra 1.1.2020 
Slik at:  jeg har de rettighetene som trengs for å se en samlet katalog 1.1.2020.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Dei fleste kommunar ser ut til å komme frå data.norge.no-importen, så her kan det være nyttig å samtidig tenke migrering til ny FDK-registreringsløysing jf #186

**Comment by KjerstiSteien** [comment]
@KurtStian @oystein-asnes  vet dere om vi har noen restanser her?

**Comment by KurtStian** [comment]
I data.norge i dag er det kun aktive kommuner (som finnes i ER) som har data. Ser at mange har ikke oppdatert beskrivelsene sine siden de ble importert inn ved sammenslåingen av FDK og data.norge i mai 2020.

Tror saken kan lukkes.
