### ISSUE TITLE
[EPOS] Virksomhet skal kunne registrere begreper på vegne av andre virksomheter 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#385]
Som: ansvarlig for registrering av begrep for en større aktørgruppe
Ønsker jeg å: kunne registrere begreper på vegne av andre virksomheter
Slik at: begrepet blir publisert på vegne av de andre virksomhetene

Tilknyttede brukerhistorier: kommer

Dette er et område som må balansere faren for misbruk og administrative prosedyrer. Pr idag har noen virksomheter allerede rett til å publisere datasettbeskrivelser på vegne av andre der hvor de forvalter kataloger, som Data.norge.no og GeoNorge. Dette er en kvalifisert vurdering gjort av forvalter av Felles datakatalog. For "begrep" er det ikke en utbredt praksis, selv om vi ser tilfeller av at en virksomhet publiserer sine fortolkninger av begreper andre eier - dette er i imidlertid en annen problemstilling, som bør løses gjennom sammenligning av begreper og videre arbeid med begrepskoordinering og -harmonisering.  Standard for begrepsbeskrivelser åpner for å ha forskjellige virksomheter i feltet "ansvarlig virksomhet". Standarden støtter også begrepssamlinger. 

Dette eposet dreier seg om å gjøre noe i registreringsløsningen for begrep. Se oså tilsvarende epos for datasettregistrering her: #341 

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
@Te-Bert kan du se på denne og vurdere prioritet?

**Comment by KjerstiSteien** [comment]
Dette er mulig i dag, så lenge vedkommende har fått tilgang fra den andre virksomheten i Altinn autorisasjon. Regnes som løst.
