### ISSUE TITLE
[BRUKERHISTORIE] Vise tjenestetype på et API

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#39]
Som: en bruker av et API 
Ønsker jeg å: se om et API er av en viss type eller realiserer en standard
Slik at: jeg enkelt kan forstår hva slags informasjon jeg får av apiet

Relatert til epos: #11 

Lenke til design: https://projects.invisionapp.com/share/FWBFRNSAM#/screens/308321878
Lenke til løsningsarkitektur:

**Akseptansekriterier:** 
# language: no
Egenskap: 

Kriterier:
⦁	Leser av en publisert API-beskrivelse skal kunne finne informasjon om API-ets type og om den realiserer en standard.  
⦁	Dersom tjenestetypen/standarden er dokumentert et annet sted på internett, skal det lenkes dit.  Dersom slik referanse ikke finnes, skal Tjenestetype være ren tekst.

Dekkes ikke:
⦁	Filtersetting av tjenestetype

Referanser:

  
Scenario: Vise tjenestetype for en API-beskrivelse
Gitt at API-beskrivelse med tjenestetype lik "Kundeforhold" er registrert
Og bruker søker gitt API-beskrivelse 
Når bruker åpner detaljsiden for gitt API-beskrivelse
Så skal bruker finne Tjestetype på venstremenyen
Og bruker skal finne seksjonen tjenestetype på detaljsiden
Og verdien tjenestetype skal være  lik "Kundeforhold" 

Scenario: Åpne lenke til dokumentasjon
Gitt at API-beskrivelse med tjenestetype lik "Kundeforhold" er registrert
Og tjenestetypen er dokumentert andre steder på internett
Når bruker åpner detaljsiden for gitt API-beskrivelse
Så skal bruker kunne klikke på lenken til dokumentasjonen
Og dokumentasjonsiden skal åpnes

**Comment by sindresandvik2** [comment]
_Fra Lars, Joachim og Sindre:_ 
Hvilket term skal vi bruke?  Er Tjenestetype riktig eller?  I flg David N kan Tjenestetype være reservert for Tjenestekatalog.  Kan også bli misvisende da Altinn også benytter tjenestetype for noe annet

Det må spesifiseres hvilke typer som skal tilgjengeliggjøres nå i først omgang.   (Antar det er Kundeforhold og Kontoopplysninger)

**Comment by sindresandvik2** [comment]
Startar med å jobbe ut akseptansekriteriarø Men først bør heile saka flyttast tilbake til "Beskrive design og løsningsarkitektur" inntil den er heilt klar for konstruksjon.  Og så må eg få meir rettigheter slik at eg kan  sjå all info i brukerhistorien.

**Comment by stigbd** [comment]
Til spørsmåla over @sindresandvik2:
* Termene er gitt av trådskissene. Vi kan endre seinare dersom disse viser seg å vere problematiske.
* Det er korrekt at det dreier seg om Kundeforhold og Kontoopplysninger, slik designet viser.
* Nei. Det er ikkje identifsert brukerhistorie på at brukar av skal sette filter på dette i FDK.
* Ingenting. Det er ikkje identifsert brukerhistorie på at brukar av skal søke på type.

**Comment by sindresandvik2** [comment]
Utgangspunkt akseptansekriterier:  (To be apporved) 
# language: no
Egenskap: 
Brukerhistorie:  
Som en bruker av et API ønsker jeg å se om et API er av en viss type eller realiserer en standard slik at jeg enkelt kan forstår hva slags informasjon jeg får av apiet

Akseptansekriterier:
⦁	Som tilbyder av API-beskrivelsen må en kunne velge tjenestetype og om den realiserer en standard når API-beskrivelsen registreres.
⦁	Leser av en importert API-beskrivelse skal kunne finne informasjon om API-ets type og om den realiserer en standard.  
Dekkes ikke:
⦁	Filtersetting av tjenestetype
⦁	Søking spesifikt mot tjenestetype

Referanser:

  
Scenario: Registrere tjenestetype for en API-beskrivelse
Når bruker henter inn en ny API-beskrivelse 
Så skal bruker legge til informasjon om tjenestetype lik Kundeforhold

Scenario: Vise tjenestetype for en API-beskrivelse
Gitt at API-beskrivelse med tjenestetype lik Kundeforhold er registrert
Når bruker søker gitt API-beskrivelse 
Og åpner detaljsiden for gitt API-beskrivelse
Så skal verdien tjenestetype lik Kundeforhold vises på siden

**Comment by sindresandvik2** [comment]
Det må avklares ang ekstern lik.
I designet vises symbol for ekstern lenke på Tjestetypen.  Hva/hvor skal det linkes til?

**Comment by lillelars** [comment]
@sindresandvik2 @stigbd akseptansekriterier bør legges inn i selve beskrivelsen og ikke som kommentarer.

**Comment by stigbd** [comment]
Ekstern link: Dersom tjenestetypen/standarden er dokumentert ein annan stad på internett, skal det lenkes dit. Eg skal finne ut det faktisk fins slike lenker og gi disse til utviklingsteamet. Om slik referanse ikkje fins, skal Tjenestetype vere rein tekst. 

Akseptansekriterier: Disse skal ligge i .feature-fil i løsning. Men sidan vi ikkje har gode nok rutiner/opplegg for å håndtere disse filene enno, er det greit at akseptansekriteria ligg i beskrivelselsen.

**Comment by sindresandvik2** [comment]
@stigbd   Klar for akseptansetest i UT1.  Planen vår er å prodsette alt omkring Tenestetype i morgon!
