### ISSUE TITLE
[BRUKERHISTORIE] Roller i registreringsløsningen

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/behov#390]
Som: begrepskoordinator i en virksomhet og bruker av registreringsløsningen
Ønsker jeg å: tilordne roller for godkjenning og publisering til utvalgte personer
Slik at: ansvarlige kan godkjenne eller publisere begrepsbeskrivelser. Dette, i tillegg til mulighet for å kommentere utkast, vil gjøre det mulig for vår virksomhet å utelukkende benytte registreringsløsningen som virksomhetsintern begrepsbeskrivelsesprosess.

Relatert til epos: Begrepets livssyklus

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Med mulighet for å skille mellom lesebruker, skrivebruker og virksomhetsadministrator, mulighet for å melde inn forslag til nye begrep og endringer på eksisterende begrep, og mulighet for å kommentere på begrep, anser vi dette behovet som løst. 

@hanber hvis du fortsatt er aktiv her, så si fra om det er noe funksjonalitet dere fortsatt savner.
