### ISSUE TITLE
[EPOS] Utvidet funksjonalitet Protokoll over behandlingsaktiviteter

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#391]
Som: virksomhet
Ønsker jeg: utvidet funksjonalitet ... 
Slik at: jeg kan ta i bruk en mer fullverdig løsning utover det grunnleggende

Tilknyttede brukerhistorier:
#169 
#380 
#381 
#475

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by RogerSOlsen** [comment]
Eposet lukkes. Arbeid med brukerhistorie #396 , #397 , #458 og #366  fortsetter
