### ISSUE TITLE
[BRUKERHISTORIE] Feilmeldinger

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/behov#392]
Som: bruker av FDK
Ønsker jeg å: melde om feil og tvilsom funksjonalitet, som ikke er funksjonelle behov, og som dermed ikke egentlig hører hjemme i brukerhistoriene som beskriver behov
Slik at: Disse meldingene skilles fra behovene. Kan vi f.eks. lage en ny kategori [FEILMELDING] i tillegg til [BRUKERHISTORIE] og [EPOS]?
Eller skal jeg omformulere en feilmelding som et behov for å få rettet feilen?

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kjekt å ha

**Comment by chajoh** [comment]
Jeg beklager, så vidt jeg forstår skal slike ting meldes i Informasjonsforvaltning/fdk.
