### ISSUE TITLE
[BRUKERHISTORIE] Retting av skrivefeil i publiserte begrepsbeskrivelser

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/behov#393]
Som: bruker av registreringsløsningen for begrep
Ønsker jeg å: kunne gjøre endringer i publiserte begrepsbeskrivelser som ikke endrer meningsinnholdet (skrivefeil) uten at det blir til en ny versjon som genererer varsler til brukere/interesserte. Dette gjelder også anbefalt term og definisjon
Slik at: begrepsbeskrivelsen blir så korrekt som mulig

Relatert til epos: #153 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Brukere har nå mulighet for å påvirke versjonsnummeret selv. Vi vil anbefale at man minorversjon (Eks fra 1.0.0 til 1.0.1) ved mindre endringer, som retting av skrivefeil. Det kan være relevant for andre. Saken regnes som løst.
