### ISSUE TITLE
[BRUKERHISTORIE] Komplettere/supplere innhold i publiserte begrepsbeskrivelser

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/behov#394]
Som: bruker av registreringsløsningen
Ønsker jeg å: Endre deltaljer i publiserte begrepsbeskrivelser, f.eks. å legge til nye tillatte termer, endre fra tillatt til frarådet term, samt å legge til nye detaljer.
Slik at: Begrepsbeskrivelsene blir vedlikeholdt med økende kunnskap og bevissthet.

Relatert til epos: #153 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by marittor** [comment]
Er ikke dette en bug som burde vært meldt til fdk-issues?
