### ISSUE TITLE
[BRUKERHISTORIE] Kontroll med endringer i publiserte begrepsbeskrivelser

### ISSUE THREAD

**Issue by hanber** [Informasjonsforvaltning/behov#395]
Som: bruker av registreringsløsningen for begrep
Ønsker jeg å: ha bedre kontroll med publisering av endringer gjort i registreringsløsningen
Slik at: jeg ikke ved en feiltakelse publiserer en endring jeg ikke hadde tenkt.
Nå er det slik at når jeg gjør en endring i registreringsløsningen blir endringen umiddelbart gjenspeilet i portalen. Det er ønskelig å kunne kontrollere dette ved en aktiv handling (republisering) når jeg er ferdig med endringene. Det er ikke mulig å legge inn nye egenskaper som tillatt term o.l. dersom de ikke var registrert ved første gangs publisering.

Relatert til epos: #153 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Løst ved manuell lagring og republisering
