### ISSUE TITLE
Tittel på Distribusjoner

### ISSUE THREAD

**Issue by BredeD** [Informasjonsforvaltning/behov#398]
Som: bruker av transportportal
Ønsker jeg å: raskt se hvilke Distribusjon som jeg er ute etter
Slik at: jeg slipper å bruke unødig tid for å finne riktig distribusjon

En Tittel på hver distribusjon vil kunne være en grei løsning. Se på datasettet for Nasjonalt rutedatasett for kollektivtrafikk i Norge
https://nap.fellesdatakatalog.brreg.no/datasets/f8327e57-60fa-440f-9ecd-a8765ca13ae6

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by stigbd** [comment]
Her kan vi bruke distribution-title (dct:title) på dcat:Distribution.

**Comment by oystein-asnes** [comment]
[dct:title ](https://doc.difi.no/dcat-ap-no/#distribusjon-tittel) er valgfri, så det vil gi oss lite basert på dagens innhold.  Ein mulig fix kan være å bruke `dct:format` (som er obligatorisk) som fallback for dct:title dersom tittel er tom . Då kan ein designe GUI ut  frå at tittel alltid har ein verdi (sjølv om vi vil få titlar som "JSON" og "XML"). På data.norge.no har vi droppa `dct:title` og valgt å løfte `dct:format `og `dct:description` i GUIet (`dct:description` er anbefalt btw).  Dette valet var ma basert på ei erfaring om at tittel og beskrivelse ofte var redundant informasjon.
