### ISSUE TITLE
[BRUKERHISTORIE] Filtrere API på tjenestestype

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#40]
Som: en maskin-til-maskin konsument
Ønsker jeg å: få en liste over API som er av en viss type (standard)
Slik at: jeg kan gjøre forespørsler til disse apiene

Relatert til epos: #11 

Lenke til design: n/a
Lenke til løsningsarkitektur: sjå epos

**Comment by sindresandvik2** [comment]
Fra Lars, Joachim og Sindre:
Hvor er Løsningsarkitekturen?  

Bør akseptansekriteriene inneholde at API-spec'en vår oppdateres?

**Comment by stigbd** [comment]
Følgande feature dekker denne brukerhistorien. Skal inn i en fil med navn oppslag_paa_standardiserte_API.feature
# language: no
Egenskap: Oppslag på standardiserte API
  Som en maskin-til-maskin konsument
  Ønsker jeg å få en liste over API som er av en viss type (standard)
  Og eventuelt som tilhører en gitt virksomhet
  Slik at jeg kan gjøre forespørsler til disse apiene

  Ref:
  https://github.com/Informasjonsforvaltning/behov/issues/40
  https://github.com/Informasjonsforvaltning/behov/issues/70

  Scenario: Liste standardiserte API med gitt tjenestetype
  Når konsumenten gjør en GET mot /apis
  Og setter et filter på tjenestetype lik "Kontoopplysning"
  Så skal kun API som implementerer denne tjenestetypen returneres som en liste
  Og endepunktet til APIet skal være en av opplysningene i listen

  Scenario: Liste standardiserte API med gitt tjenestetype og gitt virksomhet
  Når konsumenten gjør en GET mot /apis
  Og setter et filter på tjenestetype lik "Kontoopplysning"
  Og setter et filter på virksomhet lik "<orgnr>"
  Så skal kun API som implementerer denne tjenestetypen returneres som en liste
  Og listen skal kunne inneholde virksomhetens API
  Og endepunktet til APIet skal være en av opplysningene i listen

**Comment by stigbd** [comment]
API-spec må oppdateres med dei nye filtera. (Samtidig kan vi vurdere om ikkje spec-fil skal flyttast inn i fdk-repoet. Den burde versjonerast i lag med koden.)

**Comment by stigbd** [comment]
Løst, ref https://informasjonsforvaltning.github.io/felles-datakatalog/api-katalog/api/
