### ISSUE TITLE
[EPOS] Visning av modeller

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#406]
Relatert til epos #310.
Som: modellkonsument

Ønsker jeg at: en modellbeskrivelse med tilhørende modell presenteres i henhold til spesifikasjonen for informasjonsmodeller, samt knytninger til andre kataloger og at de vises i formater som jeg kan laste opp i eget modelleringsverktøy eller bruke i implementering av egne løsninger

Slik at: jeg lettere kan få en oversikt over hva modellene beskriver og bruke dem til egne formål.

Tilknyttede brukerhistorier:

#282 
#284 
#281 
#267 
#407 
Lenke til trådskisser: https://www.figma.com/proto/nrqaa1JB8pY6pBvUBxp1EV/Infomodels-structure?node-id=547%3A273726&viewport=596%2C408%2C0.09372920542955399&scaling=min-zoom

Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by ToHelland** [comment]
Fjernet brukerhistorie 266 og flyttet disse til epos #500.

**Comment by RogerSOlsen** [comment]
Lukket i møte Rydding av behovsboard 02.03.2022
