### ISSUE TITLE
[BRUKERHISTORIE] Portal - ny design på filter

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#41]
Som: tjensteutvikler som bruker FDK
Ønsker jeg å: se hvilke filter jeg har aktivert
Slik at: det er forståelig hvorfor resultatsettet er begrenset

Relatert til epos: #36 

Lenke til design: https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/334290117
Lenke til løsningsarkitektur:

Vi skal nå vise aktive filter:
- merk også at pilen er flyttet og fått ny farge
- det er også ønskelig at filterne skal være SPESIFIKT for den fanen man velger de i (altså skal f.eks filter for virksomhet bare gjelde for fanen du står i - husk at tall i parantes i faneheading skal dermed ikke oppdateres for de andre fanen)
- dersom man kommer tilbake til samme fane bør det huskes hvilke filtre som var valgt.

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Bruker skal kunne se alle filtrene som er satt samlet i toppen av siden
⦁	Bruker skal lett kunne nullstille filtersettingen, fjerne filtrene
⦁	Bruker skal kunne sette filter på en fane uten at det påvikrer datautvalget på andre faner
⦁	Dersom en bruker har satt filter for en fane skal disse bevares selv om en navigerer til andre faner.

Dekkes ikke:

Referanser:
OBS: Denne brukerhistorien dekkes kun delvis med Gherkin-tester.  Manuell test må hovedsaklig benyttes for å oppnå tilstrekkelig testdekning

Scenario: Sette filter 
Gitt at bruker viser fanen "Datasett"
Og setter et filter = "Offentlig"
Så skal filteret "Offentlig" vises tydleig i toppen av siden
Og det skal kun vises Datasett som er "Offentlig"

**Comment by lillelars** [comment]
@sindresandvik2  trenger vi akseptansekriterier her?
@stigbd løsningsarkitektur bør være "N/A"

**Comment by sindresandvik2** [comment]
Akseptansekriteriet "Dersom en bruker har satt filter for en fane skal disse bevares selv om en navigerer til andre faner."   vil ikke bli implementert i første omgang pga forholdsvis stor arbeidsmengde.
