### ISSUE TITLE
[BRUKERHISTORIE] Behov for å gjøre oppslag i IANA-typer direkte i reg.løsing

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#411]
Som: registrator av et datasett
Ønsker jeg å: gjøre oppslag i IANA-formater i registreringsløsningen
Slik at: jeg slipper å klippe og lime URIer fra en egen nettside

Relatert til epos: #91 
Relatert til brukerhistorie #145 , #422 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
 
[Liste over filtyper som er i bruk på data.norge.no (uten IANA urier)](https://github.com/Informasjonsforvaltning/behov/files/4154042/filtyper-data-norge.txt)

Akseptansekriterier:
De 12-15 mest kjente formater er lett tilgjengelige å velge. Det er mulig å skrive inn egendefinerte formater.

- kan ta utgangspunkt i eksisterande oversikt: 
https://livarbergheim.no/api/datanorge_codes.php

UTKAST til kort-liste over format:

Format:
<kortnamn> - <liste over ein eller fleire mime-types som fører til bruk av kortnamnet> - <tal på data-oppføringar i data.norge.no> - <tal på distribusjonar med denne mime-type i data.norge.no>

Første mime-type er primær-mime-type. Dvs. at dersom ein vel det kortnamnet i registreringsløysinga, så vert den mime-type'n brukt.

CSV — text/csv — 389 — 472
JSON — application/json, application/javascript — (268 — 343) + (164 — 227)
XML — application/xml, text/xml - (232 — 312) + (3 — 3)
GeoJSON — application/vnd.geo+json — 81 — 81
HTML — text/html — 35 — 38
SOSI — application/x-­ogc-sosi — 19 — 20
XLSX — application/vnd.openxmlformats-officedocument.spreadsheetml.sheet — 51 — 54
XLS — application/vnd.sealed-xls — 19 — 22

Kommentarar:
F1. YAML er stort sett kun datahotell-distribusjonar, og formatet er lite/ingenting brukt av andre distribusjonar. Veldig lav trafikk på YAML på datahotellet.
F2. application/javascript = JSONP. Foreslår å kun vise "JSON".

Format som er i data.norge.no pr. 11.03.2020, og som foreslås å ikkje takast med:
YAML — application/x.yaml — 151 — 213
RSS — text/xml
GPX — application/gpx+xml — 52 — 52
ESRI FGDB — application/zip — 23 — 23
PDF — application/pdf — 14 — 14
WMS — application/x.wms — 13 — 13
GML — application/gml+xml — 6 — 7
WFS — application/x.wfs — 5 — 5
RDF/XML — application/rdf+xml — 4 — 4
Turtle — text/turtle — 4 — 4
JSON-LD — application/ld+json — 3 — 3
TXT — text/plain — 3 — 3
TIFF — image/tiff — 3 — 3
KML — application/vnd.google-earth.kml+xml — 2 — 2
ODS — application/vnd.oasis.opendocument.spreadsheet — 2 — 2
N-Triples — application/n-triples — 2 — 2
GTFS — application/x.gtfs — 2 — 2
NeTEx — application/x.netex — 2 — 2
SIRI — application/x.siri — 1 — 1
UALF — application/x.ualf — 1 — 1
SQL — application/sql — 1 — 1
SHAPE — application/octet-stream — 0 — 0
GTFSRT — application/x.gtfsrt — 0 — 0
TSV — text/tab-separated-values — 0 — 0
GPKG — application/geopackage+sqlite3 — 0 — 0
SQLite — application/vnd.sqlite3 — 0 — 0

**Comment by lillelars** [comment]
@oystein-asnes @livarb  Kan vi liste opp de 12-15 mest kjente formatene vi/design kan starte med?

**Comment by livarb** [comment]
@lillelars : Vi skal få ut kodelista som er i data.norge.no i dag.
Det er lagra som innhaldstype. Eksempel:
![image](https://user-images.githubusercontent.com/3617256/75040398-df95ad00-54ba-11ea-96f9-8ee4eb6a5706.png)

**Comment by livarb** [comment]
Fordeling på mime-typar i data.norge.no og kor mange distribusjonar som har kvar mime-type. Ein distribusjon kan ha fleire mime-typar/format:
![image](https://user-images.githubusercontent.com/3617256/76414204-2890a100-6397-11ea-9411-af9f08162cbe.png)

Fordeling på distribusjonar:
    [text/csv] => 390
    [application/json] => 270
    [application/xml] => 234
    [application/javascript] => 167
    [application/x.yaml] => 166
    [application/vnd.geo+json] => 81
    [application/gpx+xml] => 52
    [application/vnd.openxmlformats-officedocument.spreadsheetml.sheet] => 51
    [text/html] => 35
    [application/zip] => 23
    [application/x-­ogc-sosi] => 19
    [application/vnd.sealed-xls] => 19
    [application/pdf] => 14
    [application/x.wms] => 13
    [application/gml+xml] => 6
    [application/x.wfs] => 5
    [application/rdf+xml] => 4
    [text/turtle] => 4
    [application/ld+json] => 3
    [text/xml] => 3
    [image/tiff] => 3
    [text/plain] => 3
    [application/x.netex] => 2
    [application/n-triples] => 2
    [application/vnd.google-earth.kml+xml] => 2
    [application/vnd.oasis.opendocument.spreadsheet] => 2
    [application/x.gtfs] => 2
    [application/sql] => 1
    [application/x.ualf] => 1
    [application/x.siri] => 1

**Comment by livarb** [comment]
Innspel frå Lars om å også ta med Turtle, RDF/XML, JSON-LD og YAML. Andre forslag? @stigbd @oystein-asnes

**Comment by stigbd** [comment]
> Akseptansekriterier:
> Bruk de 12-15 mest kjente formater, resten kan gå under "annet"/"Ukjent"
Eg tenker at ein bør få lov til å taste inn dei som ikkje dukkar opp i søk på kjente formater.

**Comment by livarb** [comment]
> > Akseptansekriterier:
> > Bruk de 12-15 mest kjente formater, resten kan gå under "annet"/"Ukjent"
> 
> Eg tenker at ein bør få lov til å taste inn dei som ikkje dukkar opp i søk på kjente formater.

Einig. Tanken her er vel at dersom ein fører opp eit format (gitt ved mime-type) som ikkje har ein kortform (e.g. CSV), så dukkar det opp som "Annet" i visning.

**Kort eller lang liste?**

I visning av format, er det lagt opp til at ein berre har ei kort liste (sjå relaterte brukarhistoriar). Alt som ikkje er på den korte lista visast som f.eks. "Annet".

Spørsmålet er om ein skal ha kun denne korte lista for registreringsløysinga?
Eller om ein skal ha ei lengre liste?

Dersom ein har ei lengre liste, er det eit stort pluss at dei mest brukte formata lettare tilgjengeleg for brukaren av registreringsløysinga.

**Comment by livarb** [comment]
Akseptansekriteriet foreslår eg endrast. Det passar betre på dei frontend-relaterte brukarhistoriane. Grunnen er at det alltid må vere mogeleg å skrive inn eigendefinerte mime-typar, sidan det må vere mogleg å definere eigne format, f.eks. subset av xml eller json, og fordi det alltids er nokre obskure format som ein ikkje har i lista frå før.

Endra frå:
> Akseptansekriterier:
> Bruk de 12-15 mest kjente formater,
> resten kan gå under "annet"/"Ukjent"

Til:
> Akseptansekriterier:
> De 12-15 mest kjente formater er lett tilgjengelige å velge. Det er mulig å skrive inn egendefinerte formater.

Sei gjerne ifrå om du har forslag til endring.

**Comment by stigbd** [comment]
Presisering: Det hadde vore kjekt om valg blir gjort ved eit søk mot lista over kjente formater. (Dette har implementert støtte for andre stader.) Lista over kjente formater er då lagra (cache) i referanse-data tjenesten vår. 
Spørsmål: Kvar kan vi hente _master_ for mediaTypes?

**Comment by livarb** [comment]
@stigbd : Det er vel dette som er fasiten: https://www.iana.org/assignments/media-types/media-types.xhtml
Spørs om det finst eit API ein stad? Eg veit ikkje om noko. Dersom vi ikkje har noko tilgjengeleg, tenker eg vi nyttar eit eige kontrollert vokabular i denne omgang.

**Comment by oystein-asnes** [comment]
IANA har desverre ikkje API.

**Comment by eggedosis** [comment]
Kan noen tagge meg her når lista er klar? :)

**Comment by stigbd** [comment]
Då kan vi _lage_ eit api , eller eigentleg gjenbruke vårt referanse-data api på bakgrunn av https://www.iana.org/assignments/media-types/media-types.xml
Dette er grei skuring å hente ned og redistribuere via https://github.com/Informasjonsforvaltning/fdk-reference-data

Som minner meg på at vi burde gjere fdk-reference-data apiet tilgjengeleg som eit datasett og dataService på internett. Dermed kan andre aktørar bruke dette i staden for å implementere sine eigne.

**Comment by lillelars** [comment]
@livarb Skal vi lande på noe her? Skal vi vise alle og gjøre det til en søkbar liste likevel?
Ønsker uansett fullstendig oversikt over listen :)

**Comment by livarb** [comment]
@lillelars : Utover det som står i akseptansekriteria, så har eg ikkje nokon sterke meiningar om å gjere det på den eine eller andre måten. Eg kan alltids kome med tankar, men det kan vere dei ikkje gir meining ut frå arkitektur, tid som krevst å implementere osv. :) Kva foreslår de?

**Comment by livarb** [comment]
@lillelars : Er denne også klar til akseptansetest, sidan #422 og #145 er flytta dit?

**Comment by lillelars** [comment]
@livarb stemmer :)
