### ISSUE TITLE
[BRUKERHISTORIE] Vise status for fremdrift for datasett som etterspørres

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#415]
Som: konsument som bruker datakatalogen til å etterpørre data som ikke er tilgjengeliggjort
Ønsker jeg å: få vite /se status for fremdrift med behandlingen
Slik at: både jeg og andre konsumenter kan se hvor i prosessen tilbyder er.

Relatert til epos: #188 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by lillelars** [comment]
Løses i https://github.com/Informasjonsforvaltning/behov/issues/551
