### ISSUE TITLE
[BRUKERHISTORIE] Tredjeparts kommentarer på datasettbeskrivelser

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#416]
Som: bruker av felles datakatalog 
Ønsker jeg å: å kommentere på datasettbeskrivelser
Slik at: min kommentar , tilbyders eventuelle tilsvar og andre parters kommentarer er synlige for alle  

Relatert til epos: #213 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Anser denne som oppfylt no som vi har fått kommentarfelt i data.norge.
https://github.com/datadeling/behov-issue-tracker/issues/112
