### ISSUE TITLE
[BRUKERHISTORIE] Behov for å synliggjøre åpne data i listevisning (sammendragsbokser)

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#418]
Som: tilbyder av en portal for åpne data på oppdrag fra KMD
Ønsker jeg å: synliggjøre åpne data i en sammenslått løsning
Slik at: det er tydelig for alle hvor på portalen en finner åpne data

Relatert til epos: #91 

Lenke til trådskisser:
https://www.figma.com/proto/YR7KkVmJ6vzCAUOqxgyrKD/Dataset?node-id=172%3A50096&viewport=208%2C-806%2C1.075514316558838&scaling=min-zoom

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/search-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
Kritisk

**Akseptansekriterie:**
* Bruker skal kunne se "Åpne data" tag på de datasettbeskrivelsene der kriteriene for dette er fylt
* Bruker skal ha mulighet til å filtrere på åpne data fra filtermenyen

Dekkes bare ved tid:
* Bruker skal kunne få informasjon om hva Åpne data betyr når hen holder musepeker over "åpne data"

Scenario: Bruker skal ha mulighet til å filtrere på åpne data fra filtermenyen
Gitt at det finnes datasett markert som "åpne data"
og bruker står i fanen "alle" eller står i fanen"Datasett"
når bruker huker av filter for "åpne data"
Så skal bare datasett markert med "åpne data" vises i resultatlisten

Scenario: Bruker skal kunne se "Åpne data" tag på de datasettbeskrivelsene der kriteriene for dette er fylt
Gitt at det finnes datasett som har kriteriene tilgangsnivå = "offentlig
og at datasettet har en distribusjon
og at distribusjonen har åpen lisens
så skal datasettbeskrivelsen markeres med "åpne data" i sammendragsboksen

Innspill til løsning:
- Legg inn hjelpetekst som forklarer hva de ulike avkrysningsalternativene innebærer. F.eks. tilgjengelig ved et spørsmålstegn-ikon ved siden av filter-overskriften (e.g. "Tilgang"). I hjelpeteksten er det forklart f.eks. at "Åpne data" betyr at et datasett har minst en distribusjon med åpen lisens.

Forslag til hjelpetekst for de ulike kategoriene:

**Åpne data:**
Datasett som er publisert under en åpen lisens slik at alle kan få tilgang, bruke og dele. Dette omfatter også løsninger som krever brukeregistrering/API-nøkler, så lenge alle kan få tilgang.

**Kan deles offentlig:**
 Datasett som kan gjøres tilgjengelig for alle, men som ikke er publisert som åpne data.

**Begrenset offentlighet:**
Datasett som ikke kan gjøres åpent tilgjengelig for alle. Årsaker til skjerming kan for eksempel være at datasettet inneholder personopplysninger eller er omfattet av tredjeparts rettigheter.

**Unntatt offentlighet:**
 Datasett som det kreves særskilt rettslig grunnlag for å få tilgang til. Typiske eksempler er gradert informasjon, sensitive personopplysninger eller forretningshemmeligheter. 

**Ukjendt:**
Datasett som mangler vurdering  av tilgangsnivå.

**Comment by livarb** [comment]
La inn forslag om hjelpetekst, sidan dei ulike alternativa i filter ikkje er intuitive for alle.

**Comment by oystein-asnes** [comment]
Opplysninger av tilgangsnivå er et obligatorisk felt i dcat-ap-no, så dette bør fanges opp av valideringen, @stigbd  og/eller flagges rødt i rapporten som tilbyderne får tilgang til i #179

**Comment by livarb** [comment]
Funksjonaliteten ser bra ut!
Utover scope for denne saka: det spørs på innhaldet. Trur at f.eks. denne oppføringa frå Entur skal klassifiserast som opne data, men den er ikkje det no: https://fellesdatakatalog.digdir.no/datasets/f8327e57-60fa-440f-9ecd-a8765ca13ae6
Dette gjeld kanskje anna innhald i katalogen og.

**Comment by oystein-asnes** [comment]
Ser bra ut, men forstår ikkje heilt kvifor Entur sitt datasett ikkje vert fanga opp. Det oppfyller alle kriterer etter det eg kan sjå. Har ikkje funne andre eksempel. Bortsett frå det er denne klar :-)
