### ISSUE TITLE
[EPOS] Ny frontside for sammenslått løsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#420]
Som: bruker av datakatalogen   
Ønsker jeg å: komme til en frontside
Slik at: jeg raskt kan ta stilling til om portalen er relevant for mitt behov

Relatert til epos: #91 
Tilknyttede brukerhistorier: 
#140 - Twitter-embed
#139 - Redaksjonelt innhold (EPOS) - aktuelt/nyheter, statiske sider tilgjengeleg via meny (veiledere, NLOD o.l.)
#463 - Søk (søkefelt og søkeresultat)
#464 - Sist publiserte/mest relevante

I dagens FDK-løsning er datasettkatalogen frontside. En ny frontside bør...
- reflektere at brukerne primært ønsker å oppdage, vurdere og ta i bruk data
- gi et umiddelbart inntrykk av aktualitet (sist oppdatert osb..)
- fungere som kontekst for alle katalogene (datasett, api, begrep, modeller osb)
- understøtte pådriverrollen (inkludert å gjøre det lett å finne veiledere, registrering, øvrig informasjon) 

Lenke til trådskisser: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Vi ser for oss dette på forsiden/startsiden:
- beholde søkeboksen 
- eksempelvis gjør et søk over alle katalogene og resultatlisten viser også dette
- Videre kan bruker gå ned i de ulike katalogene og gjøre søk bare her
- ønsker å ha tydelig informasjon om registreringsløsning (evnt lenke til informasjon)
- ønsker å ha tydelig informasjon om veiledere (evnt lenke til informasjon)
- Ønsker tydelig informasjon om "norsk lisens for offentlige data" NLOD (evnt lenke til informasjon)
- ønsker å ha type nyheter fra en redaktør (behovseiere om de ulike katalogene)
- ønsker å synliggjøre hva vi har av innhold (f.eks antall datasett og antall ulike virksomheter) se f.eks data.gov.ie

Tenke på:
- begrense mengde informasjon
- twitter-feed vises? sjå #140 
- skal vi tematisere dette? f.eks LOS? Se data.gov.ie her og
- Mulighet for å se organisasjoner som deler datasettbeskrivelser (og organisasjoner som ikke deler)
-

**Comment by livarb** [comment]
La inn info om Twitter-filteret for Twitter-embed på data.norge.no i dag.
Denne oppskrifta bør kanskje endrast. F.eks. til å både ta inn tweets frå FDK-kontoen og @opnedata-kontoen?

**Comment by livarb** [comment]
I trådskissa er det tre blokker nederst med NLOD, Registrere ... (vegleding), og Veiledere ...
Foreslår å droppe alle desse tre til fordel for å kunne finne dei i menyen på toppen.
Dette var også nemt på eit tidlegare møte. Legg det inn som ein kommentar her for å vere sikker.

**Comment by lillelars** [comment]
@livarb Nytt designforslag ute nå - disse blokkene er trappet ned til bare tekst. Synes selv det ser mye bedre ut :) Du vil også finne igjen disse i menyen øverst under "verktøy"

@oystein-asnes Har du kommet med et forslag til Tittel på hele startsiden?
F.eks data.gov har "The home of the U.S. Government’s open data". Mener å huske du skulle komme med forslag her :)

**Comment by livarb** [comment]
@lillelars : Ser veldig bra ut med nye blokker og meny :)

**Comment by oystein-asnes** [comment]
Ser veldig bra ut, men ser to problemer:
1. Sammenslåingen er en "statoil-hydro"-løsning i den forstand at begge brukergruppene skal skjønne at de er kommet til rett side. "data.norge.no" bør inn i designet på lik linje med felles datakatalog. Det er ikke nok at det kun er i URLen.

2. Det er ikke så lett å skjønne forskjellen på et åpent datasett (`åpne data`) og  et åpent api (`åpent`). Jeg forstår det ikke selv. 

Problem nr 2 er ikke så lett å løse nå, men fint om vi kan synliggjøre data.norge.no i toppbanneret @eggedosis ?

Forslag til fantastisk tittel: 

> Oversikt over data fra offentlig sektor i Norge

eller:

> Alt du trenger for å oppdage, vurdere og ta i bruk offentlige data

**Comment by eggedosis** [comment]
@oystein-asnes 
1. Er dette en midlertidig løsning til brukerne blir vant til å bruke Felles datakatalog, eller tenker vi en varig løsning der data Norge også på sikt skal være en tydelig del av profilen? Det første betyr at det er mulig å «kompromisse», mens en varig løsning bør være litt mer helstøpt synes jeg. Det kan uansett være en god idé å fremheve åpne data på forsiden fremfor andre beskrivelser.

Ny tittel er forøvrig tatt inn 👍🏻

**Comment by lillelars** [comment]
2. @oystein-asnes @eggedosis angående Åpent API så kan vi skrive en infotekst på hover for dette også (?). Altså på lik linje som en infotekst på hover over "Åpne data" forklarer hva dette er.

**Comment by eggedosis** [comment]
@lillelars Hover på _Åpent API_ er implementert i skissene.

**Comment by oystein-asnes** [comment]
> 1. Er dette en midlertidig løsning til brukerne blir vant til å bruke Felles datakatalog, eller tenker vi en varig løsning der data Norge også på sikt skal være en tydelig del av profilen? 

Dette er tenkt å være ei varig løysing der vi slår saman to produkt til eitt. Om det vert eitt eller begge navna/branda som overlever på sikt har et ikkje noko meining om.

Kontekst: Data.norge.no er ein portal som Digidir forvaltar på oppdrag frå KMD.  

Det første betyr at det er mulig å «kompromisse», mens en varig løsning bør være litt mer helstøpt synes jeg. Det kan uansett være en god idé å fremheve åpne data på forsiden fremfor andre beskrivelser.
> 
> Ny tittel er forøvrig tatt inn 👍🏻

**Comment by oystein-asnes** [comment]
@eggedosis Legg meg flat! Mitt eige forslag "Alt du trenger for å oppdage, vurdere og ta i bruk offentlige data" er ikkje god fisk ettersom offentlige data kan forståast som data som alle kan ha tilgang til . Dermed må vi endre til nok slikt som dette:

"Alt du trenger for å oppdage, vurdere og ta i bruk data fra offentlig sektor" 

No inneheld katalogen også data frå private aktørar, men forelår å la den ballen ligge.

**Comment by eggedosis** [comment]
@oystein-asnes Den er god, tittel er oppdartert =)

Har også oppdatert logoen slik at data.norge er inkludert, samt fokusert på åpne data og api-er på forsiden. Det var den løsningen vi kom fram til på statusmøtet i dag, så jeg håper det fungerer for morgendagens visning. Og kanskje til og med litt lenger.

Om løsningen – mot all formodning – skulle være nede i morgen finner du pdf av skissene her:
https://www.dropbox.com/s/cp06mr4grnbbrnt/FDK%20portal.pdf?dl=0

**Comment by shenluna** [comment]
Sammenslåing fullført 2020, lukker saken.
