### ISSUE TITLE
[BRUKERHISTORIE] Visning av format på distribusjoner

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#422]
Som: bruker av datakatalogen
Ønsker jeg å: se  (på en enkel og intuitiv måte) hvilke formater som er tilgjengelig for en gitt distribusjon
Slik at: jeg slipper  lange tekststrenger av typen `application/vnd.oasis.opendocument.spreadsheet` i detalj-, og listevisninger

Listen over lovlige verdier i IANA mediatypes er lang som et vondt år, og det er mulig en bør lage en lokal liste over de mest sannsynlige verdiene (som en kan gjenbruke i reg.løsningen jf issue #411) og finne en generisk løsning på de som ikke treffer. Ev. bare bruke siste leddet i URIen i det grafiske elementet (`ODF` jf eksemplet over)

Relatert til epos: #91 
Relatert til brukerhistorie: #411, #418 

Lenke til design, søkeside: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/search-default.html
Lenke itl skisse, detaljside: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kjekt å ha?

**Comment by oystein-asnes** [comment]
Liste over filtyper som er i bruk på data.norge.no:
[filtyper-data-norge.txt](https://github.com/Informasjonsforvaltning/behov/files/4154042/filtyper-data-norge.txt)

**Comment by shenluna** [comment]
Navn på mediatyper fra IANA vises
![image](https://user-images.githubusercontent.com/73637969/134491764-a3fb8ca1-7537-4759-99d7-013db01c245b.png)
