### ISSUE TITLE
[EPOS] Detaljvisning av datasett

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#426]
Som: bruker av datakatalogen på jakt etter åpne data
Ønsker jeg å: en intuitiv detaljvisning
Slik at: raskt finner sentrale elementer i detaljvisningen

Relatert til epos: #91 
Relatert til brukerhistorie: #422 #158 #143 #145 #144 #432 #430 #434 

For brukere på jakt etter åpne datasett følgende elementer sentrale for datasett med distribusjoner:

- Lisens  (`dct:license` -  Vilkår for bruk av datasettet) (#143)
- TilgangsURL (`dcat:accessURL `/ lenke datasettet eller til en infoside om datasettet) (#143)
- Nedlastningslenke (`dcat:downloadURL` / direktelenke for nedlasting av fil) (#430)
- Tilgjengelige format (`dct:format` - jf #145 )
- Lenke til API-et (`dcat:accessService`) 

I tillegg kan distribusjonene ha følgende felter

- Tittel (valgfritt)
- Beskrivelse (anbefalt)
- Innholdsstandard 
- Informasjonsmodell 
- Sist endret
- Filstørrelse
- ++ ca 8-10 til som er mindre viktige

Eksempler (gode og dårlige) på hvordan dette er løst i andre portaler:
- https://data.norge.no/data/bergen-kommune/dokart-bergen-sentrum
- https://data.gov.ie/dataset/roscommon-public-slipways
- https://data.gov.uk/dataset/a2416481-271a-42b2-ace8-fc247dd251be/legislation-api
- https://catalog.data.gov/dataset/ncdc-storm-events-database
- https://www.data.gouv.fr/en/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/
- https://oppnadata.se/datamangd/#esc_entry=43843&esc_context=43

Lenke til design, åpen tilgang: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html
Lenke til design, begrenset tilgang: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-restricted-default.html 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
@oystein-asnes : har vi noko som gjenstår i dette eposet?

**Comment by oystein-asnes** [comment]
#432 står igjen her, men lukker eposet.
