### ISSUE TITLE
Synliggjøre innholdsleverandører til ett datasett

### ISSUE THREAD

**Issue by BredeD** [Informasjonsforvaltning/behov#427]
Som: Bruker av NAP/Fellesdatakatalog 
Ønsker jeg å: se hvilke innholdsleverandører som er med i datasettet
Slik at: jeg raskt finner riktig datasett

Som: Leverandør av data til et nasjonalt datasett 
Ønsker jeg å: sikre at mine data er lett tilgjengelig og synlig på NAP/Fellesdatakatalog
Slik at: vi ikke trenger å legge inn duplikate datasett

Relatert til epos:

Lenke til design: 
Kan løses på mange måter.
![Merknad 2020-02-12 092448](https://user-images.githubusercontent.com/27970417/74316279-8ff80880-4d79-11ea-960b-91944b1967a0.png)
Se også mail til Joackim 18.11.19 15:06.

Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by oystein-asnes** [comment]
Sett med dcat-briller handler dette om at det skal være mulig å uttrykke flere roller i relasjoner mellom aktører (foaf:Agent) og datasett. I versjon 1.1 har vi:
- `dct:publisher` (utgiveren av datasettet), 
- `dct:creator` (norsk tillegg for å skille mellom utgiver og produsenten av datasettet).
( i tillegg har `dcat:contactPoint `som er referanse til kontaktpunktsobjekt med kontaktopplysninger). 

`dct:creator` er `0..n` så her kan en i prinsippet legge til så mange produsenter en vil, men vil aldri kunne skille mellom feks ansvarlig produsent og underleverandør (dersom det er et behov).

I versjon 2 har vi flere muligheter:

> Based on the experience gained with the use of domain-specific extensions for additional ‘agent roles’ in the exchange of information about Datasets and on the requests of implementors and stakeholders, the DCAT Application Profile release 2.0.0 is extended with additional roles as proposed by DCAT Version 2, W3C Working Draft 28 May 201947 that have proven to be useful across domains. Precisely, properties dct:creator, prov:qualifiedAttribution and prov:qualifiedRelation have been added to dcat: dataset class to further facilitate relationships between datasets and agents

Dette betyr at vi også har muligheten til å bruke `prov:qualifiedAttribution` og `prov:qualifiedRelation`
(jeg kommer tilbake med mer detaljer her)

**Comment by joebrreg** [comment]
Løst ved å bruke qualifiedAttribution
