### ISSUE TITLE
[BRUKERHISTORIE] Høste datahotell-API-er til  API-katalogen

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#428]
Som: tilbyder av en felles API-tjeneste (hotell.difi.no)
Ønsker jeg å: ...
Slik at:

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Lukkar denne til fordel for #666
