### ISSUE TITLE
[BRUKERHISTORIE] Nedlastingslenke mangler i registreringsløsningen

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#430]
Som: tilbyder av et datasett
Ønsker jeg å: oppgi nedlastningslenken i registreringsløsningen
Slik at: brukerne finner filen min

Dette felter mangler i reg.-løsningen (under distribusjon). Nedlastningslenken er en dedikert lenke til selve filen  i motsetning til `dcat:access:URL` som KANvære  til en infoside. (Dersom nedlastningslenken er eneste tilgjengelige URL skal denne gjentas som acess:URL)

URI: `dcat:downloadURL`
Range: `rdfs:Resource`
Beskrivelse: Direktelenke (URL) til en nedlastbar fil i et gitt format
Kardinalitet: 0..n
Status: Valgfri

Relatert til epos: #91 
Relatert til brukerhistorie: #158

Lenke til design: 
Lenke til løsningsarkitektur:

Dokumentasjon/brukarveiledning må oppdateres når nytt felt kommer inn i registreringsløsning.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): **Kritisk**

**Comment by eggedosis** [comment]
Hvor i registreringsflyten tenker dere at denne hører hjemme? Altså under hvilken seksjon?
@oystein-asnes @livarb

**Comment by lillelars** [comment]
Her er det naturlig å legge det inn i flyten @eggedosis 
![image](https://user-images.githubusercontent.com/39513382/76420763-ea00e380-63a2-11ea-93bf-e62bf9592daf.png)

**Comment by livarb** [comment]
Vi bør avgrense til kun ein verdi - at ein kun kan skrive inn ei nedlastingslenke pr. distribusjon. Sjølv om kardinalitet på feltet i dcat-ap-no er 0...n så gir det ikkje noko spesiell verdi å ha fleire nedlastingslenker. Tilgangslenke har forøvrig kardinalitet 1...n, og det er kun anledning til å skrive inn ein verdi.

Einaste tilfellet for bruk eg kan tenke meg er dersom ein har nedlasting av samme datasett i ulike format. Då passar det uansett betre å føre det opp som ulike distribusjonar. Dersom ein skal ha fleire nedlastingslenker, så er det vanskeleg å skilje mellom forskjellen på lenkene, sidan det ikkje er informasjon om format knytt til ei nedlastingslenke, innad i samme distribusjon.

**Comment by stigbd** [comment]
Det korte svaret er: Vi bør i utgangspunktet støtte standarden. Om standarden er feil, bør den rettast opp i.

**Comment by livarb** [comment]
@stigbd : No er det revisjon på gang, så det er ei god anledning til å gje innspel på standarden :)

God hjelpetekst er viktig å ha med i registreringsløysinga om ein har anledning til å skrive inn fleire nedlastingslenker på same distribusjon.

Einaste case for å ha fleire nedlastingslenker i same distribusjon som vi kom på, er dersom det er fleire serverar som serverer ut samme fil. Dersom det er eit datasett som tilbys til nedlasting i ulike format (f.eks. CSV og JSON), bør CSV-fila vere i ein distribusjon og JSON-fila i ein distribusjon. Dette sidan format-attributten er knytt til distribusjon og ikkje den enkelte nedlastingslenka.

Eg tenker det er lurt å avgrense til berre kunne skrive inn ei nedlastingslenke i registreringsløysinga, for å unngå at brukarar fyller inn feil og at det blir for mange alternativ i registreringsløysinga, på same måte som ein ikkje har med absolutt alle felt i DCAT-standarden. Dette har eg ikkje ei veldig sterk meining på, så tenker de må gjere ei vurdering på. Det viktigaste er å kunne redigere nedlastingslenke i registreringsløysinga.

**Comment by lillelars** [comment]
@stigbd @livarb Skal vi gå for en lenke i registreringsløsningen da? vil gjerne at vi bestemmer oss for noe hvertfall! :) 

Slik standarden er nå må vi støtte flere lenker for høsting og visning av dette i portal hvertfall... Det er kanskje ikke ås ofte det vil være flere enn en lenke pr distribusjon uansett.

**Comment by stigbd** [comment]
Tenker vi går for 1 stk lenke i registrerings-gui, mens api kan støtte standard, dvs mulig for fleire.

**Comment by shenluna** [comment]
Dette er løst, bilde fra registrering, lukker dermed saken.
![image](https://user-images.githubusercontent.com/73637969/134493347-38e0e8c0-ce6f-48d3-bdd2-f3219f874a28.png)
