### ISSUE TITLE
[BRUKERHISTORIE] Side for organisasjon

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#431]
Som: Bruker av FDK
Ønsker jeg å: få oversikt over oppføringene til en organisasjon
Slik at: jeg lettere kan finne fram til rett datasett og relaterte datasett

Relatert til epos: #91

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/report/organizations.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig (må drøftast)

Eksempel frå dagens data.norge.no:
https://data.norge.no/organization/registerenheten-i-br%C3%B8nn%C3%B8ysund

Innhald på ei slik side:
- Vise organisasjonen sitt innhald
- Om organisasjonen: logo, foretaksnamn, org.nr., organisasjonsform, forretsningsadresse

Drøfte:
- Kva meir skal visast? Næringskodar? Nettside dersom ført opp i Brreg.?
- Korleis skal innhald visast? Kunne sortere på ulike måtar? E.g. tittel, sist oppdatert, sist publisert
Alle katalogar i ei visning, eller tabs for ulikt innhald?
- RSS-feed (som på data.norge.no)
- Alternativt namn til foretaksnamn? T.d. "Registerenheten i Brønnøysund" --> "Brønnøysundregistrene", "Statens Kartverk" --> "Kartverket" etc.

**Comment by lillelars** [comment]
@livarb hvor viktig er denne delen av denne brukerhistorien:
![image](https://user-images.githubusercontent.com/39513382/77628068-0d519400-6f48-11ea-9cc4-6058d318c2ff.png)

For vår del vil denne kunne leveres mye raskere hvis vi bare viser oversikt over organisasjoner og gjør utdrag på datasett.

**Comment by livarb** [comment]
@lillelars : Tenker ein slik boks bør vere med, så ein har meir informasjon om verksemda.
Tenker mesteparten av informasjonen kan gjerast ved eit kall til data.brreg.no i det sida vert lasta inn. Det vil seie at ein treng ikkje lagre all informasjonen i FDK. Kan lage eit forslag til kva attributtar som bør vere med.

Ei grei plassering for ein slik boks er kanskje til venstre for søkeresultata, rett over eventuelle filter.

Kva er det som tek mest tid med å lage ein slik boks? Er det å tilpasse front-end?

**Comment by livarb** [comment]
Nemt på behovsstandup:
- Optimalisering av ytelse er under arbeid. Tar ca. 10 sekund før lista over verksemder dukkar opp.
- Manglar overskriftsrad i tabellen, jamfør designskisse
- Ta gjerne med hover-tekst på overskriftsrad

**Comment by livarb** [comment]
Lukkar denne saka. Vidare forbetring av organisasjonsside i #479 

https://data.norge.no/organizations/889640782

![image](https://user-images.githubusercontent.com/3617256/122399929-87ba6980-cf7b-11eb-9f71-ea411df6e84f.png)
