### ISSUE TITLE
[BRUKERHISTORIE] Få med tittel på "relevante lenker"

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#432]
Som: datautgiver
Ønsker jeg å: få migrert tittel på "relevante lenker" fra data.norge.no
Slik at: denne informasjonen blir med og hjelper brukere til å lettere forstå lenkene i datasett-beskrivelsen

Relatert til epos: #426 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/dataset/detail-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):
Kritisk

**Comment by livarb** [comment]
Korleis skal desse titlane kome ut i DCAT-eksport frå data.norge.no? Kva felt?
Og korleis skal det sjå ut i detaljvisning i FDK?

Eksempel med Enhetregisteret:
https://data.norge.no/data/registerenheten-i-br%C3%B8nn%C3%B8ysund/enhetsregisteret
Der er relevante lenker:
![image](https://user-images.githubusercontent.com/3617256/75038442-aa875b80-54b6-11ea-9fc4-9c5bce5d8fd1.png)

Utsnitt frå registreringsskjema i data.norge.no:
![image](https://user-images.githubusercontent.com/3617256/75038467-b8d57780-54b6-11ea-8ba3-803d50af11a3.png)

I DCAT-eksport frå data.norge.no blir ikkje tittel med:
![image](https://user-images.githubusercontent.com/3617256/75038512-c985ed80-54b6-11ea-97c9-33bd3077f2aa.png)

Og dermed blir lenkene "fattigare" i FDK:
https://fellesdatakatalog.brreg.no/datasets/0368649b-c377-4c19-8583-50fba07550bd

![image](https://user-images.githubusercontent.com/3617256/75038546-da366380-54b6-11ea-8568-ce6faa56755c.png)

**Comment by livarb** [comment]
Forslag til endring på data.norge-API-et for å få med tittel på lenkene.
@stigbd : Har du nokon kommentarar på formatet?
`"dct:relation":[
    {
        "@id":"https://www.ssb.no/klass/",
        "dct:title":{
            "@language": "no",
            "@value": "Klassifikasjoner"
        }
    }
]`

**Comment by stigbd** [comment]
rdfs:Resource er klassen som omfattar "alt", så her står vi ganske fritt, ja. Eg foreslår ein litt enklare konstruksjon:
```
<http://example.com/datasets/1> a dcat:Dataset ;
    dct:relation [ rdf:about "https://www.ssb.no/klass/" ;
                         rdf:label "Klassifikasjoner"@nb ;
    ]
.
```

**Comment by stigbd** [comment]
Evt
```
<http://example.com/datasets/1> a dcat:Dataset ;
    dct:relation <https://www.ssb.no/klass/>
.
<https://www.ssb.no/klass/> a rdfs:Resource;
    rdfs:label "Klassifikasjoner"@nb ;
.
```

**Comment by livarb** [comment]
Sidan vi no ser på å migrere ved hjelp av database-dump, så er det ikkje lenger snakk om å endre noverande API på data.norge.no for migrering.

Så då er det eit spørsmål om korleis det skal uttrykkast i DCAT. @oystein-asnes har kanskje kommentarar om eksempelet frå Stig over?

**Comment by shenluna** [comment]
Jobber med nytt design for visning av relaterte lenker
https://github.com/Informasjonsforvaltning/fdk-portal/issues/1052

**Comment by livarb** [comment]
Ser i tilknytta sak nemt av Luna at det no er støtte for relaterte lenker.
Spørsmålet er om vi må re-importere namn på lenker som ikkje kom med i migreringa frå gamle data.norge.no. Dette må undersøkast.
Flytta denne tilbake til "Analysere behov".

**Comment by KjerstiSteien** [comment]
@livarb er dette fortsatt noe det er behov for å løse? Skal vi gjøre en analyse av dataene?

**Comment by livarb** [comment]
Tenker verdien av å gjere dette er for lav til å ta jobben.
Foreslår vi lukkar denne saka.
Dei som treng å henvise til dokumentasjon, nettsider etc. som er relevante for ei datasett-beskriving, kan enten legge inn ein URL (sjå under) eller få URL-ane inn i beskrivelsen. Lenker i beskrivelsen er ikkje så pent, men det er beste alternativet så vidt eg kan sjå.

Tenkte meir på dette:
Det interessante her hadde vore å fått eit betre opplegg for lenker.
Slik det er i dag, er det framleis berre mogeleg å registrere ein URL med lenke til meir informasjon om eit datasett:
Eksempel med datasettet «Mottakere i ELMA» (Digdir)
https://data.norge.no/datasets/5a5374c3-c6a7-49f8-b9cc-0a9e48c1acd7

Slik ser det ut i registreringsløysinga
![image](https://github.com/user-attachments/assets/edfbf323-9601-40a1-b5bc-41580a9cbdcf)

Slik ser det ut i portal:
![image](https://github.com/user-attachments/assets/52f10d36-da03-4337-b818-f6e583945e87)
Den lenka («Mer informasjon om datasettet») er noko vekkgøymt.

Eit mogeleg grep kan vere å flytte den til rett under beskrivelsen i staden for.

Kva tenker de? @KjerstiSteien @oystein-asnes

**Comment by KjerstiSteien** [comment]
Det kan godt være at det burde komme tydeligere frem. Vi skal jobbe videre med en bedre brukeropplevelse for data.norge.no fremover. Lenke for mer informasjon vil bli naturlig å vurdere i forbindelse med det. Jeg lukker denne saken.
