### ISSUE TITLE
[EPOS] Enklere å finne fram til informasjon om tjenester

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#433]
Som: tjeneste-interessent
Ønsker jeg å: finne frem til informasjon om relevante tjenester
Slik at: jeg enkelt kan få dekket mine behov

Tilknyttede brukerhistorier:

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Behovet/tiltaket vil gi…
- [ ] betre brukaroppleving (inkluderer UU/wcag) 
- [ ] meir innhald og/eller betre kvalitet på innhald i FDK
- [ ] betre samanheng mellom katalogprodukta 
- [ ] andre omsyn (sikkerheit, ekstern finansiering, ledig kompetanse/kapasitet i teamet)

**Comment by KjerstiSteien** [comment]
@KurtStian Er dette behovet dekket gjennom søket på data.norge.no? Eller er det noe vi mangler for å dekke dette?

**Comment by KurtStian** [comment]
@KjerstiSteien Det er jo mulig å søke etter tjenester i dag basert på navn, beskrivelse og nøkkelord, samt egen arkfane som viser alle tjenester og hendelser. Og vi har et annent epos som går på filtrering og avansert søk: https://github.com/Informasjonsforvaltning/behov/issues/709
Tror vi kan lukke denne.
