### ISSUE TITLE
[BRUKERHISTORIE] Vurdere å avvikle angivelse av distribusjon som fil, webservice eller feed

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#435]
Som:
Ønsker jeg å:
Slik at:

Denne praksisen er ikke støttet av verken DCAT 1 eller 2 og heller ikke en del av DCAT-AP-NO. Med DCAT 2 og innføring av egen klasse for dataservice blir dette redundant informasjon (?) 
Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by lillelars** [comment]
Denne er nå ferdig vurdert :D. Dette gjør vi.

**Comment by lillelars** [comment]
er nå fjernet fra løsningen vår.
