### ISSUE TITLE
[EPOS] Etabler en BETA-løsning for å presentere informasjon om tjenester

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#436]
Som: konsument av en tjeneste
Ønsker jeg å: få oversikt over alle registrerte tjenester
Slik at: jeg kan oppdage, evaluere og bruke tjenester 

Tilknyttede brukerhistorier:
#445 
#446
#450
#460 
#462

Relatert til epos:
#1

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by KurtStian** [comment]
BETA-versjonen er laget og ble produksjonssatt i 2021.
