### ISSUE TITLE
[EPOS] Høste til felles tjenestekatalog

### ISSUE THREAD

**Issue by BRespen** [Informasjonsforvaltning/behov#437]
Som: forvalter av en virksomhets tjenestekatalog
Ønsker jeg å: kunne publisere hele eller deler av min katalog i felles tjenestekatalog
Slik at: dette blir tilgjengelig for andre

Tilknyttede brukerhistorier:
#465 

Relatert til epos:
#1

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by KurtStian** [comment]
CPSV-AP versjon 2.2.1.
https://raw.githubusercontent.com/catalogue-of-services-isa/CPSV-AP/master/releases/2.2.1/CPSV-AP%20Specification%20v2.2.1%20-%20PNG.png
Mandatory:
description: Text
identifier: Text
name: Text
Optional:
keyword
language
processingTime
sector
spatial
status
thematicArea
type

**Comment by KurtStian** [comment]
Excel-filen med spesifikasjon v 2.2.1 av CPSV-AP ligger her:
https://joinup.ec.europa.eu/solution/core-public-service-vocabulary-application-profile/distribution/cpsv-ap-specification-v221-spreadsheet-template
Klikk på External for å åpne filen.

**Comment by KurtStian** [comment]
Lukket da den overlapper med epos #440, samt at tilhørende brukerhistorien er blitt lukket pga. overlapp med #466
