### ISSUE TITLE
[BRUKERHISTORIE] Vise sammenhengen mellom en hendelse og tjenester

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#448]
Som: konsument av en hendelse
Ønsker jeg å: se hvilke tjenester som inngår i en hendelse
Slik at: jeg kan se hvilke tjenester som utløses av hendelsen

Relatert til epos: #447 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by KurtStian** [comment]
@lillelars
Forslag til endring av tekst/design slik at det bedre fremgår at tjenestene er en del av hendelsen:

![image](https://user-images.githubusercontent.com/43232700/110626766-6c340b80-81a1-11eb-8273-f51f67ee77a5.png)

**Comment by lillelars** [comment]
@KurtStian 
Løst i https://github.com/Informasjonsforvaltning/behov/issues/462.
Lukker du denne?

**Comment by KurtStian** [comment]
Denne er delvis levert (mangler beskrivelsen):
 ![image](https://user-images.githubusercontent.com/43232700/111784635-ec522380-88bb-11eb-81a7-f522e51783e4.png)

og i overskriften kunne det ha stått «Tjenester som inngår hendelsen».

I tillegg blir det litt rart når også denne vises:
![image](https://user-images.githubusercontent.com/43232700/111784683-f96f1280-88bb-11eb-846e-bbc272050b46.png)

Jeg antar det er fordi man har «related services» på hendelsen og «Is grouped by» på tjenesten. Men slik jeg ser det er jo disse egentlig helt de samme relasjonene bare registrert motsatt vei, - er det ikke?

Er det noe behov for å vise i portalen at relasjonen er kun registrert en vei eller begge veier? 
Og skal det være mulig å registrere kun en relasjon mot en hendelse på en tjeneste som kun vises under «Andre som relatere til denne hendelsen», mens da «Tjenester som inngår i hendelsen» er tom?
Kan det være en mulighet å vise både «related services» og «Is grouped by» under visningen «Tjenester som inngår i hendelsen», der man selvfølgelig sorterer bort dubletter?

**Comment by KurtStian** [comment]
@lillelars @shenluna 
Angående denne (fra forrige kommentar):

> I tillegg blir det litt rart når også denne vises:
> image
> 
> Jeg antar det er fordi man har «related services» på hendelsen og «Is grouped by» på tjenesten. Men slik jeg ser det er jo disse egentlig helt de samme relasjonene bare registrert motsatt vei, - er det ikke?
> 
> Er det noe behov for å vise i portalen at relasjonen er kun registrert en vei eller begge veier?
> Og skal det være mulig å registrere kun en relasjon mot en hendelse på en tjeneste som kun vises under «Andre som relatere til denne hendelsen», mens da «Tjenester som inngår i hendelsen» er tom?
> Kan det være en mulighet å vise både «related services» og «Is grouped by» under visningen «Tjenester som inngår i hendelsen», der man selvfølgelig sorterer bort dubletter?

Diskuterte denne med Espen og vi ble enig om at denne kunne løses slik det er gjort med datasett. Eks. fra datasettet Enhetsregisteret:
![image](https://user-images.githubusercontent.com/43232700/113984757-bb766600-984b-11eb-872c-0e2fe10d608b.png)

**Comment by KurtStian** [comment]
@lillelars @shenluna 
«Tjenester som inngår i hendelse» er nå endret til «Tjenester som inngår i hendelsen» og beskrivelsen til tjenestene er også kommet med😊 . 

Det som mangler er å få med relasjonstype for tjeneste og hendelse under «Andre som relaterer til denne hendelsen», jf. kommentaren ovenfor.

**Comment by KurtStian** [comment]
@BRespen Har du noen forslag på hva vi vi skal kalle relasjonstypene som automatisk vises på den som blir pekt på?
Også jf.: chat'en som har vært på teams.

**Comment by KurtStian** [comment]
Relasjonstypene mellom tjenester og hendelser blir sannsynligvis endret i forbindelse med den norske utgaven av CPSV. Foreslår av vi lukker denne og så får vi melde ev. endringer av relasjonstyper og navn i en ny sak når første versjon av CPSV-AP-NO er på plass.
