### ISSUE TITLE
[BRUKERHISTORIE] Navigere fra en tjeneste til et datasett

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#450]
Som: konsument av en tjeneste
Ønsker jeg å: se hvilke datasett som er input (evidence) og output til en tjeneste og navigere til disse
Slik at: jeg kan se hvilke data som inngår i en tjeneste

Relatert til epos: #436 

Relatert til brukerhistorie: #100, #101

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterie:
- Relasjonen skal finnes begge veier

**Comment by KurtStian** [comment]
@lillelars 
Har testet litt og kan ikke se at det er mulig å navigere fra datasett til tjenesten (dvs. at relasjonen finnes begge veier jf. akseptansekriterie).

**Comment by lillelars** [comment]
@KurtStian har en bug på dette. sjekker det opp videre

**Comment by KurtStian** [comment]
Testet OK.
