### ISSUE TITLE
[BRUKERHISTORIE] Søke etter tjeneste

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#451]
Som: konsument av tjenester
Ønsker jeg å: kunne søke blant alle tjenestene
Slik at: jeg få opp en oversikt over alle tjenester som helt eller delvis overlapper med mitt søk

(Følger standard søk som for de andre katalogene.)

Relatert til epos: #439 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KurtStian** [comment]
@lillelars
Siden tjenester og hendelser ble i en katalog/arkfane i stedet for to, så må det være mulig å filtrere søket til å bare søke etter tjenester.

**Comment by lillelars** [comment]
@KurtStian Per nå støtter vi generelt søk på tjenester og hendelser + filtrering på ulike hendelser. 
For å være litt streng er løsningen som det matcher med tittel og kriterier på brukerhistorien. 
Er det et ønsket behov å kunne filtrere søket til bare tjenester, eller bare hendelser, må vi implementere f.eks et radiofilter med valg på tjeneste og hendelse. Dette bør i så fall beskrives i et separat behov?

@joebrreg litt usikker på om vi skal prioritere en ny funksjon på dette nå, hva tenker du?

**Comment by KurtStian** [comment]
@lillelars @joebrreg 
På denne er jeg ikke enig i din kommentar siden søket også går mot hendelser, Men jeg lager egen brukerhistorie.

**Comment by KurtStian** [comment]
Filtering på tjenester ved søk i tjeneste- og hendelsekatalogen er beskrevet i seperat brukerhistorie: #565
