### ISSUE TITLE
[BRUKERHISTORIE] Søke etter hendelse

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#452]
Som: konsument av hendelser
Ønsker jeg å: kunne søke blant alle hendelsene
Slik at: jeg få opp en oversikt over alle hendelser som helt eller delvis overlapper med mitt søk

(Følger standard søk som for de andre katalogene.)

Relatert til epos: #453

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KurtStian** [comment]
@lillelars 
Siden tjenester og hendelser ble i en katalog/arkfane i stedet for to, så må det være mulig å filtrere søket på bare hendelser eller bare tjenester.

**Comment by lillelars** [comment]
@KurtStian 
Kommentar relatert til https://github.com/Informasjonsforvaltning/behov/issues/451

@KurtStian Per nå støtter vi generelt søk på tjenester og hendelser + filtrering på ulike hendelser.
For å være litt streng er løsningen som det matcher med tittel og kriterier på brukerhistorien.
Er det et ønsket behov å kunne filtrere søket til bare tjenester, eller bare hendelser, må vi implementere f.eks et radiofilter med valg på tjeneste og hendelse. Dette bør i så fall beskrives i et separat behov - og at vi i så fall kan lukke denne saken?

@joebrreg litt usikker på om vi skal prioritere en ny funksjon på dette nå, hva tenker du?

**Comment by KurtStian** [comment]
@lillelars @joebrreg 
Ser den, men samtidig ble denne brukerhistorien laget da man så for seg to separate kataloger. Men jeg kan lage et nytt behov.

**Comment by KurtStian** [comment]
Filtering på hendelser ved søk i tjeneste- og hendelsekatalogen er beskrevet i seperat brukerhistorie: #565
