### ISSUE TITLE
[BRUKERHISTORIE] Filtrere på hendelser

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#454]
Som: konsument av hendelser
Ønsker jeg å: kunne filtrere på hendeles på bakgrunn av gitte kriterier
Slik at: slik at jeg enklerer kan finne frem til hendelser som jeg er interessert i

Kriterier: ansvarlig, hendelsestyper, tjenestetype?  (spesifikasjonen for hendelser må avklares før man har oversikt over alle kriterier)

Relatert til epos: #453 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KurtStian** [comment]
@BRespen Burde det være overordnet filtreringsmulighet på om en hendelse er næringsbasert eller innbyggerbasert?
F.eks. jeg ønsker å se alle næringsbaserte hendelser. Samtidig vil jo dette begrense valget i dagens filter "Hendelser"

**Comment by KurtStian** [comment]
@shenluna 
Her mangler filtreringsmuligheten på næring og innbygger. Du sa i kommentar  https://github.com/Informasjonsforvaltning/behov/issues/457#issuecomment-856710189 at Lene skulle se på saken.
Har snakket med Espen og han er enig om at vi må få på plass dette. Dette kan f.eks. løses ved næring og innbygger er de to øverste nivåene i filteret. Mener kanskje at jeg har sett et forslag til design på dette?

**Comment by shenluna** [comment]
Filtreringsmulighet for næring og innbygger er lagt til. Lukker dermed brukerhistorien.
