### ISSUE TITLE
[BRUKERHISTORIE] Filtrere på tjenester

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#455]
Som: konsument av tjenester
Ønsker jeg å: kunne filtrere på tjenester på bakgrunn av gitte kriterier
Slik at: slik at jeg enklerer kan finne frem til tjenester som jeg er interessert i

Kriterier: ansvarlig, tjenestetype, hendelsestype (spesifikasjonen for tjenester må avklares før man har oversikt over alle kriterier)

Relatert til epos: #439 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KurtStian** [comment]
Aksepteres foreløpig med manglende tjenestetype da denne ikke er avklart. Tjenestetype (type) må sees på i sammenheng med Tema (Thematic Area ) og muligens også Næringskode (Sector).

**Comment by KurtStian** [comment]
@shenluna Ser at du flyttet denne fra Utført til Klar til akseptansetest i dag. Er det skjedd noe nytt angående denne brukerhistorien, som jeg lukket og flyttet til Utført den 10. mars?

**Comment by shenluna** [comment]
@KurtStian Oi, det var ikke meningen, tror jeg tilfeldigvis kom borti og klarte å dra den over uten å mene det. Jeg lukker den igjen.
