### ISSUE TITLE
[BRUKERHISTORIE] Se hendelser og tjenester under samme fane

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#457]
Som: konsument av hendelser
Ønsker jeg å: se alle hendelser og tjenester i samme fane
Slik at: jeg enklere kan finne frem til hendelser jeg er interessert i

Hendelsene presenteres med navn, beskrivelse (sammendragstekst), hendelsestype (Næring/Innbygger) og relaterte tjenester (flere egenskaper kan bli tilføyd).

Relatert til epos: #453 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/service/search-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by KurtStian** [comment]
@lillelars 
Mangler «hendelsestype (Næring/Innbygger) og relaterte tjenester».

![image](https://user-images.githubusercontent.com/43232700/110323472-f0a55380-8014-11eb-9557-cf409a8296e4.png)

**Comment by KurtStian** [comment]
@shenluna Se min kommentar ovenfor fra 8. mars. Kan ikke se at dette er løst.

**Comment by shenluna** [comment]
@KurtStian Skal alle tjenester relatert til en hendelse vises i sammendragsboksen?

**Comment by KurtStian** [comment]
Ja, det var det vi tenkte ( tillegg til om det er en næring eller innbygger hendelse). Mulig at det må legges på en begrensning på hvor mange tjenester som vises i tilfelle det er noen hendelser som har veldig mange tjenester.

**Comment by shenluna** [comment]
@KurtStian Jeg forstår ikke helt nytten av å ha en separat detaljeside hvis så å si all informasjon også skal vises i en sammendragsboks, det blir fort veldig mye innhold i sammendragsboksen. I tillegg får man alle tjenester knyttet til hendelsen som egne sammendragsbokser når man sorterer/filtrerer på hendelsen.

**Comment by KurtStian** [comment]
@shenluna Jeg ser den. Vi kan la den ligge inntil vi får mer erfaring. Men opplysningen om det er næring- elle innbyggerhendelse er aktuell informasjon. Kanskje skulle vi også ha sortert hendelsesfiltreringen under disse to kategoriene?

**Comment by shenluna** [comment]
@KurtStian Jeg har bedt Lene ta en titt på hvordan designet skal være for de to tingene du nevner, altså hendelsestype i sammendragsboksen og sortering på hendelsesfilter

**Comment by KurtStian** [comment]
@shenluna Fint 😊 Sortering/filterering på hendelsestype næring/innbygger hører vel egentlig innenfor sak #454. La inn en kommentar der i går.

**Comment by shenluna** [comment]
@KurtStian Nå vises informasjon om hendelsen er av typen innbygger og næring i sammendraget.
![image](https://user-images.githubusercontent.com/73637969/128705930-198b497a-8b3e-4ba4-8c9e-33696006ac0f.png)

**Comment by KurtStian** [comment]
Denne lukkes hvis filtrering på hendelsestype Næring og Innbygger blir løst i sak #454 .

**Comment by shenluna** [comment]
Lukker denne da nåværende løsning tilfredsstiller brukerhistorien. Filtrering blir løst i egen sak.
