### ISSUE TITLE
[BRUKERHISTORIE] Navigere fra en tjeneste til en hendelse

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#462]
Som: konsument av tjenester
Ønsker jeg å: kunne navigerer fra en tjeneste til en hendelse som er koblet til denne tjenesten
Slik at: jeg kan få mer informasjon om denne hendelsen

Relatert til epos: #436 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KurtStian** [comment]
Forslag til endring av tekst/design slik at det bedre fremgår at tjenesten er en del av en hendelse:

![image](https://user-images.githubusercontent.com/43232700/110625146-5ae9ff80-819f-11eb-9176-c5b2b27d3d41.png)

**Comment by KurtStian** [comment]
@lillelars 
Har flyttet tilbakemeldingen ovenfor til brukerhistorien "Vise sammenhengen mellom en tjeneste og hendelse #446". Det blir mer korrekt og passer med tilsvarende tilbakemelding som er gjort på brukerhistorien "Vise sammenhengen mellom en hendelse og tjenester #448".

Men oppdaget en annen feil:
1. Er inne på tjenesten "Samordnet registermelding"
2. Klikke på lenken til hendelsen "Starte og drive et idrettslag" (under Andre som relaterer til denne tjenesten)
3. Hendelsen "Starte og drive et idrettslag vises, men det er ingen lenke tilbake til tjenesten "Samordnet registermelding".

Så relasjonen går ikke begge veier. Som eks. kan også tjenesten "Søknad om skjenkebevilling" brukes.

**Comment by lillelars** [comment]
@KurtStian Oppretter issue på buggen din.

**Comment by lillelars** [comment]
@KurtStian Denne skal være fikset nå - får du resjekket og evnt akseptert?

**Comment by KurtStian** [comment]
Relasjonene går nå begge veier og saken lukkes derfor 😊
