### ISSUE TITLE
[BRUKERHISTORIE] Relevante/siste publiserte - ny framside

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#464]
Som: bruker av FDK
Ønsker jeg å: kjapt se mest interessante oppføringer
Slik at: jeg kan kjapt finne frem

Relatert til epos: #420 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Spørs her om kva type sortering vi skal bruke?
1. Sist publisert - nyast publiserte oppføringar
2. Mest relevant - usikker på kriterier. Ta med dei som er autorative? Eller redaksjonelt styrt liste?
3. Sist oppdatert - sist oppdaterte oppføringar
4. Mest populære - basert på kva oppføringar som har flest visningar. Data f.eks. frå Google Analytics.

Usikker på om vi landa på noko her i møtene der vi drøfta dette.

Kanskje skal det vere mogleg å bytte mellom fleire ulike alternativ?
Om vi kun går for å nytte ei sortering, bør ein ha i tankane at det kan utvidast til å velje sortering seinare.

**Comment by stigbd** [comment]
Eg trur i alle fall punkt (4) Mest poplære er relevant i forhold til #656

**Comment by KjerstiSteien** [comment]
Lukker denne, og løfter det heller opp igjen, dersom dette etterlyses av brukere igjen.
