### ISSUE TITLE
[BRUKERHISTORIE] Registrere endepunkt for høsting av tjenester

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#465]
Forrutsetning: Gitt at virksomheten har tilgjengeliggjort en tjenestekatalog i henhold til felles spesifikasjon for tjenestekatalog (Må lages. Skal være basert på CPSV-AP). 

Som: forvalter av en virksomhets tjenstekatalog 
Ønsker jeg å: registrere et endepunkt i Felles datakatalog (FDK-admin)
Slik at: endepunktet kan bli høstet og våre tjenester blir tilgjengeliggjort i felles tjenestekatalog.

Følgende formater skal støttes:

* RDF/XML
* Turtel
* Json-LD?

Relatert til epos: #440 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by lillelars** [comment]
Realiseres av #466
