### ISSUE TITLE
[BRUKERHISTORIE] Høsting av en virksomheten sin tjenestekatalog til FDK

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#466]
Som: forvalter av en tjenestekatalog til en virksomhet
Ønsker jeg at: FDK skal høste tjenestekatalogen fra endepunktet jeg har registrert hos FDK
Slik at: beskrivelsene av tjenestene i katalogen blir tilgjengeliggjort i Felles tjenestekatalog.

Relatert til epos: #440 

Lenke til design: N/A
Lenke til løsningsarkitektur: Utviklerne bestemmer hvilken eksisterende høster vi skal basere denne brukerhistorien på.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterie:
- Når en virksomhet publiserer sin tjenestekatalog på gyldig format, 
og virksomheten har registrert endepunktet sitt i administreringsløsningen
så skal relevant innhold i tjenestekatalogen vises i https://data.norge.no/public-services

**Comment by lillelars** [comment]
@KurtStian @BRespen Denne bør vi få eksterne aktører til å gi oss testdata før vi godkjenner. Fra utviklingen sin side ser vi oss i prinsippet ferdig med denne ettersom vårt endepunkt kan høstes fra admin-løsningen i dag.

**Comment by shenluna** [comment]
@KurtStian Kan denne lukkes?

**Comment by KurtStian** [comment]
Denne erstattes nå av https://github.com/Informasjonsforvaltning/behov/issues/651 og kan derfor lukkes.
