### ISSUE TITLE
[BRUKERHISTORIE]  generere rapport over obligatoriske felter

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#468]
Som: virksomhet (eventuelt personvernombud i virksomheten)
Ønsker jeg å: generere rapport  som kun viser innhold som er obligatorisk etter artikkel 30 i GDPR (protokoll).
Slik at: jeg kan vise fram dette til andre parter, for eksempel Datatilsynet ved tilsyn

Relatert til epos: #391 

Lenke til trådskisser:
Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/protocol-list.html
Lenke til løsningsarkitektur: 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by RogerSOlsen** [comment]
@eggedosis @joebrreg Skulle gjerne hatt noen trådskisser på denne

**Comment by lillelars** [comment]
@RogerSOlsen dette tar nok en uke eller to før vi får prioritert....

**Comment by lillelars** [comment]
@RogerSOlsen Kan jeg spøre hvem som har kommet med dette behovet? Hvorfor er det ønskelig å bare vise "obligatoriske felt" Ønsker man ikke å vise alle felt som er utfylt?

**Comment by RogerSOlsen** [comment]
Det er noen måneder siden brukerhistorien ble laget, så jeg husker ikke
nøyaktig hvem som sa hva i diskusjonen, men oppfattet at både Oddhild og
deltakerne fra BR ønsket dette. Jeg kan ta en ny sjekk med deltakerne på om
dette er noe begge parter ønsker, samt hvordan de vurderer
forretningsverdien.

Roger.

fre. 26. jun. 2020 kl. 08:16 skrev Lars M Riiser Haraldsen <
notifications@github.com>:

**Comment by lillelars** [comment]
@RogerSOlsen Er det i denne ønskelig å bare vise felter for behandlingsaktiviteter som er 'godkjent'? Eller for alle obligatoriske uavhengig av status?

**Comment by RogerSOlsen** [comment]
> @RogerSOlsen Er det i denne ønskelig å bare vise felter for behandlingsaktiviteter som er 'godkjent'? Eller for alle obligatoriske uavhengig av status?

@lillelars : Vi ønsker denne prioritetsrekkefølgen:
1. (viktigst): Rapport med kun obligatoriske felter for behandlingsaktiviteter som er godkjent. 
Denne gir mest verdi fordi man kan lagre en slik rapport i et NOARK-godkjent arkiv og oppfylle krav til artikkel 30 og er et minimumskrav for denne brukerhistorien

2. Rapport med kun obligatoriske felter for alle behandlingsaktiviteter som er godkjent uavhengig av status. 
Denne er ikke absolutt nødvendig dersom vi har muligheter for å ta ut rapport med kun obligatoriske felter for behandlingsaktiviteter som er godkjent. Det kan imidlertid gi økt bruksverdi av løsningen å kunne ta ut en rapport med kun obligatoriske felter for alle behandlingsaktiviteter som er godkjent uavhengig av status, for bruk i arbeidet med å gjennomføre registrering av behandlingsaktiviteter. Valg nr. 2 bør derfor også tas med i denne sprinten dersom det er mulig

**Comment by RogerSOlsen** [comment]
Det finnes rapport som kun viser innhold som er obligatorisk etter artikkel 30 i GDPR (protokoll).
Rapporten heter "Protokoll" og genererer rapport over obligatoriske felter i godkjente behandlingsaktiviteter, samt navn og kontaktopplysninger til Personvernombud, behandlingsansvarlig, behandlingsansvarliges representant – og representant for behandlingsansvarlig utenfor EU/EØS. Brukerhistorien er derfor lukket.
