### ISSUE TITLE
[BRUKERHISTORIE] Statisk innhold/sider

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#469]
Som: Pådriver for innhold i katalogene (data.norge.no/FDK)
Ønsker jeg å: publisere og redigere dynamisk og statisk innhold på portalen
Slik at: jeg kan bruke portalen som informasjonskanal for pådriverarbeid, veiledning, mm

Relatert til epos: #139 #420 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Innholdselementer - statisk innhold:**
- Tittel*
- Body/tekst*

**Sider som må migrerast**
Med utgangspunkt i dagens innhald på data.norge.no er det under forslag og kommentarar på korleis innhaldet kan setjast opp i FDK.

1. Veiledning (topp-punkt i menyen)
https://data.norge.no/veiledning
Kommentar: Skal vi ha ei slik oversiktsside, eller held det å ha under-meny-punkt?

Under-punkter til Veiledning i menyen:

2. Veileder i tilgjengeliggjøring av åpne data (ekstern lenke)
Dette er i dag lenke til ei ekstern side: https://doc.difi.no/data/veileder-apne-data/

3. "Slik registrerer du datasett"
https://data.norge.no/slik-registrerer-du-datasett
Innhaldet på denne sida bør gjerne slåast saman med vegledinga i FDK:
https://fellesdatakatalog.digdir.no/about-registration

4. "Standard for beskrivelse av datasett og datakataloger"
https://data.norge.no/standard-beskrivelse-av-datasett-og-datakataloger
Ei kort landingsside som peikar ein vidare til ekstern lenke.

5. "Retningslinjer ved tilgjengeliggjøring av offentlige data"
https://data.norge.no/retningslinjer-ved-tilgjengeliggj%C3%B8ring-av-offentlige-data
Denne må vere med i FDK. Foreslår å ha ei kortare side med eit par setningar om kva retningslinjene er, som så peikar vidare på regjeringen.no.
I dag er retningslinjene på regjeringen.no kopiert over på data.norge.no, og denne dupliseringa av innhald er ikkje nødvendig.

6. "Om data.norge.no" (lenke til sida oppe til høgre)
https://data.norge.no/om
Her må ein flette innhald saman med eksisterande om-side på FDK.

**Editor:**
Enkel editor med formateringsvalg:` bold, kursiv, liste, blockquote, lenke, inline bilder, underoverskrifter, tabell, embed.`

**Comment by shenluna** [comment]
Er en del av sammenslåing 2020, lukker saken.
