### ISSUE TITLE
[BRUKERHISTORIE] Aktuelt (nyhets-oppslag)

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#470]
Som: Pådriver for innhold i katalogene (data.norge.no/FDK)
Ønsker jeg å: publisere og redigere aktuelt-poster
Slik at: jeg kan bruke portalen som informasjonskanal for aktuelt; arrangement, nyheter og liknende

Relatert til epos: #139 #420 

Lenke til design: 
https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Innholdselementer - dynamisk innhold (aktuelt/nyheter):**
- Tittel*
- Ingress*
- Bilde 
- Bildetekst
- Body/tekst*
- Publiseringsdato*
- Forfatter 
- Tags*
- Kommentarer (av/på)
- Vedlegg (pdf, pptx, ppt, osv...)

 `*` = obligatoriske felter.

**Comment by livarb** [comment]
Usikker på kva av innholdselementa som er støtta i dagens løysing, og kva som ikkje er støtta.

**Comment by shenluna** [comment]
Knyttet til sammenslåing 2020, lukker saken.
