### ISSUE TITLE
[BRUKERHISTORIE] Peke til eksterne begreper fra lokal begrepskatalog

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#473]
Som: intern begrepskatalogløsning
Ønsker jeg å:  maskinelt kunne slå opp begrep vi peker til eksternt i den lokale katalogen vår, 
Slik at: jeg, i tillegg til å vise egne begreper, også kan eksponere begreper som kommer fra andre innholdet på en menneskelesbar måte til brukere av begrepskatalog.  

Eksempel/scenario:
Som kommunikasjonsmedarbeider i Skatteetaten har jeg behov for å kunne slå opp i lokal begrepskatalog og finne alle begrep vi tar i bruk i etaten, også de som er eksterne, slik at jeg kan utforme hjelpetekster på en effektiv måte

Relatert til epos: 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by marittor** [comment]
@stigbd Du er den eneste jeg får lov å tagge her, så da tagger jeg deg! Denne brukerhistorien har ikke p.t. noe epos, men bør løses samtidig som flere av historiene i #153

**Comment by stigbd** [comment]
Heilt fint å bli tagga :-) Eg sliter litt med å forstå denne: 

- Er "intern begrepskatalog" vår "registreringsløysing" eller dykkar feks Jira?
- Kva for bruk av bruk av begrep i etaten tenker du på? Feks begreper tatt i bruk i ein informasjonsmodell/datasett/api?

**Comment by marittor** [comment]
Så flott! Med de tilgangene jeg har tror jeg at jeg kun kan tagge de som er assignet til den enkelte historie. 
- Intern begrepskatalog betyr i denne konteksten vår Jira eller Skatteetatens interne verktøy. 
- Eksempelet med kommunikasjonsmedarbeideren tror jeg handler om å kunne gjøre oppslag (for menneske) på et hvilket som helst begrep som Skatteetaten har i sin begrepskatalog, uavhengig av om det er Skatteetaten eller andre som opprinnelig er ansvarlig for begrepet, for å gjenbruke teksten til f. eks hjelpetekster eller på nettsidene til Skatt.

**Comment by stigbd** [comment]
Fortsatt litt uklart for meg kva det faktisk behovet er, men vi har eit åpen API mot begrepskatalogen der det er mogleg å hente alle begrep i FDK:
https://fellesdatakatalog.digdir.no/apis/9879eb46-9e54-4be0-9ecf-83f1bba7fc5e

Eller rett til eksempler på bruk:
https://informasjonsforvaltning.github.io/felles-datakatalog/begrepskatalog/api/

Som minner meg på at vi bør legge begrepssamlinga inn som eit datasett i FDK, så den blir lettare å finne ;-)

**Comment by marittor** [comment]
Har justert brukerhistorien noe. Vi trenger kanskje et SKOS-api selv om vi idag har et api allerede.

**Comment by KjerstiSteien** [comment]
Lukker denne saken da behovet er uklart og begge nevnte virksomheter har tatt i bruk registreringsløsning for begrep.
