### ISSUE TITLE
[BRUKERHISTORIE] Utvida side for organisasjon

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#479]
Som: besøkende på FDK
Ønsker jeg å: få mer informasjon om ei enkelt verksemd
Slik at: eg veit meir om utgjevaren

Relatert til brukarhistorie: #431 Side for organisasjon

Lenke til design: (trykk videre på en virksomhet)
https://eggedosis.github.io/fdk-design/redirects/portal/report/organizations.html

Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Bør ha informasjon liknande den ein hadde i data.norge.no. Med informasjonboks. Sjå skjermbilete: https://github.com/Informasjonsforvaltning/behov/issues/431#issuecomment-604308030

Ein bør kun ta inspirasjon frå korleis det var på gamle data.norge.no.
Nokre aktuelle moment å ta med:
- Logo
- Org.nr.
- Sektor (stat, kommune eller privat?)
- URL til heimeside (kan hentast frå enhetsregisteret)
- Overordna enhet (særleg aktuelt for stat)
- Fylke (dersom det er ein kommune)
- Forretningsadresse

**Comment by livarb** [comment]
Har sjekka, og dette ser bra ut!

Foreslår 2. og 3. utførast. Foreslår å splitte ut til separat sak og lukke denne.

Nokre avvik frå beskrivelsen i saka:
1. Forretningsadresse er ikkje med. Tenker det er ok. Ein følgje lenka til enhetsregisteret for å sjå dette.
2. Overordna enhet er ikkje med. Foreslår ein tar med dette, og at det er ei lenke som fører til FDK-side for overordna enhet. Forutset at FDK-visning av overordna enhet også viser info for enheter som ikkje har innhald i FDK.
3. Fylke vert ikkje vist. Er nyttig å ha med sidan det er kommunar med same namn som ligg i forskjellige fylker: https://no.wikipedia.org/wiki/Norges_kommuner#Kommunene
Enkel fiks er å hente ut fylkesnummer ut frå kommunenr. som ligg lagra i enhetsregister-data. Gir korrekt resultat i nesten alle tilfelle.
4. Boksen som viser denne informasjonen er ikkje synleg med ein gang ein opnar ei virksomhetsside. Bør vise til brukaren i grensesnittet at innhaldet vert lasta. No poppar innhaldet fram frå intet i etter eit par sekund.

**Comment by shenluna** [comment]
@livarb Kan du lage brukerhistorier på punktene du nevner i kommentaren over slik at vi kan splitte opp og lukke denne.

**Comment by livarb** [comment]
@shenluna Har laga ny sak #624 for pkt. 2 og 4. Punkt 3 er dekka av #622
