### ISSUE TITLE
[BRUKERHISTORIE] Velge særlige kategorier av personopplysninger i henhold til artikkel 9

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#481]
Som: behandlingsansvarlig
Ønsker jeg å: kunne velge særlige kategorier av personopplysninger i henhold til artikkel 9
Slik at: det blir enkelt å angi riktig kategori

Relatert til epos: #645 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Foreslår at dette løses tilsvarende som for artikkel 6 hvor det er nedtrekksliste for valg av behandlingsgrunnlag. 
Nedtrekkslisten vil da komme i stedet for nåværende fritekstfelt som kommer fram når man klikker på "Artikkel 9 - Behandling av særlige kategorier av personopplysninger". Nedtrekkslisten skal inneholde en liste med vilkårene a-j i "Artikkel 9.Behandling av særlige kategorier av personopplysninger", ref https://lovdata.no/dokument/NL/lov/2018-06-15-38/KAPITTEL_gdpr-2#gdpr/a9  
Gitt at jeg har valgt en bokstav, med unntak av a, så skal det dukke opp ekstra fritekstfelt med overskrift “Henvisning til annen lovgivning”. 

Artikkel 9: Forslag til overskrift pr bokstav

a)            Samtykke
b)           Trygde-, arbeids- og sosialrettslige forhold
c)           Vern av noen vitale interesser
d)           Medlemsopplysninger
e)           Offentliggjorte opplysninger
f)             Rettskrav/domstolsbehandling
g)            Viktige allmenne interesser
h)           Medisinske opplysninger
i)             Allmenne folkehelseopplysninger
j)             Arkiv- og forskningsformål

**Comment by eggedosis** [comment]
@RogerSOlsen 

For å forsikre at jeg henger med, er det sånn ca her vi er?
https://www.figma.com/proto/EcV8ACVTIJaWru4q8WJLkm/Register-%E2%80%93-Protocol?node-id=312%3A26720&viewport=-4871%2C-1753%2C0.4081609845161438&scaling=min-zoom

Teksten som ønskes i dropdown er ganske massiv. Foreslår derfor en liste med radiobuttons (eller checkbox'er?) i stedet, slik at teksten/listen er bedre å lese for brukeren. Noe sånt som dette vil det i såfall kunne se ut:
https://www.figma.com/proto/7saFVKZnIpy7ywlyNBhBRu/Tr%C3%A5dskisser?node-id=85%3A2154&viewport=-15%2C424%2C0.2510606050491333&scaling=min-zoom

Videre vil det kunne komme enda et nivå med et fritekstfelt i denne listen avhengig av hva brukeren velger?

Er vi sånn omtrent på samme side? Eller er jeg heeelt ute og sykler her? =)

**Comment by RogerSOlsen** [comment]
Liste med radiobuttons virker som et bedre forslag enn nedtrekksliste, @LeneSundsbo Det skal være mulig å kunne velge flere enn en bokstav for samme behandlingsaktivitet

**Comment by oyvindis** [comment]
@RogerSOlsen  Ref. siste kommentar: "Det skal være mulig å kunne velge flere enn en bokstav for samme behandlingsaktivitet.".

Vi må bruke checkbox-er i stedet for radiobuttons.

Hvordan gjør vi med fritekstfeltet “Henvisning til annen lovgivning”? Hvis man velger flere av valgene b, g, h, i, j, skal det være et felles fritekstfelt med henvisning til lovgivning?

**Comment by RogerSOlsen** [comment]
Nåværende løsning for artikkel 9 har et fritekstfelt for artikkel 9:
![image](https://user-images.githubusercontent.com/32771488/152515200-8677791a-d3d4-4689-b0e6-68a1f6feda6d.png)
Nytt løsningsforslag i staging har avkryssingsbokser for valg av artikkel 9:
![image](https://user-images.githubusercontent.com/32771488/152515627-88b14424-7c81-464e-9727-607a3f90b68e.png)
Har vi noen mulighet for overføring av allerede registrert fritekst til de nye forvalgene slik at informasjon som er lagret i de gamle fritekstfeltene blir automatisk overført til de nye avkryssingsboksene? Dersom svaret er nei på dette, må vi fortsatt vise  det gamle fritekstfeltet, i tillegg til de nye avkryssingsboksene. Dette forutsetter sannsynligvis at veiledende tekst blir oppdatert slik at nye og gamle brukere forstår hvorfor vi både har fritekstfelt og avkryssingsbokser/strukturerte valg i løsningen. Vi kan ikke gå i produksjon med løsningen slik den er nå i staging før vi har funnet en løsning som sikrer at tekst som er registrert i fritekst som nå er i produksjon fortsatt kan bli vist og endret. @oyvindis @LeneSundsbo @shenluna

**Comment by oyvindis** [comment]
Nei, vi kan ikke overføre fra fritekstfeltet automatisk til avkryssing, den mappingen klarer vi ikke å gjøre automatisk for brukeren.

Hvis fritekstfeltet er fylt ut så vises den til sist etter alle avkryssningsfeltene. Men vi skjuler feltet på de aktivitetene der den ikke allerede er fylt ut. @shenluna tester også dette tilfellet i staging.

**Comment by RogerSOlsen** [comment]
> Nei, vi kan ikke overføre fra fritekstfeltet automatisk til avkryssing, den mappingen klarer vi ikke å gjøre automatisk for brukeren.
> 
> Hvis fritekstfeltet er fylt ut så vises den til sist etter alle avkryssningsfeltene. Men vi skjuler feltet på de aktivitetene der den ikke allerede er fylt ut. @shenluna tester også dette tilfellet i staging.

OK. Flott at dere har tenkt på hvordan gamle fritekstfelt skal fylles ut. Jeg så ikke at det var forskjell på gammel og ny behandlingsaktivitet for dette feltet. Jeg ber om at det gamle feltet flyttes til toppen, slik at man ser det med en gang i artikkel 9 i gammel behandlingsaktivitet. Nå vises det langt nede på siden, og er ikke så lett å få øye på umiddelbart. 
Ser for meg noe som er omtrent slik:
![image](https://user-images.githubusercontent.com/32771488/152533455-96c4dbe6-d187-4950-b518-bfbd3656b4ba.png)

**Comment by RogerSOlsen** [comment]
Det er mulig å registrere i registreringsfeltene fra b og nedover uten å klikke i boksene. Kan vi få til en løsning hvor man må klikke av for å kunne skrive inn henvisning til annen lovgiving? Jeg tror det vil gjøre det mer oversiktlig. Her er eksempel uten avkryssing:
![image](https://user-images.githubusercontent.com/32771488/152534930-a5643dc8-b3c0-46e7-9fae-739d6fe12bf1.png)
Samme eksempel med avkryssing:
![image](https://user-images.githubusercontent.com/32771488/152535061-a32d648b-84bb-468e-b1cc-659b4d156492.png)

**Comment by shenluna** [comment]
@RogerSOlsen Det er allerede implementert, se staging nå :)

**Comment by shenluna** [comment]
Her er et eksempel hvor gammel tekstboks er flyttet opp
![image](https://user-images.githubusercontent.com/73637969/152535880-bce57a9b-fcfe-41bb-8bbc-f111636cd573.png)

I tillegg har vil lagt til ja/nei valg for artikkel 10. Slik at den blir lik artikkel 9.
