### ISSUE TITLE
[BRUKERHISTORIE] bolk for Risikovurdering og sikkerhet

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#482]
Som: forvalter av behandlingsaktivitet
Ønsker jeg å: få god oversikt over tekniske og organisatoriske sikkerhetstiltak
Slik at: det blir enkelt å se tema som omhandler sikkerhet i sammenheng ved registrering av sikkerhetstiltak

Relatert til epos:

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/github482.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Bolken skal kalles "Sikkerhetstiltak og DPIA" og skal inneholde disse feltene som nå ligger i bolk "Personopplysninger":

- "Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak"
- "Er det gjennomført risikovurdering?"

Bolken skal komme etter bolk "Overføring av personopplysningene" og før ny bolk "Kategorier av mottakere". 

Akseptansekriterier:
- Egen bolk for sikkerhetstiltak og DPIA skal være opprettet
- Felt for "generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak" skal være flyttet til ny bolk
- Felt for "er det gjennomført risikovurdering" skal flyttes til ny bolk OG endres tittel
- Hvis bruker svarer "Ja" her skal det dukke opp nytt fritekstfelt der bruker skal kunne fylle ut arkivreferanse/lenke
- Felt for "Kan behandlingen innebære høy personvernrisiko?" skal slettes fra løsningen

OBS: må sees i sammenheng med issue "Endre overskrifter i “Er det gjennomført risikovurdering?” #3168" og issue "Slette "Kan behandlingen innebære høy personvernrisiko?" #3169"

**Comment by lillelars** [comment]
@RogerSOlsen  NB! For denne må vi også huske og oppdatere rapportsiden

**Comment by RogerSOlsen** [comment]
OK. Er det noe jeg må gjøre i forbindelse med oppdatering ?

tir. 1. sep. 2020 kl. 14:32 skrev Lars M Riiser Haraldsen <
notifications@github.com>:

**Comment by lillelars** [comment]
@RogerSOlsen da er denne klar til akseptanse.

**Comment by RogerSOlsen** [comment]
@lillelars jeg har testet for skrivebruker. Resultat OK. Felt for "er det gjennomført risikovurdering" tittel er flyttet og har fått nytt navn "Er det gjennomført vurdering av personvernkonsekvenser (DPIA)?". 
Jeg venter på at det blir mulig å teste også for lesebruker og gjennomfører ny test da. Venter derfor med å overføre brukerhistorie til Utført.

**Comment by RogerSOlsen** [comment]
Test av brukerhistorien: oppsummert: endringene er levert og brukerhistorien lukkes. 

Grunnlag for testing (kursiv) og kommentar og resultat fra testing:

_Bolken skal kalles "Sikkerhetstiltak og DPIA" og skal inneholde disse feltene som nå ligger i bolk "Personopplysninger":
•	"Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak"
•	"Er det gjennomført risikovurdering?"
Bolken skal komme etter bolk "Overføring av personopplysningene" og før ny bolk "Kategorier av mottakere"._
**Kommentar:** bolken «Sikkerhetstiltak og DPIA» kommer nå etter bolk «Overføring av personopplysningene». Vi har valgt å opprette felt for «Mottakere eller kategori av mottakere» i bolk «Overføring av personopplysningene» i stedet for å opprette egen bolk for «Kategorier av mottakere». 

Bilde fra skrivebruker:
![image](https://user-images.githubusercontent.com/32771488/96104591-4ef05f00-0ed9-11eb-8b58-af20c03873e0.png)

Bilde fra lesebruker:
![image](https://user-images.githubusercontent.com/32771488/96105914-df7b6f00-0eda-11eb-9460-6231bb61f535.png)


_Akseptansekriterier:
Egen bolk for sikkerhetstiltak og DPIA skal være opprettet_
**Test**: det finnes egen bolk for "Sikkerhetstiltak og DPIA" i lesebruker og skrivebruker. Se bilder av skrivebruker og lesebruker ovenfor her. 

_Felt for "generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak" skal være flyttet til ny bolk_
**Test**: det finnes felt for "Generell beskrivelse av tekniske og organisatoriske sikkerhetstiltak" i lesebruker og skrivebruker. Se bilder av skrivebruker og lesevises ovenfor her. 

_Felt for "er det gjennomført risikovurdering" skal flyttes til ny bolk OG endres tittel_
**Test**: I følge issue https://github.com/Informasjonsforvaltning/fdk/issues/3168 skulle overskrift "Er det gjennomført risikovurdering" endres til "Er det gjennomført personvernkonsekvensvurdering (DPIA)?" i bolk Personopplysninger. 
Denne overskriften er i stedet endret til «Er det gjennomført vurdering av personvernkonsekvenser (DPIA)?» og lagt til bolk «Sikkerhetstiltak og DPIA». Se bilder av skrivebruker og lesebruker ovenfor her. 

I tillegg skulle det i følge issue https://github.com/Informasjonsforvaltning/fdk/issues/3168  endres tittel på registreringsfeltet “Lenke til risikovurdering” til “"Sak-/arkivreferanse eller lenke til personvernkonsekvensvurdering (DPIA)". Lenken er i stedet gitt navn «Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)» og lagt til bolk «Sikkerhetstiltak og DPIA». SSe bilder av skrivebruker og lesebruker ovenfor her. 

I issue https://github.com/Informasjonsforvaltning/fdk/issues/3169 fremgår det at tema "Kan behandlingen innebære høy personvernrisiko?" i bolk «Personopplysninger» skal slettes. Dette må sees i sammenheng med denne brukerhistorien. Endringen er utført i lese- og skrivebruker. Bilde fra skrivebruker:
![image](https://user-images.githubusercontent.com/32771488/96104859-9f67bc80-0ed9-11eb-912d-178f76c437e5.png)
Bilde fra lesebruker:
![image](https://user-images.githubusercontent.com/32771488/96106244-46992380-0edb-11eb-9d17-db56ed080aa8.png)


_Hvis bruker svarer "Ja" her skal det dukke opp nytt fritekstfelt der bruker skal kunne fylle ut arkivreferanse/lenke_
**Test**: «ja» viser i brukerhistorien til «er det gjennomført risikovurdering» som senere er endret til «Er det gjennomført vurdering av personvernkonsekvenser (DPIA)», ref https://github.com/Informasjonsforvaltning/fdk/issues/3168. Her kan man nå klikke på valg Ja eller Nei. Velger man Nei markeres radioknapp. Velger man Ja markeres radioknapp og registreringsfelt «Sak-/arkivreferanse eller lenke til vurdering av personvernkonsekvenser (DPIA)» vises. Se nederst i øverste skjermdumper for skrivebruker og lesebruker. . 

_Felt for «Kan behandlingen innebære høy personvernrisiko?» skal slettes fra løsningen_
**Test**: Dette feltet lå tidligere i bolk "Personopplysninger", men er nå slettet. Se skjermbilder for lese- og skrivebruker av bolk Personopplysninger
