### ISSUE TITLE
[BRUKERHISTORIE] bolk for Kategorier av mottakere

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#484]
Som: virksomhet som skal dokumentere behandlingsaktivitet
Ønsker jeg å: ha en ny bolk i tillegg til de eksisterende bolker som skal hete "Kategorier av mottakere", og som inneholder to obligatoriske felter: Kategorier av mottakere (felt 1). Neste felt er også obligatorisk men kan løses som et spørsmål: Er mottakerne tredjeland eller internasjonale organisasjoner?". Hvis JA skal et nytt obligatorisk "conditional" felt dukke opp: "Oppgi hvilke kategorier av mottakere i tredjeland eller internasjonale organisasjoner
Slik at: jeg får fram hvilke temaer som er viktig etter artikkel 30. 

Relatert til epos:

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/protocol/github484.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk (dette er et obligatorisk felt ihht artikkel 30)

Bolken skal komme etter ny bolk "Risikovurdering og sikkerhet" (se brukerhistorie #482 )

Se lignende løsning for "Overføres personopplysningene til tredjeland?"

**Comment by eggedosis** [comment]
Noen spørsmål @marittor

Felt 1) Skal dette feltet være inputfelt med fritekst som lager tags for hver kategori? Hver kategori vil da se ut som en egen tag, ikke bare en string. Vi har løst det slik for andre kategorifelt.

Felt 2) Skal kategoriene her begrenses til de kategoriene som er oppgitt i felt 1, eller kan man fritt skrive inn kategorier?

**Comment by marittor** [comment]
@eggedosis, har du sjekket med @RogerSOlsen  og Oddhild hva de tenker her? Jeg er redd jeg ikke kjenner til status/beslutning her .

**Comment by eggedosis** [comment]
@marittor Nå har vi kontroll =)

**Comment by lillelars** [comment]
@RogerSOlsen Dette behovet endret seg til "kategorier av registrerte" og "Kategorier av personopplysninger tilknyttet den registrerte" - stemmer ikke det?

I så fall er denne klar til akseptanse den og.

**Comment by RogerSOlsen** [comment]
erstattes av #522
