### ISSUE TITLE
[EPOS] Høsting av modeller som er konforme med ModellDCAT-AP-NO til FDK

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#489]
Som: modellansvarlig i en virksomhet
Ønsker jeg at: Felles datakatalog skal kunne høste min virksomhets modeller som er konforme med ModellDCAT-AP-NO versjon 1.1
Slik at: disse kan vises i portalløsningen til Felles datakatalog

ModellDCAT-AP-NO-spesifikasjonen (høringsutkast): https://informasjonsforvaltning.github.io/modelldcat-ap-no/

OWL-fil: https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/dcatno_informationModel_en.owl

Tilknyttede brukerhistorier: #504      

Modeller for testing: https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl
 
https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/modelldcatno_Test2FlereEksempler.ttl

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by RogerSOlsen** [comment]
Er løst i henhold til ModellDCAT-AP-NO
