### ISSUE TITLE
[BRUKERHISTORIE] Høsting av modeller som er konforme med ModellDCAT-AP-NO til Felles datakatalog

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#504]
Som: modellansvarlig i en virksomhet
Ønsker jeg at: Felles datakatalog skal fra et endepunkt kunne høste min virksomhets modellkatalog som er konforme med ModellDCAT-AP-NO
Slik at: disse kan presenteres i portalløsningen til Felles datakatalog

Skal kunne høste på følgende format: RDF og alle relevante serialiseringer (turtle, json-ld, rdf/xml etc)
ModellDCAT-AP-NO-spesifikasjonen (høringsutkast): https://informasjonsforvaltning.github.io/modelldcat-ap-no/

OWL: https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/dcatno_informationModel_en.owl

Akseptansekriterier:
- Vi skal høste alt fra modelleksempelet og kunne verifisere det med postman/curl eller liknande

Relatert til epos: #489 
Modell for testing: https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl

Lenke til design: 
Lenke til løsningsarkitektur: løses ved å implementere støtte for ny versjon av spesifikasjon i eksisterende høster: https://github.com/Informasjonsforvaltning/fdk-informationmodel-harvester

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by RogerSOlsen** [comment]
Er løst i forhold til ModellDCAT-AP-NO
