### ISSUE TITLE
[BRUKERHISTORIE] Visning av modeller konforme med ModellDCAT-AP-NO

### ISSUE THREAD

**Issue by ToHelland** [Informasjonsforvaltning/behov#506]
Som: modellkonsument
Ønsker jeg at: portalløsningen i Felles datakatalog skal kunne presentere informasjonsmodeller og metadata om disse som er konforme med ModellDCAT-AP-NO
Slik at: jeg kan få kunnskap om disse

Relatert til epos: #505 

ModellDCAT-AP-NO-spesifikasjonen (høringsutkast): https://informasjonsforvaltning.github.io/modelldcat-ap-no/

OWL-fil: https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/dcatno_informationModel_en.owl
Tilknyttede brukerhistorier: #506, #512, #513, #497

Lenke til trådskisser: https://www.figma.com/proto/nrqaa1JB8pY6pBvUBxp1EV/Detail-infomodel?node-id=979%3A1772&viewport=-269%2C285%2C0.06454936414957047&scaling=min-zoom

Trådskisser med enkelteksempler: https://www.figma.com/proto/nrqaa1JB8pY6pBvUBxp1EV/Detail-infomodel?node-id=1012%3A2547&viewport=569%2C244%2C0.27625539898872375&scaling=min-zoom Her finnes eksempler på ulike typer egenskaper. Disse korresponderer med testmodellene med enkelteksemplene. Se også beskrivelse av eksemplene [her](https://teams.microsoft.com/l/file/AD9EE0E3-DBBC-4F1E-84CF-D520F4B796CE?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=docx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1%2FDelte%20dokumenter%2FModellkatalog%2FBeskrivelse%20av%20eksempler%20i%20tr%C3%A5dskisser.docx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FInformasjonsforvaltning-rammeverkS.T.4.1&serviceName=teams&threadId=19:1d63088cc0e1451cb991a9ccd9d8ada6@thread.skype&groupId=937040ec-fca4-412c-97ff-28d0f60c75a3).

Modell for testing:
https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl

https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/modelldcatno_Test2FlereEksempler.ttl (inneholder en del enkelteksempler)

Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by RogerSOlsen** [comment]
Lukket i Rydding av behovsboard 02.03.2022
