### ISSUE TITLE
[BRUKERHISTORIE] Deaktivere redigering av katalog for brukere av "Felles brukerhåndtering" for en virksomhet

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#510]
Som: forvalter av datasett, api, begrep m.m. (virksomhet)
Ønsker jeg å: hindre at ansatte i min virksomhet kan gjøre endringer i virksomhetens oppføringer i Felles datakatalog når de logger seg på med "Felles brukerhåndtering"
Slik at: jeg beholder kontrollen over hvem som har rettigheter til å redigere virksomhetenes innhold i Felles datakatalog

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig [BR]

Bakgrunn:
Brønnøysundregistrenes rammeverk for informasjonsforvaltning har ulike roller knyttet til forvaltning av beskrivelser av datasett, API, begrep etc, og tildeler rettigheter iht rammeverket. Gjennom "Felles brukerhåndtering" kan alle i organisasjonen få redigeringstilgang. Vi ønsker mulighet til å kunne deaktivere redigeringstilgang for vår organisasjon for brukere som logger på med "Felles brukerhåndtering".

**Comment by joebrreg** [comment]
@sskagemo Defaultsetting for innlogging med Felles brukerhåndtering er lesetilgang. Skal en bruker ha skrivertilgang, må det sendes en henvendelse til FDK.

**Comment by sskagemo** [comment]
Takk skal du ha @joebrreg ! Burde testet det så hadde jeg skjønt det :-) Tenkte det var motsatt siden det stod at Felles brukerhåndtering var "For deg som tidligere brukte registreringsløsningen på data.norge.no". Infosiden om registrering tydet heller ikke på at man ikke fikk redigeringsbruker: https://data.norge.no/about-registration 

Lukker saken.
