### ISSUE TITLE
[EPOS] Registreringsportal

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#514]
Som bruker av registreringsløsningene til data.norge.no
Ønsker jeg å enkelt finne og forstå hva som skal til for å registrere seg og logge seg på registreringsløsningen
Slik at jeg får publisert mine dataset/dataservices/begreper i data.norge.no

Tilknyttede brukerhistorier:
#515 
#516 
#517 

Lenke til trådskisser: 
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Lukker denne basert på at alle brukerhistorier tilknyttet er levert.
