### ISSUE TITLE
[BRUKERHISTORIE] Publiserer datasett med det samme

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#52]
Som: datasetteier
Ønsker jeg å: kunne se mine registreringer i portal umiddelbart etter de er publisert
Slik at: de kan verifiseres

Relatert til epos: #36 

Lenke til design: N/A
Lenke til løsningsarkitektur: det skal løysast på same måte som i api-registrering.

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Publisere nytt datasett
⦁	Avpublisere datasett
⦁	Endre innhold i et datasett

Dekkes ikke:

Referanser:

Scenario: Publisere nytt datasett
Gitt at bruker er pålogget registreringsløsningen for en gitt virksomhet
Når bruker har opprettet et nytt datasett
og trykker knappen "Publiser"
Så skal det nye datasettet kunne søkes fram i søkeportalen
og registrerte data skal vises på detaljsiden

Scenario: Avpublisere datasett
Gitt at bruker er pålogget registreringsløsningen for en gitt virksomhet
Nå trykker knappen "Avpubliser" for et gitt datasett
Så skal  datasettet ikke kunne søkes fram i søkeportalen

Scenario: Endre innhold i et datasett
Gitt at bruker er pålogget registreringsløsningen for en gitt virksomhet
Når bruker har endre verdier i et fel for et gitt datasett
Så skal de nye verdiene vises på detaljsiden i søkeportalen for gitt datasett

**Comment by sskagemo** [comment]
Inkluderer historien mulighet for tilsvarende umiddelbar "avpublisering", dersom den som har publisert datasettbeskrivelsen finner feil/angrer på publiseringen?

**Comment by joebrreg** [comment]
Ja. Det er slikt det fungerer for api-beskrivelser.

**Comment by lillelars** [comment]
@stigbd trenger vi løsningsarkitektur her?
design: N/A

**Comment by stigbd** [comment]
Eg tenker at dersom det skal fungere akkurat som i api-beskrivelser, slik Joachim seier over, så trengs ikkje løsningsarkitektur. Då trenger vi berre presisere at det skal løysast på same måte som i api-registrering.
