### ISSUE TITLE
[BRUKERHISTORIE] mulighet for å etterspørre det jeg ikke finner i katalogene

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#521]
Som:  konsument av data.norge.no 
Ønsker jeg å: ønsker jeg en å  måte å kommunisere at jeg ikke finner det jeg leter etter (datasett, datatjenester, begreper, modeller) når jeg søker 
Slik at: slik at det jeg leter etter bli publisert i data.norge.no etter hvert.

#### Akseptansekriterier:

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Regner denne som løst. Vi har i dag en egen kanal for etterspørsler i datalandsbyen, som er integrert med oversikt over etterspørsler. Restanser er beskrevet i https://github.com/Informasjonsforvaltning/behov/issues/864
