### ISSUE TITLE
[BRUKERHISTORIE] DCAT-AP-NO validator

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#530]
Som: konsument av et DCAT-AP-NO høste-endepunkt
Ønsker jeg å: validere at det jeg får ut av endepunktet er gyldig ihht DCAT-AP-NO
Slik at: jeg kan stole på at datakvaliteten er god.

Relatert til epos:

Lenke til design:
https://eggedosis.github.io/fdk-design/redirects/register/portal/validator-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by jimjyang** [comment]
I validatorens GUI, ønsker jeg at det skal kunne vises, i det språket som brukeren har valgt for GUI (f.eks. norsk bokmål eller engelsk), bl.a. følgende: 
1. navn på shape/klasse/egenskap (sh:name). 
2. resultatmelding (sh:message).
