### ISSUE TITLE
[BRUKERHISTORIE] Maskinell bruk av bibliotek for å lage høsteendepunkt for begrep

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/behov#532]
Som: ekstern virksomhet
Ønsker jeg å: kunne ta i bruk digdir sine biblioteker for å lage en begrepskatalog ihht skos-ap-no-begrep fra mine applikasjoner, på tvers av programmeringsspråk
Slik at: jeg kan enkelt eksponere et endepunkt som kan høstes inn i Felles datakatalog

Relatert til epos:

Lenke til design: n/a
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by Te-Bert** [comment]
Løst. Men det må opprettes nye issues når det skjer endringer i standardene (innhold)
