### ISSUE TITLE
[BRUKERHISTORIE]  Navigere fra en tjeneste til et API

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#536]
Som: konsument av en tjeneste
Ønsker jeg å: se hvilke API-er som er input (evidence) og output til en tjeneste og navigere til disse
Slik at: jeg kan se hvilke data som inngår i en tjeneste

Relatert til epos: 
* #705

Relatert til brukerhistorie:
* #100 
* #101  

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterie:

Relasjonen skal finnes begge veier

**Comment by KurtStian** [comment]
Per i dag er denne koblingen ikke implementert i CPSV-profilen.

**Comment by lillelars** [comment]
@KurtStian skal det skje noe mer med denne relasjonen? Per i dag finnes det vel fortsatt ikke i CPSV-profilen? Vi avventer til vi hører noe mer her

**Comment by KurtStian** [comment]
Ja, vi ønsker relasjon til API. Her har vel @stigbd  klare tanker på hvordan dette skal/kan løses, jf. flere diskusjoner.

**Comment by KurtStian** [comment]
Avventer behovet da det ikke finnes støtte for dette i cpsv-ap-no. Det kan være aktuelt å se nærmere på behovet hvis det skulle bli etterspurt fra konkrete miljø.

**Comment by KjerstiSteien** [comment]
@KurtStian @BRespen kan vi lukke denne, og heller opprette ny sak dersom noen utenfra spiller det inn som behov?

**Comment by KurtStian** [comment]
@KjerstiSteien @BRespen  Ja, jeg tenker at denne kan lukkes da spesifiksjonen ikke støtter dette behovet. 
Lukker saken.
