### ISSUE TITLE
[BRUKERHISTORIE] Tune søket

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#54]
Som: forretningsutvikler
Ønsker jeg å: søke i FDK
Slik at: jeg får relevante treff

Relatert til epos: #36 

Lenke til design: 
Lenke til løsningsarkitektur: N/A

https://docs.google.com/document/d/1YOE31vqQsBWL-Res70D6hFxtDth3BaAyuXlQBOGgXF0/edit#heading=h.knjgp8rlu40d

Akseptansekriterier: 
1. Søk skal gi resultater i henhold til forventninger beskrevet i dokumentet "Søk og kvalitet på søk" (se ovenfor)
2. Søket skal gi resultater i henhold til ønsket vektlegging spesifisert her:  
https://drive.google.com/file/d/1Ck6grw3iZALnhR0DtD9i8a0k2bKd23VP/view?usp=sharing
https://drive.google.com/file/d/1gbbza9Vw4VKPyzDul8G8c08uLpQPTWAy/view?usp=sharing
3. Løsningen aksepteres når uttesting av søkefunksjonen er gjennomført og godkjent av produkteier.

**Comment by lillelars** [comment]
@sindresandvik2 @joebrreg her trenger vi akseptansekriterier bestemt ut fra lenken i beskrivelsen.

design: N/A
løsningsarkitektur: N/A

**Comment by RogerSOlsen** [comment]
Lukket i møte Rydding av behovsboard 02.03.2022
