### ISSUE TITLE
[BRUKERHISTORIE] kunne beskrive behov for data

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#552]
Som: utvikler
Ønsker jeg å: kunne presentere et use case i portalen
Slik at: jeg kan få tilbakemelding på hva slags data jeg trenger

Kommentar: 
Ref spørsmål 19 under Open data portal, 3.1 Portal features som ble brukt som grunnlag for Open Data Maturity Report 2020: "Does the national portal provide the possibility for users to submit their own use cases? "

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
@RogerSOlsen @livarb @oystein-asnes Vil dere si at dette behovet er tilstrekkelig dekket gjennom datalandsbyen og etterspørselsiden?

**Comment by livarb** [comment]
Eg tenker det er ivaretatt gjennom Datalandsbyen.
