### ISSUE TITLE
[BRUKERHISTORIE] presentere use cases

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#557]
Som forvalter av data.norge.no
Ønsker jeg å kunne presentere brukssaker (use cases) 
Slik at jeg kan vise hvilke muligheter og hvilken verdi deling av data kan gi

Forretningsverdi:
Viktig

Kommentar:
Ref spørsmål 18 under Open data portal, 3.1 Portal features som ble brukt som grunnlag for Open Data Maturity Report 2020: 
"Does the national portal have a designated area to showcase use cases? "

Relatert til epos: #569 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette vil være mulig å gjøre i brukerforumet Datalandsbyen
