### ISSUE TITLE
[BRUKERHISTORIE] Område for show cases på data.norge

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#560]
Som: besøkende på nettsiden til data.norge  
Ønsker jeg å: se hva FDKs tjenester blir brukt til
Slik at: jeg kan forstå produktet og vurdere å ta det i bruk

Relatert til epos: #569 

Lenke til design: 
Lenke til løsningsarkitektur:
Sverige har et eget community-område på nettsidene deres: https://community.dataportal.se/ 
Irland har show cases på forsiden: https://data.gov.ie/ 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk - høyt prioritert til neste måling.

**Comment by lillelars** [comment]
@ChristianeFrhlich mener man her "Visning av bruk av dataene i Felles datakatalog" eller "visning av funksjonalitet og muligheter ved _bruk_ av Felles datakatalog"? 

Trenger litt mer detaljer rundt hva "produkt" er her og noen detaljer/eksempler

**Comment by lillelars** [comment]
Kan det knyttes til denne:
https://github.com/Informasjonsforvaltning/behov/issues/100 ?

**Comment by ChristianeFrhlich** [comment]
Hei, Lars.

Jeg tror historien kan knyttes til dette med Community.
Beklager for at brukerhistorien jeg lagde er uklar. Er ikke så dreven i det


Vennlig hilsen

Christiane Andrea Fröhlich
førstekonsulent

Mob: +47 908 27 835
Grev Wedels Plass 9, 0151 Oslo, NO

Digitaliseringsdirektoratet
Postboks 1382 Vika, 0114 Oslo, NO
-
www.digdir.no<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digdir.no%2F&data=02%7C01%7C%7C717097a616294d0f12fa08d8379c76d1%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637320492441409664&sdata=IFZvryCfq6Rcdl5aiBjIw3omMwjJqSHLYKZNCR7a5P0%3D&reserved=0>

***@***.***D71BD3.85AAED60]

Fra: Lars M Riiser Haraldsen ***@***.***>
Sendt: onsdag 17. mars 2021 14:20
Til: Informasjonsforvaltning/behov ***@***.***>
Kopi: Fröhlich, Christiane Andrea ***@***.***>; Mention ***@***.***>
Emne: Re: [Informasjonsforvaltning/behov] [BRUKERHISTORIE] Område for show cases på data.norge (#560)


Kan det knyttes til denne:
#100<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FInformasjonsforvaltning%2Fbehov%2Fissues%2F100&data=04%7C01%7C%7C2b56cb0a92c8434e9e2708d8e9476920%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637515840226304594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XEo0KcDxfNCcwYJXSeq0A2KDsxPROfFodxhLaJgJ9RQ%3D&reserved=0> ?

-

**Comment by ChristianeFrhlich** [comment]
Jeg mener visning av funksjonalitet og muligheter. Ved produkt mener jeg FDKs tjenester og kataloger.


Vennlig hilsen

Christiane Andrea Fröhlich
førstekonsulent

Mob: +47 908 27 835
Grev Wedels Plass 9, 0151 Oslo, NO

Digitaliseringsdirektoratet
Postboks 1382 Vika, 0114 Oslo, NO
-
www.digdir.no<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digdir.no%2F&data=02%7C01%7C%7C717097a616294d0f12fa08d8379c76d1%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637320492441409664&sdata=IFZvryCfq6Rcdl5aiBjIw3omMwjJqSHLYKZNCR7a5P0%3D&reserved=0>

***@***.***D71BD3.DEAD0790]

Fra: Lars M Riiser Haraldsen ***@***.***>
Sendt: onsdag 17. mars 2021 14:15
Til: Informasjonsforvaltning/behov ***@***.***>
Kopi: Fröhlich, Christiane Andrea ***@***.***>; Mention ***@***.***>
Emne: Re: [Informasjonsforvaltning/behov] [BRUKERHISTORIE] Område for show cases på data.norge (#560)


@ChristianeFrhlich<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChristianeFrhlich&data=04%7C01%7C%7Ccea726825f894a1abb4008d8e946a6bb%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637515836940324932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8ghEqWzFtTJcYFyF46BlAaFZvrC8smvzI9r4gGHFLgU%3D&reserved=0> mener man her "Visning av bruk av dataene i Felles datakatalog" eller "visning av funksjonalitet og muligheter ved bruk av Felles datakatalog"?

Trenger litt mer detaljer rundt hva "produkt" er her og noen detaljer/eksempler

-

**Comment by shenluna** [comment]
Dette blir løst med Datalandsbyen
