### ISSUE TITLE
[BRUKERHISTORIE] lagre innhold i rapport til regnearkformat

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#561]
Som: virksomhet
Ønsker jeg å: enkelt kunne lagre rapport til et regnearkformat
Slik at: det blir enkelt å kunne overføre rapportens innhold maskinelt til andre systemer, samt gjøre analyse og generere statistikk 
på bakgrunn av innholdet i rapporten

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Dette er et behov blant annet Mattilsynet har uttrykt.

**Comment by perbratterud** [comment]
Heisann @RogerSOlsen . 

Mattilsynet har tatt i bruk Behandlingsaktivitet som internt verktøy for å få styr på våre GDPR forpliktelser. Løsningen er utmerket. Vi har godt over 100 registreringer gjort av et stort antall ansvarlige i organisasjonen.

Men vi har altså meldt inn behov for å kunne få bedre oversikt over innholdet i alle våre registrerte behandlinger. Ledelsen i etaten trenger en grei måte å kunne se i hvilken grad registreringene er komplette og holder den kvaliteten vi trenger.

Løsningen har i dag en utmerket PDF-rapport. Grunnlaget for PDF-rapporten er strukturerte data i løsningen. Vi vil gjerne ha ut de strukturerte dataene for enkel analyse i regneark. Det kan ikke være vanskelig selv om det vel er noen felter som vil være sammensatt av flere "svar"?
(Og PDF-rapporten egner seg heller ikke veldig godt til skraping av data ;-))

Siden dette ønsket fortsatt ikke har gått noe lenger i prioriteringsprosessen ønsker vi svar på noen spørsmål:

1. Har andre etater tatt i bruk Behandlinger i samme skala som Mattilsynet (>100 registreringer)
2. Har andre etater nevnt behov for tilgang til strukturerte data rapport?
3. Har det blitt gjort et overslag på hvor vanskelig (kostbart) det vil være å lage en slik eksport av strukturerte data - rapport?

**Comment by RogerSOlsen** [comment]
> Heisann @RogerSOlsen .
> 
> Mattilsynet har tatt i bruk Behandlingsaktivitet som internt verktøy for å få styr på våre GDPR forpliktelser. Løsningen er utmerket. Vi har godt over 100 registreringer gjort av et stort antall ansvarlige i organisasjonen.
> 
> Men vi har altså meldt inn behov for å kunne få bedre oversikt over innholdet i alle våre registrerte behandlinger. Ledelsen i etaten trenger en grei måte å kunne se i hvilken grad registreringene er komplette og holder den kvaliteten vi trenger.
> 
> Løsningen har i dag en utmerket PDF-rapport. Grunnlaget for PDF-rapporten er strukturerte data i løsningen. Vi vil gjerne ha ut de strukturerte dataene for enkel analyse i regneark. Det kan ikke være vanskelig selv om det vel er noen felter som vil være sammensatt av flere "svar"?
> (Og PDF-rapporten egner seg heller ikke veldig godt til skraping av data ;-))
> 
> Siden dette ønsket fortsatt ikke har gått noe lenger i prioriteringsprosessen ønsker vi svar på noen spørsmål:
> 
> 1. Har andre etater tatt i bruk Behandlinger i samme skala som Mattilsynet (>100 registreringer)
> 2. Har andre etater nevnt behov for tilgang til strukturerte data rapport?
> 3. Har det blitt gjort et overslag på hvor vanskelig (kostbart) det vil være å lage en slik eksport av strukturerte data - rapport?

Angående punkt 1:
Nei, ingen andre har tatt i bruk løsningen i samme skala som Mattilsynet. 
Angående punkt 2: 
Under brukertest har andre etater meldt ønske om å kunne ta ut rapport til bruk i excel eller maskinlesbart format slik at det er mulig å gjenbruke data i andre systemer. 
Angående punkt 3:
Vi har som mål å få til løsning hvor vi kan eksportere rapporter fra Behandlingsoversikt til CSV-format i løpet av juni, eventuelt august (2021).

**Comment by perbratterud** [comment]
Takk for rask respons. Juni er en god ambisjon.

Jeg har forslag om en berikning av rapportdataene når de skal bli levert digitalt: 
- at det legges til et felt med komplett endringshistorikk i form av dato(/tid) for innlogget sesjon med endring og navn/initialer på den som utførte endring i den enkelte protokoll. 
- Det er ikke nødvendig med identifisering av hvilke endringer som har blitt utført ala googledocs.

**Comment by RogerSOlsen** [comment]
Generering  av CSV-filer  er godkjent etter sammenligning mellom innhold i registreringer og filer. 
Det er mulig å generere CSV-fil av alt innhold i virksomhetens behandlingsoversikt (tilsvarer innhold i html-rapport "Behandlingsoversikt") og CSV-fil av innhold knyttet til protokoll-kravene (tilsvarer innhold i html-rapport "Protokoll".  I begge CSV-filer vises i tillegg virksomhetens organisasjonsnummer
