### ISSUE TITLE
[En fane/ side/ lenke til verktøykassa på FDKs nettside]

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#576]
Som: Bruker av Felles datakatalog
Ønsker jeg å: finne tilgjengelig veiledning om FDK i Nasjonal verktøykasse for deling av data.
Slik at: jeg enklere kan finne ut på hvilken måte FDK kan legge til rette for deling av data. 

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): viktig

**Comment by stigbd** [comment]
Dette er veldig bra. Samtidig bør vi harmonisere språket i verktøykassa og på data.norge.no.

Feks heiter det
"Finne og vurdere data" (https://www.digdir.no/apne-data/finne-og-vurdere-data/2256), mens på data.norge.no heiter det "oppdage, vurdere". (data.norge.no)
Og det er sikkert fleire stader vi treng å harmonisere.

**Comment by KjerstiSteien** [comment]
Lukker denne, da vi må se informasjonen om datadeling helhetlig på tvers av alle kanaler. Dette vil inngå som et mulig valg i det arbeidet.
