### ISSUE TITLE
[Brukerhistorie: Informasjon og rettighetsside for forumsbrukere] 

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#581]
Som: Registrert i Community/ brukerforum
Ønsker jeg å: få informasjon om mine rettigheter knyttet til GDPR
Slik at: jeg enklere kan be om innsyn/ kreve kopi/ kreve sletting av mine personopplysninger

Relatert til epos: [EPOS] Brukerforum #569 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): kritisk

**Comment by ChristianeFrhlich** [comment]
I Sveriges community er det lag til rette for at den registrerte kan få vite hvilke personopplysninger som behandles. Dette er grunnleggende rettigheter i personvernlovgivningen. Brukeren skal få informasjon om retten til dataportabilitet, kopi, innsyn, retting av feilaktige personopplysninger og sletting. Denne informasjonen burde være tilgjengelig for brukeren.

**Comment by shenluna** [comment]
Dette vises under "Samtykke og vilkår" for innloggede brukere i Datalandsbyen
