### ISSUE TITLE
[BRUKERHISTORIE] Kommunisere med andre datakonsumenter 

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#583]
Som: datakonsument
Ønsker jeg å: kommunisere med andre datakonsumenter som bruker samme datasett eller API
Slik at: jeg enklere kan ta datasett eller API i bruk 

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette vil være mulig med nettforumet Datalandsbyen
