### ISSUE TITLE
[BRUKERHISTORIE] Registrere på flere språk

### ISSUE THREAD

**Issue by joebrreg** [Informasjonsforvaltning/behov#59]
Som: dataeier
Ønsker jeg å: kunne registrere en datasettbeskrivele (++) på flere språk
Slik at: en datasettbeskrivelse kan vises på ulike språk

Relatert til epos: #36 

Lenke til design: 
Lenke til løsningsarkitektur:

Spørsmål fra SVV:
tospråklighet – norsk og engelsk?

Svar fra BRREG:
Portalen støtter flerspråklighet i brukergrensesnittet (i dag bokmål, nynorsk og engelske oversettelser). Kodelister osv. er også flerspråklige og endrer språk etter valgt språk i browser. Registereringsløsningen som dataeiere kan benytte er p.t. språket i brukergrensesnittet kun på norsk.

Innhold, beskrivelser av datasett, følger standarden DCAT-AP-NO som også gir flerspråklighet på tekster. Registeringsløsningen her er imidlertid begrenset slik at du i dag må velge beskrivelse av datasettet på engelsk eller norsk.

Dersom behovet, og dataeierene aktivt ser for seg å beskrive datasettene på flere språk, kan vi prioritere opp muligheten til å registrere samme datasett med flere språk.

**Gjelder:**
Registrering Datasett
Begrenset til 3 språk:  Norsk Bokmål, Norsk Nynorsk og Engelsk

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Mulig å velge oversettelse til to andre språk
⦁	Registrere tittel i to språk

Dekkes ikke:   (Dekkes i andre brukerhistorier) 
API-Registrering
Begrepsregistrering

 
Referanser:
Scenario: Mulig å velge oversettelse til to andre språk
Gitt at bruker er pålogget siden registering.fellesdatakatalog.no med skriverrettighet
Og at bruker har Norsk Bokmål som valgt språk i registreringsløsningen
Når bruker klikker på  "Registere Datasett" 
Så skal  detaljsiden for datasettregistering vises
Og  siden skal vise knapp for Norsk nynorsk
Og  siden skal vise knapp for Engelsk

Scenario:   Registrere tittel i to språk
Gitt at bruker er pålogget siden registering.fellesdatakatalog.no med skriverrettighet
Og at bruker har Norsk Bokmål som valgt språk i registreringsløsningen
Når bruker klikker på  "Registere Datasett"  
Og velger Norsk Nynorsk som "ekstraspråk"
Så skal bruker skal kunne registrere "Et Datasett" i feltet  NB -Tittel
Og  bruker skal kunne registrere "Eit Datasett" i feltet  NN -Tittel

**Comment by lillelars** [comment]
@joebrreg setter deg som behovsdriver her. Skal Terese prioritere denne samtidig som språk på Begrep?
