### ISSUE TITLE
[BRUKERHISTORIE] Hvordan få informasjon om feil i Felles datakatalog publisering

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#590]
Som: bruker av Felles datakatalogs publiseringsportal
Ønsker jeg å: får informasjon om feil og driftshendelser i registrering og høsteløsning
Slik at: jeg er oppdatert om eventuelle kjente feil og driftshendelser som kan påvirke mitt arbeid

Relatert til epos: #589 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/portal/start-alert-d.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by shenluna** [comment]
Denne er prodsatt og i drift. Lukker dermed saken.
