### ISSUE TITLE
[BRUKERHISTORIE] Informasjon om feil og driftshendelser i registreringsløsning

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#591]
Som: bruker av Felles datakatalogs registreringsløsning
Ønsker jeg å: får informasjon om feil og driftshendelser i registreringsløsning
Slik at: jeg er oppdatert om eventuelle kjente feil og driftshendelser som kan påvirke mitt arbeid

Relatert til epos: #589 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Kommentar:
Gjelder for de som bruker direktelenker

**Comment by shenluna** [comment]
Denne er prodsatt og i drift. Lukker dermed saken.
