### ISSUE TITLE
[BRUKERHISTORIE] Informasjon om feil og driftshendelser i høsteløsning

### ISSUE THREAD

**Issue by RogerSOlsen** [Informasjonsforvaltning/behov#592]
Som: bruker av Felles datakatalogs høsteløsning
Ønsker jeg å: får informasjon om feil og driftshendelser i høsteløsning
Slik at: jeg er oppdatert om eventuelle kjente feil og driftshendelser som kan påvirke mitt arbeid

Relatert til epos: #589 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/register/admin/start-alert-desktop.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Kommentar:
Gjelder for de som bruker direktelenker

**Comment by shenluna** [comment]
Denne er prodsatt og i drift. Lukker dermed saken.
