### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over dato/tidspunkt for arrangementer og møter 

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#595]
Som: faglig interessert og bruker av Community 
Ønsker jeg å: enkelt kunne finne frem til hvilken dato og tidspunkt aktuelle arrangementer og møter arrangeres. 
Slik at: jeg bedre kan se hvilke møter jeg har mulighet til å delta på. 

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ChristianeFrhlich** [comment]
Det er best om det var mulig å begrense bruk av kalenderen i forumet til  gjelde møter og arrangementer.

**Comment by shenluna** [comment]
Dette er utført, lukker dermed saken
