### ISSUE TITLE
[BRUKERHISTORIE] Rettigheter, info om samtykke og brukervilkår

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#598]
Som: registrert i nettforumet 
Ønsker jeg å: å raskt kunne vite hva jeg har samtykket til (brukervilkår og behandling av personopplysninger) 
Slik at: jeg kan se rettighetsinformasjon

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): viktig

[vilkår og samtykket.docx](https://github.com/Informasjonsforvaltning/behov/files/6538092/vilkar.og.samtykket.docx)

**Comment by ChristianeFrhlich** [comment]
![image](https://user-images.githubusercontent.com/69573572/119473726-bb72ec80-bd4b-11eb-87aa-d7c4674df5eb.png)
Slik rettighetssiden er i dag er det ikke tydelig nok hva en finner av info på denne siden. 
For det første: "Navigasjonsknappen" heter "brukervilkår", men på denne siden er det info om "rettigheter, samtykket og brukervilkår". For det andre: siden trenger tydelige overskrifter som beskriver hva som står i boksene.

**Comment by shenluna** [comment]
Bruksvilkår og samtykke kan leses inne på Datalandsbyen under "Samtykke og brukervilkår" fra menyen.
