### ISSUE TITLE
[BRUKERHISTORIE] Bruker opprettes selv om bruker avbryter registrering 

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#599]
Som: Bruker av nettforumet 
Ønsker jeg å: at det er mulig å avbryte registrering uten at en bruker opprettes
Slik at: slik jeg enklere kan holde kontroll over om jeg er registrert

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): viktig

**Comment by ChristianeFrhlich** [comment]
Se vurdering av dette etter brukertest: https://digdir.sharepoint.com/:x:/r/sites/FDKUtviklingsteam/Delte%20dokumenter/General/Community/Brukertest/Testplan.xlsx?d=wa30ac2d4c5df45d8bd1a7f12136ba647&csf=1&web=1&e=rObXgS

**Comment by shenluna** [comment]
For å kunne få opp brukervilkår og samtykke krever NodeBB at det opprettes en bruker. Hvis bruker ikke aksepterer brukervilkår og samtykke innen en time blir det kjørt en automatikk som sletter brukeren fra systemet.
