### ISSUE TITLE
[BRUKERHISTORIE] Rollebasert tilgangsstyring

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#60]
Som administrator
ønsker jeg enkelt å administrere rollebasert tilgang til virksomhetsintern katalog 
slik at jeg kan utøve god tilgangsstyring

Relatert til epos: #5 

Aktuelle roller:
Minimum er 1) les og 2) skrive/lese tilgang. 
Kanskje: 3) Skrive- og lesetilgang, med publiserings- og godkjenningsfunksjon
Kanskje: 4) Adminbruker?

Arkitekturspørsmål: Integrasjon med AD/LDAP.  Merk at i såfall det er ikke ønskelig at denne delegeringen skal skje i produktet (FDK), men utenfor.

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by KjerstiSteien** [comment]
Tilganger administreres i Altinn. Regner denne saken som løst.
