### ISSUE TITLE
[BRUKERHISTORIE] Opprette og melde seg inn i gruppe

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#602]
Som: medlem av nettforum
Ønsker jeg å: kunne opprette og melde meg inn i grupper
Slik at: jeg kan diskutere spesifikke fagområder og problemstillinger med likesinnede

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Dette blir løst i nettforumet Datalandsbyen
