### ISSUE TITLE
[BRUKERHISTORIE] Tilby personlig bilde for brukere av nettforum

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#603]
Som: leverandør av nettforumet
Ønsker jeg å: å kunne tilby brukeren å laste opp et personlig bilde fra et gitt utvalg
Slik at: brukeren er enklere å kjenne igjen for andre 

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur: ettersom vi ikke ønsker å behandle bilder av enkeltpersoner, ville det likevel se bedre ut om en kunne velge å ha bilde av en "avatar". Slik som et dyr, ulike figurer, plante, lage en personlig figur eller liknende

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): kjekt å ha

**Comment by livarb** [comment]
Tenker dette er noko vi bør støtte i Datalandsbyen på sikt. Kan vi flytte dette til backlog, kanskje?

**Comment by ChristianeFrhlich** [comment]
Ser at denne kan lukke for en periode.
