### ISSUE TITLE
[BRUKERHISTORIE] RSS-strøm på FDKs forside

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#607]
Som: besøkende på data.norge.no
Ønsker jeg å: gjøres oppmerksom på siste innlegg fra nettforumet Datalandsbyen 
Slik at: jeg kan holde meg oppdatert på hva som skjer i forumet

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Dette vart vel prodsett for eit par dagar sidan, så kortet bør gjerne flyttast vidare? @shenluna

**Comment by shenluna** [comment]
@livarb Stemmer, takk for påminnelse. Flytter den til klar til akseptansetest, tar du en titt @ChristianeFrhlich
