### ISSUE TITLE
[BRUKERHISTORIE] Annotering av datasett med virksomhetsintern tematisk inndeling

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#62]
Som: tjenesteutvikler og data scientist 
Ønsker jeg å: kunne annotere datasettene etter egen tematisk inndeling
Slik at: jeg kan relatere datasettene til virksomhetenes fagområder og prosjekter

Relatert til epos: #5 

Minimum er utvidelse til LOS, som gir et mer omfattende vokabular enn de få temaene vi har idag

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by tereseskavhaug** [comment]
Jeg har skissert registrering og filtrering på LOS-temaer nå. Hvor skal jeg legge inn trådskisser på det @stigbd ? Syns denne saken er mest relevant av de som ligger der nå, men mulig det skal være en egen brukerhistorie. Det gjelder i utgangspunktet ikke kun virksomhetsintern katalog, men FDK generelt.

**Comment by KjerstiSteien** [comment]
LOS-temaer er støttet i dag.
