### ISSUE TITLE
[BRUKERHISTORIE] Påminnelse om å kommentere datasett i Datalandsbyen

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#623]
Som: konsument av et datasett
Ønsker jeg å: få informasjon om at det er mulig å komme med tilbakemeldinger på et datasett 
Slik at: jeg vet at der mulig å komme med info om det bestemte datasettet

Relatert til epos:

Lenke til design: 

Nåværende er design er kun en visning av siste kommentar om datasettet.

Lenke til løsningsarkitektur:

Skriv noe supplerende, slik som: Om du ønsker kommentere datasettet kan du logge deg inn i Datalandsbyen. Ved å kopiere inn URL-en til datasettet i forumdiskusjonen, dukker diskusjonen opp her. 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Foreslår vi lukkar denne no som vi har fått kommentarfelt på data.norge.no.
Eller er det noko anna i denne saka som bør gjerast?
