### ISSUE TITLE
[BRUKERHISTORIE] Knytte FDK-rettigheter til en virksomhet sine roller i intern tilgangsstyringssystem (OpenID Connect)

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#625]
Som: administrator i en virksomhet som bruker en eller flere løsninger i Felles datakatalog som krever tilgangsstyring
Ønsker jeg å: kunne knytte virksomhetens definerte roller i intern tilgangsstyringssystem (OpenID Connect) til de ulike rettighetene i Felles datakatalog
Slik at: jeg kan videreføre roller og rettigheter ut i fra virksomhetens behov og dermed utøve god tilgangsstyring.

Relatert til epos: #68 
Relatert til brukerhistorie:
#60
#234 

Eks. på rettigheter:

- Lesetilgang til datakatalogen i registreringsløsningen
- Skrivetilgang til datakatalogen i registreringsløsningen
- Godkjenningstilgang til datakatalogen i registreringsløsningen
- Publiseringstilgang til datakatalogen i registreringsløsningen
- Lesetilgang til begrepskatalogen i registreringsløsningen
- Skrivetilgang til begrepskatalogen i registreringsløsningen
- Publiseringstilgang til begrepskatalogen i registreringsløsningen
- osv.

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Etter erfaringene vi har hatt med å koble på interne ADer hittil, er min vurdering at vi ikke kommer til å integrere med virksomheters interne AD. Lukker derfor denne saken.
