### ISSUE TITLE
[BRUKERHISTORIE] Tilgangsstyringen mot FDK via virksomhetens interne tilgangsstyringssystem

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#627]
Som: bruker i en virksomhet som har en egen tilgangsstyringstjeneste som støtter OpenID Connect
Ønsker jeg at: tilgangsstyringen mot FDK skjer via min virksomhets interne tilgangsstyringssystem
Slik at: jeg slipper egen innlogging når jeg skal jobbe i Felles datakatalog

Relatert til epos: #68 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by KjerstiSteien** [comment]
Etter å ha gjort oss erfaring med å koble oss mot virksomheters egen AD, kommer vi ikke til å forfølge dette sporet videre. Lukker derfor saken.
