### ISSUE TITLE
[BRUKERHISTORIE] Oppdatere tilgangsnivåene for datasett (og API-er)

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#634]
Som: bruker av datakatalogen
Ønsker jeg at kategoriene for å klassifisere tilgang blir oppdatert
Slik at: de er i tråd med EUs definisjoner

Relatert til epos: 
Også beskrevet her: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/484 
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

| Nåværende term | Ny term | Ny beskrivelse |
| --- | ---| --- |
| offentlig | allmenn tilgang | Tilgang som hvem som helst kan få. Tillatte hindringer inkluderer brukerregistrering og forespørsel om API-nøkler, så lenge alle kan få slik registrering og/eller API-nøkler. | 
| begrenset offentlighet | betinget tilgang| Tilgang som kun kan fås under visse betingelser bestemt av eieren eller tilbyderen.  Eksempler på betingelser kan være betaling eller å inngå fortrolighetsavtale. Kategorien inkluderer også tilgang som ennå ikke er kategorisert som allmenn tilgang eller ikke-allmenn tilgang. | 
| unntatt offentlighet| ikke-allmenn tilgang | Tilgang som ikke hvem som helst kan få som følge av lovregulerte begrensninger knyttet til sikkerhet, personvern eller lignende. Kategorien inkluderer tilgang til ressurser som inneholder sensitive data eller personopplysninger. | 

Dette medfører at en god del av datasettene som i dag er klassifisert som `begrenset offentlighet` må omklassifiseres til `ikke-allmenn tilgang`.

**Comment by oystein-asnes** [comment]
Alle datasett med innhold i feltet skjermingshjemmel som har verdien "restricted" flyttes til "non-public"

**Comment by oystein-asnes** [comment]
@shenluna  Her gjenstår å oppdatere ´tilgangsnivå´-navnene (norsk) i frontend på data.norge.no tråd med tabellen over. (Opplysninger om tilgangsnivå mangler i detaljvisningen, så det kommer eget issue på det.)

**Comment by shenluna** [comment]
@oystein-asnes Navnene er oppdatert i prod nå.
