### ISSUE TITLE
[BRUKERHISTORIE] Løfte relasjoner mellom datasett og datatjenester i frontend

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#635]
Som: bruker av datasett-katalogen
Ønsker jeg å: raskt se hvilke datatjenester som er relatert til et datasett
Slik at: det er intuitivt å ta i bruk data

Relatert til epos:

Eksempel: Datatjenesten  [Kjøretøyopplysninger (tekniske data enkeltoppslag)](https://data.norge.no/dataservices/39d971db-534a-3e05-af54-a74ea4cd15c4) er relatert til datasettet  [Teknisk kjøretøyinformasjon](https://data.norge.no/datasets/a8533876-cca7-4417-90be-b368f7d9542c) 

Uten å ha sett RDF-en vil jeg tro det er relasjonen `dcat:servesDataset` som er benyttet. Dette er altså ikke en `dcat:distribusjon` men like fullt en leveranse av datasettet.
_EDIT: I tillegg er det en tilsvarende relasjon fra en distribusjon til en datatjeneste: `dcat:accessService` Resultatet for sluttbruker er det samme: data er tilgjengelig gjennom en datatjeneste_

I detaljvisningen av datasettet er denne relasjonen oppgitt som "Andre som relaterer til dette datasettet". Dette er ganske misvisende.  API-et er for noen brukeren et av de aller viktigste  informasjonselementene i detaljvisningen. 

Jeg foreslår å løfte dette elementet opp sammen med/sidestilt med  `distribusjoner`  og lage design som tydelig kommuniserer at dette datasettet har et tilknyttet API/datatjeneste. 

Forslag til tekst: `Datatjeneste:  [tittel på datatjenesten] `

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Datatjenester som er registrert pre dcat-ap-no versjon 2.0 er ikke definert som datatjenester, men kun distribusjoner. I gamle data.norge.no brukte vi en støttevokabular for å skille mellom filer, feeds og apier (webservice). Dette er trolig gått tapt i ETL-en? @stigbd ?

**Comment by stigbd** [comment]
Det er korrekt at vi ikkje fekk med oss api i etl. Trur vi har eit issue på det ein stad. Men det er ikkje for seint. Det er stadig mulig å fikse. Meiner å hugse at @livarb sa at desse er specca av WADL?

**Comment by oystein-asnes** [comment]
Obs. se https://github.com/Informasjonsforvaltning/fdk-portal/issues/1116

**Comment by livarb** [comment]
> Det er korrekt at vi ikkje fekk med oss api i etl. Trur vi har eit issue på det ein stad. Men det er ikkje for seint. Det er stadig mulig å fikse. Meiner å hugse at @livarb sa at desse er specca av WADL?

Det er WADL-definisjon på datahotellet, men den er abstrahert opp til å gjelde på tvers av alle datasett, så eg tvilar på at den er til noko nytte:
https://hotell.difi.no/application.wadl

Eg laga eit script for lenge sidan som genererer OpenAPI-spec for alle datasett på datahotellet. Scriptet er ikkje oppdatert for å fungere med FDK i skrivande stund. Om eg pussar opp det, så kan det bidra inn i å få datasett i datahotellet inn som API i FDK.

For andre datasett-oppføringar i gamle data.norge.no som ikkje peika til datasett på datahotellet, så veit eg ikkje. Vi treng vel noko slags spesifikasjon for å føre desse opp som datatenester?

**Comment by oystein-asnes** [comment]
Denne oppgaven kan løses uavhengig av  Datahotell-distribusjonene, Har skilt denne oppgaven ut i nytt issue #666

**Comment by oystein-asnes** [comment]
Levert.
