### ISSUE TITLE
[Brukerhistorie] Synliggjøre veiledning som er relevant for å komme i gang med FDK 

### ISSUE THREAD

**Issue by ChristianeFrhlich** [Informasjonsforvaltning/behov#636]
Som: Som en nybegynner i Felles datakatalog
Ønsker jeg å: enkelt kunne finne frem til relevante standarder, spesifikasjoner og veiledninger
Slik at: kan komme i gang med å dokumentere og publisere i katalog 

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig 

Jeg tror det ville være enklere om veiledningsmateriell for FDK var øverst i menylinjen, som et eget punkt.

**Comment by KjerstiSteien** [comment]
Hjelp og veiledning har nå egen inngang fra forsiden. Vi regner denne saken som løst, og vil jobbe med å videreutvikle dokumentasjon og veiledning fremover.
