### ISSUE TITLE
[BRUKERHISTORIE] Eierskap til dataene / intern kontaktinformasjon

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#64]
Som: tjenesteutvikler eller data scientist 
Ønsker jeg å: å finne informasjon om dataeier 
Slik at: jeg kan ta kontakt for å finne ut hvordan jeg kan få tilgang til dataene

Relatert til epos: #5 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by oystein-asnes** [comment]
Dersom dette behovet ikke er tilstrekkelig ivaretatt av https://doc.difi.no/dcat-ap-no/#_kontaktpunkt bør dette spilles inn her: https://github.com/difi/dcat-ap-no/issues

**Comment by KjerstiSteien** [comment]
Lukkes da vi har løst kontaktinformasjon for eksterne. Dersom vi skal støtte virksomhetsinterne behov i datasettkatalog, regner vi med at behovet vil spilles inn på nytt.
