### ISSUE TITLE
[BRUKERHISTORIE] Behandlingsgrunnlag - henvisning til annen lovgivning

### ISSUE THREAD

**Issue by Texasslim** [Informasjonsforvaltning/behov#648]
Som: bruker av registreringsløsningen / Behandlingsoversikt som registrerer en behandling
Ønsker jeg å: kunne legge inn flere henvisninger til annen lovgivning i de tilfeller der artikkel 6 paragrafen jeg velger tilsier at det skal fylles ut henvisning til annen lovgivning
Slik at: jeg kan legge inn flere henvisninger for hver paragraf hvis jeg ønsker

Relatert til epos: Informasjonsforvaltning/tmp_behandlingsoversikt_behov#52 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by RogerSOlsen** [comment]
Brukerhistorien er overført til eget behovsprosjekt for Behandlingsoversikt, https://github.com/behandlingsoversikt/behov/issues/77
