### ISSUE TITLE
[BRUKERHISTORIE] Styre publisering av datasettbeskrivelsene

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#65]
Som: dataeier
Ønsker jeg å: kunne styre publiseringen av en datasettbeskrivelse slik at den kan publisere enten til virksomhetsintern publisering eller til felles datakatalog
Slik at: har fleksibiliet og kontroll over hvem som får se datasettbeskrivelsene

Forutsetning: Ved publisering til felles datakatalog blir datasettbeskrivelsen også tilgjengelig i den  virksomhetsinterne publiseringen.

Relatert til epos: #5 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by sskagemo** [comment]
Skisse for publisering viser også kravet om å kunne "avpublisere". Forutsetter at #52 er implementert, inkludert "avpublisering".

**Comment by KjerstiSteien** [comment]
Slik vi har valgt å løse virksomhetsinterne behov i begrepskatalog, og antakelig vil fortsette med dersom vi skal støtte tilsvarende behov i andre kataloger, anser vi ikke lenger dette behovet som nødvendig. Bruker vil ha mulighet til å bruke status og eget API for å hente datasettbeskrivelser til egen oversikt.
