### ISSUE TITLE
[BRUKERHISTORIE] Vise informasjon om en tjeneste som er beskrevet i henhold til cpsv-ap-no

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/behov#650]
Som: konsument av en tjeneste
Ønsker jeg å: se all informasjon om en tjeneste (både private og offentlige) i henhold til spesifikasjon for tjenester i cpsv-ap-no
Slik at: jeg enkelt kan få tilgang til informasjonen om en tjeneste

Regneark som viser utkast til CPSV-AP-NO versjon 1 med angivelse av hva som er prioritert som leveranse 1:
[Utkast CPSV-AP-NO versjon 1.0](https://digdir.sharepoint.com/:x:/r/sites/Informasjonsforvaltning-rammeverkS.T.4.1/Delte%20dokumenter/Felles%20tjenestekatalog/CPSV-AP-NO%20v1-0_utkast.xlsx?d=w34d6e8b9b16d4408b461da625c5218de&csf=1&web=1&e=PRmaru)
Eksempelfil RDF (inneholder ikke alle egenskapene for CPSV-AP-NO, men skal minimum ha eksempler knyttet til leveranse 1):
https://raw.githubusercontent.com/Informasjonsforvaltning/cpsv-ap-no/develop/examples/exAlleKlasser2.ttl
Oversiktsbilde over klassene i CPSV-AP-NO og relasjonene mellom disse: 
https://informasjonsforvaltning.github.io/cpsv-ap-no/images/ForenkletModell-CPSV-AP-NO.png
Lenke til Spesifikasjon for tjeneste- og hendelsesbeskrivelser (CPSV-AP-NO): 
https://informasjonsforvaltning.github.io/cpsv-ap-no/

Relatert til epos: 
* #705 

Relatert til brukerhistorier:

Lenke til design: [Detaljside desktop](https://www.figma.com/proto/N5yRmXN2WW6sv6J3ILiav7/Portal-%E2%80%93-Detail?page-id=3212%3A49591&node-id=4622-140247&viewport=-4792%2C95%2C0.3&scaling=min-zoom&starting-point-node-id=3915%3A97954&show-proto-sidebar=1)
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Akseptansekriterier:
* Tjenestebeskrivelser som blir høstes skal vises på detaljesiden for tjenester i FDK-portalen
* Detaljesiden skal være i henhold til design

CPSV-AP 3.0 (html): https://semiceu.github.io/CPSV-AP/releases/3.0.0/
CPSV-AP 3.0 (RDF): https://github.com/SEMICeu/CPSV-AP/blob/master/releases/3.0.0/rdf/cpsv-ap.ttl

------------------------------------------------------------------------------------------------------------------------------------

Frontend:
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1359
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1370
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1371
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1372
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1373
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1374
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1375
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1376
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1377
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1378
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1380

Backend:
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/166 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/167
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/168 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/169 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/170 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/171 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/172 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/173 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/174 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/175 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/176 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/179  
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/180 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/181 
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/112
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/113
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/114
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/115
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/116
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/117
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/182
- [x] https://github.com/Informasjonsforvaltning/fdk-reasoning-service/issues/66
- [x] https://github.com/Informasjonsforvaltning/fdk-public-service-harvester/issues/54

Tas separat fra denne brukerhistorien:
~https://github.com/Informasjonsforvaltning/fdk-reasoning-service/issues/67~

**Comment by terjesyl** [comment]
Foreslår at vi betrakter tema-issuet (fdk-reasoning-service#67) som seperat fra denne brukehistorien, slik at vi kan fullføre denne leveransen og akseptansetesten den. Det issuet er relatert til både datasett og tjenester.
@KjerstiSteien @KurtStian @NilsOveTen

**Comment by KurtStian** [comment]
@terjesyl Leveransen som er gjort er vel uansett en delleveranse, men ser behovet for å kunne fulle saken. Skal vi døpe saken om til delleveranse 1?

**Comment by KjerstiSteien** [comment]
Støtter forslagene over!
