### ISSUE TITLE
[BRUKERHISTORIE] Unngå at personopplysninger blir publisert til felles datakatalog

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#66]
Som: dataeier
Ønsker jeg å: forhindre at personopplysninger knyttet til dataeier, kontaktinformasjon etc ikke publiseres til felles datakatalog
Slik at: jeg unngår at personopplysninger som er nødvendige å behandle for interne aktiviteter blir publisert uten rettslig grunnlag

Relatert til epos: #5 

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by KjerstiSteien** [comment]
Anses ikke lenger som relevant. Mener dette er dekket i tilstrekkelig grad i dagens løsning.
