### ISSUE TITLE
[BRUKERHISTORIE] Datasett i datahotellet inn som API

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#666]
Som: bruker av datakatalogen
Ønsker jeg å: se hvilke APIer som er knyttet til datasettet
Slik at:jeg ta datasettene i bruk

Relatert til brukerhistorie #635 :

Lage/oppdatere script som genererer OpenAPI-spec for alle datasett på datahotellet slik at vi får datasetta i datahotellet inn som API i datasettkatalogen.

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by KjerstiSteien** [comment]
Lukker denne da datahotellet legges ned.
