### ISSUE TITLE
[EPOS] Oppdage og evaluere virksomhetens interne datasett

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#67]
Som: dataeier
Ønsker jeg å: gjøre virksomhetens interne datasettbeskrivelser tilgjengelige for virksomhetens ansatte
Slik at: de kan oppdage, evaluere og få informasjon om hvordan de kan få tilgang til dataene

Relatert til #5 som handler om å registrere virksomhetenes interne datasettbeskrivelser.

Lenke til trådskisser: 
Lenke til overordna arkitektur:

**Comment by BRespen** [comment]
Anser dette for å være dekt av brukerhistorie #299 og lukker derfor brukerhistorien
