### ISSUE TITLE
[BRUKERHISTORIE] Eksport av opplysninger i registreringsløsningen for begreper

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#671]
Som: begrepsansvarlig
Ønsker jeg å: kunne eksportere innholdet i registreringsløsningen (både for status utkast og godkjent)
Slik at: jeg enkelt kan dele dette med andre (utenfor virksomheten)

Dette er for eksempel aktuelt der flere samarbeider om innhold i "samhandlingstjenester" (livshendelser)
og ønsker å samordne/kvalitetssikre opplysningene før publisering

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Se også:  #531](https://github.com/Informasjonsforvaltning/behov/issues/531
[Eksport av begreper fra registreringsløsning]

**Comment by KjerstiSteien** [comment]
@Te-Bert @oystein-asnes For meg ser det ut som at dette behovet er dekket av #531 Kan vi lukke denne?

**Comment by oystein-asnes** [comment]
Heilt greit for meg :-)
