### ISSUE TITLE
[BRUKERHISTORIE] Flere roller i katalogene

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#672]
Som: ansvarlig for kvalitet på innhold i katalogene
Ønsker jeg: flere roller, utover les – og skriv, f. eks "godkjenner", "publiserer", som kan knyttes til begrepets livssyklus
Slik at: vi har kontroll på godkjenning og publisering av begreper mm.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Mindre viktig

Se også BR: https://github.com/datautvikling/behov/issues/76

**Comment by KjerstiSteien** [comment]
Duplikat av #790

**Comment by KjerstiSteien** [comment]
Duplikat av https://github.com/Informasjonsforvaltning/behov/issues/790. Lukkes.
