### ISSUE TITLE
[BRUKERHISTORIE] Se endringslogg på et begrep

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#673]
Som: lesebruker
Ønsker jeg: å se en oversikt over alt som er gjort på et begrep, hva endringen bestod i, når endringen ble gjort, og hvem som har gjort endringer
Slik at: jeg kan følge med på hva som er gjort og det er etterprøvbart

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Se også BR: https://github.com/datautvikling/behov/issues/77

**Comment by KjerstiSteien** [comment]
Løst av https://github.com/Informasjonsforvaltning/behov/issues/787
