### ISSUE TITLE
[BRUKERHISTORIE] Egne felter i Begrepskatalogen for virksomhetsinterne behov

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#674]
Som: virksomhet som skal bruke framtidig intern Begrepskatalog
Ønsker jeg: å angi interne felter som er relevant for min virksomhet
Slik at: jeg kan forvalte intern informasjon jeg trenger å dokumentere

Liste over interne felter
Begrepseier (Bruker)
Godkjenner (Bruker)
Offentlig tilgjengelig (boolean, Ja/Nei)
Ansvarlig (Bruker)

NB: Interne felter skal også kunne vises i intern søkeportal.

Ad. feltet offentlig tilgjengelig: Dette feltet indikerer om et begrep er publisert hos data.norge.no. Hvis et begrep tidligere har vært offentlig tilgjengelig (Off- tilgj= JA) endrer verdi (Off.tilgj. = NEI), skal følgende skje: Begrepet består hos data.norge.no men merkes som "utgått", da det ikke lenger er ønskelig at det brukes og det heller ikke vil bli vedlikeholdt fra virksomhetens side.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Se også BR: https://github.com/datautvikling/behov/issues/78

**Comment by KjerstiSteien** [comment]
Løst av https://github.com/Informasjonsforvaltning/behov/issues/788
