### ISSUE TITLE
[BRUKERHISTORIE] Bruke interne kodelister i eksisterende felter i registreringsløsningen for begreper

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#675]
Som: Virksomhet som skal bruke framtidig intern Begrepskatalog
Ønsker jeg: å bruke og angi interne kodelister, internt eierskap, interne fagområder osv.  
Slik at: jeg kan dokumentere interne forhold ved virksomheten

Liste over felter der jeg ønsker interne kodeverk brukt, som en start:
Fagområde
Bruksområde

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Se også BR: https://github.com/datautvikling/behov/issues/81

**Comment by KjerstiSteien** [comment]
Anser denne som løst
