### ISSUE TITLE
[BRUKERHISTORIE] Vise fram hvilken status begrepet er i 

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#676]
Som: leser i BR begrepskatalog
Ønsker jeg: at det framkommer tydelig hvilken status* begrepet er i
Slik at: jeg kan få et inntrykk av hvor gjennomarbeidet det er

*Aktuelle statuser:

Se også: https://github.com/datautvikling/behov/issues/82

Relatert til epos: #792

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: 
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by KjerstiSteien** [comment]
Test: 
- [x] Begrepsstatus vises i treffliste i intern begrepskatalog
- [x] Begrepsstatus vises på detaljside
- [x] Begrepsstatus er frikoblet fra publiseringstilstand
