### ISSUE TITLE
[BRUKERHISTORIE] Vise hvem som er ansvarlig for å jobbe med et begrep

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#677]
Som: leser i intern begrepskatalog
Ønsker jeg: visning av et navn* på den som som er ansvarlig for begrep
Slik at: jeg ser at det er tydelig hvem som har ansvaret for begrep innenfor et domene.

 *Må definere hvor dette skal hentes fra (liste over ansatte).

Se også BR: https://github.com/datautvikling/behov/issues/83

Relatert til epos: #792

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by KjerstiSteien** [comment]
Løst ved felt for tildelt og kodeliste over brukere, som administreres av virksomheten selv.
