### ISSUE TITLE
[BRUKERHISTORIE] Filtrering på begrep i intern begrepskatalog

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#678]
Som: leser i intern begrepskatalog
Ønsker jeg: å filtrere
Slik at: jeg enkelt kan finne fram til de begrepene jeg vil se

Det må være mulig å filtrere på følgende felter (som en start):
Fagområde (kodeliste)
Bruksområde (kodeliste)
Statuser (kodeliste)
Eier (intern, avdeling/seksjon)
Ekstern eier (virksomhet)
Rolleinfo (godkjenner, begrepseier, assignee)

Vis alle begreper i katalog vs vis bare "min" katalog er også en type filtrering - ev en egen brukerhistorie for denne?

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

https://github.com/datautvikling/behov/issues/84

**Comment by KjerstiSteien** [comment]
Duplikat av #791
