### ISSUE TITLE
[BRUKERHISTORIE] Utvide søk til å søke i flere felter i begrepskatalogen

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#679]
Som: leser i intern begrepskatalog
Ønsker jeg: at jeg kan velge hvilke felter det skal søkes i
Slik at: jeg får bedre treff

Dette kan f. eks løses som et avansert søk.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Se også BR: https://github.com/datautvikling/behov/issues/85

**Comment by KjerstiSteien** [comment]
Duplikat av #789
