### ISSUE TITLE
[BRUKERHISTORIE] Tilpasse kommentarfunksjonen til  virksomhetsinterne behov

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#680]
Som: Intern lese og skrivebruker
Ønsker jeg: at kommentarer kan opprettes, redigeres, slettes og leses (CRUD) som del av "begrepsposten" (når jeg har gjort oppslag på et begrep)
Slik at: Jeg kan gi innspill til begrepsinnhold i en intern begrepskatalog

Når det er flere enn fem kommentarer på et begrep skal de slås sammen

Se også BR: https://github.com/datautvikling/behov/issues/86

Relatert til epos: #792 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til trådskisser: 
Lenke til design: https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7525%3A157668&node-id=7880-163833&viewport=-6463%2C517%2C0.45&scaling=min-zoom&starting-point-node-id=7880%3A163833
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by jeffreiffers** [comment]
Kommentarfunksjonen er flyttet.
Opprettet eget issue til å vise begrenset antall komentarer: https://github.com/Informasjonsforvaltning/catalog-frontend/issues/118

**Comment by KjerstiSteien** [comment]
Kommentarfunksjon ligger nå på detaljside. Brukeren som opprettet kommentaren kan redigere eller slette egne kommentarer. Det gjenstår å slå kommentarene sammen. Laget egen sak på dette. Godkjenner denne saken.
