### ISSUE TITLE
[BRUKERHISTORIE] Intern begrepskatalog - opprettelse og registrering/redigering i ett og samme GUI

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#682]
Som: Leser av intern begrepskatalog
Ønsker jeg: at opprettelse, registrering/redigering og visning av begreper er mulig i ett og samme brukergrensesnitt
Slik at: den interne begrepskatalogen blir gjenkjennbar og dagens skille mellom registrering og visning blir borte/mindre.

Bruk for eksempel portaldelen i data.norge.no. som et utgangspunkt

Begrepsvisningen skal kun vise feltene som er fylt ut, men det skal være mulig å redigere i alle feltene, dette kunne f. eks vært løst vha et skjema som kan nås f. eks via en "rediger"-knapp/funksjon. Begreps statuser bør også kunne endres som del av redigere-funksjonen.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Se også BR: https://github.com/datautvikling/behov/issues/88

**Comment by marittor** [comment]
@KurtStian  Jeg har fortsatt ikke muligheten til å redigere.. handler det om at det er andre enn meg som har oppretta issuet? Jeg skulle ha fått lagt inn følgende designskisser fra Lene: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-(D)?page-id=0%3A1&node-id=84%3A14320&viewport=388%2C48%2C0.55&scaling=min 

https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-(D)?page-id=0%3A1&node-id=91%3A45921&viewport=388%2C48%2C0.33&scaling=min-zoom&starting-point-node-id=91%3A45921&show-proto-sidebar=1&hide-ui=1
