### ISSUE TITLE
[EPOS] Tilgangsstyring

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#69]
Som: Forvalter av Felles datakatalog
Ønsker jeg å: Samle all håndtering av tilgangsstyring for alle komponentene i ett felles sett av tjenester
Slik at: Det blir raskere å ta i bruk ulike mekaniser for de ulike løsningene

Relatert til Epos #68 

Lenke til trådskisser: 
Lenke til overordna arkitektur: https://confluence.brreg.no/display/FDK/Tilgangsstyring

**Comment by KurtStian** [comment]
Lukkes, fordi den blir dekket av #68
