### ISSUE TITLE
[BRUKERHISTORIE] Tilbyders behov for å gruppere datasett som hører naturlig sammen

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#695]
Som datatilbyder har jeg behov for å gruppere datasett som hører naturlig sammen i katalogen slik at jeg kan presentere datasett som en del av en større kontekst for brukerne.

Relatert til epos: #694 

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes fordi den er dekket av #694 og #754

**Comment by KjerstiSteien** [comment]
Lukker i henhold til Øysteins kommentar
