### ISSUE TITLE
[EPOS] Nasjonalt tilgangspunkt for transportdata/NAP

### ISSUE THREAD

**Issue by data-david** [Informasjonsforvaltning/behov#7]
Som utvikler av transportapp ønsker jeg **tilgang til et egen portal for transport datasett** slik at jeg kun ser datasett som omhandler transport

Statens Vegvesen (SVV) har ansvaret for Nasjonalt tilgangspunkt for transportdata (NAP). Brønnøysundregistrene (BRREG) har fått en forespørsel om vi gjennom felles datakatalog (FDK) ønsker å ta rollen som “hjem” for NAP.

Saken har vært oppe i Styringsrådet for Felles datakatalog, som har stilt seg positive til dette, og linjeledelsen i avdeling for Digitalisering støtter dette.

Tilknyttede brukerhistorier:
- [x] #190
- [x] #189 
- [x] #59
- [x] #191
- [x] #288
- [x] #287 
- [x] #289 

[Dialog med SVV](https://docs.google.com/document/d/13ybXV1ECnbi28IaKG0eJeT2_d2o0jtWBDIzXrbH_YPY)

**Comment by data-david** [comment]
Øvrige spørsmål fra SVV som skal svares ut:

* Har dere utenlandske aktører som legger inn data? Kan de i såfall benytte Altinn?
* Hvordan får man tilgangsstyringsrolle?
* Har dere sett på den svenske løsningen https://www.trafficdata.se/? Hva tenker dere om denne løsningen?
* Du skriver at "Konsekvensene dreier seg først og fremst om avklaring av ansvar og roller i forvaltning (se siste spørsmål) og eventuelle økte driftskostnader som følge av uforutsett bruk." Kan du si mer om hva du tenker på her og hva typisk kostnader knyttet til dette kan være?

**Comment by data-david** [comment]
**Under hvilke forutsetninger kan BRREG la felles datakatalog være “hjem” for NAP?**
Felles datakatalog er oppbygd på en slik måte at det teknisk sett er få konsekvenser å drifte en sektoriell portal som NAP.  Konsekvensene dreier seg først og fremst om avklaring av ansvar og roller i forvaltning (se siste spørsmål) og eventuelle økte driftskostnader som følge av uforutsett bruk.
Beste praksis herunder hjelpetekster på felter koordineres mellom BRREG, SVV og Difi - som er ansvarlig for standarden DCAT-AP-NO. Dette gjøres minst én gang årlig.
SVV inngår også i Styringsrådet til felles datakatalog som en viktig bruker og aktør i løsningen. Styringsrådet har møter ca. 4 ganger årlig.
'
**I hvilken grad får man til Dedikert URL for NAP subsettet av Felleskatalogen?**
Felles datakatalog har parametriserte URL-er for alle sider og spørringer. Det lar seg med andre ord gjøre.

**I hvilken grad får man dedikert design av NAP subsettet, med tydeliggjøring av det vi ønsker å tydeliggjøre rundt SVV sin rolle**
Grafisk design som logo, farger og fonter, samt dedikerte tekster på headere og footere vil være uproblematisk. Merk at Registreringsløsningen ikke vil ha dedikert design.

**I hvilken grad vil man få beholde NAP kontekst ved søk innenfor NAP dataene når man kommer inn via dedikert portal?**
Når du kommer inn via NAP vil denne konteksten bevares, herunder grafisk profil. NAP-konteksten avgjøres av at dataeierne markerer datasettene med nøkkelord i henhold til transportspesifikke emneord. Man kan imidlertid bevege seg ut av konteksten dersom dataeier fra et NAP datasett refererer videre til et datasett som IKKE er en del av NAP-konteksten. F.eks. at datasett Bomstasjoner refererer til datasett om Kjøretøyregisteret (som er utenfor NAP-kontekst.. 
Videre vil IKKE man bevege seg inn i NAP-konteksten fra felles datakatalog kontekst ettersom NAP-datasettene også finnes her.

**I hvilken grad vil man få tilgang til «staging» funksjonalitet, ved at SVV får tilgang til å godkjenne innsendte metadata før de blir synlige, kommunisere med dataeiere mm.?**
Som vi var inne på i møtet, er dette en betydelig utvidelse i vår tilgangsstyringssmodell. Vi anbefaler derfor et alternativ der SVV får jevnlige rapporter over nye registreringer, slik at disse kan kvalitetssjekkes. Om det er datasett som har blitt lagt til som ikke oppfyller kvalitetskrav, kan disse fjernes.

**I hvilken grad vil man få tospråklighet – norsk og engelsk?**
Portalen støtter flerspråklighet i brukergrensesnittet (i dag bokmål, nynorsk og engelske oversettelser). Kodelister osv. er også flerspråklige og endrer språk etter valgt språk i browser.  Registereringsløsningen som dataeiere kan benytte er p.t. språket i brukergrensesnittet kun på norsk.
Innhold, beskrivelser av datasett, følger standarden DCAT-AP-NO som også gir flerspråklighet på tekster. Registeringsløsningen her er imidlertid begrenset slik at du i dag må velge beskrivelse av datasettet på engelsk eller norsk.  
Dersom behovet, og dataeierene aktivt ser for seg å beskrive datasettene på flere språk, kan vi prioritere opp muligheten til å registrere samme datasett med flere språk.

**I hvilken grad vil man skille mellom faglig forvaltning og portaldrift?**
Det forutsettes at SVV er førstelinje for forespørsler på datasett som markeres som “transportdata”, og som kommer frem i NAP-portalen. I praksis vil dette si at det vil være en banner e.l. som henviser tilbakemeldinger til Vegvesenet. Det vil også være SVV som da har kontakt med dataeierne for disse datasettene. BRREG er annen linje for tekniske spørsmål og drift.

**Comment by data-david** [comment]
_Spørsmål til BRREG foran møte i SG i NAP 13/2_

**Har dere utenlandske aktører som legger inn data? Kan de i såfall benytte Altinn?**

**Hvordan får man tilgangsstyringsrolle?**

**Har dere sett på den svenske løsningen https://www.trafficdata.se/? Hva tenker dere om denne løsningen?**

**Du skriver at "Konsekvensene dreier seg først og fremst om avklaring av ansvar og roller i forvaltning (se siste spørsmål) og eventuelle økte driftskostnader som følge av uforutsett bruk." Kan du si mer om hva du tenker på her og hva typisk kostnader knyttet til dette kan være?**

**Comment by sskagemo** [comment]
I møte idag bekreftet SVV at iht direktivet som regulerer NAP dreier NAP seg kun om *åpne* data

**Comment by sskagemo** [comment]
I møte idag ble vi enige om at det ikke skal lages funksjonalitet for at SVV skal forhåndsgodkjenne/være redaktør for innholdet i NAP i første omgang, i tråd med svar på spørsmål fra januar (se over): "I hvilken grad vil man få tilgang til «staging» funksjonalitet, ved at SVV får tilgang til å godkjenne innsendte metadata før de blir synlige, kommunisere med dataeiere mm.?"

Primærmekanisme er å kontakte tilbyder og be om at beskrivelse slettes eller rettes opp.

Det kan være et generelt behov for å kunne gjøre endringer/fjerne enkeltregistreringer i felles datakatalog. Trenger egen brukerhistorie på det.
