### ISSUE TITLE
[BRUKERHISTORIE] Måling av metadatakvalitet i samsvar med data.europa.eu

### ISSUE THREAD

**Issue by shenluna** [Informasjonsforvaltning/behov#729]
Som: tilbyder av data
Ønsker jeg å: vite noe om kvaliteten på beskrivelsene jeg tilbyr
Slik at: jeg kan forbedre kvaliteten på virksomhetens datakatalog

------------------
EUs måling: https://data.europa.eu/mqa/methodology?locale=en

[Gapanalyse-metadatakvalitet.xlsx](https://github.com/datadeling/behov-issue-tracker/files/7895194/Gapanalyse-metadatakvalitet.xlsx)

Relatert til epos: 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Flyttet over fra Datadeling https://github.com/datadeling/behov-issue-tracker/issues/138
Se gammel brukerhistorie for historikk.

**Comment by oystein-asnes** [comment]
Har testa med dette datasettet som case: https://data.norge.no/organizations/991825827/datasets/c479c6db-af9d-4467-a238-f30480d153e9. Finn ein del negative måleresultat som ikkje samsvarar med den informasjonen som ligg i reg.-løysinga. Truleg fungerer målinga som den skal, men inputdata frå registreringsløysinga er feil @joachim-me ?  

Kontekst: 

- [ ]  File Size: Egenskapen er ikkje støtta av reg.-løysing
- [ ]  Rights: Egenskapen er ikkje støtta av reg.-løysing

Interoperabilitet:
- [ ] DCAT-AP compliance: Feilar. Det gjer også heile datasettkatalogen i EDPs katalog-test. Sjekk DCAT-output

- [ ] Format match:  Reg. løysinga gir ikkje særleg logiske forslag til IANA mediatypar. Test: søk på "RDF" gir kun to snåle forslag: prs.rdf-xml-crypt og vnd.biopax.rdf+xml. Det er ikkje muleg å oppgi application/rdf+xml i reg. løysinga (?)

- [ ] Format/Media type machine interpretable: Feilar. Heng mest truleg saman med feil i reg. løysinga ?
 
- [ ] Format/Media type non proprietary: Feilar. Samme feil som over?
 
- [ ] Media type: Feilar. Kan være følgefeil av DCAT-AP-NO sin norske vri på format/Mediatype
 
- [ ] Content syntax valid: Feilar utan å gi feedback på kvifor. Truleg følgefeil av feilen over 

Gjenbrukbarheit:

- [ ] Access restriction vocaulary: Feilar. Her er skal vi være up to speed med DCAT-AP, så uvist kvifor denne feilar.
 
- [ ] Known license: Feilar. Lisens er oppgitt (CC0), så her må vi sjekke URI-en som reg.løysinga spyr ut.

- [ ] License information: Feilar. Lisens er oppgitt (CC0), så her må vi sjekke output frå reg.løysinga

**Comment by jeffreiffers** [comment]
DCAT-AP compliance sjekkes ikke per i dag. Ligger i pipelinen å lage en tjeneste som skal sjekke dette.

Har du noe eksempler på hvor format/mediatype ikke får score?

Access restriction sjekk var ikke implementert. Fikses her https://github.com/Informasjonsforvaltning/fdk-mqa-property-checker/issues/27

Known license sjekk var ikke implementert: Fikses her https://github.com/Informasjonsforvaltning/fdk-mqa-property-checker/issues/26

License information skal være riktig implementert. Har du noe eksempler som burde fått poeng?

**Comment by oystein-asnes** [comment]
> Har du noe eksempler på hvor format/mediatype ikke får score?

@jeffreiffers  Her er det ingen som får score i dag. Eller meir presist: Alle får godkjent `Format`, men det ser ut som denne berre testar om det er oppgitt ein verdi og `Format match` sjekkar om gyldig URI er på plass. Eksempel: [Denne ](https://data.norge.no/organizations/991825827/datasets/c479c6db-af9d-4467-a238-f30480d153e9)feilar på `Format match`, `Format/media machine interpretable` og `Format/media type non proprietary`.  Min hypotese er at alle desse er følgefeil av at vi ikkje brukar [rett vokabular for format](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/file-type). 

> License information skal være riktig implementert. Har du noe eksempler som burde fått poeng?

Samme eksempel som over. [Denne ](https://data.norge.no/organizations/991825827/datasets/c479c6db-af9d-4467-a238-f30480d153e9) burde i teorien fått poeng. Men er har vi brukt URL til lisensen som URI og ikkje [EUs lisensvokabular](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/licence) Her må vi hente ut URI-ar for dei lisensane vi har i registrering i dag (NLOD 2.0, CC0 og CC-BY 4.0) og putte inn i reg.-applikasjonen /reference data og ETL-e eksistande datasett.

**Comment by stigbd** [comment]
Forslag til løysing av format/media-type problematikken i registreringsløysinga:
- under egenskapet Distribusjon->format skal brukar velge frå eu sitt "file-type" vokabular. Denne skal publiserast på dct:format egenskapen.
- innfør ny egenskap Distribusjon->medietype og la brukar få velge frå iana. Denne skal publiserast på dcat:mediaType egenskapen.

Vi må så gjere ein ETL på eksisterande datasett i registreringsløysinga.
Så kan vi la fdk-reasoner-service "rekne ut" ei mapping dersom ein av disse ikkje er oppgitt.

Høyres greit ut @oystein-asnes ?

På lengre sikt bør vi undersøke om ikkje dct:MediaType bør vere lov under dct:format, sidan dct:MediaType faktisk er ein sub-klasse av MediaTypeOrExtent ref http://purl.org/dc/terms/MediaTypeOrExtent
Eg meiner altså at EU tek feil her.

**Comment by oystein-asnes** [comment]
Dette er god fisk @stigbd. Dei vi haustar frå, kan også ha nytte av mapping-tabell. Vi kan vurdere å tilby dette som eit datasett.
