### ISSUE TITLE
[BRUKERHISTORIE] Registrere alternativ formulering og angi målgruppe til et begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#73]
Som: skrivebruker
Ønsker jeg å: kunne registrere alternativ formulering til et begrep, i tillegg til definisjonen. 
Og å: kunne angi en mågruppe til et begrep
Slik at: jeg kan ha ulike formuleringer basert på hvilken målgruppe jeg skal nå ut til. 

Målgruppe skal være en kodeliste (dropdown) og det skal kun være mulig å velge én av følgende lovlige verdier (fra forvaltningsstandard for begrepsbeskrivelser): 
- allmennheten
- fagspesialist

Relatert til epos: #329
Relatert til brukerhistorie: #76 

Lenke til trådskisser:
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by marittor** [comment]
Standarden legger kun opp til én definisjon. Kan evt ivaretas av "alternativ formulering". Endrer brukerhistorie, bør kunne støtte registrering av alternativ formulering selv om få bruker det idag.

**Comment by marittor** [comment]
@AleksandraHrpka Her mangler vi trådskisser, men denne kommer ikke før del 3 av begrepsforvaltning.

**Comment by KjerstiSteien** [comment]
Løst av å støtte definisjon for flere målgruppper https://github.com/Informasjonsforvaltning/concept-catalog/issues/189
