### ISSUE TITLE
Bug ved visning av bilder i kommentarfeltet

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#734]
Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Ser ut til å vere problem med å vise bilder i ein kommentar-post. Problemet er ikkje i Datalandsbyen, kun visning av kommentarfeltet i data.norge.no og i Datafabrikken (sjå lenker under)

Eksempel: https://data.norge.no/datasets/b8da2c09-d2ab-3258-9bc7-ec2472a7e9fd#comment-section
Samme for [visning i Datafabrikken](https://datafabrikken.norge.no/finn-data/sok/datasett/b8da2c09-d2ab-3258-9bc7-ec2472a7e9fd).
![image](https://user-images.githubusercontent.com/3617256/179508402-ce05018b-dd58-4186-9704-46a7bab37591.png)

Dersom ein ser den samme kommentaren direkte i Datalandsbyen, så er bileta synlege:
![image](https://user-images.githubusercontent.com/3617256/179508494-a49b7bb3-c0bc-4c02-862e-f8c626c24dec.png)
https://datalandsbyen.norge.no/topic/221/datasett-leveranser-til-slakteri-i-landbruket-i-2021-landbruksdirektoratet/2

Bileta var sett inn i posten ved å redigere kommentaren frå Datalandsbyen.

**Comment by KjerstiSteien** [comment]
@livarb i hvilken tjeneste er det bildene ikke vises riktig?

**Comment by livarb** [comment]
@KjerstiSteien Det er kommentarfeltet i data.norge.no. Sjå første lenka i beskrivelsen.
Problemet gjeld også visning av kommentarfeltet i Datafabrikken.
Skal legge inn lenke og presisere dette.

**Comment by KjerstiSteien** [comment]
Topp! Burde vi ha en egen sak i repo for datafabrikken og lenke dem sammen? Så løses de sammen om det koster lite ekstra, mens vi vurderer om begge skal løses hvis ikke.

**Comment by livarb** [comment]
God idè. Har laga ein plasshaldar i [Datafabrikken sitt behovsbrett](https://github.com/orgs/datadeling/projects/1). Her hadde det vore ein fordel å hatt Datafabrikken-brettet i samme GitHub-organisasjon så ein kunne lagt samme issue inn i fleire prosjekt.

**Comment by livarb** [comment]
Feilen er der framleis: https://data.norge.no/dataservices/ed933ffe-a32c-38a2-9921-1fed86ad3173#comment-section

**Comment by KjerstiSteien** [comment]
Vi skal ha bugsquash til uka. Ser om vi får løst det da, hvis ikke får vi det inn i en sprint snart.
