### ISSUE TITLE
[BRUKERHISTORIE] Søke på begreper

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#75]
Som: Intern leser og skrivebruker
Gitt at jeg står i Registreringsløsningens landingsside kataloger
Og jeg klikker på Begrepskatalog_
Ønsker jeg å: kunne søke blant begrepene i min liste (søket skal gå mot feltene "anbefalt term", "tillatt term" og "frarådt term")
Slik at: jeg enkelt kan se begreper som allerede er registrert i begrepskatalogen

Relatert til epos: #329 

Lenke til trådskisser: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_skriverolle 
Lenke til trådskisser for lesebruker: https://vfy2gg.axshare.com/#g=1&p=oversiktside_begrep_leserolle
Lenke til design (består av flere skisser som viser hele flyten): https://invis.io/3SRCN149CQN#/385601277_BEGREP-REG-Relaterte-Default--D-
Lenke til løsningsarkitektur: denne løses ved at [api-et](https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml) må støtte query på list begreper samt at gui må implementere "standard" søk.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Søk på begrep - skrivetilgang
⦁	Søk på begrep - lesetilgang

Dekkes ikke:   (Dekkes i andre brukerhistorier) 

Referanser:
Scenario: Søk på begrep  - skrivetilgang
Gitt at bruker er pålogget med skrivetilgang 
og bruker har startet opp siden "Begrep fra..."
Når bruker registerer søkeordet "Saksarkiv" og klikker på søkeikonet
Så skal listen med begrep inneholde anbefalt term = saksakiv"

Scenario: Søk på begrep  - lesetilgang
Gitt at bruker er pålogget med lesetilgang 
og bruker har startet opp siden "Begrep fra..."
Når bruker registerer søkeordet "Saksarkiv" og klikker på søkeikonet
Så skal listen med begrep inneholde anbefalt term = saksakiv"

**Comment by marittor** [comment]
Lukkes da den ivaretas av #77

**Comment by lillelars** [comment]
@marittor  Ser denne er closed. Ønsker at alle issues som er closed fjernes fra "Analysere behov" kolonnen...

**Comment by stigbd** [comment]
Det bør presiseres kva for felter søket skal søke mot. Feks er det kun "anbefalt term"?

**Comment by marittor** [comment]
Jeg mener det må søkes i feltene:
- Anbefalt term
- Tillatt term
- Frarådt term

Som et minimum

**Comment by shenluna** [comment]
I første omgang er det implementert søk på anbefalt term. Vi utvider søket ved behov.
