### ISSUE TITLE
[BRUKERHISTORIE] OPPRETTE nytt begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#76]
Som: skrivebruker
Ønsker jeg å: kunne opprette et nytt begrep og beskrive det i Felles begrepskatalog
Slik at: begrepet er opprettet med status "Utkast"
OG jeg kan synliggjøre min virksomhets begrepsforståelse i tråd med gjeldende standarder, i begrepskatalog GUI, for alle brukere i virksomheten

Følgende felter skal være med: 

- Anbefalt term (selve begrepsnavnet)
- Definisjon
- Kilde
- Merknad
- En ID til begrepet < Bør genereres automatisk
- Ansvarlig virksomhet < Bør settes automatisk ut fra at man har valgt katalog å registrere i
 
Det skal kunne knyttes hjelpetekster til alle feltene, se her (dokumentet oppdateres og vil være i versjon 1 - ferdig innen 2.5.: https://docs.google.com/document/d/1FrrPgJJ_4Krqrb58sNdSFCJpF__5_NGqpuKfaF2HaL0/edit?usp=sharing 

Relatert til epos: #176 
Relatert til brukerhistorier: Resten av feltene som skal støttes ligger i #201

Erstatter følgende brukerhistorier: 
#25
#22 

**Trådskisser skrivebruker**
Velg språk: https://69d4ft.axshare.com/#g=1&p=velg_spr_k
Registrer på bokmål: https://69d4ft.axshare.com/#g=1&p=bokm_l_valgt
Oversett til nynorsk: https://69d4ft.axshare.com/#g=1&p=nynorsk
Oversett til engelsk: https://69d4ft.axshare.com/#g=1&p=engelsk
Oversett til nynorsk og engelsk: https://69d4ft.axshare.com/#g=1&p=nynorskogengelsk

Lenke til design: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356259394
Lenke til løsningsarkitektur: Se epos

**Akseptansekriterier:** 
,# language: no
Egenskap: 

Kriterier:
⦁	Et begrep skal kunne lagres med mulig innhold i alle felt som er beskrevet i brukerhistorien med status "Utkast"
⦁	Felt som er obligatoriske skal tydelig markeres som mangel helt til verdier er lagt inn
⦁	Hvert felt  skal ha en tilhørende hjelpetekst som kan vises ved behov.
Dekkes ikke:   (Dekkes i andre brukerhistorier) 
⦁	Publisere begrep
⦁	Slette begrep
⦁	Endre begrep

Referanser:

Scenario: Et begrep skal kunne lagres med mulig innhold i alle felt som er beskrevet i brukerhistorien med status "Utkast"
Gitt at bruker med skriverettigheter har opprettet nytt begrep med informasjon i alle felt
Når bruker avslutter registreringsbildet 
Så skal verdiene i alle registrete felt lagres
Og lagret begrep skal ha status  = "Utkast"

Scenario: Felt som er obligatoriske skal tydelig markeres som mangel helt til verdier er lagt inn
Gitt at bruker med skriverettigheter har opprettet nytt begrep 
Når bruker legger inn verdier i obligatoriske felt 
Så skal markeringen som viser at verdier mangler fjernes

Scenario: Hvert felt  skal ha en tilhørende hjelpetekst som kan vises ved behov
Gitt at  registreringssiden for nytt begrep er åpnet
Når bruker klikker på linken "hjelp" for  et gitt felt
Så skal  hjelpeteskt for gitt felt vises

**Comment by marittor** [comment]
Må være mulig å angi at noen felter skal være obligatoriske å fylle ut.
Bør være mulig at løsningen gir en feilmelding når enten obligatoriske felter ikke er utfylt, eller tekst er lagt inn der vi forventer URL.

**Comment by marittor** [comment]
Skal legge inn beskrivelse av lesebruker.

**Comment by lillelars** [comment]
@marittor er denne egentlig "Klar til konstruksjon" virker ganske klar for min del :)

**Comment by stigbd** [comment]
Vi må nøye tenke igjennom krav til begrep når det opprettes. I en naturlig arbeidsflyt skal det vere mulig å **opprette** et begrep utan at alle obligatoriske felter er utfylt. Men når begrepets status blir endra frå "utkast" til "godkjent", må begrepet validere.
