### ISSUE TITLE
[BRUKERHISTORIE] LISTE OPP alle begrep

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#77]
Som: Intern leser og skrivebruker
Gitt at jeg står i Registreringsløsningens landingsside kataloger
Og jeg klikker på Begrepskatalog_
Ønsker jeg å: se en liste alle begrep som jeg kan sortere, alfabetisk på term og status
Slik at: jeg enkelt kan se begreper som allerede er registrert i begrepskatalogen, hvilke som er publisert i Felles begrepskatalog og hvilke som jobbes med (statuser), og få oversikt etterhvert som det blir mange begreper i min virksomhets katalog. 

NB: Intern leser kan gjøre det samme som skrivebruker unntatt: å legge til nytt begrep.

Relatert til epos: #176 
Relatert til brukerhistorier: 
#75 

Trådskisser skrivebruker : https://69d4ft.axshare.com/#g=1&p=oversiktside_begrep_skriverolle
Trådskisser lesebruker: https://69d4ft.axshare.com/#g=1&p=oversiktside_begrep_leserolle

Lenke til design:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356258577
Lenke til løsningsarkitektur: se epos

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Alle registrerte begrep skal vises for både skrive- og lesetilgangsroller i en liste.
⦁	Det skal være mulig å sortere begrepslisten basert på kolonneheadingene Anbefalt term og status 

Dekkes ikke:  (Dekkes i #175)
⦁	Søke og filtrere blant begrep i registreringsløsningen
⦁	Sortering på feltene Gyldighet og Fagområde

Referanser:

Scenario: Alle registrerte begrep skal vises for skrivetilgangsrollen i en liste
Gitt at bruker er pålogget med skrivetilgang
Når bruker åpner siden for virksomhetens berepsbeskrivelser
Så skal det vises en liste med status over alle begreper opprettet av virksomheten 

Scenario: Alle registrerte begrep skal vises for lesetilgangsrollen i en liste
Gitt at bruker er pålogget med lesetilgang
Når bruker åpner siden for virksomhetens berepsbeskrivelser
Så skal det vises en liste med status over alle begreper opprettet av virksomheten 

Scenario: Det skal være mulig å sortere begrepslisten basert på kolonneheadingene "Anbefalt term" og "Status" 
Gitt at bruker er pålogget med lesetilgang
Når bruker klikker på kolonneheadingen "Status"
Så skal listen sorteres etter verdiene i kolonnen "Status"

**Comment by lillelars** [comment]
@sindresandvik2 @marittor mangler akseptansekriterier

**Comment by marittor** [comment]
@tereseskavhaug Setter deg opp på denne igjen da vi trenger at det skisses for filtrering, se det som er skrevet om "gyldighetsfiltrering". historien er oppdatert etter forrige møte med innføringsteamet. idag er gyldighet en sortering, men ønsker gjerne at dette blir et filter.

**Comment by tereseskavhaug** [comment]
@marittor mener du da at filteret skal erstatte sorteringen? 

@joebrreg hvordan prioriterer vi ny funksjonalitet som dette? altså filtrering på oversiktssiden for begrep i regløsningen. det har ikke vært diskutert i de andre løsningene.

**Comment by marittor** [comment]
@tereseskavhaug Vi tenker at det kan være mer nyttig med et filter her enn sortering, ja, da dette sikkert blir sortert alfabetisk.

**Comment by marittor** [comment]
Funksjonalitet som er tatt ut ligger i #175 175
