### ISSUE TITLE
Ny Begrepsstandard - Nytt Kravnivå og endring av kravnivå

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#772]
Som: tilbyder av begrepsbeskrivelser
Ønsker jeg å: forholde meg til siste versjon av SKOS-AP-NO spesifikasjonen
Slik at:

Det er innført et nytt kravnivå "Anbefales" (i tillegg til de tidligere kravnivåene "obligatorisk" og "ikke-obligatorisk"/valgfri)
Det nye kravet **anbefalt** får under klassen Begrep betydning for 
den eksisterende egenskapen "**Ansvarlig virksomhet**" (tidligere obligatorisk) 
og den nye egenskapen "**Dato opprettet**"

Egenskapen "**Kontaktpunkt**" under Begrepssamling endres til "**obligatorisk**" (tidligere ikke-obligatorisk/valgfritt)

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Kritisk (FDK må til enhver tid forholde seg til gjeldende versjon av spesifikasjonene)
Se også: https://data.norge.no/specification/skos-ap-no-begrep#Endringslogg
for en nærmere beskrivelse av endringene

**Comment by KjerstiSteien** [comment]
Duplikat av https://github.com/Informasjonsforvaltning/behov/issues/840
