### ISSUE TITLE
Ny Begrepsstandard - verdiområder

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#774]
Som: tilbyder av begrepsbeskrivelser
Ønsker jeg å: forholde meg til siste versjon av begrepsstandarden
Slik at:

~~Egenskapen "**Fagområde**" under Begrep endres til å tillate **både kodet verdi og tekst** (tidligere bare tekst) (løst)~~

Egenskapen "**Verdiområde**" (tidligere "omfang") under Begrep endres til å tillate **både kodet verdi og tekst** (tidligere bare kodet verdi)

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Viktig. FDK må til enhver tid forholde seg til den sist gyldige versjon av standarden

**Comment by KjerstiSteien** [comment]
Fagområde er løst

**Comment by NilsOveTen** [comment]
For verdiområde:

Tidligere så var dette en uri med tilhørende tittel, siden skos-ap-no gir typen til feltet som `rdf:langString or xsd:anyURI` så prioriteres nå uri hvis det er oppgitt og verdi fra tittelfeltet brukes hvis ikke.

Regner med det trengs litt oppdatering av skjemaet, trenger design på det. Ser ut som dette i skjemaet nå:
![Image](https://github.com/Informasjonsforvaltning/behov/assets/50194012/ea0b0b38-bd1c-4163-84e0-d32f57d9f3e5)

Trenger også design for detaljsiden i begrepskatalogen og fdk-portal om det skal endres noe der.

**Comment by KjerstiSteien** [comment]
Forslag til tekstendringer: 

Felt "Tittel på omfang" endres til "Tekst"
Felt "Lenke til omfang" endres til "Lenke"
Den korte beskrivelsen beholdes som den er. 
Den utvidede beskrivelsen oppdateres til  "Verdiområde kan beskrives som tekst, lenke eller begge deler. Eksempel på verdiområde beskrevet som tekst: For begrepet "alder" kan verdiområdet beskrives som "alle positive tall". Eksempel på verdiområde beskrevet som tekst og lenke: For begrepet sivilstand kan verdiområdet beskrives som "standard for sivilstand" og "https://www.ssb.no/klass/klassifikasjoner/19". Dette feltet skal ikke brukes for å oppgi eksempler."

**Comment by KjerstiSteien** [comment]
Trenger også oppdatering i backend, da man skal kunne velge begge eller en av delene. Sette språk på tekst uavhengig av om lenke finnes.

**Comment by KjerstiSteien** [comment]
Sjekke med Jim at vi forstår det riktig når vi tolker standarden som at multiplisitet av verdiområde er en til mange for å kunne dekke tekst på flere språk, ikke for å legge til flere lenker.

**Comment by KurtStian** [comment]
I følge Jim kan det finnes flere verdiområder (med flere språk) og i teori så kan tekst og lenke være adskilt, dvs. de trenger ikke å ha noe sammenheng.

**Comment by NilsOveTen** [comment]
så vi må tolke `valueRange: <uri> , "title"@en , "tittel"@nb` som 3 helt uavhengige verdiområder?

**Comment by NilsOveTen** [comment]
i så fall kan vi vel ikke ha mulighet for å legge til tekst og lenke samtidig? siden det ikke er mulig å garantere at de hører sammen

**Comment by NilsOveTen** [comment]
@KjerstiSteien er dette ok for den utvidede beskrivelsen?
 "Verdiområde kan beskrives som tekst eller lenke. Eksempel på verdiområde beskrevet som tekst: For begrepet "alder" kan verdiområdet beskrives som "alle positive tall". Eksempel på verdiområde beskrevet som lenke: For begrepet sivilstand kan verdiområdet beskrives som "https://www.ssb.no/klass/klassifikasjoner/19". Hvis et verdiområde beskrives med både tekst og lenke så vil det bli tolket som to seperate verdiområder. Dette feltet skal ikke brukes for å oppgi eksempler."

**Comment by KurtStian** [comment]
Forslaget til tekst har også fått tommelen opp av Jim den 27.06.2024.
