### ISSUE TITLE
Ny Begrepsstandard - Egenskaper som flyttes til / legges til klassen Begrep

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#777]
Som: tilbyder av begrepsbeskrivelser
Ønsker jeg å: forholde meg til siste versjon av standarden
Slik at:

"Eksempel" flyttes fra Definisjon til Begrep
"Merknad" flyttes fra Definisjon til Begrep
"Verdiområde" flyttes fra Definisjon til Begrep

Følgende egenskaper legges til:
"Dato opprettet"  - anbefalt
"Publisert av" - obligatorisk
"Status" - valgfri
"Versjonsnummer" - valgfri
"Versjonsnote" - valgfri

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Kritisk. FDK må til enhver tid forholde seg til siste versjon av standarden

Se også: Se også: https://data.norge.no/specification/skos-ap-no-begrep#Endringslogg
for en nærmere beskrivelse av endringene

**Comment by KjerstiSteien** [comment]
Løses som del av arbeidet for å støtte ny versjon av skos-ap-no-begrep
