### ISSUE TITLE
Ny  Begrepsstandard - DEFINISJON: Egenskaper som flyttes, utgår eller endrer verdiområde

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#778]
Som: tilbyder av begrepsbeskrivelser 
Ønsker jeg å: forholde meg til siste versjon av begrepsstandardene
Slik at:

Egenskapene: **Eksempel**, **Merknad** og **Verdiområde** flyttes **fra "Definisjon" til "Begrep"**
Egenskapen "Kilde" endres til "Kilder" med _rekkefølge_ (flere)
Egenskapen "Sist oppdatert" utgår

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Kristisk. Felles datakatalog må til enhver tid forholde seg til siste gyldige versjon av standardene

Se også: https://data.norge.no/specification/skos-ap-no-begrep#Endringslogg

**Comment by KjerstiSteien** [comment]
Dekkes av https://github.com/Informasjonsforvaltning/behov/issues/834
