### ISSUE TITLE
[BRUKERHISTORIE] SE DETALJER på begrep 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#78]
Som: lesebruker
Ønsker jeg å: se detaljer på begrep
Slik at: jeg kan lese innholdet

Relatert til epos: #329  
Relatert til brukerhistorie:  #71, #110 

**Trådskisse**
Se begrep lesebruker: https://69d4ft.axshare.com/#g=1&p=sebegrep_leserolle

Lenke til design: https://invis.io/3SRCN149CQN#/388727723_BEGREP-REG-LESEROLLE-Alle-Felter-Flersprak--D-
Lenke til løsningsarkitektur: se epos

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Som bruker med kun lesetilgang  skal jeg kunne se detaljer for et begrep vist i 6 felt definert i brukerhistorie #76 og 7 felt definert i brukerhistorie #201
⦁	Som bruker med lesetilgang skal jeg IKKE kunne editere verdiene i feltene

Dekkes ikke:  (Dekkes i #79)
⦁	Se detaljer for bruker med skrivetilgang.

Referanser:

Scenario: Som bruker med kun lesetilgang  skal jeg se men ikke kunne editere detaljer for et begrep 
Gitt at bruker er pålogget med kun lesetilgang
Når bruker åpner et begrep fra listen i registreringsløsningen
Så skal detaljside vises med detaljer fra alle registrerte felt
Og bruker skal ikke kunne editere detaljene

**Comment by sindresandvik2** [comment]
@marittor  Korleis skal "tomme" felt visast? Felt som ikkje er fylt ut.
