### ISSUE TITLE
Ny Begrepsstandard - Begrepsrelasjonene GENERISK og PARTITIV, Egenskaper som utgår

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#780]
Som: tilbyder av begrepsbeskrivelser 
Ønsker jeg å: forholde meg til siste versjon av begrepsstandardene
Slik at:

Egenskapen "**Sist oppdatert**" **utgår for** Begrepsrelasjonene **Generisk** og **Partitiv**

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Kritisk. Felles datakatalog må til enhver tid forholde seg til sist gjeldene versjon av standarden

Se også: https://data.norge.no/specification/skos-ap-no-begrep#Endringslogg

**Comment by KjerstiSteien** [comment]
Dekkes av https://github.com/Informasjonsforvaltning/behov/issues/834
