### ISSUE TITLE
Ny Begrepsstandard - Klasser som utgår

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#781]
Som: tilbyder av begrepsbeskrivelser
Ønsker jeg å: forholde meg til sist gjeldende versjon av standarden
Slik at:

Følgende klasser utgår:
"Alternativ formulering" (dekkes av "Definisjon" + "Målgruppe")
"Betydningsbeskrivelse" (eg. abstrakt klasse)
"Begrepsrelasjon" (eg. abstrakt klasse) - bruker nå konkrete/spesialiserte direkte
"Term" (eg. sbstrakt klasse)

"Anbefalt term", Tillatt term", "Frarådet term", "Datastrukturterm"
Det er ikke lenger behov for egenskapene i disse klassene («(dato) sist oppdatert» og «målgruppe»).

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi: Kritisk. Felles datakatalog må til enhver tid forholde seg til siste versjon av standardene

Se også: https://data.norge.no/specification/skos-ap-no-begrep#Endringslogg

**Comment by KjerstiSteien** [comment]
Dekkes av https://github.com/Informasjonsforvaltning/behov/issues/834
