### ISSUE TITLE
[Brukerhistorie] Opprettelse og registrering/redigering i ett og samme GUI

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#784]
Som: leser av intern begrepskatalog
Ønsker jeg: at opprettelse, registrering/redigering og visning av begreper er mulig i ett og samme brukergrensesnitt
Slik at: begrepskatalogen blir gjenkjennbar og dagens skille mellom registrering og visning blir borte/mindre.

Det er ønsket at vi har spesielt tett kontakt rundt utviklingen av denne saken, da resultatet har mye å si for mottakelsen av løsningen.

Se: https://github.com/datautvikling/behov/issues/88

Relatert til epos: Informasjonsforvaltning/behov#792 

Brukerhistorier som løser dette behovet: 

- [ ] https://github.com/Informasjonsforvaltning/behov/issues/807
- [ ] https://github.com/Informasjonsforvaltning/behov/issues/902
- [ ] Informasjonsforvaltning/behov#930

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til trådskisser: 
Lenke til design: 
Lenke til løsningsarkitektur:
Grovt estimat: ca 6 uker (avhenger av løsning)

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by synnesol** [comment]
@KjerstiSteien se brukerhistorier https://github.com/datautvikling/behov/issues/100 og https://github.com/datautvikling/behov/issues/99

**Comment by jeffreiffers** [comment]
Forslag til løsning:
Detailvisning er read-only når man kommer fra oversikten og ligner på visningen på data.norge.no. Når man trykker på rediger vises skjemaet slik som det er nå. Her kan man da redigere alle felter.

**Comment by KjerstiSteien** [comment]
Testet ok
