### ISSUE TITLE
[Brukerhistorie] Virksomhetsspesifikt design

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#785]
Som: bruker av intern begrepskatalog
Ønsker jeg: at den interne begrepskatalogen har et design som gjenspeiler designet på virksomheten som eier katalogen
Slik at: Jeg kjenner igjen hvilken virksomhet som eier katalogen

Et minstekrav er at det skal gå an å ha virksomhetsspesifikk logo og farge i intern katalog.

Kan vi legge til rette for at virksomhetene kan legge inn virksomhetsspesifikt design selv?

Se: https://github.com/datautvikling/behov/issues/94

Relatert til epos: Informasjonsforvaltning/behov#792 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til trådskisser: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-(D)?page-id=0%3A1&node-id=84%3A14320&viewport=388%2C48%2C0.55&scaling=min-zoom&starting-point-node-id=84%3A14320&show-proto-sidebar=1&hide-ui=1
Lenke til design: 
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Kan Digdir slippe å forholde seg til et eksternt bibliotek? | Ok fra BR. Venter avklaring fra Skatt | | |
| | | | |

### Akseptansekriterier:

Gitt at jeg er bruker med admin-rettigheter, så skal jeg kunne, 
1. velge logoen som skal vises i toppbanneret i begrepskatalogen, slik at det vises på
  a) treffliste
  b) detaljside for begrep
  c) endringsforslagsliste
  d)  registreringsskjema? (kan vente hvis vanskelig)

2. Kunne velge bakgrunnsfarge og tekstfarge for begrepskatalogen uten at dette valget bryter med wcag-kravene til kontrast. Dette påvirker:
  a) Toppbanner
  b) Sidemeny på treffliste (kan vente hvis vanskelig)
  c) knapper (kan vente hvis vanskelig)

### Utviklingsoppgaver

- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/88
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/89
- [x] Informasjonsforvaltning/catalog-frontend#145
- [x] https://github.com/Informasjonsforvaltning/catalog-admin-service/issues/6
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/32

**Comment by KjerstiSteien** [comment]
Logo og farger kan velges for toppbanner og for de sidene som er del av ny begrepskatalog. Registreringsskjema og forside vil oppdateres etter hvert som vi får flyttet dem over i ny løsning. Test godkjent.
