### ISSUE TITLE
[Brukerhistorie] Opprette, redigere og slette interne kodelister i eksisterende felter i begrepsregistrering

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#786]
Som: Virksomhet som skal bruke intern begrepskatalog
Ønsker jeg: å opprette, redigere og slette interne kodelister, internt eierskap, interne fagområder osv.  
Slik at: jeg kan dokumentere interne forhold ved virksomheten

Eksempler på felter der jeg ønsker interne kodeverk brukt.
Fagområde
Bruksområde
Tildelt

### Tre sider for kodelister: 
* Oversikt over kodelister for innlogget virksomhet
* Oversikt over koder i den enkelte kodeliste
* Detaljert visning av den enkelte koden i en kodeliste.

### Opprette kodelister: 
Kodene i kodelister består av: 
* Kode (URI som genereres automatisk)
* Kodenavn + språktag (kan gjentas)
Regel: Kodenavn må være knyttet til et språk.

Ingen begrensning på hvilke tegn som skal være tillatt.
Må kunne støtte samiske tegn på sikt. 

Det skal være mulig å plassere en kode i en kodeliste i en hierarkisk relasjon til en annen kode i samme kodeliste (oppover/nedover).

### Redigere kodelister
* Selve koden skal ikke kunne endres
* Kodenavn og språk skal kunne endres
* Skal kunne legge til nye kodenavn og språk. 
* Skal kunne legge til nye koder til en kodeliste.
* Etter endring skal alle begrep hvor endret kode er i bruk oppdateres, slik at endringen gjenspeiles på begrepene.

### Sletting av koder i kodeliste: 
* Koder som er i bruk skal kunne slettes, men bruker skal få en advarsel ved forsøk på sletting. 
* I advarselen skal bruker få beskjed om antall begrep som bruker koden, helst med en liste over begrepene som bruker koden.
* Etter sletting skal koden fjernes fra alle begrep som brukte koden

### Sletting av kodelister
* Kodelister som er i bruk av felt kan ikke slettes.
* Ved forsøk på sletting av kodelister som er i bruk, skal bruker få beskjed om dette og en liste over hvilke felt som bruker kodelisten. 
* Kodelister som ikke er i bruk skal kunne slettes. Bruker skal bekrefte sletting før kodelisten slettes. 

Se: https://github.com/datautvikling/behov/issues/81

Relatert til epos: #792 

Relaterte brukerhistorier: 

- [ ] https://github.com/Informasjonsforvaltning/behov/issues/677
 
Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til trådskisser: 
Lenke til design: https://www.figma.com/proto/m7wqpogaZzXrD7jau1Ed4E/Admin-grensesnitt?page-id=422%3A57234&type=design&node-id=422-57241&viewport=993%2C517%2C0.19&scaling=scale-down-width
Lenke til løsningsarkitektur:

### Test 
Lenke: https://catalog-admin.staging.fellesdatakatalog.digdir.no/
Rolle: Administrator

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Er dette en komplett liste over feltene der interne kodeverk skal brukes? Hvis ikke, kan vi få en fullstendig, prioritert liste over dette? | | | |
| Kan dere legge kodelistene som skal brukes i saken, knyttet til felttype? Vi trenger både Skatt og BR sine kodelister. | | | |

### Akseptansekriterier:

Gitt at jeg er bruker med admin-rettigheter, så skal jeg kunne, 
1. opprette kodelister som er brukes av min virksomhet og
- [x] registrere navn på kodelisten. 
- [x]  se ID for kodelisten, denne opprettes automatisk av systemet og skal være en URI. 
- [x] enkelt kunne markere og kopiere ID-en for kodelisten

 2. opprette koder i en kodeliste, 
- [x] ved å registrere navn på koden knyttet til en språktag.
- [x] og kunne legge inn koden på flere språk
- [x] uten å kunne legge inn kodenavn uten å knytte dem til et språk.
- [x] og kunne legge inn en overordnet kode for koden. Overordnet kode må være fra samme kodeliste. En kode kan ikke være overordnet kode for seg selv. 
- [x] og se ID for den enkelte kode, denne genereres automatisk og kan være et løpenummer.
- [x] enkelt kunne markere og kopiere ID-en for de enkelte kodene i kodelisten

3. se en oversikt over kodelister i min virksomhet, med 
- [x] navn på kodelistene 
- [x] mulighet for å velge en kodeliste for å se kodene i kodelisten

4. se en oversikt over kodene i kodelistene, med
- [x] navn på de ulike kodene (et språk holder. Prioritet: bokmål, nynorsk. engelsk)
- [x] visning av hierarki dersom dette finnes. Visningen bør støtte minst 4 nivåer. 
- [x] mulighet for å velge en kode for å se detaljer om koden.

5. velge den enkelte koden i kodelista for å se følgende detaljer om koden,
- [x] navn på koden på ulike språk
- [x] ID for koden
- [x] overordnet kode for koden, dersom dette finnes. 

6. Redigere kodelister,
- [x] ved å endre navn på kodelisten 
- [x] uten å kunne endre selve ID-en til kodelisten
- [x] ved å opprette nye koder i en eksisterende kodeliste ( se akseptansekriterie 2)

7. Redigere kodene i en kodeliste
- [x] ved å endre navn på koden på ulike språk
- [x] ved å legge til nye navn på koden knyttet til språk
- [x] ved å legge inn/endre overordnet kode for koden. Overordnet kode må være fra samme kodeliste. En kode kan ikke være overordnet kode for seg selv. 
- [x] uten å kunne endre selve ID-en til koden
- [x] og kunne se at alle begrep som bruker koden som ble endret har blitt oppdatert med endringene jeg la inn. Endringen skal føre til ny høsting av begrepene til portal.

8. Slette koder i en kodeliste
- [ ] og få en advarsel selv om koden ikke er i bruk, med spørsmål om jeg virkelig ønsker å slette koden.
- [ ] og få en advarsel dersom koden jeg forsøker å slette er i bruk, med beskjed om antall begrep som bruker koden, helst med en liste over begrepene som bruker den. 
- [ ] og kunne velge å slette koden likevel, selv om koden er i bruk og ikke er brukt av et obligatorisk felt.
- [ ] uten å kunne slette koder som er i bruk av et obligatorisk felt. 
- [ ] og kunne se at koden er fjernet fra begrep som brukte koden etter at koden er slettet. Sletting av koder som er i bruk skal føre til ny høsting av begrepene til portal. 

9. Slette kodelister
- [ ] og og få en advarsel selv om koden ikke er i bruk, med spørsmål om jeg virkelig ønsker å slette koden. 
- [ ] og få en advarsel dersom koden jeg forsøker å slette er i bruk og derfor ikke kan slettes, med en liste over hvilke felt som bruker kodelisten.
- [ ] uten å kunne slette kodelister som er i bruk. 

---------------------------------------------------------------------------------------------------------
Saker til utvikling:
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/39
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/37
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/36
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/39
- [x] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/37

**Comment by synnesol** [comment]
@KjerstiSteien formålet med denne brukerhistorien er at det vil oppstå ulike behov i ulike virksomheter. Vi ønsker å ha mulighet til å opprette, redigere og slette kodelister. Vi må snakke om dette for å avklare behov og muligheter knyttet til denne brukerhistorien.

**Comment by KjerstiSteien** [comment]
@synnesol dette får bli et av temaene i første møte etter nyttår.

**Comment by KjerstiSteien** [comment]
Til pre-refinement: Sjekk at vi har planlagt for å dekke alle behovene beskrevet her.

**Comment by jeffreiffers** [comment]
Mateus avstemmer designet med Breg og Skatt på mandag.

**Comment by KjerstiSteien** [comment]
Kan testes med adminbruker på: https://catalog-admin.staging.fellesdatakatalog.digdir.no/

**Comment by KjerstiSteien** [comment]
Test 13.09.2023:

Gitt at jeg er bruker med admin-rettigheter, så skal jeg kunne,

opprette kodelister som brukes av min virksomhet og
a) registrere navn på kodelisten. **OK**
b) se ID for kodelisten, denne opprettes automatisk av systemet og skal være en URI. **OK**
c) enkelt kunne markere og kopiere ID-en for kodelisten. **OK** - _kan dra musepekeren over og markere ID. Dobbelklikk tar med felttekst ID: Tenker at man kan leve med dette._ 

opprette koder i en kodeliste,
a) ved å registrere navn på koden knyttet til en språktag. **OK**
b) og kunne legge inn koden på flere språk **OK**
c) uten å kunne legge inn kodenavn uten å knytte dem til et språk. **OK** - ikke mulig i grensesnittet.
d) og kunne legge inn en overordnet kode for koden. Overordnet kode må være fra samme kodeliste. En kode kan ikke være overordnet kode for seg selv. En kode kan ikke være underordnet kode for en av sine egne underordnede koder eller underordnede koder av denne.  **FEILET** Kan legge koder under koder som er underordnet underordnede koder (altså to steg under koden jeg tester med) 
e) og se ID for den enkelte kode, denne genereres automatisk og kan være et løpenummer. Se ID **OK** Generere ID 
f) enkelt kunne markere og kopiere ID-en for de enkelte kodene i kodelisten. **OK**

se en oversikt over kodelister i min virksomhet, med
a) navn på kodelistene **OK**
b) mulighet for å velge en kodeliste for å se kodene i kodelisten **OK** 

se en oversikt over kodene i kodelistene, med
a) navn på de ulike kodene (et språk holder. Prioritet: bokmål, nynorsk. engelsk)
b) visning av hierarki dersom dette finnes. Visningen bør støtte minst 4 nivåer. **OK**
c) mulighet for å velge en kode for å se detaljer om koden. **OK**

velge den enkelte koden i kodelista for å se følgende detaljer om koden,
a) navn på koden på ulike språk **OK**
b) ID for koden **OK**
c) overordnet kode for koden, dersom dette finnes. **OK**

Redigere kodelister,
a) ved å endre navn på kodelisten **OK**
b) uten å kunne endre selve ID-en til kodelisten **OK**
c) ved å opprette nye koder i en eksisterende kodeliste ( se akseptansekriterie 2) **OK**

Redigere kodene i en kodeliste
a) ved å endre navn på koden på ulike språk **OK**
b) ved å legge til nye navn på koden knyttet til språk **OK**
c) ved å legge inn/endre overordnet kode for koden. Overordnet kode må være fra samme kodeliste. En kode kan ikke være overordnet kode for seg selv. En kode kan ikke være underordnet kode for en av sine egne underordnede koder eller underordnede koder av denne.
d) uten å kunne endre selve ID-en til koden **OK**
e) og kunne se at alle begrep som bruker koden som ble endret har blitt oppdatert med endringene jeg la inn. Endringen skal føre til ny høsting av begrepene til portal. 

Slette koder i en kodeliste
a) og få en advarsel selv om koden ikke er i bruk, med spørsmål om jeg virkelig ønsker å slette koden. **OK**
b) og få en advarsel dersom koden jeg forsøker å slette er i bruk, med beskjed om antall begrep som bruker koden, helst med en liste over begrepene som bruker den.
c) og kunne velge å slette koden likevel, selv om koden er i bruk og ikke er brukt av et obligatorisk felt.
d) uten å kunne slette koder som er i bruk av et obligatorisk felt.
e) og kunne se at koden er fjernet fra begrep som brukte koden etter at koden er slettet. Sletting av koder som er i bruk skal føre til ny høsting av begrepene til portal.

Slette kodelister
a) og og få en advarsel selv om koden ikke er i bruk, med spørsmål om jeg virkelig ønsker å slette koden. **OK**
b) og få en advarsel dersom koden jeg forsøker å slette er i bruk og derfor ikke kan slettes, med en liste over hvilke felt som bruker kodelisten.
c) uten å kunne slette kodelister som er i bruk.


Test av UU:
Tabulator fungerer stort sett som forventet. Enkelt å tabbe seg mellom elementene på siden. Kan velge funksjoner med enter. Ingen tastaturfeller.
**Tabulatormarkør forsvinner når jeg forsøker å tabbe mellom kodelister.**

**Comment by KjerstiSteien** [comment]
Oppsummering etter test, utover det som er nevnt over:
* Noen småbugs, lagt til i https://github.com/Informasjonsforvaltning/catalog-frontend/issues/284 
* Gjenstår å teste endring og sletting av koder/kodelister der koder er i bruk og der koder er i bruk i obligatoriske felt. 
* Må teste litt mer på kodenavn på ulike språk - usikker på om det er realistisk at noen legger inn kode på andre språk enn norsk bokmål uten å legge inn norsk bokmål i tillegg.
