### ISSUE TITLE
[Brukerhistorie] Se endringslogg på et begrep

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#787]
Som: lesebruker
Ønsker jeg: å se en oversikt over endringer i alle felt på et begrep, hva endringen bestod i, når endringen ble gjort, og hvem som har gjort endringer
Slik at: jeg kan følge med på hva som er gjort og det er etterprøvbart

Mer konkret ønsker vi:

Speile" gjeldende og forrige versjon ned på feltnivå, se trådskisser
Endring av status på et begrep må også tas med i endringsloggen
Endringsloggen bør gjelde alle felter som kan endres på, pluss metadata om brukernavnet som endret, og når.

Det må være lett å orientere seg i endringsloggen og kommentarfeltene også når det er mange endringer eller kommentarer.

Lagring av historikk er det aller viktigste, men vi har ambisjoner om at de vises også.

Se: https://github.com/datautvikling/behov/issues/77

Relatert til epos: #792 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til trådskisser: https://user-images.githubusercontent.com/33412376/144229740-94dafde5-1c7e-4f44-9a3f-2633f3ccefc5.png
Lenke til design: https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7525%3A157668&node-id=7708%3A185636&viewport=-4689%2C725%2C0.66&scaling=min-zoom&starting-point-node-id=7534%3A168387 (OBS! mangler lenke til se mer. Før man trykker se mer skal kun nytt innhold vises. Når man trykker på se mer får man også se tidligere innhold i feltene som ble endret).
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| | | | |
|  | | | |

### Akseptansekriterier:

Gitt at jeg er innlogget, uavhengig av rolle (les, skriv) 
så skal jeg få presentert alle endringer på alle felt i begrepet. 
- [x] se hva endringen bestod i
- [x] tidsstempel - når endringen ble gjort
- [x] hvem som har gjort endringer
- [x] Endringer skal presenteres i motsatt kronologisk rekkefølge (nyeste endring øverst)
- [ ] Plassering, krav
- [ ] speiling

1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

-----------------------------------------------------------------------------------------------------------------------------------------
Frontend: 

- [x] https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/495
- [ ] #842

Backend:

- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/14
- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/12
- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/9
- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/8
- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/2
- [x] https://github.com/Informasjonsforvaltning/catalog-history-service/issues/11
- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/181

**Comment by KjerstiSteien** [comment]
Mangler vi en frontendoppgave på design her?

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Vil det være nyttig å kunne huke av på endringslogg og kommentarer samtidig, slik at man kan se disse under hverandre, eller holder det å se en av gangen? Hvis det siste så endrer vi til faner eller radioknapper i designet.

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Vil det være nyttig å kunne huke av på endringslogg og kommentarer samtidig, slik at man kan se disse under hverandre, eller holder det å se en av gangen? Hvis det siste så endrer vi til faner eller radioknapper i designet.

**Comment by kristinekv** [comment]
> @synnesol @kristinekv Vil det være nyttig å kunne huke av på endringslogg og kommentarer samtidig, slik at man kan se disse under hverandre, eller holder det å se en av gangen? Hvis det siste så endrer vi til faner eller radioknapper i designet.

Begge deler fungerer helt fint for meg :)

**Comment by synnesol** [comment]
> > @synnesol @kristinekv Vil det være nyttig å kunne huke av på endringslogg og kommentarer samtidig, slik at man kan se disse under hverandre, eller holder det å se en av gangen? Hvis det siste så endrer vi til faner eller radioknapper i designet.
> 
> Begge deler fungerer helt fint for meg :)

Begge deler funker fint for oss også, så dere kan avgjøre hva dere synes er best :)

**Comment by KjerstiSteien** [comment]
Kommentarer til test: 

Jeg kan se hva som ble lagt til i den nye endringen, men jeg kan ikke se hva det ble endret fra. Usikker på om det er ok for lanseringsversjon. 

Forstår ikke hva som menes med "plassering, krav" og "speiling"

**Comment by KjerstiSteien** [comment]
Visningen i endringsloggen ved oppretting av begrep ser litt rar ut. Noen felt som ikke er fylt ut er ikke med. Se stein eidem sitt begrep test av endringslogg. 

- [ ] Speile" gjeldende og forrige versjon ned på feltnivå, se trådskisser **Restanse, løses senere (middels prio).**
- [ ] Endringsloggen viser endring for alle redigerbare felt. **Liten feil knyttet til egendefinerte interne felt https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/812 Restanse, løses senere (middels prio)**
- [x] Endringsloggen inneholder brukernavnet på den som endret begrepet. 
- [x] Endringsloggen inneholder tidspunkt for endring av begrepet.

**Comment by KjerstiSteien** [comment]
Godkjent med noen restanser.
