### ISSUE TITLE
[BRUKERHISTORIE] Filtrering i intern Begrepskatalog

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#791]
Som: leser i virksomhetsintern begrepskatalog
Ønsker jeg: å filtrere
Slik at: jeg enkelt kan finne fram til de begrepene jeg vil se

Det må være mulig å filtrere på følgende felter. som en start:
Fagområde (kodeliste) - avhengig av administering av interne kodelister i admingrensesnitt
Publiseringstilstand (Skatt ønsker ikke å filtrere på dette) - avhengig av å hente publiseringstilstand ut fra begrepsstatus
Begrepsstatus (kodeliste) Samme kodeliste for BR og Skatt - avhengig av å hente publiseringstilstand ut fra begrepsstatus
Tildelt (personer som er tildelt et begrep) Det må gå an å filtrere på andre enn seg selv. Trenger et søkefelt framfor fixed list. - avhengig av administering av interne kodelister i admingrensesnitt
Egenskapsnavn (boolsk verdi) Spesielt for Skatt - avhengig av administering av interne kodelister i admingrensesnitt
Forretningsbegrep (boolsk verdi) Spesielt for Skatt. - avhengig av administering av interne kodelister i admingrensesnitt

Relaterte brukerhistorier:

- [ ] https://github.com/datautvikling/behov/issues/84 (Brukerhistorie hos Breg)
- [x] https://github.com/Informasjonsforvaltning/behov/issues/806

Relatert til epos: #792

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=899%3A34682&viewport=520%2C695%2C0.5&scaling=min-zoom
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

### Avklaringer: 

| Spørsmål | Svar | Avklart med | Avklart dato |
| ---------- | ----- | ------------- | ------------- |
| Er listen over filtre man har behov for uttømmende? Hvis ikke, kan vi få en uttømmende, prioritert liste? | Det vil dukke opp interne kodelister det er behov for å filtrere på. Bør være mulig å håndtere dette i admingrensesnitt. | Synne Solbakken | 21. des. 2022 |
| | | | | 

### Akseptansekriterier:

Gitt at jeg er innlogget, uavhengig av rolle (les, skriv)
skal jeg kunne filtrere på følgende felter (i første leveranse): 
- [x] Fagområde (kodeliste). Skatt trenger minst tre nivåer (hierarki)
- [x] Publiseringstilstand (Skatt ønsker ikke å filtrere på dette)
- [x] Begrepsstatus (kodeliste) Samme kodeliste for BR og Skatt
- [x] Tildelt (personer som er tildelt et begrep). Det må gå an å filtrere på andre enn seg selv. Tildelt-filteret bør vises som et søkefelt og ikke fixed list over alle brukere, ref virksomhetssøket i sidemeny på data.norge.no 
- [x] **Spesifikt for Skatt:** Egenskapsnavn og forretningsbegrep (boolske verdier, ved filtrering skal begrep med JA-verdi vises)

--------------------------------------------------------------------------------------------------------------------------------------------
Issues utvikling: 

- [x] https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/484
- [x] https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/492
- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/142

**Comment by synnesol** [comment]
@KjerstiSteien vi kan sette opp en foreløpig uttømmende liste som er bra nok til å begynne med, men vi ønsker muligheten til å utvide dette. Det vil blant annet dukke opp en del interne felter med kodelister som det er behov for å filtrere på.
- fagområde
- status
- publiseringsstatus
- tildelt (navn/brukerinfo. f.eks vil jeg ønske å filtrere på alle begrep som er tildelt meg)
- merkelapp

**Comment by KjerstiSteien** [comment]
@pooriamehregan Dekkes alle behovene i denne saken av #484 og #492?

**Comment by pooriamehregan** [comment]
@KjerstiSteien Ikke helt. Men lagde nå nye issuer basert på siste endringene i skissen. De nye issuene dekker da filtrering på Tildelt og Begrepsstatus og er lagt inni https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/492. 
Lurer på Egenskapsnavn og Forretningsbegrep skal også være med i 492, fordi de er fraværende fra skissen? Hvis ikke, så tror jeg nå dekkes alt av de to issuene du nevnte ovenfor. :)

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Skal Egenskapsnavn og forretningsbegrep være mulig å filtrere på? Er dette de to boolske verdiene vi har snakket om for skatt? 

Jeg kutter også språkfilter nå etter møtet vårt på tirsdag. Så lenge vi ikke vet hva kriteriene skal være er det vanskelig å få verdi ut av språkfilteret.

**Comment by KjerstiSteien** [comment]
@matfuru Vi må få Egenskapsnavn og forretningsbegrep inn i skissene. Foreslår at de kan velges med en avhukingsknapp.

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Skal det være mulig å avgrense søk på merknad i tillegg til term (inkl foretrukken term, tillatt term, frarådet term) og definisjon?

**Comment by kristinekv** [comment]
> @synnesol @kristinekv Skal det være mulig å avgrense søk på merknad i tillegg til term (inkl foretrukken term, tillatt term, frarådet term) og definisjon?

@KjerstiSteien Det er en nice to have (ikke need to have), supert å få det opp hvis det er enkelt.

**Comment by kristinekv** [comment]
> @synnesol @kristinekv Skal Egenskapsnavn og forretningsbegrep være mulig å filtrere på? Er dette de to boolske verdiene vi har snakket om for skatt?
> 
> Jeg kutter også språkfilter nå etter møtet vårt på tirsdag. Så lenge vi ikke vet hva kriteriene skal være er det vanskelig å få verdi ut av språkfilteret.

@KjerstiSteien OK for oss å fjerne språkfilter i treffliste. 

Stemmer at Egenskapsnavn og Forretningsbegrep er interne boolske verdier for Skatt, som vi ønsker å kunne filtrere på.

**Comment by matfuru** [comment]
Jeg har fjernet språkfilter og satt inn Egenskapsnavn og forretningsbegrep. Oppdatert skisse her: https://www.figma.com/proto/aUbrqwhcDAaCcAuXlLmPhV/Portal-%E2%80%93%C2%A0Concept-internal?page-id=899%3A34681&node-id=1159-41103&viewport=73%2C645%2C0.28&scaling=min-zoom

**Comment by matfuru** [comment]
Oppdatert skisse: https://www.figma.com/proto/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?page-id=1%3A668&node-id=1-4176&viewport=-1328%2C351%2C0.23&scaling=scale-down-width

**Comment by matfuru** [comment]
ser ut som linken over ikke viser innhold: Her er den oppdatert: https://www.figma.com/proto/CsZl0GuNdXtefq4KYGfPs9/Begrepskatalog?page-id=1%3A668&node-id=63-28833&viewport=560%2C385%2C0.11&scaling=scale-down-width

**Comment by KjerstiSteien** [comment]
Testet ok. Filtre spesifikt for skatt kan settes opp i admingrensesnittet.
