### ISSUE TITLE
[BRUKERHISTORIE] Publiseringstilstand

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#793]
Som: Begrepseier
Ønsker jeg: å kunne publisere begreper i begrepskatalogen
Slik at: begrepene blir synlig for eksterne

Oppgave: 
Frikoble publiseringstilstand i Felles datakatalog ut fra begrepsstatus. Kan gjerne være en boolsk verdi. 
Publiseringstilstand skal avgjøre om begrepet høstes til felles datakatalog eller ikke. 

Se: https://github.com/datautvikling/behov/issues/93

Relatert til epos: Informasjonsforvaltning/behov#792

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

------------------------------------------------------------------------------------------------------------------------------

## Tilknyttede issues
- https://github.com/Informasjonsforvaltning/concept-catalog/pull/161
- [x] Informasjonsforvaltning/catalog-frontend#84
- https://github.com/Informasjonsforvaltning/concept-catalog/issues/291

**Comment by terjesyl** [comment]
Kan brytes ned i issues.

**Comment by NilsOveTen** [comment]
Skal være løst av https://github.com/Informasjonsforvaltning/concept-catalog/pull/163

**Comment by jeffreiffers** [comment]
@NilsOveTen Vi mangler publiseringsdato i tillegg til bool verdi. Bedre at vi dropper boolean og kun bruker dato isteden.

**Comment by KjerstiSteien** [comment]
Testet ok. Med ny håndtering av publiseringstilstand mister vi noe validering av enkelte felt. Dette vil vi følge med på gjennom kvalitetsarbeidet vi planlegger sammen med Termportalen fremover.
