### ISSUE TITLE
[BRUKERHISTORIE] Flere statuser for begrep

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/behov#794]
Som: begrepseier
Ønsker jeg: støtte for flere statuser i begrepskatalogen
Slik at: jeg kan synliggjøre hvor i løpet et begrep ligger

<html>
<body>

 

Status |Forklaring |Foreløpig mapping EU
-- | -- | --
Utkast | Begrepsbruker jobber med begrepet. Det er ikke kvalitetssikret enda. | [Draft](https://op.europa.eu/s/yJ3g)
Kvalitetssikring | Begrepet er sendt til kvalitetssikring av linja/fagområdet som skal bli begrepsansvarlig. | [Candidate](https://op.europa.eu/s/yJ3h)
(til) Godkjenning | Begrepet er sendt til godkjenning av begrepskatalogadministrator. Dette er en teknisk/metodisk sjekk, ikke en faglig innholdssjekk. | [Waiting](https://op.europa.eu/s/yJ3i)
Godkjent | Begrepet er godkjent og eierskapet er plassert. | [Current](https://op.europa.eu/s/yJ3f)
Avvist | Begrepet ble laget ved en feil – dette bør slettes. Det er ikke behov for begrepet – skal være mulig å gå fra utkast, kvalitetssikring og til godkjenning | [Deprecated](https://op.europa.eu/s/yJ3l)?
Utgått | Begrepet har vært gyldig, men det er ikke lenger er ønskelig at det brukes og det heller ikke vil bli vedlikeholdt fra virksomhetens side. Denne statusen gjelder bare begrep som har vært Godkjent. | [Retired](https://op.europa.eu/s/yJ3k)

 

</body>
</html>

Nye statuser som samsvarer i stor grad med EU-statusene
![image](https://github.com/Informasjonsforvaltning/behov/assets/64894537/a76b83d3-066a-45f7-aece-ea1d49b20923)Se: https://github.com/datautvikling/behov/issues/64

Oversettelser av statusbeskrivelsene: 
- Statusen “KANDIDAT” angir at et begrep er foreslått, og krever godkjenning.
- Statusen “GJELDENDE” angir at begrepet er i bruk. Dette er den versjonen av begrepet som skal brukes i nåværende periode.
- Statusen “UTKAST” brukes for utarbeidelse av begreper som skal bli “KANDIDAT”.
- Statusen “FORELDET” angir at begrepet er trukket tilbake og ikke lenger skal brukes. Hvis en etterfølger er angitt, bruk dette begrepet i stedet.
- Statusen “TIL GODKJENNING” angir at begrepet “KANDIDAT” er sendt til godkjenning.

Relatert til epos: #792

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Grovestimat: 6-8 uker (inkludert admingrensesnitt)

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

--------------------------------------------------------------------------------------------------------------------------------------

Utviklingsoppgaver: 
- [x] https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/151
- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/179

**Comment by jeffreiffers** [comment]
Hvordan skal GUI til avansert se ut? Slik som dette?
![image](https://user-images.githubusercontent.com/430997/209133736-1a24cdf3-1228-4a13-b257-4457af8ebab0.png)

**Comment by terjesyl** [comment]
Trenger adminløsning

**Comment by KjerstiSteien** [comment]
@NilsOveTen er det denne du jobber med nå? Er den fortsatt blocked?

**Comment by NilsOveTen** [comment]
Ja, det er de to issuene jeg lagde i går jeg jobber med:
Har startet på dette i reference-data: https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/151
Dette i concept-catalog er blokkert frem til jeg lander det i ref-data: https://github.com/Informasjonsforvaltning/concept-catalog/issues/179
Vi trenger også to frontend-issue jeg ikke har lagd enda, de er uansett blokkert av backend-issuene.
Må vi også få dette ut til data-norge før behovet er løst? trenger i så fall også issues i reasoning og fdk-portal

**Comment by KjerstiSteien** [comment]
Ja, vi bør løse dette helt ut i data.norge.no for at dette behovet skal være løst fullt ut. Lager dere saker på det som mangler?

**Comment by NilsOveTen** [comment]
Har oppdatert lista med tilknyttede issues:

For å få det med i registrering:
- https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/151
- https://github.com/Informasjonsforvaltning/concept-catalog/issues/179
- https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/532
- https://github.com/Informasjonsforvaltning/catalog-frontend/issues/125

For å kunne vise statusene i fdk-portal:
- https://github.com/Informasjonsforvaltning/fdk-reasoning-service/issues/93
- https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/277
- https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/251
- https://github.com/Informasjonsforvaltning/fdk-portal/issues/1720

**Comment by KjerstiSteien** [comment]
@synnesol @kristinekv Hva tror dere om å bruke de norske termene fra EU-vokabularet? Dette er lettere å forsvare for oss når vi endrer begrepsstatusene for alle. Hvis det er flere som ønsker andre navn, er kanskje det beste å få endret oversettelsene i vokabularet? Hører gjerne deres tanker rundt dette. 

## Oversikt over statusene i EU-vokabularet opp mot deres forslag:

| EU engelsk | EU norsk | Brreg/skatt | 
| ---------- | -------- | ----------- | 
| Candidate | Kandidat | Kvalitetssikring |
| Current | Gjeldende | Godkjent |
| Draft | Utkast | Utkast |
| Retired | Foreldet | Utgått |
| Revised | Revidert | - | 
| Waiting | På vent | Til godkjenning |
| Deprecated | Frarådet | Avvist |

**Comment by kristinekv** [comment]
> @synnesol @kristinekv Hva tror dere om å bruke de norske termene fra EU-vokabularet? Dette er lettere å forsvare for oss når vi endrer begrepsstatusene for alle. Hvis det er flere som ønsker andre navn, er kanskje det beste å få endret oversettelsene i vokabularet? Hører gjerne deres tanker rundt dette.
> 
> ## Oversikt over statusene i EU-vokabularet opp mot deres forslag:
> EU engelsk	EU norsk	Brreg/skatt
> Candidate	Kandidat	Kvalitetssikring
> Current	Gjeldende	Godkjent
> Draft	Utkast	Utkast
> Retired	Foreldet	Utgått
> Revised	Revidert	-
> Waiting	På vent	Til godkjenning
> Deprecated	Frarådet	Avvist

Jeg synes dette er en veldig god ide, og "riktig", bortsett fra at EU-oversettelsene ikke er så gode etter min mening. Jeg synes vi mister en del semantikk, men det kan hende det er en vanesak. Jeg vet ikke hvordan vi evt. kan gå frem for å endre de oversettelsene?

**Comment by jimjyang** [comment]
@Te-Bert @KjerstiSteien @synnesol @kristinekv 

Unnskyld at jeg blander meg inn i denne diskusjonen :-), og med fare for at jeg ikke har forstått behovene korrekt ...

Jeg er ikke enig i at "godkjent" skal være anbefalt term (heller ikke synonym) til begrepet som har engelsk term "current". Definisjonen til begrepet sier "... in force", dvs. "... i kraft" og dermed "gjeldende". At noe er "godkjent" betyr ikke nødvendigvis også "gjeldende", man kan f.eks. ha godkjent ting som skal tre i kraft i fremtid (dermed ennå ikke "gjeldende"). "Godkjent" er dessuten for meg en slags "prosess-status" mens "gjeldende" er en slags "bruksstatus" (i mangel av bedre ord). 

Tilsvarende er jeg heller ikke enig i å bruke "avvist" som anbefalt term (eller synonym) for begrepet med engelsk term "deprecated". Definisjonen til begrepet sier "... no longer in force and should not be used", dvs. "... har vært i bruk men ikke bør brukes lenger". Man kan avvise et helt nytt begrepsforslag uten at begrepet har vært i bruk. Man kan også avvise et begrepsforslag fordi det er utenfor mandatet til vedkommende virksomhet å definere, uten nødvendigvis samtidig også å si at begrepet ikke bør brukes. "Avvist" er en slags "prosess-status" mens "frarådet" er en slags "bruksstatus". 

Hvis jeg har forstått behovene korrekt må man gjerne opprette/tilføye nye status-verdier for denne type "prosess-statuser", dvs. med nye definisjoner (noe a la "forklaring" i tabellen som Terje tok med i begynnelsen av denne tråden). 

Det er selvsagt rom for forbedringer når det gjelder norske oversettelser av termer på EU-listene (altså ikke bare denne listen), ved at vi oversender våre forslag til Publications Office i EU som forvalter slike lister.

**Comment by KjerstiSteien** [comment]
Testet ok. Statuser som støttes per nå: Kandidat, Gjeldende, Utkast, Avvist, Foreldet, Til godkjenning. Alle statuser er knyttet til Euvoc, med unntak av avvist.
