### ISSUE TITLE
[BRUKERHISTORIE] Side for tilgjengelighetserklæringen til data.norge.no

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#798]
Som: Bruker av data.norge.no
Ønsker jeg å: kunne se tilgjengelighetserklæringen for nettstedet og finne ut hvor jeg skal henvende meg om jeg har spørsmål eller klager om tilgjengeligheten.
Slik at: Jeg kan finne ut om dere kjenner til feil som påvirker min evne til å bruke siden og hva planen deres er for å løse dem, og slik at jeg kan melde fra dersom jeg oppdager en feil som ikke er på deres radar. 

Relatert til epos:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk (Som del av uu-kravene som trer i kraft 1. februar, skal vi tilgjengeliggjøre tilgjengelighetserklæringen på nettsidene våre.)

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7229%3A151670&node-id=7306%3A147110&viewport=-4512%2C1704%2C0.8&scaling=min-zoom
Lenke til tekst på bokmål:
Lenke til tekst på nynorsk: 
Lenke til tekst på engelsk:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by KjerstiSteien** [comment]
@matfuru kan du legge inn lenke til skisser her?

**Comment by KjerstiSteien** [comment]
@AinaEngen kan du se på skissene til matteus og lage forslag til tekst? Utgangspunktet er tilgjengelighetserklæringen. Vi bør ha tekst på alle tilgjengelige språk. Bør være klart tidlig neste uke. Si fra om du trenger bistand.

**Comment by matfuru** [comment]
her er linken til skissen:

https://www.figma.com/proto/tkHD7njZcjSNJIAPDnyN4d/Portal-%E2%80%93%C2%A0Search?page-id=7229%3A151670&node-id=7306%3A147110&viewport=-4512%2C1704%2C0.8&scaling=min-zoom

**Comment by KjerstiSteien** [comment]
Vi klarer oss med å lenke direkte til tilgjengelighetserklæringen på https://uustatus.no/nb/erklaringer/publisert/8020b962-b706-4cdf-ab8b-cdb5f480a696
