### ISSUE TITLE
[BRUKERHISTORIE] Se forhåndsvisning av begrep 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#80]
Som: Skrivebruker i registreringsløsningen til Felles begrepskatalog
Ønsker jeg å: kunne se en forhåndsvisning av begrep uavhengig av om begrepet er publisert
Slik at: jeg kan få oversikt over innholdet i begrepet. 

Trenger en knapp for "Forhåndsvisning" i statusbaren. Det må også kunne gå an å "avslutte forhåndsvisning" og gå tilbake til redigeringsvindu. 

Relatert til epos: #329 
Relatert til brukerhistorie: #78 
Lenke til design: https://invis.io/3SRCN149CQN#/356259892_BEGREP-REG-LESEROLLE-Alle-Felter--D-
Lenke til løsningsarkitektur: slik eg forstår dette, representerer denne brukerhistorien front-end funksjonalitet for å støtte "forhåndsvisning".

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Prioritet fra innføringteam etter prio-runde på resterende brukerbehov "Del 3", 21.8.2019: Kritisk (høyest prioritet)

**Comment by lillelars** [comment]
@marittor  Skal dette bare gjøres for Begrep? Er ikke dette behovet ønskelig for Datasett og API også? Skal vi estimere ut fra et paraply-perspektiv eller at det bare gjøres på begrep i første omgang

**Comment by marittor** [comment]
> 
> 
> @marittor Skal dette bare gjøres for Begrep? Er ikke dette behovet ønskelig for Datasett og API også? Skal vi estimere ut fra et paraply-perspektiv eller at det bare gjøres på begrep i første omgang

@lillelars Det tenker jeg at @joebrreg, evt. datasettgruppa og API-gruppa bør si noe om, mener å ha hørt at dette er et behov for førstnevnte.

**Comment by marittor** [comment]
Prioritet fra innføringteam etter prio-runde på resterende brukerbehov "Del 3", 21.8.2019: Kritisk (høyest prioritet)

**Comment by stigbd** [comment]
Er det godt forstått kva "forhåndsvisning" er? Er det å simulere gui-et til søkeportalen i registreringsløsningen? (Dyrt) Eller er det å gi oversiktlig les av detaljside for begrep? (Billig)

**Comment by marittor** [comment]
Det som er tenkt er å kunne se en forhåndsvisning i registreringsløsningen, ikke i portal. Det kan godt hende det holder å gjenbruke slik det ser ut for lesebruker som går inn på et begrep i registreringsløsningen.
