### ISSUE TITLE
[BRUKERHISTORIE] PUBLISERE et begrep som står i utkast 

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#81]
Som: skrivebruker
Ønsker jeg å: kunne publisere et begrep som står i status "Utkast"
Slik at: begrepet får status "Publisert" 
OG det blir tilgjengelig i Felles datakatalog Portal.

Relatert til epos: #176 
Relatert til brukerhistorie: #24 #25 

**Trådskisse**
Begrepet er publisert: https://69d4ft.axshare.com/#g=1&p=begrepet_er_publisert

Lenke til design: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356259403
Lenke til løsningsarkitektur: se epos

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Som bruker med skrivetilgang skal jeg kunne publisere et begrep og dermed bytte status fra "Utkast" til "Publisert"
⦁	Alle obligatoriske felt må være utfylt for å kunne publisere

Dekkes ikke:  
⦁	Avpublisering

Referanser:

Scenario: Som bruker med skrivetilgang skal jeg kunne publisere et begrep og dermed bytte status fra "Utkast" til "Publisert"
Gitt at bruker er pålogget med skrivetilgang
Når bruker åpner et begrep og trykker på knappen Publisere
Så skal status endres fra "Utkast" til "Publisert"

Scenario: Alle obligatoriske felt må være utfylt for å kunne publisere
Gitt at bruker er pålogget med skrivetilgang
Når bruker åpner et begrep der ikke alle obligatoriske felt er fylt ut
Så skal ikke knappen "Publisere" vere disablet
(evt: Så skal en ikke kunne publisere)

**Comment by sindresandvik2** [comment]
@marittor Skal det også vere mulig å avpublisere?

**Comment by marittor** [comment]
@sindresandvik2 : Ut fra referatet til innføringsteamet leser jeg: "Vi skal ikkje ha avpublisering, vi må versjonshåndtere (semantisk versjonering). (Impliserer at vi ser på et begrep som et dokument som representerer en “kontrakt”.)". Ad versjonering må dette tenkes mer rundt.

**Comment by stigbd** [comment]
Validering må skje på bakgrunn av kravene i Difi sin Forvaltningsstandard for beskrivelse av begreper - Versjon 2.0, vedlegg A:
https://doc.difi.no/data/forvaltningsstandard-begrepsbeskrivelser/#vedlegga
