### ISSUE TITLE
[BRUKERHISTORIE] Forbedre brukeropplevelse på versjonering

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#831]
Som: begrepseier
Ønsker jeg å: få noen flere verktøy til å si noe om endringer
Slik at: jeg får en bedre brukeropplevelse. 

Dagens løsning med versjonering oppleves som unødvendig tung og det er vanskelig å få oversikt over utkastene man lager. 

Hvis du vil endre på et godkjent begrep kan det gjøres på to måter:
- Redigere godkjent begrep (rediger knapp) (Skrivebruker/admin)
- Foreslå endring på godkjent begrep (lesebruker) se https://github.com/Informasjonsforvaltning/behov/issues/854 

Gitt at jeg trykker på rediger-knappen så skal redigeringssiden til begrepet dukke opp.
Skal ha mulighet til å lagre endringer ved å trykke på en lagre-knapp når man gjør endringer. 

Løsningen bør også oppdatereres til å inkludere minor, major, patch. Dette kunne vært løst med knapper som redigerer selv kan velge. Må gå an å velge minor, major, patch - Obligatorisk å velge. Trenger ikke å legge logikk på hva som er minor, major, patch. Dette er subjektive påstander som den enkelte redigerer må vurdere. På sikt kan man se om det er interessant å lage noe logikk knyttet til versjonsnummer og statuser.

Minor, major og patch påvirker versjonsnummeret slik: 
Major: Første ledd økes med 1 **x**.x.x
Minor: Andre ledd økes med 1: x.**x**.x
patch: Siste ledd økes med 1: x.x.**x**

Relatert til epos:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at jeg er logget inn med en bruker som har skrivetilgang eller tilgang på et høyere nivå, så skal, 
1. jeg finne en inngang til redigering av begrep på detaljsiden for begrepet
  a) og kunne klikke på den
  b) knappen skal føre meg til redigeringsskjema for begrepet. 
2. jeg finne en lagreknapp på redigeringsskjema for begrepet
  a) Og kunne klikke på den
  b) Klikk på knappen fører til at endringene blir lagret. 
  c) Endringer blir _ikke_ lagret automatisk
3. jeg kunne endre versjonsnummer selv
a) ved å fylle inn tekstfelt for major, minor og patch
b) for publiserte begrep kan versjonsnummer ikke være mindre enn forrige versjonsnummer. 

------------------------------------------------------------------------------------------------------------------------------------------
Løsning: 
* Vi støtter minor, major, patch. Skrivebruker velger mellom disse selv. 
* Skrivebruker får mulighet til å endre versjonsnummer i felt for versjonsnummer. 
* Logikk knyttet til publisering til data.norge.no beholdes, vi legger ikke på logikk for versjonsnummer internt i katalogen. 

### Utviklingsoppgaver
- [x] Informasjonsforvaltning/concept-catalog-gui#535
- [x] https://github.com/Informasjonsforvaltning/concept-catalog/issues/198

**Comment by marittor** [comment]
@synnesol, @kristinekv @ragnhag

**Comment by KjerstiSteien** [comment]
Til pre-refinement: Trengs det design her? Bryt ned så langt dere kan uten design og kommenter gjerne hva dere eventuelt trenger design på.

**Comment by KjerstiSteien** [comment]
Test: 
Logget inn som skrivebruker Stein Eidem
- [x] jeg finner en inngang til redigering av begrep på detaljsiden for begrepet 
- [x] og kan klikke på den
- [x] knappen fører meg til redigeringsskjema for begrepet.

- [x] jeg finne en lagreknapp på redigeringsskjema for begrepet
- [x] Før jeg gjør endringer er lagreknappen inaktiv
- [x] Etter at jeg har gjort endringer, kan jeg klikke på lagreknappen
- [x] Klikk på knappen fører til at endringene blir lagret.
- [x] Etter lagring oppdateres informasjon om lagring, så jeg ser at lagring er gjennomført. 
- [x] etter lagring blir jeg værende på redigeringsskjema for begrepet. **FEIL! blir sendt til treffliste i begrepskatalog etter lagring** Issue: https://github.com/Informasjonsforvaltning/concept-catalog-gui/issues/585

- [x] jeg kan endre versjonsnummer selv
- [x] ved å fylle inn tekstfelt for major, minor og patch
- [x] når jeg endrer versjonsnummer for publiserte begrep, får jeg feilmelding hvis versjonsnummeret er lavere enn forrige versjonsnummer.
- [x] Etter lagring kan jeg se at versjonsnummeret på begrepet har endret seg.
