### ISSUE TITLE
[BRUKERHISTORIE] Støtte endret kravnivå for egenskaper/klasser

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#840]
Som: Eier av Skos-ap-no
Ønsker jeg: å oppdatere klasse for egenskaper som har fått ny klasse i SKOS-AP-NO v2.0.3
Slik at: våre løsninger er i henhold til siste versjon av standarden.

Egenskaper med oppdatert URI: 
| Klasse |KlasseURI| Egenskapsnavn |EgenskapsURI | Kravnivå i v1.1.1 | Kravnivå i v2.0.3|
| ------ | ----------- | ---------- | ---------------- | ------------- | ------- |
|Begrep| skos:Concept| Begrep – ansvarlig virksomhet | dct:creator | obligatorisk | anbefalt |
|Begrep| skos:Concept| Begrep - kontaktpunkt | dcat:contactPoint | ikke-obligatorisk | obligatorisk |
|Begrepssamling| skos:Collection |Begrepssamling - kontaktpunkt | dcat:contactPoint | ikke-obligatorisk | obligatorisk |

Forslag til løsning:
Kravnivå obligatorisk: 
Kravnivå anbefalt:
Høsteløsning og portal bør støtte både oppdatert og tidligere URIer for egenskapene, klassene i høsting. 
Registreringsløsning oppdateres med ny URI for egenskaper/klasser. 
Alle begrep i registreringsløsning oppdateres med ny URI for egenskaper/klasser

Relatert til epos: #833 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| Usikker på om ansvarlig virksomhet skal løses her, eller om det løses ved at vi endrer navn på dct:publisher og lager nytt felt for dct:creator | | | |
| Hvordan løser vi kontaktpunkt for begrepssamling? | Vi venter med dette til vi kan håndtere begrepssamling på en bedre måte. Lages egen sak på dette. | @KjerstiSteien | 9.4.2024 |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by Te-Bert** [comment]
Endringer i kravnivå må fremkomme i registreringsløsningen og i portalen: Markert der det er obligatoriske eller  anbefalte felter (som for datasett) 

Kontroll av (obligatorisk) og visning av multiplisitet - Anbefalt term endres fra 1..n til 2..n fordi denne skal finnes på både bokmål og nynorsk. 
I registreringsløsningen må det utføres kontroll av at feltene er utfylt før publisering er tillatt. Ved høsting bør det komme et varsel, men vi må forvente at virksomhetene trenger tid for å få begge målformer på plass, og vi kan ikke "blokkere" for import selv om det her er mangler i forhold til de nye kravene
+
"Fagområde" - endres fra bare tekst til: tekst eller kodet verdi (tilrettelegge for mest mulig strukturerte data)
"Verdiområde" - endres fra bare kodet verdi til: tekst eller kodet verdi (tilrettelegge for å oppgi verdiområde direkte)
Verdiområde (definisjon) må også nummereres fordi det skal være mulig å oppgi en bestemt rekkefølge

**Comment by KjerstiSteien** [comment]
@KjerstiSteien lag egen sak på eget skjema for begrepssamling i regløsning. Stryk ut de feltene vi ikke løser nå.

**Comment by terjesyl** [comment]
Om jeg forstår det rett treffer dette bare registreringsløsningen. Det er kun snakk om endret kravnivå for egenskaper som allerede eksisterte i v1.1.1 av skos-ap-no?
