### ISSUE TITLE
[BRUKERHISTORIE] Datadelingsoversikt for statlig og kommunal sektor

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#841]
Som: premissgiver 
Ønsker jeg å: få oversikt over statlig sektor og kommunal sektor
Slik at: jeg ser hvem som deler data og hvor mye

Relatert til epos: Informasjonsforvaltning/behov#755

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=1%3A47&node-id=159-23792&viewport=15403%2C-843%2C1.14&scaling=scale-down-width
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Endringer sammenlignet med 2022-skisser
Se skisser limt i kommentar under.
1. «Virksomheter i katalogene» --> «Alle virksomheter»
2. Endre radio-buttons («Virksomheter som deler data» / «Alle virksomheter») til checkbox («Vis kun virksomheter med innhold i katalogene»
3. Vi dropper «hurtigvisning» av en virksomhet i første omgang. De små pilene til høyre på hver virksomhetsrad utgår.

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| Legg inn måte å åpne og lukke alle grupper på i visning av stat og kommune | Ja. Vi skal ha funksjonen. Mateus lagar design|Mateus, Kjersti, Terje og Livar | 28.03.2023 |
| Hvordan vise detaljer for virksomheter som ikke har innhold i katalogene (enda) | | | |
| Skal vi ha med summar for gruppene i raden for gruppa? Forslag: fjern frå grupperad, legg inn sum-linje rett under |Ikkje avklara. Vi tenker meir på det. Livar testar på samferdselsprosjekt | | |
| Sortering i lista? | Vi droppar sortering på stat/kommune. Skal vi også sortere den vanlege lista? | | |
| Tekst som forklarer | Livar lagar utkast til tekst og forslag til korleis legge opp (inne i Virksomhetssida vs. eiga side) | | |

### Akseptansekriterier:

Gitt at bruker på data.norge.no går inn på virksomhetssidene, så skal, 
1. bruker kunne se oversikt over statlig sektor samlet
  a) gruppert på toppnivå i staten (departement + domstoler, Stortinget m.m.)
4. bruker kunne se oversikt over kommunal sektor samlet
  a) gruppert på fylke, med fylkeskommune + kommuner i hver gruppe
5. bruker også kunne se enheter i statlig og kommunal sektor som ikke har innhold i katalogene
6. man lett kunne se antall data/API en virksomhet har i katalogene og annet (begrep, informasjonsmodeller, tjeneste/hendelse)
7. kunne se hvor mange nye (siste måned) oppføringer (på tvers av alle kataloger) en virksomhet har
8. se aggregert sum for hver gruppe (samme tall som enkeltvirksomheter, men summert på gruppen)
9. På toppen av både Stat og Kommune, ser man en oppsummering av hvor mange enheter som deler data. F.eks. X av Y deler data.
10. bruker skal kunne lese mer informasjon om datadelingsoversikten, forklaring på hvilke virksomheter som er med i stat/kommune m.m.

### Refinement
- [x] Informasjonsforvaltning/fdk-organization-bff#106
- [x] Informasjonsforvaltning/fdk-portal#1672

**Comment by livarb** [comment]
Skisse som viser korleis Virksomhetssider kan utvidast med visning for Stat og kommune:
![image](https://user-images.githubusercontent.com/3617256/226170509-db3a56ce-138e-4f62-9202-816b18e08d5b.png)

Skisse: vise kommunal sektor, gruppert på fylker
![image](https://user-images.githubusercontent.com/3617256/226330482-f501ab96-64a3-48d2-8e91-98629222c948.png)

Skisse: statleg sektor, gruppert på departement
![image](https://user-images.githubusercontent.com/3617256/226330719-4ae9f65a-1145-4a0f-b894-4e597d62bbf9.png)

Skisse: med tal for verksemder under Finansdepartementet oppdatert:
![image](https://user-images.githubusercontent.com/3617256/226330940-87473a9a-59cd-44e5-860e-93be125ff323.png)

Skisse: oppdaterte tal for nokre av verksemdene under KDD
![image](https://user-images.githubusercontent.com/3617256/226331019-71b9a3e6-52ac-43d6-bae4-c249d807b5c3.png)

**Comment by KjerstiSteien** [comment]
Viser ikke noe under nivå 2. Aggregerer opp organisasjonsnumrene til nivå 2.

**Comment by livarb** [comment]
La til eit nytt akseptansekriterie nr. 9, å vise oppsummert kor mange av verksemdene som deler data.
Tenker dette kun visast på stat- og kommuneoversikt.

Dette var ikkje med i den versjonen av skissene som vi såg på i møtet no i dag.

Utsnitt frå 2022-skisser:
![image](https://user-images.githubusercontent.com/3617256/234813525-8fb814ae-1499-4158-be8f-ac729b9ca9bc.png)

**Comment by matfuru** [comment]
her er oppdaterte 2022 skisser etter dagens møte med @jeffreiffers og @pooriamehregan https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=211%3A29406&node-id=289-26672&viewport=-142%2C483%2C0.34&scaling=min-zoom

**Comment by livarb** [comment]
> her er oppdaterte 2022 skisser etter dagens møte med @jeffreiffers og @pooriamehregan https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=211%3A29406&node-id=289-26672&viewport=-142%2C483%2C0.34&scaling=min-zoom

1. Saknar anledning til å velje "Alle" i tillegg til "Kommune" og "Stat". Korleis er det tenkt at ein kan navigere til den vanlege virksomhetsoversikta? (tilsvarande den ein har i dag)

2. Kan vi kalle «Vis alle felter» noko anna? F.eks. «Utvid alle grupper» og «Lukk alle grupper». «felter» klinger rart for meg.

3. Kan du endre nokre småting i innhaldet i skissa så det blir endå meir realistisk?
Dette er nyttig når eg viser skissa til andre. Folk heng seg fort opp i detaljar som at det står 12 000 virksomheter.
a) Legg inn «Buskerud fylkeskommune» i lag med kommunane — rett etter «Aurskog», så ein ser at fylkeskommunane er med også.
b) Endre til "59 av 366 virksomheter deler data". Betre tal for kommunal sektor. 366 er antallet i kommune-oversikt-scriptet og 59 er eit omtrentleg tal.

**Comment by matfuru** [comment]
> > her er oppdaterte 2022 skisser etter dagens møte med @jeffreiffers og @pooriamehregan https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=211%3A29406&node-id=289-26672&viewport=-142%2C483%2C0.34&scaling=min-zoom
> 
> 1. Saknar anledning til å velje "Alle" i tillegg til "Kommune" og "Stat". Korleis er det tenkt at ein kan navigere til den vanlege virksomhetsoversikta? (tilsvarande den ein har i dag)
> 2. Kan vi kalle «Vis alle felter» noko anna? F.eks. «Utvid alle grupper» og «Lukk alle grupper». «felter» klinger rart for meg.
> 3. Kan du endre nokre småting i innhaldet i skissa så det blir endå meir realistisk?
>    Dette er nyttig når eg viser skissa til andre. Folk heng seg fort opp i detaljar som at det står 12 000 virksomheter.
>    a) Legg inn «Buskerud fylkeskommune» i lag med kommunane — rett etter «Aurskog», så ein ser at fylkeskommunane er med også.
>    b) Endre til "59 av 366 virksomheter deler data". Betre tal for kommunal sektor. 366 er antallet i kommune-oversikt-scriptet og 59 er eit omtrentleg tal.

Jeg har gjort de endringene over:)

**Comment by livarb** [comment]
@matfuru Glimrande at du fekk endra det raskt :) Fekk vist den oppdaterte skissa i to samtaler i går.
Sett gjerne inn 28 (i staden for 59). Rekna ut korrekt tal seint i går.

**Comment by KurtStian** [comment]
Funksjonalitet prioriteres først. Frontend er usikker da man ikke vet hvor krevende er å utvikle nytt design. Forslår å foreløpig implementere i nåværende design.
Del1 - vise informasjon i nåværende design. @NilsOveTen leder arbeid med å lage issue.
Del2 - vise informasjon i nytt design

**Comment by livarb** [comment]
Oppsummert kva funksjonalitet som er på plass, sett opp mot akseptansekriteria
1, 2, 3 og 6 er levert i denne omgang
4 er delvis levert
5, 7 og 8 ikkje implementert i denne omgang. Nr. 8 avhenger av behovsdrivar (meg)
Skal lage ny brukarhistorie på nytt epos der det vi ikkje rakk her er med.
