### ISSUE TITLE
Sette opp innlogging for virksomhetene ved virksomhetenes interne AD.

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#845]
--------------------------------------------------------------------------------------------------------------------
- [x] https://github.com/Informasjonsforvaltning/sso/issues/122
- [x] https://github.com/Informasjonsforvaltning/sso/issues/125

**Comment by KjerstiSteien** [comment]
@NilsOveTen @valosnah Her er resultatene etter dagens test av innlogging: 

* Brreg får ikke logget inn i demo. Skjermbilde av respons:
![MicrosoftTeams-image (14)](https://github.com/Informasjonsforvaltning/behov/assets/110605570/b3e8b554-3c11-46b4-a161-d9221d38c2d7)
* Innlogging fungerer for skatt i både demo og staging (Hurra!)
* Skatt har ikke tilgang til den nye begrepskatalogen i staging - kan være internt hos dem. @kristinekv sjekker opp dette. 

Spørsmål:
* Finnes ny versjon av begrepskatalogen i demo?

**Comment by valosnah** [comment]
@KjerstiSteien 
Er i kontakt med brregs AD-ansvarlig for å verifisere verdiene vi har i Keycloak

Den nye versjonen er ikke klar i prod/demo, men er like rundt hjørnet

**Comment by pooriamehregan** [comment]
@valosnah @NilsOveTen @KjerstiSteien Ser ut som denne saken er ferdig. Kan den lukkes?

**Comment by NilsOveTen** [comment]
> @valosnah @NilsOveTen @KjerstiSteien Ser ut som denne saken er ferdig. Kan den lukkes?

Hvis brreg og skatt sier alt fungerer som det skal så kan vi lukke
