### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over alle etterspørsler

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#852]
Som: bruker
Ønsker jeg å: få oversikt over alle etterspørsler
Slik at: jeg kan se om det er noe interessant (lett se gjennom hele listene, se hvilke som er mest populære)

Relatert til epos: Informasjonsforvaltning/behov#864 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=539%3A8304&type=design&node-id=566-2086&viewport=631%2C469%2C0.18&t=LXUp0f8MkhxLAP5p-1&scaling=scale-down-width&mode=design

Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Endringer i skisse
Sammenlignet med skisse i kommentar under.
1. Ny kolonne for antall visninger

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| Eiga kolonne for kva verksemd etterspørselen evt. er tilknytt| | | |
| Muleg å sjå sine favorittar (e.g. dersom innlogga i Datalandsbyen, vis dei trådane som har fått stemme opp eller abonnerer på varsel)| | | |
| Kunne filtrere vekk lukka etterspørslar (forutset måte å markere Emne som lukka)| | | |
| API / RSS | | | |
| Vis alle. Mulig å velge å se alle etterspørsler uten paginering/vis mer | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

### Refinement
- [ ] Informasjonsforvaltning/fdk-portal#1673
- [ ] Informasjonsforvaltning/fdk-portal#1674

**Comment by livarb** [comment]
Skisse: eiga side på data.norge.no som gir oversikt over etterspørslar
Merk nytt punkt i toppmenyen: «Etterspørsler»
![image](https://user-images.githubusercontent.com/3617256/226329596-5ea4ed69-4603-4840-9bd6-819cca481410.png)

**Comment by KurtStian** [comment]
Setter ned prioritet pga arbeidet med virksomhetsintern begrepskatalog.

**Comment by livarb** [comment]
La inn lenke til [noverande design](https://www.figma.com/proto/1OV9DQyiS6L9fMZvBpTJbY/Datadelingsoversikt-og-ettersp%C3%B8rsler?page-id=539%3A8304&type=design&node-id=566-2086&viewport=631%2C469%2C0.18&t=LXUp0f8MkhxLAP5p-1&scaling=scale-down-width).

Det ser bra ut. Nokre kommentarar:
a) Skal vere mogeleg å vise alle etterspørsler som ei liste utan paginering. F.eks. alternativ nederst. Oppdater gjerne design-skisse for dette.
b) Bør vere opne-data-API-endepunkt med tilhøyrande oppføring i datasett-katalogen.
b) Ikkje med i denne omgang: Støtte for å skilje mellom opne/lukka etterspørsler, kolonne for kva verksemd ein etterspørsel er tilknytt, kunne sjå favorittar.

**Comment by hegeaal** [comment]
Ferdig - kan sees på https://data.norge.no/requests 😄

**Comment by livarb** [comment]
Har lagt nokre bugs og småting i #948 og oppretta brukarhistorie #949 for versjon 2
