### ISSUE TITLE
[BRUKERHISTORIE] Hente oversikt over stat og kommune fra Enhetsregisteret

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#855]
Som: data.norge.no
Ønsker jeg å: hente oversikt over stat og kommune fra Enhetsregisteret
Slik at: jeg kan vise datadelingsoversikt

Relatert til epos: #755 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design: N/A
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Tekniske avklaringer:
1. Utvide organisation-bff

--------------------------------------------------------------------------------------------------------------------------------------------

- [x] https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/97
- [x] https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/98
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1649
- [x] https://github.com/Informasjonsforvaltning/fdk-portal/issues/1650

**Comment by livarb** [comment]
Har oppretta ein tråd i Datalandsbyen om korleis lage oversikt over enhetane i staten:
https://datalandsbyen.norge.no/topic/268/oversikt-over-enhetane-i-staten
Har også skrive eit PHP-script som gjer API-oppslag i data.brreg.no for å hente ut oversikt over staten i to nivå (departement og etat) der nederste nivå også tar med ei liste over alle tilhøyrande org.nr. (underordna enheter og underenheter). Skal få delt det så ein har muleghet til å gjenbruke framgangsmåten om det er ønskjeleg.
Dette er ein jobb som gjer mange kall mot data.brreg.no. Dette er data som endrar seg sjelden, så det passar nok godt til å setjast opp med ein jobb som køyrer kvar natt for å generere datasettet.

For kommunal sektor:
https://datalandsbyen.norge.no/topic/315/oversikt-over-kommunal-sektor

Oppdatert 25/4: Tråden i Datalandsbyen er oppdatert med PHP-script og eksempeldata (JSON) på oversikt over statsforvaltninga
Oppdatert 26/4: La ut oppskrift på korleis lage hierarki av kommunal sektor.

**Comment by NilsOveTen** [comment]
Jeg har oppretta 3 issues som jeg tror vil løse dette på en grei måte mtp hvordan organization-bff fungerer fra før:
https://github.com/Informasjonsforvaltning/fdk-portal/issues/1650, https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/97 og https://github.com/Informasjonsforvaltning/organization-catalog/issues/129

Det vil bety rimelig enkle oppdateringer av fdk-portal og org-bff. Det vi gjør er å utvide organization-catalog til å alltid ha informasjon om alle statlige og kommunale virksomheter.

For virksomhetslista vil det bety at vi kan vise alle kommunale og statlige virksomheter, uansett om de har katalogdata eller ikke, men det vil i tillegg dukke opp private virksomheter som ikke har katalogdata. Akkurat hvilke som dukker opp og ikke vil føles rimelig tilfeldig, hvis det ikke er ønskelig så tror jeg det er bedre å filtere ut private uten katalogdata enn å komplisere koden til org-bff med henting av kommunale og statlige direkte fra enhetsregisteret.

**Comment by livarb** [comment]
@NilsOveTen : Vi bør unngå å dra inn fleire verksemder utan innhald i katalogane enn dei som er i stat og kommune. Om det dukkar opp private verksemder utan innhald i katalogane, blir det både ekstra støy i oversikta og kan tolkast til at det er verksemder som burde hatt innhald, samt at det opnar for å begynne å etterspørre data på dei private verksemdene som måtte dukke opp.

**Comment by NilsOveTen** [comment]
Ok, da filtrerer vi bare ut alt som ikke er kommune, fylke eller stat :+1:

**Comment by livarb** [comment]
Ein ting å vere obs på at dersom ein drar inn fleire enheter frå statsforvaltninga (for eksempel drar inn alle enheter med sektorkode = 6100), så får ein inn ein del ekstra støy i form av enheter som ikkje dukkar opp i datadelingsoversikt for staten. Til dømes enheter under NAV. F.eks. 974652269 som er to ledd under NAV (NAV --> NAV Tjenestelinje --> NAV Oslo).
Så det ideelle er naturlegvis å kun dra inn dei enhetane i statsforvaltninga som skal visast i datadelingsoversikt for stat slik at det ikkje vert unødig støy i oversikt over alle virksomheter.

For fylkeskommuner og kommuner er det færre slike bieffektar. Blant denne gruppa, for dei som ikkje har innhald i katalogane, må ein berre fjerne førehandsregistrerte og sletta (filtrere på foretaksnamn som nemt i Datalandsbyen-tråd).

**Comment by livarb** [comment]
Når det gjeld datakjelde for oversikt over kommunar og fylkeskommunar, så har eg etterspurt det som nemt i prat med @NilsOveTen .
Lagt ut i Datalandsbyen: https://datalandsbyen.norge.no/topic/346/oversikt-kommuner-og-fylker-inkludert-organisasjonsnummer  og har i bakkant sendt e-post til Kartverket og SSB.
Fekk nettopp svar frå SSB, som har datasett for dette.

**Comment by NilsOveTen** [comment]
> Når det gjeld datakjelde for oversikt over kommunar og fylkeskommunar, så har eg etterspurt det som nemt i prat med @NilsOveTen . Lagt ut i Datalandsbyen: https://datalandsbyen.norge.no/topic/346/oversikt-kommuner-og-fylker-inkludert-organisasjonsnummer og har i bakkant sendt e-post til Kartverket og SSB. Fekk nettopp svar frå SSB, som har datasett for dette.

De kodelistene inkluderer ikke kommunenr eller fylkesnr? Kan jo prøve å sammenligne navn, men som du nevnte sist uke, vi møter vel fortsatt på problemet med kommuner som har samme navn? (feks Herøy og Våler)

**Comment by livarb** [comment]
> 

Stilte oppfølgingsspørsmål og SSB svarte kjapt i tråden i Datalandsbyen. Dei har andre datasett der desse koblingane er.

**Comment by livarb** [comment]
> De kodelistene inkluderer ikke kommunenr eller fylkesnr? Kan jo prøve å sammenligne navn, men som du nevnte sist uke, vi møter vel fortsatt på problemet med kommuner som har samme navn? (feks Herøy og Våler)

Stilte oppfølgingsspørsmål og SSB svarte kjapt i tråden i Datalandsbyen. Dei har andre datasett der desse koblingane er.

**Comment by KjerstiSteien** [comment]
@NilsOveTen Det ser ut som alt er løst her. Kan jeg lukke saken?

**Comment by NilsOveTen** [comment]
Er ikke det mer opp til @livarb? Men ja, bare å lukke for min del

**Comment by livarb** [comment]
Eg anser denne som vel utført. Flyttar til «Utført».
Til seinare saker må de gjerne flytte til «Klar til akseptansetest», så kan eg ta saka vidare derifrå
