### ISSUE TITLE
[BRUKERHISTORIE] Registrere begreper på flere språk

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#86]
Som: Skrivebruker
Ønsker jeg: å registrere begreper på flere språk
Slik at: jeg kan kommunisere begreper på ulike språk

Det må være mulig å velge et følgende språk, som vil opptre som utgangspunktet for andre oversettelser:
Språkkode (ISO 639-1)|Språk
------------|-------------
nb|norsk bokmål 
nn|norsk nynorsk
en|engelsk

Språkkoden "no" skal ikke brukes. 
Lenke til wiki-versjon av ISO-639 (lukke standard, må kjøpes): https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes 

Relatert til epos: #2 
Relatert til brukerhistorie: #76 
Se også #108 
Se også: #59 (for datasett)

**Trådskisser**
Velg språk: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/381427538 
Skriverolle med Bokmål valgt: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/381427539
Bokmål og Nynorsk valgt: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/381427540
Bokmål, Nynorsk og Engelsk valgt: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/381427541

Lenke til design: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/381837554 
Lenke til løsningsarkitektur: denne løses ved at [api-et](https://github.com/Informasjonsforvaltning/concept-catalogue/blob/develop/applications/concept-catalogue/src/main/resources/static/ConceptRegistrationAPI.yaml) må støtte flerspråk i alle relevante felt.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Akseptansekriterier:**
,# language: no
Egenskap: 
Kriterier:
⦁	Velg språk
⦁	Registrer et felt for språk 1
⦁	Registrer et felt for språk 2
Dekkes ikke:   (Dekkes i andre brukerhistorier) 

Referanser:
Scenario: Velg språk 
Gitt at bruker har valgt å starte prosessen "Opprett nytt begrep"
Når bruker velger språk "Norsk Bokmål"
Så skal siden "Registrer nytt begrep" dukke opp 
og teksten "Valgt språk: Norsk bokmål" skal vises på siden

Scenario: Registrer et felt for språket
Gitt at siden "Registrer nytt begrep" vises
og bruker har valgt språk "Norsk Bokmål"
Så skal bruker skal kunne registrere teksten "pantedokument" i feltet "Anbefalt term"

Scenario: Registrer et felt for  språk 2
Gitt at siden "Registrer nytt begrep" vises
og bruker har valgt språk "Norsk Bokmål"
og bruker har valgt språk 2 = Engelsk
Så skal bruker skal kunne registrere teksten "Mortgage deed" i feltet "Anbefalt term" for Engelsk oversettelse

**Comment by marittor** [comment]
Har oppdatert kommentaren til å peke til invision der hvor nye trådskisser ligger. Trådskissene er diskutert med Steinar og meg + vist til Språkrådet.

**Comment by marittor** [comment]
@sindresandvik2 Flytter denne over til KTK nå men bør kriteriene oppdateres her all den tid vi ikke ber bruker om å velge språk hver gang?

**Comment by sindresandvik2** [comment]
Oppdatering av akseptansekriterane kan me justere nå behovet i i utvikling

**Comment by marittor** [comment]
Testet gjennom hele registreringsløsningen for begrep på alle språk og språkfelter. Alt fint og akseptansetestet :) Lukker saken.
