### ISSUE TITLE
Begrep Kun tillate ett utkast per begrep

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/behov#876]

**Comment by KjerstiSteien** [comment]
@NilsOveTen husker du hva vi trenger å gjøre for å støtte dette behovet?

**Comment by NilsOveTen** [comment]
> @NilsOveTen husker du hva vi trenger å gjøre for å støtte dette behovet?

Har allerede fjerna støtte for det i backend: https://github.com/Informasjonsforvaltning/concept-catalog/commit/cf1c71e8866673df585e8624f56587dc67f21e82

I frontend må vi vel hindre noen å lage utkast fra begrep som det allerede finnes nyere versjoner av, og potensielt linke til det eventuelle utkastet. Men trenger vel å bestemme akkurat hvordan det skal se ut osv før vi kan gå videre med denne?

**Comment by AinaEngen** [comment]
@KurtStian - er dette noe du også kunne teste samtidig som du driver og tester andre ting i Begrep?

**Comment by KurtStian** [comment]
@jeffreiffers Er denne klar for testing? Får 404 når jeg velger "Forslag til nytt begrep" (gjelder staging).
![image](https://github.com/Informasjonsforvaltning/behov/assets/43232700/737367e8-0b3c-40fd-aec3-3b9eb0728967)

**Comment by KjerstiSteien** [comment]
Testet ok. Når jeg trykker rediger på publisert begrep med revisjon, kommer jeg til utkastet for begrepet.
