### ISSUE TITLE
[BRUKERHISTORIE] Vis virksomhetsside for virksomheter uten innhold i katalogene og vis mer informasjon

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#879]
Som: bruker av data.norge.no
Ønsker jeg å: kunne se informasjon om en virksomhet som ikke (enda) har innhold i katalogene
Slik at: jeg kan lære mer om virksomheten

Relatert til epos: #755

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

Stikkord:
- Dette gjelder sidene for visning av en enkelt virksomhet. Eksempel: [Arbeidstilsynet](https://data.norge.no/organizations/974761211)
- [X] Støtte å vise virksomheter som ikke har innhold i katalogene, slik at dersom man klikker på en virksomhet fra datadelingsoversikt, så får man se detaljer. Eksempel på en slik virksomhet: [Datatilsynet](https://data.norge.no/organizations/974761467) (lenken gir i dag 404-feil).
- [ ] Kan avgrense til (organisasjonsform FYLK og KOMM) eller (sektorkode = 6100) om vi ikke vil vise for alle.
- Flere felt å vise:
 - [X] antall ansatte. Dette sier noe om hvor stor virksomheten er. Dette er et felt man får ved oppslag på enhet i data.brreg.no
 - [ ] overordnet enhet (kun for staten). Også et felt man får fra data.brreg.no
 - [ ] underordna enheter (kun for staten — kan føre til å vise gruppen i datadelingsoversikt)
    Dette siste punktet er nok vanskeligere å implementere, og kan være noe vi tar igjen i en senere versjon.
    Er mulig å gjøre 1 kall mot data.brreg.no for å få ut alle enheter der overordnet enhet = orgnr.

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

Regner med at denne løses av #855

**Comment by NilsOveTen** [comment]
For å vise antall ansatte: https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/96 og https://github.com/Informasjonsforvaltning/fdk-portal/issues/1649

For å ikke gi 404 på virksomheter uten katalogdata: https://github.com/Informasjonsforvaltning/fdk-organization-bff/issues/98

overordna og underordna tror jeg vi kan løse i organization-catalog, men det kan potensielt kompliseres om vi må støtte sammenhengen fylke-kommune.

Filtrering på Fylke/kommune/underenhet er også et problem, siden de ikke følger underenhetsstrukturen vi legger bak orgPath som brukes ellers i løsningen.

Begge disse problemene tror jeg vi kan løse vha orgPath eller en noe som ligner orgPath, men som tar for seg sammenhengen fylke-kommune. Jeg trenger mer info om akkurat hva behovet blir der og må se hva vi eventuelt må støtte oss på av data fra enhetsregisteret. Men er veldig sikker på at beste løsning blir at det er organization-catalog som henter informasjonen og at virksomhetssiden kun baserer seg på data den får derfra.

**Comment by livarb** [comment]
@NilsOveTen : Overordna/underordna gjeld kun for staten. Presiserte det i beskrivelsen (la til «kun»). Grunnen til at det ikkje gjeld kommunal sektor, er at fylkeskommunane ikkje kan instruere kommunane i sitt fylke, i motsetnad til i statsforvaltninga der departementa instruerer sine underordna direktorat.
For kommunal sektor kunne ein hatt anledning til, når ein ser på ein kommune, å klikke seg vidare til å vise heile fylket, men dette tar vi ikkje i første versjon. Unntaket er om ein under arbeidet ser at det er tilnærma null ekstra arbeid å implementere.

Å gruppere fylkeskommunar og kommunar på fylker er som du seier ikkje like rett fram som med statsforvaltninga. Ein må gjerne lagre ei mapping for dette separat (spekulasjon frå mi side). Men dette er nok meir aktuelt på datadelingsoversikt for kommunal sektor, ikkje på detaljvisning av ein kommune.

Bonus: vis gjerne tal på tilsette med mellomrom som tusen-skiljeteikn så det er penare og lettare å lese. E.g.
![image](https://user-images.githubusercontent.com/3617256/235287028-98f53f9d-5439-4f42-a7af-910eb5941c54.png)

Håpar dette forenkla denne saka 🙂

**Comment by NilsOveTen** [comment]
> Overordna/underordna gjeld kun for staten. Presiserte det i beskrivelsen (la til «kun»). Grunnen til at det ikkje gjeld kommunal sektor, er at fylkeskommunane ikkje kan instruere kommunane i sitt fylke, i motsetnad til i statsforvaltninga der departementa instruerer sine underordna direktorat.
For kommunal sektor kunne ein hatt anledning til, når ein ser på ein kommune, å klikke seg vidare til å vise heile fylket, men dette tar vi ikkje i første versjon. Unntaket er om ein under arbeidet ser at det er tilnærma null ekstra arbeid å implementere.

Da tror jeg vi kan løse første versjon av dette vha organization-catalog og samme orgPath-filteret vi bruker ellers. Det er ok at vi legger til samme støtte mtp overordna/underordna for private?

**Comment by livarb** [comment]
Å legge inn for private i interne databaser eller liknande skal gå fint, så lenge ein ikkje viser det for private i portal. 

Trur dette feltet kun er brukt for offentleg sektor. Tok ein sjekk mot nyaste versjon av enhetsregisteret for å vere sikker, og det stemmer. Feltet «overordnetEnhet» er null på alle enhetar utanom diverse offentlege enheter (sektorkodar 6100, 6500, 1510, 3900, 4900, 1110).

**Comment by KurtStian** [comment]
Nesten ferdig :-)

**Comment by livarb** [comment]
Dette er fint levert!
Einaste vi ikkje rakk er overordna/underordna enhet. Har laga ny brukarhistorie på dette: #931
