### ISSUE TITLE
[BRUKERHISTORIE] Etterspørre fra virksomhetsoversikt

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#880]
Som: bruker
Ønsker jeg å: kunne etterspørre data som mangler
Slik at: data kan bli publisert eller allerede delete data blir lagt inn i katalogene

Relatert til epos: #864 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

Dersom #850 er implementert, bruk dette.
Viss ikke, er det veiledning til hvordan etterspørre via Datalandsbyen

### Første versjon
Tekst i toppen av virksomhetsoversikt med lenke til Datalandsbyen-post.
Tekst:
nb: Savner du noe i katalogene? Etterspørr her
nn: Saknar du noko i katalogane? Etterspør her
en: Missing something? Request data/API here (text in norwegian)

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

**Comment by KurtStian** [comment]
Setter ned prioritet pga arbeidet med virksomhetsintern begrepskatalog.

**Comment by livarb** [comment]
Merk at vi må ha lenke vidare til å etterspørre (jamfør beskrivelse) som eit minimum.

**Comment by livarb** [comment]
Lukkar denne.

Dette vart oppfylt ved tekst som lenker til post i Datalandsbyen
![image](https://github.com/Informasjonsforvaltning/behov/assets/3617256/d655d3d6-4687-4ee7-af2e-e9a8d9180429)
Lansert ifbm. #755 våren 2023.
Dersom vi skal gjere det annleis, for eksempel ved å kunne etterspørre direkte frå data.norge.no, takast dette gjennom #850
