### ISSUE TITLE
[BRUKERHISTORIE] Mulighet til å ta ut rapport over registrerte begrep i FD

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#89]
Som: registreringsansvarlig i Felles datakatalog
Ønsker jeg: på hvert registrerte datasett mulighet til å kjøre ut en rapport over alle registrerte begrep og som viser hvilke som har treff i Begrepskatalogen,
Slik at: jeg kan melde inn behov i BR sin lokale begrepskatalog.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by marittor** [comment]
Behovet er meldt fra datasettgruppe i BR.

**Comment by RogerSOlsen** [comment]
Må beskrives bedre. Uklart behov.
