### ISSUE TITLE
[BRUKERHISTORIE] Automatisk kobling mellom Felles datakatalog og Begrepskatalogen

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#90]
Som: registrerer av datasettbeskrivelse i Felles datatakatalog
Ønsker jeg: at det ved innlasting av fil med aktuelle begrep i Felles datakatalog, går det automatisk søk mot "Begrepskatalogen"
Slik at de begrep som er definert (får treff) blir merket.

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

**Comment by marittor** [comment]
@stigbd Synes du ikke denne ser litt lignende ut som importhistoriene våre? Jeg tenker at dersom vi løser import til Felles begrepskatalog for å jobbe videre med disse i registreringsløsningen, vil de jo kunne dukke opp automatisk i datasett-registreringskontekst når de er publisert ut i portal.

**Comment by KjerstiSteien** [comment]
Tolker kommentarer i saken som at behovet er løst gjennom mulighet for import til begrepskatalogen og videre behandling derfra.
