### ISSUE TITLE
[BRUKERHISTORIE] URL-ar som vidaresender til andre adresser

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#901]
Som: digdir-person på stand
Ønsker jeg å: sette opp URL-er til å videresende til andre adresser
Slik at: jeg kan bruke URL-ene på QR-koden på standmateriell

1. https://data.norge.no/ettersporsel
Peike til: https://datalandsbyen.norge.no/topic/56/tips-til-%C3%A5-ettersp%C3%B8rre-datasett-og-api-er

2. https://data.norge.no/hvamanglerqr
Peike til: https://app.sli.do/event/j3tHyGM9Cmu8ifyCR3JfoU

Sjå også [tråd i Slack](https://fdk-project.slack.com/archives/C7B16J66S/p1683892184477749).

**Comment by valosnah** [comment]
- [x] 1: prodsatt
- [x] 2: prodsatt
