### ISSUE TITLE
[EPOS] Slå sammen data.norge.no og Felles datakatalog til en løsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#91]
Felles datakatalog har «once only» og gjenbruk i offentlig sektor som primærformål, mens data.norge.no har verdiskaping i næringslivet og transparens i offentlig sektor som primærformål. Dette er et kunstig skille ettersom offentlige virksomheter har behov for å oppdage, vurdere og ta i bruk åpne data og private virksomheter og sivilsamfunnet ønsker å vite AT data eksisterer – selv om de ikke er åpne. 

Dagens situasjon med to nasjonale dataportaler forvirrer brukerne og skaper problemer for pådriveraktivitet, veiledning, regelverk, føringer mv. En felles portalløsning vil bidra til et felles økosystem rundt offentlige data.

De viktigste behovene (forretningsverdi = viktig eller høyere), må ivaretas i sammenslått løsning.

Brukerne av data.norge.no og Felles datakatalog har overlappende behov og det er 

Tilknyttete brukerhistorier:
#92 
#93 
#99 
#100 
#101 
#139 
#140 
#141 
#142 
#143 
#144 
#145 
#158 
#174 
#178 
#186 
#411 
#416 
#417 
#418 
#420 
#421 
#422

**Comment by data-david** [comment]
[FDK-åpne data-behov.pptx](https://github.com/Informasjonsforvaltning/behov/files/3468446/FDK-apne.data-behov.pptx)
Fra Øysteins presentasjon 28. mars 2019

**Comment by data-david** [comment]
[15032019 - EDP_Country Session NO.pdf](https://github.com/Informasjonsforvaltning/behov/files/3468447/15032019.-.EDP_Country.Session.NO.pdf)
 European Data Portal si vurdering av Norge (data.norge.no) 2018.

**Comment by shenluna** [comment]
Lukker denne. data.norge.no og Felles datakatalog ble slått sammen i mai 2020.
