### ISSUE TITLE
[BRUKERHISTORIE] Fjerne Bruksområde fra registreringsløsning. 

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#918]
Som: Forvalter av standard og registreringsløsning for begrep
Ønsker jeg å: fjerne felt som ikke lenger er støttet av standarden
Slik at: Registreringsløsningen gjenspeiler oppdatert standard best mulig, og så vi slipper å putte dem inn i detaljsiden for så å fjerne dem igjen. 

- [x] Informasjonsforvaltning/behov#933
- [x] Informasjonsforvaltning/concept-catalog-gui#558

Relatert til epos: Informasjonsforvaltning/behov#792

**Comment by NilsOveTen** [comment]
@KjerstiSteien I nåværende versjon av begrepskatalogen er bruksområde en liste og fagområde ikke det. Skal fagområde endres til en liste? Hvis den fortsatt kun skal være en enkel verdi, hva gjør vi med de som har flere verdier på bruksområde?

**Comment by Te-Bert** [comment]
Noe av bakgrunnen for endringen/sammenslåingen var at brukerne hadde vansker med å skille mellom de to. En sammenslåing innebærer vel da at fagområde også kan være en liste - f.eks. et begrep brukt innen flere fagområder med sine respektive koder (men med samme meningsinnhold/definisjon)

_"Egenskapen brukes til å oppgi fagområde som begrepet kan grupperes/klassifiseres under. Dette oppgis enten som tekst med språkkode eller som kodet verdi. Hvis tekst brukes, og når teksten finnes på flere skriftspråk, bør egenskapen gjentas for hvert skriftspråk"_
