### ISSUE TITLE
[EPOS] Migrering av kataloger fra innhøstingsløsning til registreringsløsning

### ISSUE THREAD

**Issue by oystein-asnes** [Informasjonsforvaltning/behov#92]
Som: forvalter av en lokal løsning eller sektorportal som høstes av FDK
Ønsker jeg å: migrere innhøstede kataloger/datasettbeskrivelser til registreringsløsningen i FDK
Slik at: jeg kan flytte videre forvaltning av virksomhetens katalog til FDKs registreringsløsning.

Relatert til epos: #91 #186 
Relatert til brukerhistorie: #178 #421 #444 

Lenke til design: N/A
Lenke til løsningsarkitektur:

Forretningsverdig: kritisk

**Comment by livarb** [comment]
Manglar formatering på datasett-beskrivelsar.
Eksempel:
https://data.norge.no/datasets/5a5374c3-c6a7-49f8-b9cc-0a9e48c1acd7

![image](https://user-images.githubusercontent.com/3617256/84941832-336b7800-b0e2-11ea-91e6-ac3f00b8b562.png)

Original:
![image](https://user-images.githubusercontent.com/3617256/84941863-3c5c4980-b0e2-11ea-8d6c-c4623184cb26.png)

**Comment by livarb** [comment]
Denne kan lukkast. Eventuelle manglar takast i #508 .
