### ISSUE TITLE
[BRUKERHISTORIE] Oppgradere Datalandsbyen til nyare NodeBB

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#937]
Relatert til epos: #864

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

Nødvendig å oppgrade NodeBB før vidare arbeid med integrasjon med Datalandsbyen (sjå #864 #852 #851)

**Comment by jeffreiffers** [comment]
Fixed by https://github.com/Informasjonsforvaltning/fdk-community-service/issues/195
