### ISSUE TITLE
[BRUKERHISTORIE] Fiks automatisk sletting av brukarar i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#941]
Som:
Ønsker jeg å:
Slik at:

Relatert til epos:

- [ ] Lage oppdatert automatisk slettejobb
- [ ] Lag nye e-postmalar
- [ ] Eventuelt gjenopprette innhald

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Lenker (hvis ikke relevant, skriv 'N/A')
Lenke til design:
Lenke til løsningsarkitektur:
Lenke til trusselmodellering:

### Avklaringer: 

| Spørsmål | Avklaring | Avklart med | Avklart dato | 
| -------- | --------- | ----------- | ------------ |
| | | | |
| | | | |

### Akseptansekriterier:

Gitt at ..., så skal, 
1. ...
  a) ..
  b) ..
  c) ..
2. ...
  a) ..
  b) ..
  c) ..

#### S1. Vanleg automatisk sletting av brukarar
- Når det er 14 dagar før 1 år sidan sist innlogging på ein brukarkonto: send ut e-post om at kontoen vert sletta
- Når det er 1 dag før sletting, send ut siste e-postpåminning
- Når det er 1 år sidan sist 

#### S2. Starte opp sletting på nytt

**Comment by jeffreiffers** [comment]
https://github.com/Informasjonsforvaltning/fdk-community-service/pull/206
