### ISSUE TITLE
[EPOS] Importere begrep til eget verktøy

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/behov#96]
Bergen kommune har uttalt at de ønsker at Felles datakatalog skal være autoritativ kilde for begrep som er relevante for dem, slik at de kan inmportere begrepene til sitt verktøy for begrep - for tiden Archi

**Comment by sskagemo** [comment]
Det er antagelig mulig å bruke API-et for begrepskatalogen for å få dette til idag, se eksempel på svar fra API-et, https://fellesdatakatalog.brreg.no/api/concepts

<klipp>
`{
id: "13dbd4a3-4aff-498c-abdd-61d8f7d6fc40",
uri: "https://fellesdatakatalog.brreg.no/api/concepts/13dbd4a3-4aff-498c-abdd-61d8f7d6fc40",
identifier: "http://data.brreg.no/begrep/48786",
definition: {
text: {
nb: "ethvert dokument som gir uttrykk for en panterett, stiftet ved avtale"
},
remark: {
nb: "Pantedokumentet kan være et gjeldsbrev som i så fall er undertegnet av den som har lånt kapitalen, skyldneren, og er en sikkerhet for at den som har lånt ut kapitalen, panthaveren, skal få tilbake kapitalen. I Løsøreregisteret tinglyses det pantedokumenter med pant i driftstilbehør, jernbanemateriell, varelager, fiskeredskaper, motorvogn og anleggsmaskiner og redskaper, besetning, avling mv. i landbruksnæring."
},
source: {
prefLabel: {
nb: "Tinglysingsloven § 36. _Lov 7. juni 1935 nr. 2 om tinglysing_ https://lovdata.no/NL/lov/1935-06-07-2/ [Lest: 25.05.2018]"
}
}
},
subject: {
nb: "Tinglysing"
},
prefLabel: {
nb: "pantedokument"
},
altLabel: [ ],
hiddenLabel: [ ],
contactPoint: {
email: "informasjonsforvaltning@brreg.no",
telephone: "+4775007500"
},
publisher: {
uri: "http://data.brreg.no/enhetsregisteret/enhet/974760673",
name: "REGISTERENHETEN I BRØNNØYSUND",
orgPath: "/STAT/912660680/974760673",
prefLabel: {
no: "Brønnøysundregistrene"
}
},
harvest: {
firstHarvested: "2019-02-08T13:59:30.050+0000",
lastHarvested: "2019-02-08T13:59:30.050+0000"
}
},`
</klipp>

**Comment by stigbd** [comment]
Enig, eg tenker at ein god måte å importere til eget verktøy er å bruke vårt begreps-api. Litt meir detaljar om api-et fins i Felles datakatalog her:
https://fellesdatakatalog.brreg.no/apis/cb6483b8-4d94-473d-a4b9-8ee64abb9b91
