### ISSUE TITLE
Sjekke om felt som utgår er i bruk i katalogen.

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/behov#967]
## Felt som utgår: 
| Klasse |KlasseURI | Egenskap | EgenskapsURI | I registreringsskjema? |
| ------ | ----------- | ---------- | ---------------- | ----- |
|Begrep |skos:Concept |Begrep - alternativ formulering | skosno:alternativFormulering | Nei |
|Begrep |skos:Concept |Begrep – bruksområde |skosno:bruksområde | Nei. Fjernet i 2023?|
|Term |skosxl:Label | - | - | Nei|
|Definisjon |skosno:Definisjon |Definisjon – sistOppdatert | dct:modified | Nei |
|Alternativ formulering |skosno:AlternativFormulering | - | - | Nei |
|Assosiativ relasjon |skosno:AssosiativRelasjon |Assosiativ relasjon – beskrivelse |dct:description | Ja. Innhold flyttes til Assosiativ relasjon - relasjonsrolle |
|Assosiativ relasjon |skosno:AssosiativRelasjon |Assosiativ relasjon – sistOppdatert |dct:modified | Nei |
|Generisk relasjon |skosno:GeneriskRelasjon |Generisk relasjon – sistOppdatert |dct:modified | Nei |
|Partitiv relasjon |skosno:PartitivRelasjon |Partitiv relasjon – sistOppdatert |dct:modified | Nei |

## Oppgaver: 
- [x] Sjekk om feltene i tabellen over er i bruk i katalogen i dag. (alt som er høstet inn)
- [x] Ta et møte etter at vi har resultatene. 

## Sjekkliste for at oppgaver er utført per felt: 
- [x] Begrep - alternativ formulering
- [x] Begrep – bruksområde
- [x] Definisjon – sistOppdatert
- [x] Alternativ formulering (klasse)
- [x] Assosiativ relasjon - beskrivelse (beskrevet i https://github.com/Informasjonsforvaltning/behov/issues/966) 
- [x] Assosiativ relasjon - sist oppdatert
- [x] Generisk relasjon - sist oppdatert
- [x] Partitiv relasjon - sist oppdatert

**Comment by terjesyl** [comment]
# Bruk av felter fra SKOS 1.1.1

Undersøkt 23.04.2024

| Klasse                 | KlasseURI                    | Egenskap                            | EgenskapsURI                 | Spørring # | Antall tripler |
| ---------------------- | ---------------------------- | ----------------------------------- | ---------------------------- | ---------- | -------------- |
| Begrep                 | skos:Concept                 | Begrep - alternativ formulering     | skosno:alternativFormulering | 1          | 0              |
| Begrep                 | skos:Concept                 | Begrep – bruksområde                | skosno:bruksområde           | 2          | 0              |
| Term                   | skosxl:Label                 | -                                   | -                            | 3          | 7379\*         |
| Definisjon             | skosno:Definisjon            | Definisjon – sistOppdatert          | dct:modified                 | 4          | 0              |
| Alternativ formulering | skosno:AlternativFormulering | -                                   | -                            | 5          | 0              |
| Assosiativ relasjon    | skosno:AssosiativRelasjon    | Assosiativ relasjon – beskrivelse   | dct:description              | 6          | 0              |
| Assosiativ relasjon    | skosno:AssosiativRelasjon    | Assosiativ relasjon – sistOppdatert | dct:modified                 | 7          | 0              |
| Generisk relasjon      | skosno:GeneriskRelasjon      | Generisk relasjon – sistOppdatert   | dct:modified                 | 8          | 0              |
| Partitiv relasjon      | skosno:PartitivRelasjon      | Partitiv relasjon – sistOppdatert   | dct:modified                 | 9          | 0              |

\*Se også spørring 3.1

Tilsvarende resultater i Demo. Kun `skosxl:Label` i bruk, spørring 3 gir der 6236 tripler.

## Spørringer

Prefikser:

```sparql
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX skosno: <http://data.norge.no/skosno#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
```

### 1

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:alternativFormulering ?o .
}
```

### 2

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:bruksområde ?o .
}
```

### 3

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?label a skosxl:Label .
}
```

#### 3.1

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosxl:prefLabel | skosxl:altLabel | skosxl:hiddenLabel | skosno:datastrukturTerm ?label .
}
```

Gir 6992 resultater

### 4

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:definisjon | skosno:alternativFormulering ?betydningsbeskrivelse .
  ?betydningsbeskrivelse dct:modified ?modifiedDate .
}
```

### 5

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:alternativFormulering ?o .
}
```

### 6

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:assosiativRelasjon ?relasjon .
  ?relasjon dct:description ?o .
}
```

### 7

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:assosiativRelasjon ?relasjon .
  ?relasjon dct:modified ?o .
}
```

### 8

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:generiskRelasjon ?relasjon .
  ?relasjon dct:modified ?o .
}
```

### 9

```sparql
SELECT (COUNT(*) as ?count) WHERE {
  ?concept a skos:Concept .
  ?concept skosno:partitivRelasjon ?relasjon .
  ?relasjon dct:modified ?o .
}
```

**Comment by hegeaal** [comment]
Kutter alt unntatt skosxl:Label da resten ikke er i bruk. Oppdaterer hvilken kode anbefalt term bruker i registreringsløsningen, sjekker om  skosxl:Label da fremdeles er i bruk - dersom ikke, fjernes.
