### ISSUE TITLE
[BRUKERHISTORIE] Inngang til Begrepskatalog GUI

### ISSUE THREAD

**Issue by marittor** [Informasjonsforvaltning/behov#97]
Som: intern leser i Begrepskatalog
Ønsker jeg å: kunne ha en inngang til Begrepskatalog GUI
Slik at: jeg kan lese eller registrere et begrep

Relatert til epos: #2 

Lenke til trådskisser: https://69d4ft.axshare.com/#g=1&p=landingside_kataloger__nvirksomhet
Lenke til løsningsarkitektur:

**Comment by lillelars** [comment]
@marittor @stigbd denne er closed - kan vi fjerne den fra kolonnen?
