### ISSUE TITLE
Tilgang til å registrere kommer og går (innlogging via ID-porten)

### ISSUE THREAD

**Issue by hildea** [Informasjonsforvaltning/behov#976]
Jeg logger inn på data.norge.no via ID-porten og får feilmeldinga "Det ser ikke ut til at du har fått tilgang til noen kataloger." Sist jeg prøvde (en uke eller to siden?) hadde jeg tilgang til alle katalogene jeg skal ha tilgang til.

Når jeg sjekker tilgangene mine ved å logge inn på Altinn kan jeg se at jeg har tilgang til tjenesten "Felles datakatalog - alle kataloger - virksomhetsadministrator" for Statens vegvesen.

En kollega som har skrivetilgang opplever samme problemer, inkludert at tilgangen forsvinner mens hun jobber: Hun legger inn noen begreper og alt går bra, inntil hun plutselig ikke har tilgang lenger.

(Jeg tok en kikk på https://status.digdir.no/ men der står det "Ingen kjente driftsproblemer".)

**Comment by KurtStian** [comment]
Takk for tilbakemeldingen. Vi har hatt en feil i vår innloggingstjeneste som av og til gjorde at innloggingsprosessen ikke ble fullført. Vi har produksjonssatt en endring som vi mener skal løse feilen. Jeg lar saken stå åpen en periode til vi er "helt" sikker på at feilen er løst

**Comment by KurtStian** [comment]
Relatert til: https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/930

**Comment by jeffreiffers** [comment]
@hildea Vi har gjort noe forbedringer på påloggingslogikken. Kan du sjekke om problemet har blitt borte?

**Comment by jeffreiffers** [comment]
På grunn av inaktivitet blir saken lukket.
